import { config } from 'dotenv';
import postgres from 'postgres';

config({ path: '.env.local' });
config();

async function main() {
  const databaseUrl = process.env.POSTGRES_URL || process.env.DATABASE_URL;
  if (!databaseUrl) throw new Error('POSTGRES_URL or DATABASE_URL is required');

  const sql = postgres(databaseUrl, { max: 1 });
  await sql`
    ALTER TABLE users
      ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'user',
      ADD COLUMN IF NOT EXISTS plus_trial_ends_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '3 days')
  `;
  await sql`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_users_role'
      ) THEN
        ALTER TABLE users
          ADD CONSTRAINT chk_users_role CHECK (role IN ('admin', 'user'));
      END IF;
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_users_membership'
      ) THEN
        ALTER TABLE users
          ADD CONSTRAINT chk_users_membership CHECK (membership IN ('free', 'plus'));
      END IF;
    END
    $$;
  `;
  await sql`
    UPDATE users
    SET role = 'admin',
        membership = 'plus'
    WHERE lower(username) = 'admin'
       OR lower(email) IN ('admin@openwook.local', 'admin@openwook.cloud')
  `;
  await sql`
    CREATE TABLE IF NOT EXISTS ai_artifacts (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      artifact_type VARCHAR(64) NOT NULL,
      user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
      bank_id BIGINT REFERENCES question_banks(id) ON DELETE SET NULL,
      question_id BIGINT REFERENCES questions(id) ON DELETE SET NULL,
      import_job_id BIGINT REFERENCES question_import_jobs(id) ON DELETE SET NULL,
      practice_session_id BIGINT,
      provider VARCHAR(64) NOT NULL DEFAULT 'mastra',
      model VARCHAR(128),
      input_payload JSONB NOT NULL DEFAULT '{}',
      output_payload JSONB NOT NULL DEFAULT '{}',
      status VARCHAR(32) NOT NULL DEFAULT 'completed',
      error_message TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;
  await sql`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_ai_artifacts_type'
      ) THEN
        ALTER TABLE ai_artifacts
          ADD CONSTRAINT chk_ai_artifacts_type
          CHECK (artifact_type IN ('document_parse', 'answer_generation', 'learning_report'));
      END IF;
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_ai_artifacts_status'
      ) THEN
        ALTER TABLE ai_artifacts
          ADD CONSTRAINT chk_ai_artifacts_status
          CHECK (status IN ('completed', 'failed'));
      END IF;
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_ai_artifacts_payload_object'
      ) THEN
        ALTER TABLE ai_artifacts
          ADD CONSTRAINT chk_ai_artifacts_payload_object
          CHECK (jsonb_typeof(input_payload) = 'object' AND jsonb_typeof(output_payload) = 'object');
      END IF;
      IF to_regclass('user_practice_sessions') IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_ai_artifacts_practice_session'
      ) THEN
        ALTER TABLE ai_artifacts
          ADD CONSTRAINT fk_ai_artifacts_practice_session
          FOREIGN KEY (practice_session_id) REFERENCES user_practice_sessions(id) ON DELETE SET NULL;
      END IF;
    END
    $$;
  `;
  await sql`CREATE INDEX IF NOT EXISTS idx_ai_artifacts_question ON ai_artifacts (question_id, artifact_type, created_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_ai_artifacts_import_job ON ai_artifacts (import_job_id, artifact_type, created_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_ai_artifacts_user ON ai_artifacts (user_id, artifact_type, created_at DESC)`;
  await sql.end();
  console.log('OpenWook runtime schema is ready.');
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
