import { config } from 'dotenv';
import postgres from 'postgres';
import { env } from '../openwook/env.ts';

config({ path: '.env.local' });
config();

async function main() {
  const databaseUrl = env.POSTGRES_URL || env.DATABASE_URL;
  if (!databaseUrl) throw new Error('POSTGRES_URL or DATABASE_URL is required');

  const sql = postgres(databaseUrl, { max: 1 });
  await sql`
    ALTER TABLE users
      ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'user',
      ADD COLUMN IF NOT EXISTS avatar_url TEXT,
      ADD COLUMN IF NOT EXISTS plus_trial_ends_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '3 days'),
      ADD COLUMN IF NOT EXISTS plus_expires_at TIMESTAMPTZ
  `;
  await sql`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_users_role'
      ) THEN
        ALTER TABLE users
          ADD CONSTRAINT chk_users_role CHECK (role IN ('admin', 'user'));
      END IF;
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_users_membership'
      ) THEN
        ALTER TABLE users
          ADD CONSTRAINT chk_users_membership CHECK (membership IN ('free', 'plus'));
      END IF;
    END
    $$;
  `;
  await sql`
    UPDATE users
    SET role = 'admin',
        membership = 'plus'
    WHERE lower(username) = 'admin'
       OR lower(email) IN ('admin@openwook.local', 'admin@openwook.cloud')
  `;
  await sql`
    CREATE TABLE IF NOT EXISTS ai_artifacts (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      artifact_type VARCHAR(64) NOT NULL,
      user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
      bank_id BIGINT REFERENCES question_banks(id) ON DELETE SET NULL,
      question_id BIGINT REFERENCES questions(id) ON DELETE SET NULL,
      import_job_id BIGINT REFERENCES question_import_jobs(id) ON DELETE SET NULL,
      practice_session_id BIGINT,
      provider VARCHAR(64) NOT NULL DEFAULT 'mastra',
      model VARCHAR(128),
      input_payload JSONB NOT NULL DEFAULT '{}',
      output_payload JSONB NOT NULL DEFAULT '{}',
      status VARCHAR(32) NOT NULL DEFAULT 'completed',
      error_message TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;
  await sql`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_ai_artifacts_type'
      ) THEN
        ALTER TABLE ai_artifacts
          ADD CONSTRAINT chk_ai_artifacts_type
          CHECK (artifact_type IN ('document_parse', 'answer_generation', 'learning_report'));
      END IF;
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_ai_artifacts_status'
      ) THEN
        ALTER TABLE ai_artifacts
          ADD CONSTRAINT chk_ai_artifacts_status
          CHECK (status IN ('completed', 'failed'));
      END IF;
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_ai_artifacts_payload_object'
      ) THEN
        ALTER TABLE ai_artifacts
          ADD CONSTRAINT chk_ai_artifacts_payload_object
          CHECK (jsonb_typeof(input_payload) = 'object' AND jsonb_typeof(output_payload) = 'object');
      END IF;
      IF to_regclass('user_practice_sessions') IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_ai_artifacts_practice_session'
      ) THEN
        ALTER TABLE ai_artifacts
          ADD CONSTRAINT fk_ai_artifacts_practice_session
          FOREIGN KEY (practice_session_id) REFERENCES user_practice_sessions(id) ON DELETE SET NULL;
      END IF;
    END
    $$;
  `;
  await sql`CREATE INDEX IF NOT EXISTS idx_ai_artifacts_question ON ai_artifacts (question_id, artifact_type, created_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_ai_artifacts_import_job ON ai_artifacts (import_job_id, artifact_type, created_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_ai_artifacts_user ON ai_artifacts (user_id, artifact_type, created_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_user_bank_links_user_owner_bank ON user_bank_links (user_id, bank_id) WHERE is_owner = true`;
  await sql`CREATE INDEX IF NOT EXISTS idx_user_bank_links_user_favorite_bank ON user_bank_links (user_id, bank_id) WHERE is_favorite = true`;
  await sql`CREATE INDEX IF NOT EXISTS idx_question_import_jobs_user_created ON question_import_jobs (created_by, created_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_question_import_jobs_user_status_created ON question_import_jobs (created_by, status, created_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_questions_status_type ON questions (status, question_type_id, id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_bank_question_links_bank_active ON bank_question_links (bank_id, sort_order, question_id) WHERE status = 'active'`;
  await sql`CREATE INDEX IF NOT EXISTS idx_bank_question_links_bank_status_sort ON bank_question_links (bank_id, status, sort_order, question_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_bank_group_links_bank_active ON bank_group_links (bank_id, sort_order, group_id) WHERE status = 'active'`;
  await sql`CREATE INDEX IF NOT EXISTS idx_bank_group_links_bank_status_sort ON bank_group_links (bank_id, status, sort_order, group_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_group_question_links_group_question_sort ON group_question_links (group_id, question_id, sort_order)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_questions_stem_fts ON questions USING GIN (to_tsvector('simple', COALESCE(stem, '')))`;
  await sql`CREATE INDEX IF NOT EXISTS idx_user_question_answers_user_session_question ON user_question_answers (user_id, session_id, question_id, answered_at)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_user_question_stats_user_mastery ON user_question_stats (user_id, mastery_score, wrong_count DESC, last_answered_at DESC)`;
  await sql`
    CREATE TABLE IF NOT EXISTS alipay_payment_orders (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      out_trade_no VARCHAR(64) NOT NULL,
      trade_no VARCHAR(64),
      product_code VARCHAR(64) NOT NULL,
      subject VARCHAR(256) NOT NULL,
      amount_cents INTEGER NOT NULL,
      currency CHAR(3) NOT NULL DEFAULT 'CNY',
      status TEXT NOT NULL DEFAULT 'created',
      alipay_trade_status VARCHAR(32),
      notify_id VARCHAR(128),
      notify_payload JSONB,
      query_payload JSONB,
      return_payload JSONB,
      membership_start_at TIMESTAMPTZ,
      membership_end_at TIMESTAMPTZ,
      paid_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;
  await sql`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_alipay_payment_orders_out_trade_no'
      ) THEN
        ALTER TABLE alipay_payment_orders
          ADD CONSTRAINT uq_alipay_payment_orders_out_trade_no UNIQUE (out_trade_no);
      END IF;
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_alipay_payment_orders_amount'
      ) THEN
        ALTER TABLE alipay_payment_orders
          ADD CONSTRAINT chk_alipay_payment_orders_amount CHECK (amount_cents > 0);
      END IF;
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_alipay_payment_orders_currency'
      ) THEN
        ALTER TABLE alipay_payment_orders
          ADD CONSTRAINT chk_alipay_payment_orders_currency CHECK (currency = 'CNY');
      END IF;
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_alipay_payment_orders_status'
      ) THEN
        ALTER TABLE alipay_payment_orders
          ADD CONSTRAINT chk_alipay_payment_orders_status
          CHECK (status IN ('created', 'paying', 'paid', 'closed', 'failed'));
      END IF;
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_alipay_payment_orders_membership_period'
      ) THEN
        ALTER TABLE alipay_payment_orders
          ADD CONSTRAINT chk_alipay_payment_orders_membership_period
          CHECK (
            membership_start_at IS NULL
            OR membership_end_at IS NULL
            OR membership_end_at > membership_start_at
          );
      END IF;
      IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'trg_alipay_payment_orders_set_updated_at'
      ) THEN
        CREATE TRIGGER trg_alipay_payment_orders_set_updated_at
        BEFORE UPDATE ON alipay_payment_orders
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
      END IF;
    END
    $$;
  `;
  await sql`CREATE INDEX IF NOT EXISTS idx_alipay_payment_orders_user_created ON alipay_payment_orders (user_id, created_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_alipay_payment_orders_trade_no ON alipay_payment_orders (trade_no) WHERE trade_no IS NOT NULL`;
  await sql`CREATE INDEX IF NOT EXISTS idx_alipay_payment_orders_status ON alipay_payment_orders (status, created_at DESC)`;
  await sql.end();
  console.log('OpenWook runtime schema is ready.');
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
