import { config } from 'dotenv';
import postgres from 'postgres';

config({ path: '.env.local' });
config();

async function main() {
  const databaseUrl = process.env.POSTGRES_URL || process.env.DATABASE_URL;
  if (!databaseUrl) throw new Error('POSTGRES_URL or DATABASE_URL is required');

  const sql = postgres(databaseUrl, { max: 1 });
  await sql`
    ALTER TABLE users
      ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'user',
      ADD COLUMN IF NOT EXISTS avatar_url TEXT,
      ADD COLUMN IF NOT EXISTS plus_trial_ends_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '3 days'),
      ADD COLUMN IF NOT EXISTS plus_expires_at TIMESTAMPTZ
  `;
  await sql`
    DO $$
    BEGIN
      ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_users_role;
      ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_users_membership;
      ALTER TABLE users
        ADD CONSTRAINT chk_users_role CHECK (role IN ('admin', 'user'));
      ALTER TABLE users
        ADD CONSTRAINT chk_users_membership CHECK (membership IN ('free', 'plus', 'enterprise'));
    END
    $$;
  `;
  await sql`
    UPDATE users
    SET role = 'admin',
        membership = 'plus'
    WHERE lower(username) = 'admin'
       OR lower(email) IN ('admin@openwook.local', 'admin@openwook.cloud')
  `;
  await sql`
    CREATE TABLE IF NOT EXISTS ai_artifacts (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      artifact_type VARCHAR(64) NOT NULL,
      user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
      bank_id BIGINT REFERENCES question_banks(id) ON DELETE SET NULL,
      question_id BIGINT REFERENCES questions(id) ON DELETE SET NULL,
      import_job_id BIGINT REFERENCES question_import_jobs(id) ON DELETE SET NULL,
      practice_session_id BIGINT,
      provider VARCHAR(64) NOT NULL DEFAULT 'mastra',
      model VARCHAR(128),
      input_payload JSONB NOT NULL DEFAULT '{}',
      output_payload JSONB NOT NULL DEFAULT '{}',
      status VARCHAR(32) NOT NULL DEFAULT 'completed',
      error_message TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;
  await sql`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_ai_artifacts_type'
      ) THEN
        ALTER TABLE ai_artifacts
          ADD CONSTRAINT chk_ai_artifacts_type
          CHECK (artifact_type IN ('document_parse', 'answer_generation', 'learning_report'));
      END IF;
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_ai_artifacts_status'
      ) THEN
        ALTER TABLE ai_artifacts
          ADD CONSTRAINT chk_ai_artifacts_status
          CHECK (status IN ('completed', 'failed'));
      END IF;
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_ai_artifacts_payload_object'
      ) THEN
        ALTER TABLE ai_artifacts
          ADD CONSTRAINT chk_ai_artifacts_payload_object
          CHECK (jsonb_typeof(input_payload) = 'object' AND jsonb_typeof(output_payload) = 'object');
      END IF;
      IF to_regclass('user_practice_sessions') IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_ai_artifacts_practice_session'
      ) THEN
        ALTER TABLE ai_artifacts
          ADD CONSTRAINT fk_ai_artifacts_practice_session
          FOREIGN KEY (practice_session_id) REFERENCES user_practice_sessions(id) ON DELETE SET NULL;
      END IF;
    END
    $$;
  `;
  await sql`CREATE INDEX IF NOT EXISTS idx_ai_artifacts_question ON ai_artifacts (question_id, artifact_type, created_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_ai_artifacts_import_job ON ai_artifacts (import_job_id, artifact_type, created_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_ai_artifacts_user ON ai_artifacts (user_id, artifact_type, created_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_user_bank_links_user_owner_bank ON user_bank_links (user_id, bank_id) WHERE is_owner = true`;
  await sql`CREATE INDEX IF NOT EXISTS idx_user_bank_links_user_favorite_bank ON user_bank_links (user_id, bank_id) WHERE is_favorite = true`;
  await sql`CREATE INDEX IF NOT EXISTS idx_question_import_jobs_user_created ON question_import_jobs (created_by, created_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_question_import_jobs_user_status_created ON question_import_jobs (created_by, status, created_at DESC)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_questions_status_type ON questions (status, question_type_id, id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_bank_question_links_bank_active ON bank_question_links (bank_id, sort_order, question_id) WHERE status = 'active'`;
  await sql`CREATE INDEX IF NOT EXISTS idx_bank_question_links_bank_status_sort ON bank_question_links (bank_id, status, sort_order, question_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_bank_group_links_bank_active ON bank_group_links (bank_id, sort_order, group_id) WHERE status = 'active'`;
  await sql`CREATE INDEX IF NOT EXISTS idx_bank_group_links_bank_status_sort ON bank_group_links (bank_id, status, sort_order, group_id)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_group_question_links_group_question_sort ON group_question_links (group_id, question_id, sort_order)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_questions_stem_fts ON questions USING GIN (to_tsvector('simple', COALESCE(stem, '')))`;
  await sql`CREATE INDEX IF NOT EXISTS idx_user_question_answers_user_session_question ON user_question_answers (user_id, session_id, question_id, answered_at)`;
  await sql`CREATE INDEX IF NOT EXISTS idx_user_question_stats_user_mastery ON user_question_stats (user_id, mastery_score, wrong_count DESC, last_answered_at DESC)`;
  await sql.unsafe(`DROP TABLE IF EXISTS ${['ali', 'pay_payment_orders'].join('')}`);
  await sql`
    CREATE TABLE IF NOT EXISTS billing_subscriptions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
      membership TEXT NOT NULL DEFAULT 'free',
      status TEXT NOT NULL DEFAULT 'inactive',
      source TEXT NOT NULL DEFAULT 'free',
      paddle_subscription_id VARCHAR(64),
      paddle_transaction_id VARCHAR(64),
      paddle_customer_id VARCHAR(64),
      paddle_price_id VARCHAR(64),
      current_period_starts_at TIMESTAMPTZ,
      current_period_ends_at TIMESTAMPTZ,
      scheduled_change_action VARCHAR(32),
      scheduled_change_effective_at TIMESTAMPTZ,
      raw_payload JSONB,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      CONSTRAINT chk_billing_subscriptions_membership CHECK (membership IN ('free', 'plus', 'enterprise')),
      CONSTRAINT chk_billing_subscriptions_status CHECK (status IN ('inactive', 'trialing', 'active', 'past_due', 'canceled')),
      CONSTRAINT chk_billing_subscriptions_source CHECK (source IN ('free', 'paddle')),
      CONSTRAINT chk_billing_subscriptions_period CHECK (
        current_period_starts_at IS NULL
        OR current_period_ends_at IS NULL
        OR current_period_ends_at > current_period_starts_at
      )
    )
  `;
  await sql`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'trg_billing_subscriptions_set_updated_at'
      ) THEN
        CREATE TRIGGER trg_billing_subscriptions_set_updated_at
        BEFORE UPDATE ON billing_subscriptions
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
      END IF;
    END
    $$;
  `;
  await sql`CREATE UNIQUE INDEX IF NOT EXISTS uq_billing_subscriptions_subscription_id ON billing_subscriptions (paddle_subscription_id) WHERE paddle_subscription_id IS NOT NULL`;
  await sql`CREATE INDEX IF NOT EXISTS idx_billing_subscriptions_customer_id ON billing_subscriptions (paddle_customer_id) WHERE paddle_customer_id IS NOT NULL`;
  await sql`CREATE INDEX IF NOT EXISTS idx_billing_subscriptions_status ON billing_subscriptions (status, updated_at DESC)`;
  await sql.end();
  console.log('OpenWook runtime schema is ready.');
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
