import { hash } from '@node-rs/bcrypt';
import { config } from 'dotenv';
import postgres from 'postgres';

config({ path: '.env.local' });
config();

async function seed() {
  const databaseUrl = process.env.POSTGRES_URL || process.env.DATABASE_URL;
  if (!databaseUrl) throw new Error('POSTGRES_URL or DATABASE_URL is required');

  const sql = postgres(databaseUrl, { max: 1 });
  const passwordHash = await hash('openwook123', 10);

  await sql.begin(async (tx) => {
    await tx`
      CREATE TABLE IF NOT EXISTS ai_artifacts (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        artifact_type VARCHAR(64) NOT NULL,
        user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
        bank_id BIGINT REFERENCES question_banks(id) ON DELETE SET NULL,
        question_id BIGINT REFERENCES questions(id) ON DELETE SET NULL,
        import_job_id BIGINT REFERENCES question_import_jobs(id) ON DELETE SET NULL,
        practice_session_id BIGINT,
        provider VARCHAR(64) NOT NULL DEFAULT 'mastra',
        model VARCHAR(128),
        input_payload JSONB NOT NULL DEFAULT '{}',
        output_payload JSONB NOT NULL DEFAULT '{}',
        status VARCHAR(32) NOT NULL DEFAULT 'completed',
        error_message TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `;
    await tx`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM pg_constraint WHERE conname = 'chk_ai_artifacts_type'
        ) THEN
          ALTER TABLE ai_artifacts
            ADD CONSTRAINT chk_ai_artifacts_type
            CHECK (artifact_type IN ('document_parse', 'answer_generation', 'learning_report'));
        END IF;
        IF NOT EXISTS (
          SELECT 1 FROM pg_constraint WHERE conname = 'chk_ai_artifacts_status'
        ) THEN
          ALTER TABLE ai_artifacts
            ADD CONSTRAINT chk_ai_artifacts_status
            CHECK (status IN ('completed', 'failed'));
        END IF;
        IF NOT EXISTS (
          SELECT 1 FROM pg_constraint WHERE conname = 'chk_ai_artifacts_payload_object'
        ) THEN
          ALTER TABLE ai_artifacts
            ADD CONSTRAINT chk_ai_artifacts_payload_object
            CHECK (jsonb_typeof(input_payload) = 'object' AND jsonb_typeof(output_payload) = 'object');
        END IF;
        IF to_regclass('user_practice_sessions') IS NOT NULL AND NOT EXISTS (
          SELECT 1 FROM pg_constraint WHERE conname = 'fk_ai_artifacts_practice_session'
        ) THEN
          ALTER TABLE ai_artifacts
            ADD CONSTRAINT fk_ai_artifacts_practice_session
            FOREIGN KEY (practice_session_id) REFERENCES user_practice_sessions(id) ON DELETE SET NULL;
        END IF;
      END
      $$;
    `;
    await tx`CREATE INDEX IF NOT EXISTS idx_ai_artifacts_question ON ai_artifacts (question_id, artifact_type, created_at DESC)`;
    await tx`CREATE INDEX IF NOT EXISTS idx_ai_artifacts_import_job ON ai_artifacts (import_job_id, artifact_type, created_at DESC)`;
    await tx`CREATE INDEX IF NOT EXISTS idx_ai_artifacts_user ON ai_artifacts (user_id, artifact_type, created_at DESC)`;

    const users = await tx<Array<{ id: number }>>`
      INSERT INTO users (username, email, password_hash, role, membership)
      VALUES ('admin', 'admin@openwook.local', ${passwordHash}, 'admin', 'plus')
      ON CONFLICT (LOWER(username)) DO UPDATE
      SET email = EXCLUDED.email,
          role = EXCLUDED.role,
          membership = EXCLUDED.membership
      RETURNING id
    `;
    const userId = users[0].id;

    const banks = await tx<Array<{ id: number }>>`
      INSERT INTO question_banks (name, description, subject, created_by, is_public)
      VALUES ('OpenWook 示例题库', '用于本地验证题库、题目、练习闭环。', 'general', ${userId}, true)
      ON CONFLICT DO NOTHING
      RETURNING id
    `;

    if (banks[0]) {
      await tx`
        INSERT INTO user_bank_links (user_id, bank_id, is_owner)
        VALUES (${userId}, ${banks[0].id}, true)
        ON CONFLICT (user_id, bank_id) DO UPDATE SET is_owner = true
      `;
    }
  });

  await sql.end();
  console.log('OpenWook seed complete. User: admin / openwook123');
}

seed()
  .catch((error) => {
    console.error('Seed process failed:', error);
    process.exit(1);
  })
  .finally(() => {
    console.log('Seed process finished. Exiting...');
    process.exit(0);
  });
