package com.practiq;
import static org.junit.jupiter.api.Assertions.*; import com.practiq.common.ApiException; import com.practiq.service.UploadSupport; import java.nio.file.*; import java.util.*; import org.junit.jupiter.api.Test;
class ImportMediaSliceTest {
 @Test void sniffsSupportedImagesAndRejectsMismatch(){assertEquals("image/png",UploadSupport.imageMime(new byte[]{(byte)137,80,78,71,13,10,26,10}));assertThrows(ApiException.class,()->UploadSupport.validateImport(".png","image/png","not-image".getBytes(),"x.png"));}
 @Test void validatesTextAndOfficeMagic(){UploadSupport.validateImport(".txt","text/plain","ready".getBytes(),"x.txt");assertThrows(ApiException.class,()->UploadSupport.validateImport(".docx","",new byte[]{1,2},"x.docx"));}
 @Test void storagePathStaysUnderMount()throws Exception{Path root=Files.createTempDirectory("practiq-test");assertTrue(UploadSupport.path(root.toString(),"imports/1/source.txt").startsWith(root));assertThrows(ApiException.class,()->UploadSupport.path(root.toString(),"../secret"));}
 @Test void sourceTypesCoverEveryUploadFormat(){assertEquals("image",UploadSupport.sourceType(".webp"));assertEquals("xlsx",UploadSupport.sourceType(".xlsx"));assertThrows(ApiException.class,()->UploadSupport.extension("x.exe","application/octet-stream"));}
 @Test void normalizesAiDocumentRequests(){String markdown="  # Quiz\n\n    code\n";for(String type:List.of("text","txt","md")){var request=UploadSupport.toAiDocumentRequest(type,"questions.md","text/markdown",("\ufeff"+markdown).getBytes(java.nio.charset.StandardCharsets.UTF_8));assertEquals("text",request.get("sourceType"));assertEquals(markdown,request.get("text"));assertFalse(request.containsKey("fileBase64"));}var csv=UploadSupport.toAiDocumentRequest("csv","questions.csv","text/csv","a,b\n1,2".getBytes(java.nio.charset.StandardCharsets.UTF_8));assertEquals("csv",csv.get("sourceType"));assertTrue(csv.containsKey("fileBase64"));assertFalse(csv.containsKey("text"));assertThrows(ApiException.class,()->UploadSupport.toAiDocumentRequest("rtf","x.rtf","",new byte[]{1}));}
}
