-- Purpose: Define normalized questions, bank/group question links, answer keys, and knowledge points.
-- PostgreSQL-only schema fragment. Apply after earlier numbered fragments in db/*/*.sql order.

CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_type TEXT NOT NULL DEFAULT 'standalone',
    subject_id VARCHAR(32) NOT NULL DEFAULT 'general' REFERENCES subjects(subject_id) ON DELETE RESTRICT,
    question_type_id VARCHAR(64) NOT NULL DEFAULT 'generic_answer_mode' REFERENCES question_types(type_id) ON DELETE RESTRICT,
    answer_mode TEXT NOT NULL,
    choice_variant TEXT,
    hierarchy_level INTEGER NOT NULL DEFAULT 1,
    hierarchy_path VARCHAR(512),
    chapter_ref VARCHAR(128),
    chapter_title VARCHAR(512),
    chapter_order INTEGER,
    content_mode VARCHAR(32),
    stem TEXT NOT NULL,
    analysis TEXT,
    detail_payload TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'draft',
    source_type TEXT NOT NULL DEFAULT 'parsed',
    source_ref VARCHAR(128),
    source_job_id BIGINT REFERENCES question_import_jobs(id) ON DELETE SET NULL,
    imported_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_questions_business_type_not_blank CHECK (btrim(business_type) <> ''),
    CONSTRAINT chk_questions_answer_mode CHECK (
        answer_mode IN ('choice', 'true_false', 'fill_blank', 'short_answer')
    ),
    CONSTRAINT chk_questions_choice_variant CHECK (
        choice_variant IS NULL OR choice_variant IN ('single', 'multiple')
    ),
    CONSTRAINT chk_questions_hierarchy_level CHECK (hierarchy_level >= 1),
    CONSTRAINT chk_questions_chapter_order CHECK (chapter_order IS NULL OR chapter_order > 0),
    CONSTRAINT chk_questions_content_mode CHECK (
        content_mode IS NULL OR content_mode IN ('text_only', 'mixed_media', 'structured_rich')
    ),
    CONSTRAINT chk_questions_stem_not_blank CHECK (btrim(stem) <> ''),
    CONSTRAINT chk_questions_status CHECK (status IN ('draft', 'active', 'archived')),
    CONSTRAINT chk_questions_source_type CHECK (source_type IN ('manual', 'imported', 'parsed')),
    CONSTRAINT fk_questions_subject_type
        FOREIGN KEY (subject_id, question_type_id)
        REFERENCES question_types(subject_id, type_id)
        ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_questions_id_subject ON questions (id, subject_id);
CREATE INDEX idx_questions_business_type ON questions (business_type);
CREATE INDEX idx_questions_subject_type ON questions (subject_id, question_type_id);
CREATE INDEX idx_questions_status_type ON questions (status, question_type_id, id);
CREATE INDEX idx_questions_content_mode ON questions (content_mode);
CREATE INDEX idx_questions_source_ref ON questions (source_type, source_ref);
CREATE INDEX idx_questions_source_job ON questions (source_job_id);
CREATE INDEX idx_questions_imported_by ON questions (imported_by);
CREATE INDEX idx_questions_chapter ON questions (chapter_ref, chapter_order);
CREATE INDEX idx_questions_stem_trgm ON questions USING GIN (stem gin_trgm_ops);
CREATE INDEX idx_questions_stem_fts ON questions USING GIN (to_tsvector('simple', COALESCE(stem, '')));

ALTER TABLE question_groups
    ADD COLUMN source_job_id BIGINT REFERENCES question_import_jobs(id) ON DELETE SET NULL;

CREATE INDEX idx_question_groups_source_job ON question_groups (source_job_id);

CREATE TRIGGER trg_questions_set_updated_at
BEFORE UPDATE ON questions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE bank_question_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id BIGINT NOT NULL REFERENCES question_banks(id) ON DELETE CASCADE,
    bank_subject VARCHAR(32) NOT NULL,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    question_subject_id VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 1,
    question_no VARCHAR(32),
    status TEXT NOT NULL DEFAULT 'draft',
    added_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_bank_question_links_bank_question UNIQUE (bank_id, question_id),
    CONSTRAINT uq_bank_question_links_bank_sort UNIQUE (bank_id, sort_order),
    CONSTRAINT uq_bank_question_links_bank_question_no UNIQUE (bank_id, question_no),
    CONSTRAINT chk_bank_question_links_sort_order CHECK (sort_order > 0),
    CONSTRAINT chk_bank_question_links_status CHECK (status IN ('draft', 'active', 'archived')),
    CONSTRAINT chk_bank_question_links_subject_match CHECK (bank_subject = question_subject_id),
    CONSTRAINT fk_bank_question_links_bank_subject
        FOREIGN KEY (bank_id, bank_subject)
        REFERENCES question_banks(id, subject)
        ON DELETE CASCADE,
    CONSTRAINT fk_bank_question_links_question_subject
        FOREIGN KEY (question_id, question_subject_id)
        REFERENCES questions(id, subject_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_bank_question_links_bank_sort ON bank_question_links (bank_id, sort_order);
CREATE INDEX idx_bank_question_links_bank_active
    ON bank_question_links (bank_id, sort_order, question_id)
    WHERE status = 'active';
CREATE INDEX idx_bank_question_links_bank_status_sort
    ON bank_question_links (bank_id, status, sort_order, question_id);
CREATE INDEX idx_bank_question_links_question_id ON bank_question_links (question_id);
CREATE UNIQUE INDEX uq_bank_question_links_id_question
    ON bank_question_links (id, question_id);

CREATE TRIGGER trg_bank_question_links_set_subjects
BEFORE INSERT OR UPDATE OF bank_id, question_id ON bank_question_links
FOR EACH ROW
EXECUTE FUNCTION set_bank_question_link_subjects();

CREATE TRIGGER trg_bank_question_links_set_updated_at
BEFORE UPDATE ON bank_question_links
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE bank_group_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id BIGINT NOT NULL REFERENCES question_banks(id) ON DELETE CASCADE,
    bank_subject VARCHAR(32) NOT NULL,
    group_id BIGINT NOT NULL REFERENCES question_groups(id) ON DELETE CASCADE,
    group_subject_id VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'draft',
    added_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_bank_group_links_bank_group UNIQUE (bank_id, group_id),
    CONSTRAINT uq_bank_group_links_bank_sort UNIQUE (bank_id, sort_order),
    CONSTRAINT chk_bank_group_links_sort_order CHECK (sort_order > 0),
    CONSTRAINT chk_bank_group_links_status CHECK (status IN ('draft', 'active', 'archived')),
    CONSTRAINT chk_bank_group_links_subject_match CHECK (bank_subject = group_subject_id),
    CONSTRAINT fk_bank_group_links_bank_subject
        FOREIGN KEY (bank_id, bank_subject)
        REFERENCES question_banks(id, subject)
        ON DELETE CASCADE,
    CONSTRAINT fk_bank_group_links_group_subject
        FOREIGN KEY (group_id, group_subject_id)
        REFERENCES question_groups(id, subject_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_bank_group_links_bank_sort ON bank_group_links (bank_id, sort_order);
CREATE INDEX idx_bank_group_links_bank_active
    ON bank_group_links (bank_id, sort_order, group_id)
    WHERE status = 'active';
CREATE INDEX idx_bank_group_links_bank_status_sort
    ON bank_group_links (bank_id, status, sort_order, group_id);
CREATE INDEX idx_bank_group_links_group_id ON bank_group_links (group_id);
CREATE UNIQUE INDEX uq_bank_group_links_id_group
    ON bank_group_links (id, group_id);

CREATE TRIGGER trg_bank_group_links_set_subjects
BEFORE INSERT OR UPDATE OF bank_id, group_id ON bank_group_links
FOR EACH ROW
EXECUTE FUNCTION set_bank_group_link_subjects();

CREATE TRIGGER trg_bank_group_links_set_updated_at
BEFORE UPDATE ON bank_group_links
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE group_question_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES question_groups(id) ON DELETE CASCADE,
    group_subject_id VARCHAR(32) NOT NULL,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    question_subject_id VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 1,
    question_no VARCHAR(32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_group_question_links_group_question UNIQUE (group_id, question_id),
    CONSTRAINT uq_group_question_links_group_sort UNIQUE (group_id, sort_order),
    CONSTRAINT uq_group_question_links_group_question_no UNIQUE (group_id, question_no),
    CONSTRAINT chk_group_question_links_sort_order CHECK (sort_order > 0),
    CONSTRAINT chk_group_question_links_subject_match CHECK (group_subject_id = question_subject_id),
    CONSTRAINT fk_group_question_links_group_subject
        FOREIGN KEY (group_id, group_subject_id)
        REFERENCES question_groups(id, subject_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_group_question_links_question_subject
        FOREIGN KEY (question_id, question_subject_id)
        REFERENCES questions(id, subject_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_group_question_links_group_sort ON group_question_links (group_id, sort_order);
CREATE INDEX idx_group_question_links_group_question_sort
    ON group_question_links (group_id, question_id, sort_order);
CREATE INDEX idx_group_question_links_question_id ON group_question_links (question_id);

CREATE TRIGGER trg_group_question_links_set_subjects
BEFORE INSERT OR UPDATE OF group_id, question_id ON group_question_links
FOR EACH ROW
EXECUTE FUNCTION set_group_question_link_subjects();

CREATE TRIGGER trg_group_question_links_set_updated_at
BEFORE UPDATE ON group_question_links
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_import_job_outputs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    output_kind VARCHAR(32) NOT NULL,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    confidence DOUBLE PRECISION,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_import_job_outputs_kind CHECK (
        output_kind = 'question'
    ),
    CONSTRAINT chk_question_import_job_outputs_confidence CHECK (
        confidence IS NULL OR confidence BETWEEN 0 AND 1
    )
);

CREATE UNIQUE INDEX uq_question_import_job_outputs_question
    ON question_import_job_outputs (job_id, question_id);

CREATE VIEW v_bank_question_items AS
SELECT
    bgl.bank_id,
    g.id AS group_id,
    q.id AS question_id,
    'grouped'::TEXT AS item_scope,
    bgl.sort_order AS bank_sort_order,
    gql.sort_order AS group_sort_order,
    gql.question_no AS question_no,
    bgl.status AS bank_link_status,
    q.business_type,
    q.subject_id,
    q.question_type_id,
    q.answer_mode,
    q.choice_variant,
    q.content_mode,
    q.stem,
    q.analysis,
    q.status AS question_status,
    g.title AS group_title,
    g.instructions AS group_instructions
FROM bank_group_links bgl
JOIN question_groups g ON g.id = bgl.group_id
JOIN group_question_links gql ON gql.group_id = g.id
JOIN questions q ON q.id = gql.question_id
UNION ALL
SELECT
    bql.bank_id,
    NULL::BIGINT AS group_id,
    q.id AS question_id,
    'standalone'::TEXT AS item_scope,
    bql.sort_order AS bank_sort_order,
    NULL::INTEGER AS group_sort_order,
    bql.question_no AS question_no,
    bql.status AS bank_link_status,
    q.business_type,
    q.subject_id,
    q.question_type_id,
    q.answer_mode,
    q.choice_variant,
    q.content_mode,
    q.stem,
    q.analysis,
    q.status AS question_status,
    NULL::TEXT AS group_title,
    NULL::TEXT AS group_instructions
FROM bank_question_links bql
JOIN questions q ON q.id = bql.question_id;

CREATE TABLE question_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    option_label VARCHAR(16) NOT NULL,
    sort_order SMALLINT NOT NULL DEFAULT 1,
    content TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_options_label_not_blank CHECK (btrim(option_label) <> ''),
    CONSTRAINT chk_question_options_sort_order CHECK (sort_order > 0),
    CONSTRAINT chk_question_options_content_not_blank CHECK (btrim(content) <> '')
);

CREATE UNIQUE INDEX uq_question_options_question_label ON question_options (question_id, option_label);
CREATE UNIQUE INDEX uq_question_options_question_sort ON question_options (question_id, sort_order);

CREATE TRIGGER trg_question_options_set_updated_at
BEFORE UPDATE ON question_options
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_answer_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    answer_mode VARCHAR(32) NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    is_primary BOOLEAN NOT NULL DEFAULT TRUE,
    answer_payload TEXT NOT NULL DEFAULT '{}',
    explanation_payload TEXT NOT NULL DEFAULT '{}',
    score_payload TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_answer_keys_question_version UNIQUE (question_id, version),
    CONSTRAINT chk_question_answer_keys_version CHECK (version > 0),
    CONSTRAINT chk_question_answer_keys_answer_mode CHECK (
        answer_mode IN ('choice', 'true_false', 'fill_blank', 'short_answer')
    )
);

CREATE UNIQUE INDEX uq_question_answer_keys_id_question
    ON question_answer_keys (id, question_id);
CREATE INDEX idx_question_answer_keys_question ON question_answer_keys (question_id, is_primary);
CREATE UNIQUE INDEX uq_question_answer_keys_primary
    ON question_answer_keys (question_id)
    WHERE is_primary;

CREATE TRIGGER trg_question_answer_keys_set_updated_at
BEFORE UPDATE ON question_answer_keys
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE knowledge_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id VARCHAR(32) NOT NULL REFERENCES subjects(subject_id) ON DELETE RESTRICT,
    code VARCHAR(128) NOT NULL,
    display_name VARCHAR(256) NOT NULL,
    parent_id BIGINT REFERENCES knowledge_points(id) ON DELETE SET NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_knowledge_points_subject_code UNIQUE (subject_id, code),
    CONSTRAINT chk_knowledge_points_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT chk_knowledge_points_name_not_blank CHECK (btrim(display_name) <> '')
);

CREATE UNIQUE INDEX uq_knowledge_points_id_subject ON knowledge_points (id, subject_id);
CREATE INDEX idx_knowledge_points_parent ON knowledge_points (parent_id);

CREATE TRIGGER trg_knowledge_points_set_updated_at
BEFORE UPDATE ON knowledge_points
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
