-- Purpose: Define media assets and rich content blocks attached to questions, options, and question groups.
-- PostgreSQL-only schema fragment. Apply after earlier numbered fragments in db/*/*.sql order.

CREATE TABLE media_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_path VARCHAR(512) NOT NULL UNIQUE,
    storage_disk TEXT NOT NULL DEFAULT 'local',
    external_url VARCHAR(1024),
    oss_bucket VARCHAR(128),
    oss_object_key VARCHAR(512),
    original_name VARCHAR(255),
    mime_type VARCHAR(64),
    width INTEGER,
    height INTEGER,
    size_bytes BIGINT,
    duration_ms INTEGER,
    checksum_sha256 VARCHAR(64),
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_media_assets_dimensions CHECK (
        (width IS NULL OR width > 0)
        AND (height IS NULL OR height > 0)
        AND (size_bytes IS NULL OR size_bytes >= 0)
        AND (duration_ms IS NULL OR duration_ms >= 0)
    )
);

CREATE TABLE question_media_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    media_id BIGINT NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE,
    media_kind TEXT NOT NULL,
    sort_order SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_media_links_sort UNIQUE (question_id, sort_order),
    CONSTRAINT uq_question_media_links_media UNIQUE (question_id, media_id, media_kind),
    CONSTRAINT chk_question_media_links_sort CHECK (sort_order > 0)
);

CREATE TABLE question_option_media_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_id BIGINT NOT NULL REFERENCES question_options(id) ON DELETE CASCADE,
    media_id BIGINT NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE,
    media_kind TEXT NOT NULL,
    sort_order SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_option_media_links_sort UNIQUE (option_id, sort_order),
    CONSTRAINT uq_question_option_media_links_media UNIQUE (option_id, media_id, media_kind),
    CONSTRAINT chk_question_option_media_links_sort CHECK (sort_order > 0)
);

CREATE TABLE question_group_media_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES question_groups(id) ON DELETE CASCADE,
    media_id BIGINT NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE,
    media_kind TEXT NOT NULL,
    sort_order SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_group_media_links_sort UNIQUE (group_id, sort_order),
    CONSTRAINT uq_question_group_media_links_media UNIQUE (group_id, media_id, media_kind),
    CONSTRAINT chk_question_group_media_links_sort CHECK (sort_order > 0)
);

CREATE TABLE question_content_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE,
    group_id BIGINT REFERENCES question_groups(id) ON DELETE CASCADE,
    option_id BIGINT REFERENCES question_options(id) ON DELETE CASCADE,
    media_id BIGINT REFERENCES media_assets(id) ON DELETE SET NULL,
    owner_kind VARCHAR(32) NOT NULL,
    role VARCHAR(64),
    part_type VARCHAR(32) NOT NULL,
    sequence INTEGER NOT NULL DEFAULT 1,
    content_mode VARCHAR(32),
    text_format VARCHAR(32),
    text_value TEXT,
    latex_value TEXT,
    mathml_value TEXT,
    html_value TEXT,
    markdown_value TEXT,
    json_value TEXT,
    source_url VARCHAR(1024),
    page_no INTEGER,
    bbox_json TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_content_blocks_owner_kind CHECK (
        owner_kind IN ('question', 'group', 'stem', 'option', 'answer_key', 'analysis', 'explanation')
    ),
    CONSTRAINT chk_question_content_blocks_part_type CHECK (
        part_type IN ('text', 'formula', 'image', 'table', 'list', 'html', 'markdown', 'chart', 'diagram', 'qr_code')
    ),
    CONSTRAINT chk_question_content_blocks_sequence CHECK (sequence > 0),
    CONSTRAINT chk_question_content_blocks_content_mode CHECK (
        content_mode IS NULL OR content_mode IN ('text_only', 'mixed_media', 'structured_rich')
    ),
    CONSTRAINT chk_question_content_blocks_owner_ref CHECK (
        (CASE WHEN question_id IS NOT NULL THEN 1 ELSE 0 END)
        + (CASE WHEN group_id IS NOT NULL THEN 1 ELSE 0 END)
        + (CASE WHEN option_id IS NOT NULL THEN 1 ELSE 0 END) = 1
    ),
    CONSTRAINT chk_question_content_blocks_owner_kind_ref CHECK (
        (owner_kind IN ('question', 'stem', 'answer_key', 'analysis', 'explanation') AND question_id IS NOT NULL)
        OR (owner_kind = 'group' AND group_id IS NOT NULL)
        OR (owner_kind = 'option' AND option_id IS NOT NULL)
    )
);

CREATE INDEX idx_question_content_blocks_question
    ON question_content_blocks (question_id, owner_kind, sequence);
CREATE INDEX idx_question_content_blocks_group
    ON question_content_blocks (group_id, owner_kind, sequence);
CREATE INDEX idx_question_content_blocks_option ON question_content_blocks (option_id, sequence);

CREATE TRIGGER trg_question_content_blocks_set_updated_at
BEFORE UPDATE ON question_content_blocks
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
