FROM python:3.14-slim
WORKDIR /app
COPY server/pyproject.toml /app/server/pyproject.toml
COPY server /app/server
RUN python -m pip install --no-cache-dir /app/server
COPY db /app/db
EXPOSE 3000
CMD ["python", "-m", "server"]
