FROM ghcr.io/astral-sh/uv:python3.14-bookworm-slim
WORKDIR /app
COPY server /app/server
RUN uv sync --frozen --no-dev --project /app/server
ENV PATH="/app/server/.venv/bin:$PATH"
EXPOSE 8080
CMD ["python", "-m", "server"]
