package com.practiq.auth;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.practiq.common.ApiException;
import com.practiq.service.MembershipService;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.time.*;
import java.util.*;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service public class AuthService {
 static final String ISS="practiq-api", AUD="practiq-mobile"; final JdbcTemplate jdbc; final MembershipService membership; final ObjectMapper json; final BCryptPasswordEncoder bcrypt=new BCryptPasswordEncoder(12); final String secret;
 public AuthService(JdbcTemplate jdbc, MembershipService membership, ObjectMapper json, @Value("${practiq.auth-secret}") String secret){this.jdbc=jdbc;this.membership=membership;this.json=json;this.secret=secret;if(secret==null||secret.isBlank())throw new IllegalStateException("AUTH_SECRET is required");}
 public record Tokens(String accessToken,String refreshToken,OffsetDateTime accessExpiresAt,OffsetDateTime refreshExpiresAt){}
 public Map<String,Object> register(String username,String email,String password){validate(username,email,password);try{Long id=jdbc.queryForObject("insert into users(username,email,password_hash,role,membership) values(?,?,?,'user','free') returning id",Long.class,username.trim(),normalizeEmail(email),bcrypt.encode(password));return issued(id,newSession(id));}catch(ApiException e){throw e;}catch(Exception e){throw ApiException.of(409,"USER_CONFLICT","User details conflict with an existing account");}}
 public Map<String,Object> login(String login,String password){if(login==null||password==null)throw ApiException.of(401,"UNAUTHENTICATED","Authentication required");var rows=jdbc.query("select id,password_hash,is_active from users where lower(username)=lower(?) or lower(email)=lower(?) limit 1",(rs,n)->Map.of("id",rs.getLong(1),"hash",Optional.ofNullable(rs.getString(2)).orElse(""),"active",rs.getBoolean(3)),login.trim(),login.trim());if(rows.isEmpty()||!bcrypt.matches(password,(String)rows.getFirst().get("hash")))throw ApiException.of(401,"UNAUTHENTICATED","Authentication required");if(!(Boolean)rows.getFirst().get("active"))throw ApiException.of(403,"USER_INACTIVE","User account is disabled");long id=(Long)rows.getFirst().get("id");return issued(id,newSession(id));}
 @Transactional public Map<String,Object> refresh(String raw){var rows=jdbc.query("select rt.id,rt.session_id,s.user_id,s.absolute_expires_at,rt.expires_at,rt.used_at,rt.revoked_at,s.revoked_at from refresh_tokens rt join auth_sessions s on s.id=rt.session_id where rt.token_hash=? for update",(rs,n)->new Object[]{rs.getObject(1,UUID.class),rs.getObject(2,UUID.class),rs.getLong(3),rs.getObject(4,OffsetDateTime.class),rs.getObject(5,OffsetDateTime.class),rs.getObject(6),rs.getObject(7),rs.getObject(8)},sha(raw));if(rows.isEmpty())throw invalidRefresh();Object[] x=rows.getFirst();var now=OffsetDateTime.now(ZoneOffset.UTC);if(x[5]!=null||x[6]!=null){jdbc.update("update auth_sessions set revoked_at=now(),revoke_reason='refresh_token_reuse' where id=? and revoked_at is null",x[1]);throw ApiException.of(401,"INVALID_REFRESH_TOKEN","Invalid refresh token");}if(x[7]!=null||!((OffsetDateTime)x[3]).isAfter(now)||!((OffsetDateTime)x[4]).isAfter(now))throw invalidRefresh();UUID next=UUID.randomUUID();String rawNext=randomToken();OffsetDateTime refreshExp=now.plusDays(30);if(refreshExp.isAfter((OffsetDateTime)x[3]))refreshExp=(OffsetDateTime)x[3];jdbc.update("insert into refresh_tokens(id,session_id,token_hash,parent_token_id,expires_at) values(?,?,?,?,?)",next,x[1],sha(rawNext),x[0],refreshExp);jdbc.update("update refresh_tokens set used_at=now(),replaced_by_token_id=? where id=?",next,x[0]);Tokens t=new Tokens(jwt((Long)x[2],(UUID)x[1],now.plusMinutes(10)),rawNext,now.plusMinutes(10),refreshExp);return issued((Long)x[2],t);}
 @Transactional public Map<String,Object> update(long id,String username,boolean emailSet,String email,String current,String next){if(username==null&&!emailSet&&next==null)throw validation("username, email, or newPassword is required");if(username!=null)validateUsername(username);if(emailSet&&email!=null)normalizeEmail(email);if(next!=null){validatePassword("newPassword",next);if(current==null||!passwordMatches(id,current))throw ApiException.of(401,"INVALID_CURRENT_PASSWORD","Current password is incorrect");}try{jdbc.update("update users set username=coalesce(?,username),email=case when ? then ? else email end,password_hash=case when ? then ? else password_hash end where id=?",username==null?null:username.trim(),emailSet,emailSet?(email==null?null:normalizeEmail(email)):null,next!=null,next==null?null:bcrypt.encode(next),id);if(next!=null)jdbc.update("update auth_sessions set revoked_at=now(),revoke_reason='password_changed' where user_id=? and revoked_at is null",id);return user(id);}catch(ApiException e){throw e;}catch(Exception e){throw ApiException.of(409,"USER_CONFLICT","User details conflict with an existing account");}}
 public Map<String,Object> user(long id){return jdbc.queryForObject("select id,username,email,is_active,role,membership,trial_ends_at,revenuecat_app_user_id from users where id=?",(rs,n)->{var trial=rs.getObject(7,OffsetDateTime.class);String m=rs.getString(6);var out=new LinkedHashMap<String,Object>();out.put("id",rs.getLong(1));out.put("username",rs.getString(2));out.put("email",rs.getString(3));out.put("avatarUrl",null);out.put("role",rs.getString(5));out.put("membership",m);out.put("effectiveMembership",membership.effective(m,trial));out.put("trialEndsAt",trial==null?null:trial.toString());out.put("revenuecatAppUserId",rs.getObject(8).toString());return out;},id);}
 public long require(String header){String token=header!=null&&header.startsWith("Bearer ")?header.substring(7):"";try{String[] p=token.split("\\.");if(p.length!=3||!MessageDigest.isEqual(Base64.getUrlDecoder().decode(p[2]),Base64.getUrlDecoder().decode(sig(p[0]+"."+p[1]))))throw new Exception();Map<String,Object> claims=json.readValue(Base64.getUrlDecoder().decode(p[1]),new TypeReference<>(){});if(!ISS.equals(claims.get("iss"))||!AUD.equals(claims.get("aud"))||!"at+jwt".equals(claims.get("typ")))throw new Exception();long id=Long.parseLong(String.valueOf(claims.get("sub")));UUID sid=UUID.fromString(String.valueOf(claims.get("sid")));long exp=((Number)claims.get("exp")).longValue();if(exp<=Instant.now().getEpochSecond()||jdbc.queryForObject("select count(*) from auth_sessions where id=? and user_id=? and revoked_at is null and absolute_expires_at>now()",Integer.class,sid,id)==0)throw new Exception();return id;}catch(Exception e){throw ApiException.of(401,"UNAUTHENTICATED","Authentication required");}}
 private Tokens newSession(long id){var now=OffsetDateTime.now(ZoneOffset.UTC);UUID sid=UUID.randomUUID();var absolute=now.plusDays(90);String refresh=randomToken();var refreshExp=now.plusDays(30);jdbc.update("insert into auth_sessions(id,user_id,absolute_expires_at) values(?,?,?)",sid,id,absolute);jdbc.update("insert into refresh_tokens(session_id,token_hash,expires_at) values(?,?,?)",sid,sha(refresh),refreshExp);return new Tokens(jwt(id,sid,now.plusMinutes(10)),refresh,now.plusMinutes(10),refreshExp);}
 private Map<String,Object> issued(long id,Tokens t){return Map.of("user",user(id),"tokens",Map.of("accessToken",t.accessToken,"refreshToken",t.refreshToken,"expiresAt",t.accessExpiresAt.toInstant().toString(),"refreshExpiresAt",t.refreshExpiresAt.toInstant().toString(),"tokenType","Bearer"));}
 private String jwt(long id,UUID sid,OffsetDateTime exp){try{Map<String,Object> h=Map.of("alg","HS256","typ","JWT");Map<String,Object> c=new LinkedHashMap<>();c.put("iss",ISS);c.put("aud",AUD);c.put("sub",String.valueOf(id));c.put("sid",sid.toString());c.put("typ","at+jwt");c.put("iat",Instant.now().getEpochSecond());c.put("exp",exp.toInstant().getEpochSecond());c.put("jti",UUID.randomUUID().toString());String a=b64(json.writeValueAsBytes(h)),b=b64(json.writeValueAsBytes(c));return a+"."+b+"."+sig(a+"."+b);}catch(Exception e){throw new IllegalStateException(e);}}
 private String sig(String s){try{Mac m=Mac.getInstance("HmacSHA256");m.init(new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));return b64(m.doFinal(s.getBytes(StandardCharsets.US_ASCII)));}catch(Exception e){throw new IllegalStateException(e);}} private String b64(byte[] x){return Base64.getUrlEncoder().withoutPadding().encodeToString(x);} private byte[] sha(String s){try{return MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));}catch(Exception e){throw new IllegalStateException(e);}} private String randomToken(){byte[] b=new byte[32];new SecureRandom().nextBytes(b);return b64(b);} private ApiException invalidRefresh(){return ApiException.of(401,"INVALID_REFRESH_TOKEN","Invalid refresh token");}
 private boolean passwordMatches(long id,String p){String h=jdbc.queryForObject("select password_hash from users where id=?",String.class,id);return h!=null&&bcrypt.matches(p,h);} private void validate(String u,String e,String p){validateUsername(u);normalizeEmail(e);validatePassword("password",p);} private void validateUsername(String u){if(u==null||!u.trim().matches("[A-Za-z0-9_]{3,20}"))throw validation("Must be 3-20 letters, numbers, or underscores");} private String normalizeEmail(String e){if(e==null||e.trim().length()>254||!e.trim().matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$"))throw validation("Must be a valid email address");return e.trim();} private void validatePassword(String field,String p){if(p==null||p.getBytes(StandardCharsets.UTF_8).length<8||p.getBytes(StandardCharsets.UTF_8).length>72)throw validation("Must be 8-72 bytes");} private ApiException validation(String m){return ApiException.of(422,"VALIDATION_ERROR","Invalid request",List.of(Map.of("field","body","message",m)));}
}
