-- Purpose: Define practice sessions, user answers, and per-question learning stats.
-- PostgreSQL-only schema fragment. Apply after earlier numbered fragments in db/*/*.sql order.

CREATE TABLE user_practice_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bank_id BIGINT REFERENCES question_banks(id) ON DELETE SET NULL,
    session_type VARCHAR(32) NOT NULL DEFAULT 'practice',
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    question_count INTEGER NOT NULL DEFAULT 0,
    answered_count INTEGER NOT NULL DEFAULT 0,
    correct_count INTEGER NOT NULL DEFAULT 0,
    wrong_count INTEGER NOT NULL DEFAULT 0,
    score DOUBLE PRECISION,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_user_practice_sessions_type CHECK (
        session_type IN ('practice', 'review', 'exam')
    ),
    CONSTRAINT chk_user_practice_sessions_status CHECK (
        status IN ('active', 'completed', 'abandoned')
    ),
    CONSTRAINT chk_user_practice_sessions_counts CHECK (
        question_count >= 0
        AND answered_count >= 0
        AND correct_count >= 0
        AND wrong_count >= 0
        AND answered_count <= question_count
        AND correct_count <= answered_count
        AND wrong_count <= answered_count
    ),
    CONSTRAINT chk_user_practice_sessions_score CHECK (
        score IS NULL OR score >= 0
    ),
    CONSTRAINT chk_user_practice_sessions_completed_at CHECK (
        (status = 'active' AND completed_at IS NULL)
        OR (status IN ('completed', 'abandoned') AND completed_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_user_practice_sessions_id_user
    ON user_practice_sessions (id, user_id);
CREATE INDEX idx_user_practice_sessions_user_started
    ON user_practice_sessions (user_id, started_at DESC);
CREATE INDEX idx_user_practice_sessions_bank
    ON user_practice_sessions (bank_id, status);

CREATE TRIGGER trg_user_practice_sessions_set_updated_at
BEFORE UPDATE ON user_practice_sessions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

ALTER TABLE ai_artifacts
    ADD CONSTRAINT fk_ai_artifacts_practice_session
    FOREIGN KEY (practice_session_id) REFERENCES user_practice_sessions(id) ON DELETE SET NULL;

CREATE TABLE user_question_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id BIGINT,
    bank_id BIGINT REFERENCES question_banks(id) ON DELETE SET NULL,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    answer_key_id BIGINT,
    answer_payload JSONB NOT NULL,
    is_correct BOOLEAN,
    score DOUBLE PRECISION,
    max_score DOUBLE PRECISION,
    duration_ms INTEGER,
    answered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_user_question_answers_payload_object CHECK (jsonb_typeof(answer_payload) = 'object'),
    CONSTRAINT chk_user_question_answers_score CHECK (
        (score IS NULL OR score >= 0)
        AND (max_score IS NULL OR max_score >= 0)
        AND (score IS NULL OR max_score IS NULL OR score <= max_score)
    ),
    CONSTRAINT chk_user_question_answers_duration CHECK (
        duration_ms IS NULL OR duration_ms >= 0
    ),
    CONSTRAINT fk_user_question_answers_session_user
        FOREIGN KEY (session_id, user_id)
        REFERENCES user_practice_sessions(id, user_id),
    CONSTRAINT fk_user_question_answers_answer_key_question
        FOREIGN KEY (answer_key_id, question_id)
        REFERENCES question_answer_keys(id, question_id)
);

CREATE UNIQUE INDEX uq_user_question_answers_id_user_question
    ON user_question_answers (id, user_id, question_id);
CREATE INDEX idx_user_question_answers_user_question_answered_at
    ON user_question_answers (user_id, question_id, answered_at DESC);
CREATE INDEX idx_user_question_answers_question_id ON user_question_answers (question_id);
CREATE INDEX idx_user_question_answers_session
    ON user_question_answers (session_id, answered_at);
CREATE INDEX idx_user_question_answers_user_session_question
    ON user_question_answers (user_id, session_id, question_id, answered_at);
CREATE INDEX idx_user_question_answers_bank
    ON user_question_answers (bank_id, user_id, answered_at DESC);

CREATE TRIGGER trg_user_question_answers_apply_stats
AFTER INSERT ON user_question_answers
FOR EACH ROW
EXECUTE FUNCTION apply_user_question_answer_stats();

CREATE TABLE user_question_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    correct_count INTEGER NOT NULL DEFAULT 0,
    wrong_count INTEGER NOT NULL DEFAULT 0,
    last_answer_id BIGINT,
    last_answered_at TIMESTAMPTZ,
    last_is_correct BOOLEAN,
    mastery_score DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_user_question_stats_user_question UNIQUE (user_id, question_id),
    CONSTRAINT chk_user_question_stats_counts CHECK (
        attempt_count >= 0
        AND correct_count >= 0
        AND wrong_count >= 0
        AND correct_count <= attempt_count
        AND wrong_count <= attempt_count
    ),
    CONSTRAINT chk_user_question_stats_mastery CHECK (
        mastery_score IS NULL OR mastery_score BETWEEN 0 AND 1
    ),
    CONSTRAINT fk_user_question_stats_last_answer
        FOREIGN KEY (last_answer_id, user_id, question_id)
        REFERENCES user_question_answers(id, user_id, question_id)
);

CREATE INDEX idx_user_question_stats_question
    ON user_question_stats (question_id);
CREATE INDEX idx_user_question_stats_last_answered
    ON user_question_stats (user_id, last_answered_at DESC);
CREATE INDEX idx_user_question_stats_user_mastery
    ON user_question_stats (user_id, mastery_score, wrong_count DESC, last_answered_at DESC);

CREATE TRIGGER trg_user_question_stats_set_updated_at
BEFORE UPDATE ON user_question_stats
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
