-- Purpose: Define durable question-import jobs, artifacts, and event history.
-- PostgreSQL-only schema fragment. Apply after earlier numbered fragments in db/*/*.sql order.

CREATE TABLE question_import_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    bank_id BIGINT REFERENCES question_banks(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    stage TEXT NOT NULL DEFAULT 'queued',
    available_at TIMESTAMPTZ,
    persist_questions BOOLEAN NOT NULL DEFAULT true,
    request_payload TEXT NOT NULL DEFAULT '{}',
    raw_result_json TEXT,
    warning_messages TEXT NOT NULL DEFAULT '[]',
    error_payload TEXT,
    total_questions INTEGER NOT NULL DEFAULT 0,
    imported_questions INTEGER NOT NULL DEFAULT 0,
    file_name VARCHAR(255),
    source_type TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    claim_version BIGINT NOT NULL DEFAULT 0,
    quality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    last_error_code TEXT,
    last_error TEXT,
    overall_progress_percent DOUBLE PRECISION,
    step_progress_percent DOUBLE PRECISION,
    last_event_id BIGINT,
    last_event_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT chk_question_import_jobs_status CHECK (status IN ('queued', 'processing', 'completed', 'failed', 'cancelled')),
    CONSTRAINT chk_question_import_jobs_counts CHECK (
        total_questions >= 0
        AND imported_questions >= 0
        AND imported_questions <= total_questions
        AND retry_count >= 0
        AND claim_version >= 0
    ),
    CONSTRAINT chk_question_import_jobs_progress CHECK (
        quality_score BETWEEN 0 AND 100
        AND (overall_progress_percent IS NULL OR overall_progress_percent BETWEEN 0 AND 100)
        AND (step_progress_percent IS NULL OR step_progress_percent BETWEEN 0 AND 100)
    ),
    CONSTRAINT chk_question_import_jobs_available_at CHECK (
        status = 'queued' OR available_at IS NULL
    ),
    CONSTRAINT chk_question_import_jobs_completed_at CHECK (
        (status IN ('completed', 'failed', 'cancelled') AND completed_at IS NOT NULL)
        OR (status IN ('queued', 'processing') AND completed_at IS NULL)
    )
);

CREATE INDEX idx_question_import_jobs_status_stage ON question_import_jobs (status, stage);
CREATE INDEX idx_question_import_jobs_ready
    ON question_import_jobs (available_at, id)
    WHERE status = 'queued' AND available_at IS NOT NULL;
CREATE INDEX idx_question_import_jobs_user_created
    ON question_import_jobs (created_by, created_at DESC);
CREATE INDEX idx_question_import_jobs_user_status_created
    ON question_import_jobs (created_by, status, created_at DESC);

CREATE TRIGGER trg_question_import_jobs_set_updated_at
BEFORE UPDATE ON question_import_jobs
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_import_job_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    artifact_type TEXT NOT NULL,
    storage_path VARCHAR(512),
    content_json TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_import_job_artifacts_content CHECK (
        storage_path IS NOT NULL OR content_json IS NOT NULL
    )
);

CREATE UNIQUE INDEX uq_question_import_job_artifacts_source
    ON question_import_job_artifacts (job_id)
    WHERE artifact_type = 'source_file';

CREATE TABLE question_import_job_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    stage VARCHAR(64) NOT NULL,
    step_code VARCHAR(64) NOT NULL,
    step_label VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    message TEXT,
    overall_progress_percent DOUBLE PRECISION,
    step_progress_percent DOUBLE PRECISION,
    target_kind VARCHAR(64),
    target_name VARCHAR(512),
    payload_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_import_job_events_status CHECK (
        status IN ('queued', 'processing', 'completed', 'failed', 'cancelled', 'warning', 'info')
    ),
    CONSTRAINT chk_question_import_job_events_progress CHECK (
        (overall_progress_percent IS NULL OR overall_progress_percent BETWEEN 0 AND 100)
        AND (step_progress_percent IS NULL OR step_progress_percent BETWEEN 0 AND 100)
    )
);

CREATE INDEX idx_question_import_job_events_job_id
    ON question_import_job_events (job_id, id);
CREATE INDEX idx_question_import_job_events_step_code
    ON question_import_job_events (job_id, step_code, created_at);
CREATE UNIQUE INDEX uq_question_import_job_events_id_job
    ON question_import_job_events (id, job_id);

ALTER TABLE question_import_jobs
    ADD CONSTRAINT fk_question_import_jobs_last_event
    FOREIGN KEY (last_event_id, id) REFERENCES question_import_job_events(id, job_id);
