-- Purpose: Define AI/document question-import jobs, batches, artifacts, blocks, attempts, review items, events, and outbox rows.
-- PostgreSQL-only schema fragment. Apply after earlier numbered fragments in db/*/*.sql order.

CREATE TABLE question_import_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    bank_id BIGINT REFERENCES question_banks(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    stage TEXT NOT NULL DEFAULT 'queued',
    request_payload TEXT NOT NULL DEFAULT '{}',
    raw_result_json TEXT,
    warning_messages TEXT NOT NULL DEFAULT '[]',
    error_payload TEXT,
    total_questions INTEGER NOT NULL DEFAULT 0,
    imported_questions INTEGER NOT NULL DEFAULT 0,
    file_name VARCHAR(255),
    source_type TEXT,
    conversion_id VARCHAR(64),
    page_count INTEGER NOT NULL DEFAULT 0,
    wave_count INTEGER NOT NULL DEFAULT 0,
    failed_block_count INTEGER NOT NULL DEFAULT 0,
    block_count INTEGER NOT NULL DEFAULT 0,
    completed_block_count INTEGER NOT NULL DEFAULT 0,
    retry_count INTEGER NOT NULL DEFAULT 0,
    coverage_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
    quality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    high_risk_block_count INTEGER NOT NULL DEFAULT 0,
    review_item_count INTEGER NOT NULL DEFAULT 0,
    last_error_code TEXT,
    risk_level TEXT NOT NULL DEFAULT 'low',
    last_error TEXT,
    current_step_code VARCHAR(64),
    current_step_label VARCHAR(128),
    overall_progress_percent DOUBLE PRECISION,
    step_progress_percent DOUBLE PRECISION,
    current_target_kind VARCHAR(64),
    current_target_name VARCHAR(512),
    last_event_id BIGINT,
    last_event_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT chk_question_import_jobs_status CHECK (status IN ('queued', 'processing', 'completed', 'failed')),
    CONSTRAINT chk_question_import_jobs_totals_nonnegative CHECK (
        total_questions >= 0
        AND imported_questions >= 0
        AND page_count >= 0
        AND wave_count >= 0
        AND failed_block_count >= 0
        AND block_count >= 0
        AND completed_block_count >= 0
        AND retry_count >= 0
        AND high_risk_block_count >= 0
        AND review_item_count >= 0
    ),
    CONSTRAINT chk_question_import_jobs_counts_consistent CHECK (
        imported_questions <= total_questions
        AND completed_block_count <= block_count
        AND failed_block_count <= block_count
        AND high_risk_block_count <= block_count
    ),
    CONSTRAINT chk_question_import_jobs_progress_range CHECK (
        coverage_percent BETWEEN 0 AND 100
        AND quality_score BETWEEN 0 AND 100
        AND (overall_progress_percent IS NULL OR overall_progress_percent BETWEEN 0 AND 100)
        AND (step_progress_percent IS NULL OR step_progress_percent BETWEEN 0 AND 100)
    ),
    CONSTRAINT chk_question_import_jobs_completed_at CHECK (
        (status IN ('completed', 'failed') AND completed_at IS NOT NULL)
        OR (status IN ('queued', 'processing') AND completed_at IS NULL)
    ),
    CONSTRAINT chk_question_import_jobs_risk_level CHECK (risk_level IN ('low', 'medium', 'high'))
);

CREATE INDEX idx_question_import_jobs_status_stage ON question_import_jobs (status, stage);
CREATE INDEX idx_question_import_jobs_conversion_id ON question_import_jobs (conversion_id);
CREATE INDEX idx_question_import_jobs_user_created
    ON question_import_jobs (created_by, created_at DESC);
CREATE INDEX idx_question_import_jobs_user_status_created
    ON question_import_jobs (created_by, status, created_at DESC);

CREATE TRIGGER trg_question_import_jobs_set_updated_at
BEFORE UPDATE ON question_import_jobs
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_import_job_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    wave_index INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    total_blocks INTEGER NOT NULL DEFAULT 0,
    completed_blocks INTEGER NOT NULL DEFAULT 0,
    failed_blocks INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_import_job_batches_job_wave UNIQUE (job_id, wave_index),
    CONSTRAINT chk_question_import_job_batches_status CHECK (status IN ('queued', 'processing', 'completed', 'failed')),
    CONSTRAINT chk_question_import_job_batches_counts CHECK (
        wave_index > 0
        AND total_blocks >= 0
        AND completed_blocks >= 0
        AND failed_blocks >= 0
        AND completed_blocks <= total_blocks
        AND failed_blocks <= total_blocks
    )
);

CREATE INDEX idx_question_import_job_batches_status ON question_import_job_batches (status, next_attempt_at);

CREATE TRIGGER trg_question_import_job_batches_set_updated_at
BEFORE UPDATE ON question_import_job_batches
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_import_job_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    artifact_type TEXT NOT NULL,
    storage_path VARCHAR(512),
    content_json TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_import_job_artifacts_content CHECK (
        storage_path IS NOT NULL OR content_json IS NOT NULL
    )
);

CREATE TABLE question_import_job_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    page_no INTEGER NOT NULL,
    layout_json TEXT,
    complexity_score DOUBLE PRECISION,
    coverage_status TEXT NOT NULL DEFAULT 'pending',
    render_profile TEXT,
    analysis_status TEXT NOT NULL DEFAULT 'queued',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_import_job_pages_job_page UNIQUE (job_id, page_no),
    CONSTRAINT chk_question_import_job_pages_page_no CHECK (page_no > 0),
    CONSTRAINT chk_question_import_job_pages_coverage_status CHECK (
        coverage_status IN ('pending', 'partial', 'covered', 'failed')
    ),
    CONSTRAINT chk_question_import_job_pages_analysis_status CHECK (
        analysis_status IN ('queued', 'processing', 'completed', 'failed')
    )
);

CREATE INDEX idx_question_import_job_pages_job_status ON question_import_job_pages (job_id, analysis_status);

CREATE TRIGGER trg_question_import_job_pages_set_updated_at
BEFORE UPDATE ON question_import_job_pages
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_import_job_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    batch_id BIGINT REFERENCES question_import_job_batches(id) ON DELETE SET NULL,
    block_id VARCHAR(128) NOT NULL,
    block_type TEXT NOT NULL,
    page_start INTEGER,
    page_end INTEGER,
    char_start INTEGER,
    char_end INTEGER,
    bbox_json TEXT,
    scene_hint TEXT,
    group_ref_hint TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    parser_profile TEXT NOT NULL DEFAULT 'standard',
    dpi INTEGER,
    status TEXT NOT NULL DEFAULT 'queued',
    retry_count INTEGER NOT NULL DEFAULT 0,
    selected_attempt_id BIGINT,
    risk_level TEXT NOT NULL DEFAULT 'low',
    confidence DOUBLE PRECISION,
    coverage DOUBLE PRECISION,
    error_message TEXT,
    next_attempt_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT uq_question_import_job_blocks_job_block UNIQUE (job_id, block_id),
    CONSTRAINT chk_question_import_job_blocks_status CHECK (status IN ('queued', 'processing', 'completed', 'failed', 'needs_review')),
    CONSTRAINT chk_question_import_job_blocks_retry_count CHECK (retry_count >= 0),
    CONSTRAINT chk_question_import_job_blocks_location CHECK (
        (page_start IS NULL OR page_start > 0)
        AND (page_end IS NULL OR page_end > 0)
        AND (page_start IS NULL OR page_end IS NULL OR page_start <= page_end)
        AND (char_start IS NULL OR char_start >= 0)
        AND (char_end IS NULL OR char_end >= 0)
        AND (char_start IS NULL OR char_end IS NULL OR char_start <= char_end)
    ),
    CONSTRAINT chk_question_import_job_blocks_scores CHECK (
        (confidence IS NULL OR confidence BETWEEN 0 AND 1)
        AND (coverage IS NULL OR coverage BETWEEN 0 AND 1)
    ),
    CONSTRAINT chk_question_import_job_blocks_completed_at CHECK (
        (status IN ('completed', 'failed') AND completed_at IS NOT NULL)
        OR (status IN ('queued', 'processing', 'needs_review') AND completed_at IS NULL)
    ),
    CONSTRAINT chk_question_import_job_blocks_risk_level CHECK (risk_level IN ('low', 'medium', 'high'))
);

CREATE INDEX idx_question_import_job_blocks_job_status ON question_import_job_blocks (job_id, status, next_attempt_at);
CREATE INDEX idx_question_import_job_blocks_batch_status ON question_import_job_blocks (batch_id, status);

CREATE TRIGGER trg_question_import_job_blocks_set_updated_at
BEFORE UPDATE ON question_import_job_blocks
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_import_job_block_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_id BIGINT NOT NULL REFERENCES question_import_job_blocks(id) ON DELETE CASCADE,
    attempt_no INTEGER NOT NULL,
    parser_profile TEXT NOT NULL,
    dpi INTEGER,
    raw_output_json TEXT,
    issues_json TEXT,
    confidence DOUBLE PRECISION,
    coverage DOUBLE PRECISION,
    quality_score DOUBLE PRECISION,
    error_payload TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_import_job_block_attempts UNIQUE (block_id, attempt_no),
    CONSTRAINT chk_question_import_job_block_attempts_attempt_no CHECK (attempt_no > 0),
    CONSTRAINT chk_question_import_job_block_attempts_scores CHECK (
        (confidence IS NULL OR confidence BETWEEN 0 AND 1)
        AND (coverage IS NULL OR coverage BETWEEN 0 AND 1)
        AND (quality_score IS NULL OR quality_score BETWEEN 0 AND 100)
    )
);

CREATE UNIQUE INDEX uq_question_import_job_block_attempts_id_block
    ON question_import_job_block_attempts (id, block_id);

CREATE TABLE question_import_job_review_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    severity TEXT NOT NULL,
    code TEXT NOT NULL,
    payload_json TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'open',
    resolved_by BIGINT,
    resolution_note TEXT,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_import_job_review_items_status CHECK (status IN ('open', 'resolved')),
    CONSTRAINT chk_question_import_job_review_items_severity CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    CONSTRAINT chk_question_import_job_review_items_resolution CHECK (
        (status = 'open' AND resolved_at IS NULL)
        OR (status = 'resolved' AND resolved_at IS NOT NULL)
    ),
    CONSTRAINT fk_question_import_job_review_items_resolved_by
        FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_question_import_job_review_items_job_status
    ON question_import_job_review_items (job_id, status, severity);

CREATE TRIGGER trg_question_import_job_review_items_set_updated_at
BEFORE UPDATE ON question_import_job_review_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_import_job_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    stage VARCHAR(64) NOT NULL,
    step_code VARCHAR(64) NOT NULL,
    step_label VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    message TEXT,
    overall_progress_percent DOUBLE PRECISION,
    step_progress_percent DOUBLE PRECISION,
    target_kind VARCHAR(64),
    target_name VARCHAR(512),
    payload_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_import_job_events_status CHECK (
        status IN ('queued', 'processing', 'completed', 'failed', 'warning', 'info')
    ),
    CONSTRAINT chk_question_import_job_events_progress CHECK (
        (overall_progress_percent IS NULL OR overall_progress_percent BETWEEN 0 AND 100)
        AND (step_progress_percent IS NULL OR step_progress_percent BETWEEN 0 AND 100)
    )
);

CREATE INDEX idx_question_import_job_events_job_id
    ON question_import_job_events (job_id, id);

CREATE INDEX idx_question_import_job_events_step_code
    ON question_import_job_events (job_id, step_code, created_at);
CREATE UNIQUE INDEX uq_question_import_job_events_id_job
    ON question_import_job_events (id, job_id);

CREATE TABLE question_import_outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT REFERENCES question_import_jobs(id) ON DELETE SET NULL,
    job_event_id BIGINT REFERENCES question_import_job_events(id) ON DELETE SET NULL,
    event_type VARCHAR(80) NOT NULL,
    routing_key VARCHAR(120) NOT NULL,
    payload_json TEXT NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'pending',
    retry_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    next_attempt_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_import_outbox_events_status CHECK (
        status IN ('pending', 'processing', 'published', 'failed')
    ),
    CONSTRAINT chk_question_import_outbox_events_retry_count CHECK (retry_count >= 0),
    CONSTRAINT chk_question_import_outbox_events_published_at CHECK (
        (status = 'published' AND published_at IS NOT NULL)
        OR (status <> 'published')
    )
);

CREATE INDEX idx_question_import_outbox_events_status
    ON question_import_outbox_events (status, next_attempt_at, created_at);
CREATE INDEX idx_question_import_outbox_events_job
    ON question_import_outbox_events (job_id, job_event_id);

CREATE TRIGGER trg_question_import_outbox_events_set_updated_at
BEFORE UPDATE ON question_import_outbox_events
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

ALTER TABLE question_import_jobs
    ADD CONSTRAINT fk_question_import_jobs_last_event
    FOREIGN KEY (last_event_id, id) REFERENCES question_import_job_events(id, job_id);

ALTER TABLE question_import_job_blocks
    ADD CONSTRAINT fk_question_import_job_blocks_selected_attempt
    FOREIGN KEY (selected_attempt_id, id) REFERENCES question_import_job_block_attempts(id, block_id);
