import { Button } from "@taroify/core";
import { Input, Text, View } from "@tarojs/components";
import Taro from "@tarojs/taro";
import { useCallback, useState } from "react";
import { api } from "../../../api";
import type { PracticeQuestionPage } from "../../../api/modules";
import { errorMessage } from "../../../api/message";
import { QuestionContent } from "../../../components/QuestionContent";
import { ErrorNotice, Page, PageHeader, Section, StateView, StickyActions, confirmDanger } from "../../../components/ui";
import { routeNumber } from "../../../navigation";

export default function PracticeSessionPage(): JSX.Element {
  const id = routeNumber("id"); const [page, setPage] = useState<PracticeQuestionPage | null>(null); const [selected, setSelected] = useState<string[]>([]); const [text, setText] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false);
  const load = useCallback(async (index?: number) => { if (!id) { setMessage("练习参数无效"); setLoading(false); return; } setLoading(true); setMessage(""); try { setPage(await api.practice.page(id, index ?? 0)); setSelected([]); setText(""); } catch (error) { setMessage(errorMessage(error)); } finally { setLoading(false); } }, [id]); Taro.useDidShow(() => { if (!page) void load(); });
  if (loading && !page) return <Page><StateView phase="loading" title="正在准备题目" detail="练习马上开始。" /></Page>; if (!page) return <Page><StateView phase="error" title="练习无法继续" detail={message} actionLabel="重试" onAction={() => void load()} /></Page>;
  const questionId = page.question.question_id ?? page.question.id; const exam = page.session.session_type === "exam"; const answered = Boolean(page.result);
  const submit = async () => { if (!id) return; let payload: Record<string, unknown>; if (page.question.answer_mode === "choice") payload = { selected }; else if (page.question.answer_mode === "true_false") payload = { value: text === "true" }; else if (page.question.answer_mode === "fill_blank") payload = { value: text.split(/[,，]/).map((item) => item.trim()).filter(Boolean) }; else payload = { value: text }; setSubmitting(true); setMessage(""); try { await api.practice.answer(id, { questionId, answerPayload: payload }); await load(page.questionIndex); } catch (error) { setMessage(errorMessage(error)); } finally { setSubmitting(false); } };
  const complete = async () => { if (!id) return; if (await confirmDanger("结束练习", exam ? "交卷后才能查看考试答案，确定交卷吗？" : "未作答题目将保留为空，确定结束吗？", exam ? "交卷" : "结束")) { try { await api.practice.complete(id); await Taro.redirectTo({ url: `/packages/practice/results/index?id=${id}` }); } catch (error) { setMessage(errorMessage(error)); } } };
  return <Page className="safe-bottom"><PageHeader eyebrow={`${page.questionIndex + 1} / ${page.total}`} title={exam ? "考试模式" : "在线练习"} subtitle={`已完成 ${page.answeredCount} 题`} />{message ? <ErrorNotice>{message}</ErrorNotice> : null}<Section title="题目"><View className="form-card app-stack"><QuestionContent question={page.question} revealAnswer={!exam && answered} />{!answered ? <AnswerEditor page={page} selected={selected} setSelected={setSelected} text={text} setText={setText} /> : !exam ? <Text className="app-muted">{page.result?.is_correct === true ? "回答正确" : page.result?.is_correct === false ? "回答错误，请查看解析" : "答案已提交"}</Text> : <Text className="app-muted">答案已记录，交卷前不显示判定。</Text>}</View></Section><StickyActions><Button disabled={page.previousIndex == null} onClick={() => void load(page.previousIndex ?? 0)}>上一题</Button>{!answered ? <Button color="primary" loading={submitting} onClick={() => void submit()}>提交答案</Button> : null}{page.nextIndex != null ? <Button color="primary" onClick={() => void load(page.nextIndex!)}>下一题</Button> : <Button color="primary" onClick={() => void complete()}>{exam ? "交卷" : "完成"}</Button>}</StickyActions></Page>;
}
function AnswerEditor({ page, selected, setSelected, text, setText }: { page: PracticeQuestionPage; selected: string[]; setSelected: (value: string[]) => void; text: string; setText: (value: string) => void }): JSX.Element {
  const question = page.question; if (question.answer_mode === "choice") return <View className="app-stack">{question.options.map((option) => { const active = selected.includes(option.option_label); return <View key={option.option_label} className={`answer-option ${active ? "answer-option-active" : ""}`} onClick={() => setSelected(question.choice_variant === "single" ? [option.option_label] : active ? selected.filter((item) => item !== option.option_label) : [...selected, option.option_label])}><Text className="form-label">{option.option_label}</Text><Text>{option.content}</Text></View>; })}</View>;
  if (question.answer_mode === "true_false") return <View className="button-row"><Button color={text === "true" ? "primary" : "default"} onClick={() => setText("true")}>正确</Button><Button color={text === "false" ? "primary" : "default"} onClick={() => setText("false")}>错误</Button></View>;
  return <Input className="form-input" value={text} placeholder={question.answer_mode === "fill_blank" ? "多空用逗号分隔" : "输入你的答案"} onInput={(event) => setText(event.detail.value)} />;
}
