// Generated by app/scripts/export-contracts.py. Do not edit.
pub const COMPOSITE_MODES: &[&str] = &["cloze", "gap_fill", "listening", "reading", "word_bank"];
pub const FILTER_MODES: &[&str] = &[
    "",
    "choice",
    "cloze",
    "fill_blank",
    "gap_fill",
    "grammar_fill",
    "listening",
    "matching",
    "multiple",
    "ordering",
    "paragraph_matching",
    "reading",
    "sentence_selection",
    "short_answer",
    "single",
    "translation",
    "true_false",
    "word_bank",
    "writing",
];
pub const QUESTION_KIND_MODES: &[(&str, &str)] = &[
    ("listening", "listening"),
    ("reading", "reading"),
    ("word_bank", "word_bank"),
    ("cloze", "cloze"),
    ("grammar_fill", "gap_fill"),
    ("sentence_selection", "word_bank"),
    ("paragraph_matching", "matching"),
    ("translation", "short_answer"),
    ("writing", "short_answer"),
];
pub const COMPOSITE_SQL: &str = "'cloze','gap_fill','listening','reading','word_bank'";
