-- Purpose: Define subjects, question types, question banks, bank ownership/favorites, and bank-level practice stats.
-- PostgreSQL-only schema fragment. Apply after earlier numbered fragments in db/*/*.sql order.

CREATE TABLE subjects (
    subject_id VARCHAR(32) PRIMARY KEY,
    display_name VARCHAR(64) NOT NULL,
    CONSTRAINT chk_subjects_subject_id_not_blank CHECK (btrim(subject_id) <> ''),
    CONSTRAINT chk_subjects_display_name_not_blank CHECK (btrim(display_name) <> '')
);

INSERT INTO subjects (subject_id, display_name) VALUES
    ('english', 'English'),
    ('math', 'Math'),
    ('physics', 'Physics'),
    ('chemistry', 'Chemistry'),
    ('general', 'General');

CREATE TABLE question_types (
    type_id VARCHAR(64) PRIMARY KEY,
    subject_id VARCHAR(32) NOT NULL REFERENCES subjects(subject_id) ON DELETE RESTRICT,
    display_name VARCHAR(128) NOT NULL,
    scope VARCHAR(16) NOT NULL DEFAULT 'question',
    default_answer_mode VARCHAR(32),
    CONSTRAINT chk_question_types_type_id_not_blank CHECK (btrim(type_id) <> ''),
    CONSTRAINT chk_question_types_display_name_not_blank CHECK (btrim(display_name) <> ''),
    CONSTRAINT chk_question_types_scope CHECK (scope IN ('question', 'group', 'hybrid')),
    CONSTRAINT chk_question_types_answer_mode CHECK (
        default_answer_mode IS NULL
        OR default_answer_mode IN ('choice', 'true_false', 'fill_blank', 'short_answer')
    )
);

CREATE UNIQUE INDEX uq_question_types_subject_type ON question_types (subject_id, type_id);

INSERT INTO question_types (type_id, subject_id, display_name, scope, default_answer_mode) VALUES
    ('generic_answer_mode', 'general', 'Generic Answer Mode', 'hybrid', NULL),
    ('math_proof', 'math', 'Math Proof', 'question', 'short_answer'),
    ('math_geometry', 'math', 'Math Geometry', 'question', 'short_answer'),
    ('math_calculation', 'math', 'Math Calculation', 'question', 'short_answer'),
    ('physics_experiment', 'physics', 'Physics Experiment', 'question', 'short_answer'),
    ('physics_diagram', 'physics', 'Physics Diagram', 'question', 'short_answer'),
    ('physics_calculation', 'physics', 'Physics Calculation', 'question', 'short_answer'),
    ('chemistry_reaction', 'chemistry', 'Chemistry Reaction', 'question', 'short_answer'),
    ('chemistry_experiment', 'chemistry', 'Chemistry Experiment', 'question', 'short_answer'),
    ('chemistry_calculation', 'chemistry', 'Chemistry Calculation', 'question', 'short_answer');

CREATE TABLE question_banks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    subject VARCHAR(32) NOT NULL REFERENCES subjects(subject_id) ON DELETE RESTRICT,
    total_count INTEGER NOT NULL DEFAULT 0,
    created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_banks_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT chk_question_banks_subject_not_blank CHECK (btrim(subject) <> ''),
    CONSTRAINT chk_question_banks_total_count_nonnegative CHECK (total_count >= 0)
);

CREATE UNIQUE INDEX uq_question_banks_id_subject ON question_banks (id, subject);
CREATE INDEX idx_question_banks_name ON question_banks (name);
CREATE INDEX idx_question_banks_subject ON question_banks (subject);
CREATE INDEX idx_question_banks_created_at ON question_banks (created_at);
CREATE INDEX idx_question_banks_created_by ON question_banks (created_by);
CREATE INDEX idx_question_banks_is_public ON question_banks (is_public);

CREATE TRIGGER trg_question_banks_set_updated_at
BEFORE UPDATE ON question_banks
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_type TEXT NOT NULL DEFAULT 'standalone',
    subject_id VARCHAR(32) NOT NULL DEFAULT 'general' REFERENCES subjects(subject_id) ON DELETE RESTRICT,
    group_type_id VARCHAR(64) NOT NULL DEFAULT 'generic_answer_mode' REFERENCES question_types(type_id) ON DELETE RESTRICT,
    parent_group_id BIGINT REFERENCES question_groups(id) ON DELETE SET NULL,
    hierarchy_level INTEGER NOT NULL DEFAULT 1,
    hierarchy_path VARCHAR(512),
    chapter_ref VARCHAR(128),
    chapter_title VARCHAR(512),
    chapter_order INTEGER,
    title TEXT,
    instructions TEXT,
    source_ref VARCHAR(128),
    content_mode VARCHAR(32),
    detail_payload TEXT NOT NULL DEFAULT '{}',
    imported_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_groups_business_type_not_blank CHECK (btrim(business_type) <> ''),
    CONSTRAINT chk_question_groups_hierarchy_level CHECK (hierarchy_level >= 1),
    CONSTRAINT chk_question_groups_chapter_order CHECK (chapter_order IS NULL OR chapter_order > 0),
    CONSTRAINT chk_question_groups_content_mode CHECK (
        content_mode IS NULL OR content_mode IN ('text_only', 'mixed_media', 'structured_rich')
    ),
    CONSTRAINT fk_question_groups_subject_type
        FOREIGN KEY (subject_id, group_type_id)
        REFERENCES question_types(subject_id, type_id)
        ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_question_groups_id_subject ON question_groups (id, subject_id);
CREATE INDEX idx_question_groups_business_type ON question_groups (business_type);
CREATE INDEX idx_question_groups_subject_type ON question_groups (subject_id, group_type_id);
CREATE INDEX idx_question_groups_content_mode ON question_groups (content_mode);
CREATE INDEX idx_question_groups_source_ref ON question_groups (source_ref);
CREATE INDEX idx_question_groups_parent_group ON question_groups (parent_group_id);
CREATE INDEX idx_question_groups_imported_by ON question_groups (imported_by);
CREATE INDEX idx_question_groups_chapter ON question_groups (chapter_ref, chapter_order);

CREATE TRIGGER trg_question_groups_set_updated_at
BEFORE UPDATE ON question_groups
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE user_bank_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bank_id BIGINT NOT NULL REFERENCES question_banks(id) ON DELETE CASCADE,
    is_owner BOOLEAN NOT NULL DEFAULT FALSE,
    is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_user_bank_links_has_relation CHECK (is_owner OR is_favorite)
);

CREATE UNIQUE INDEX uq_user_bank_links_user_bank ON user_bank_links (user_id, bank_id);
CREATE INDEX idx_user_bank_links_bank_id ON user_bank_links (bank_id);
CREATE INDEX idx_user_bank_links_owner ON user_bank_links (is_owner);
CREATE INDEX idx_user_bank_links_favorite ON user_bank_links (is_favorite);
CREATE INDEX idx_user_bank_links_user_owner_bank
    ON user_bank_links (user_id, bank_id)
    WHERE is_owner = true;
CREATE INDEX idx_user_bank_links_user_favorite_bank
    ON user_bank_links (user_id, bank_id)
    WHERE is_favorite = true;

CREATE TRIGGER trg_user_bank_links_set_updated_at
BEFORE UPDATE ON user_bank_links
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE user_bank_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bank_id BIGINT NOT NULL REFERENCES question_banks(id) ON DELETE CASCADE,
    completed_count INTEGER NOT NULL DEFAULT 0,
    wrong_count INTEGER NOT NULL DEFAULT 0,
    last_practiced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_user_bank_stats_completed_nonnegative CHECK (completed_count >= 0),
    CONSTRAINT chk_user_bank_stats_wrong_nonnegative CHECK (wrong_count >= 0)
);

CREATE UNIQUE INDEX uq_user_bank_stats_user_bank ON user_bank_stats (user_id, bank_id);
CREATE INDEX idx_user_bank_stats_bank_id ON user_bank_stats (bank_id);
CREATE INDEX idx_user_bank_stats_last_practiced_at ON user_bank_stats (last_practiced_at);

CREATE TRIGGER trg_user_bank_stats_set_updated_at
BEFORE UPDATE ON user_bank_stats
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
