-- OpenWook Database Schema
-- Merged from previous split files (00_functions.sql ~ 50_user_answers.sql)

-- ============================================================
-- 00_functions.sql
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION set_bank_question_link_subjects()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT subject INTO NEW.bank_subject
    FROM question_banks
    WHERE id = NEW.bank_id;

    SELECT subject_id INTO NEW.question_subject_id
    FROM questions
    WHERE id = NEW.question_id;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION set_bank_group_link_subjects()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT subject INTO NEW.bank_subject
    FROM question_banks
    WHERE id = NEW.bank_id;

    SELECT subject_id INTO NEW.group_subject_id
    FROM question_groups
    WHERE id = NEW.group_id;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION set_question_knowledge_point_link_subjects()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT subject_id INTO NEW.question_subject_id
    FROM questions
    WHERE id = NEW.question_id;

    SELECT subject_id INTO NEW.knowledge_point_subject_id
    FROM knowledge_points
    WHERE id = NEW.knowledge_point_id;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION set_group_question_link_subjects()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT subject_id INTO NEW.group_subject_id
    FROM question_groups
    WHERE id = NEW.group_id;

    SELECT subject_id INTO NEW.question_subject_id
    FROM questions
    WHERE id = NEW.question_id;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION apply_user_question_answer_stats()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO user_question_stats (
        user_id,
        question_id,
        attempt_count,
        correct_count,
        wrong_count,
        last_answer_id,
        last_answered_at,
        last_is_correct,
        mastery_score
    )
    VALUES (
        NEW.user_id,
        NEW.question_id,
        1,
        CASE WHEN NEW.is_correct IS TRUE THEN 1 ELSE 0 END,
        CASE WHEN NEW.is_correct IS FALSE THEN 1 ELSE 0 END,
        NEW.id,
        NEW.answered_at,
        NEW.is_correct,
        CASE
            WHEN NEW.is_correct IS TRUE THEN 1
            WHEN NEW.is_correct IS FALSE THEN 0
            ELSE NULL
        END
    )
    ON CONFLICT (user_id, question_id) DO UPDATE SET
        attempt_count = user_question_stats.attempt_count + 1,
        correct_count = user_question_stats.correct_count + CASE WHEN NEW.is_correct IS TRUE THEN 1 ELSE 0 END,
        wrong_count = user_question_stats.wrong_count + CASE WHEN NEW.is_correct IS FALSE THEN 1 ELSE 0 END,
        last_answer_id = NEW.id,
        last_answered_at = NEW.answered_at,
        last_is_correct = NEW.is_correct,
        mastery_score = CASE
            WHEN (user_question_stats.attempt_count + 1) > 0
            THEN (
                user_question_stats.correct_count + CASE WHEN NEW.is_correct IS TRUE THEN 1 ELSE 0 END
            )::DOUBLE PRECISION / (user_question_stats.attempt_count + 1)
            ELSE NULL
        END,
        updated_at = NOW();

    IF NEW.bank_id IS NOT NULL THEN
        INSERT INTO user_bank_stats (
            user_id,
            bank_id,
            completed_count,
            wrong_count,
            last_practiced_at
        )
        VALUES (
            NEW.user_id,
            NEW.bank_id,
            1,
            CASE WHEN NEW.is_correct IS FALSE THEN 1 ELSE 0 END,
            NEW.answered_at
        )
        ON CONFLICT (user_id, bank_id) DO UPDATE SET
            completed_count = user_bank_stats.completed_count + 1,
            wrong_count = user_bank_stats.wrong_count + CASE WHEN NEW.is_correct IS FALSE THEN 1 ELSE 0 END,
            last_practiced_at = NEW.answered_at,
            updated_at = NOW();
    END IF;

    IF NEW.session_id IS NOT NULL THEN
        UPDATE user_practice_sessions
        SET
            answered_count = answered_count + 1,
            correct_count = correct_count + CASE WHEN NEW.is_correct IS TRUE THEN 1 ELSE 0 END,
            wrong_count = wrong_count + CASE WHEN NEW.is_correct IS FALSE THEN 1 ELSE 0 END,
            updated_at = NOW()
        WHERE id = NEW.session_id
          AND user_id = NEW.user_id;
    END IF;

    RETURN NEW;
END;
$$;

-- ============================================================
-- 10_users.sql
-- ============================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) NOT NULL,
    email VARCHAR(254),
    password VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    role TEXT NOT NULL DEFAULT 'user',
    membership TEXT NOT NULL DEFAULT 'free',
    plus_trial_ends_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '3 days'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_users_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT chk_users_role CHECK (role IN ('admin', 'user')),
    CONSTRAINT chk_users_membership CHECK (membership IN ('free', 'plus'))
);

CREATE UNIQUE INDEX uq_users_username_lower ON users (LOWER(username));
CREATE UNIQUE INDEX uq_users_email_lower ON users (LOWER(email)) WHERE email IS NOT NULL;

CREATE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE users IS '用户表';
COMMENT ON COLUMN users.username IS '用户名';
COMMENT ON COLUMN users.email IS '邮箱';
COMMENT ON COLUMN users.password IS '密码哈希';
COMMENT ON COLUMN users.is_active IS '是否启用';
COMMENT ON COLUMN users.role IS '系统角色，admin / user';
COMMENT ON COLUMN users.membership IS '会员类型，free / plus';
COMMENT ON COLUMN users.plus_trial_ends_at IS 'Plus 试用到期时间，新注册用户默认 3 天';

-- ============================================================
-- 20_question_banks.sql
-- ============================================================

CREATE TABLE subjects (
    subject_id VARCHAR(32) PRIMARY KEY,
    display_name VARCHAR(64) NOT NULL,
    CONSTRAINT chk_subjects_subject_id_not_blank CHECK (btrim(subject_id) <> ''),
    CONSTRAINT chk_subjects_display_name_not_blank CHECK (btrim(display_name) <> '')
);

INSERT INTO subjects (subject_id, display_name) VALUES
    ('english', 'English'),
    ('math', 'Math'),
    ('physics', 'Physics'),
    ('chemistry', 'Chemistry'),
    ('general', 'General');

CREATE TABLE question_types (
    type_id VARCHAR(64) PRIMARY KEY,
    subject_id VARCHAR(32) NOT NULL REFERENCES subjects(subject_id) ON DELETE RESTRICT,
    display_name VARCHAR(128) NOT NULL,
    scope VARCHAR(16) NOT NULL DEFAULT 'question',
    default_answer_mode VARCHAR(32),
    CONSTRAINT chk_question_types_type_id_not_blank CHECK (btrim(type_id) <> ''),
    CONSTRAINT chk_question_types_display_name_not_blank CHECK (btrim(display_name) <> ''),
    CONSTRAINT chk_question_types_scope CHECK (scope IN ('question', 'group', 'hybrid')),
    CONSTRAINT chk_question_types_answer_mode CHECK (
        default_answer_mode IS NULL
        OR default_answer_mode IN ('choice', 'true_false', 'fill_blank', 'short_answer')
    )
);

CREATE UNIQUE INDEX uq_question_types_subject_type ON question_types (subject_id, type_id);

INSERT INTO question_types (type_id, subject_id, display_name, scope, default_answer_mode) VALUES
    ('generic_answer_mode', 'general', 'Generic Answer Mode', 'hybrid', NULL),
    ('math_proof', 'math', 'Math Proof', 'question', 'short_answer'),
    ('math_geometry', 'math', 'Math Geometry', 'question', 'short_answer'),
    ('math_calculation', 'math', 'Math Calculation', 'question', 'short_answer'),
    ('physics_experiment', 'physics', 'Physics Experiment', 'question', 'short_answer'),
    ('physics_diagram', 'physics', 'Physics Diagram', 'question', 'short_answer'),
    ('physics_calculation', 'physics', 'Physics Calculation', 'question', 'short_answer'),
    ('chemistry_reaction', 'chemistry', 'Chemistry Reaction', 'question', 'short_answer'),
    ('chemistry_experiment', 'chemistry', 'Chemistry Experiment', 'question', 'short_answer'),
    ('chemistry_calculation', 'chemistry', 'Chemistry Calculation', 'question', 'short_answer');

CREATE TABLE question_banks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    subject VARCHAR(32) NOT NULL REFERENCES subjects(subject_id) ON DELETE RESTRICT,
    total_count INTEGER NOT NULL DEFAULT 0,
    created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_banks_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT chk_question_banks_subject_not_blank CHECK (btrim(subject) <> ''),
    CONSTRAINT chk_question_banks_total_count_nonnegative CHECK (total_count >= 0)
);

CREATE UNIQUE INDEX uq_question_banks_id_subject ON question_banks (id, subject);
CREATE INDEX idx_question_banks_name ON question_banks (name);
CREATE INDEX idx_question_banks_subject ON question_banks (subject);
CREATE INDEX idx_question_banks_created_at ON question_banks (created_at);
CREATE INDEX idx_question_banks_created_by ON question_banks (created_by);
CREATE INDEX idx_question_banks_is_public ON question_banks (is_public);

CREATE TRIGGER trg_question_banks_set_updated_at
BEFORE UPDATE ON question_banks
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_type TEXT NOT NULL DEFAULT 'standalone',
    subject_id VARCHAR(32) NOT NULL DEFAULT 'general' REFERENCES subjects(subject_id) ON DELETE RESTRICT,
    group_type_id VARCHAR(64) NOT NULL DEFAULT 'generic_answer_mode' REFERENCES question_types(type_id) ON DELETE RESTRICT,
    parent_group_id BIGINT REFERENCES question_groups(id) ON DELETE SET NULL,
    hierarchy_level INTEGER NOT NULL DEFAULT 1,
    hierarchy_path VARCHAR(512),
    chapter_ref VARCHAR(128),
    chapter_title VARCHAR(512),
    chapter_order INTEGER,
    title TEXT,
    instructions TEXT,
    source_ref VARCHAR(128),
    content_mode VARCHAR(32),
    detail_payload TEXT NOT NULL DEFAULT '{}',
    imported_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_groups_business_type_not_blank CHECK (btrim(business_type) <> ''),
    CONSTRAINT chk_question_groups_hierarchy_level CHECK (hierarchy_level >= 1),
    CONSTRAINT chk_question_groups_chapter_order CHECK (chapter_order IS NULL OR chapter_order > 0),
    CONSTRAINT chk_question_groups_content_mode CHECK (
        content_mode IS NULL OR content_mode IN ('text_only', 'mixed_media', 'structured_rich')
    ),
    CONSTRAINT fk_question_groups_subject_type
        FOREIGN KEY (subject_id, group_type_id)
        REFERENCES question_types(subject_id, type_id)
        ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_question_groups_id_subject ON question_groups (id, subject_id);
CREATE INDEX idx_question_groups_business_type ON question_groups (business_type);
CREATE INDEX idx_question_groups_subject_type ON question_groups (subject_id, group_type_id);
CREATE INDEX idx_question_groups_content_mode ON question_groups (content_mode);
CREATE INDEX idx_question_groups_source_ref ON question_groups (source_ref);
CREATE INDEX idx_question_groups_parent_group ON question_groups (parent_group_id);
CREATE INDEX idx_question_groups_imported_by ON question_groups (imported_by);
CREATE INDEX idx_question_groups_chapter ON question_groups (chapter_ref, chapter_order);

CREATE TRIGGER trg_question_groups_set_updated_at
BEFORE UPDATE ON question_groups
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE user_bank_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bank_id BIGINT NOT NULL REFERENCES question_banks(id) ON DELETE CASCADE,
    is_owner BOOLEAN NOT NULL DEFAULT FALSE,
    is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_user_bank_links_has_relation CHECK (is_owner OR is_favorite)
);

CREATE UNIQUE INDEX uq_user_bank_links_user_bank ON user_bank_links (user_id, bank_id);
CREATE INDEX idx_user_bank_links_bank_id ON user_bank_links (bank_id);
CREATE INDEX idx_user_bank_links_owner ON user_bank_links (is_owner);
CREATE INDEX idx_user_bank_links_favorite ON user_bank_links (is_favorite);

CREATE TRIGGER trg_user_bank_links_set_updated_at
BEFORE UPDATE ON user_bank_links
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE user_bank_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bank_id BIGINT NOT NULL REFERENCES question_banks(id) ON DELETE CASCADE,
    completed_count INTEGER NOT NULL DEFAULT 0,
    wrong_count INTEGER NOT NULL DEFAULT 0,
    last_practiced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_user_bank_stats_completed_nonnegative CHECK (completed_count >= 0),
    CONSTRAINT chk_user_bank_stats_wrong_nonnegative CHECK (wrong_count >= 0)
);

CREATE UNIQUE INDEX uq_user_bank_stats_user_bank ON user_bank_stats (user_id, bank_id);
CREATE INDEX idx_user_bank_stats_bank_id ON user_bank_stats (bank_id);
CREATE INDEX idx_user_bank_stats_last_practiced_at ON user_bank_stats (last_practiced_at);

CREATE TRIGGER trg_user_bank_stats_set_updated_at
BEFORE UPDATE ON user_bank_stats
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- 25_question_import_jobs.sql
-- ============================================================

CREATE TABLE question_import_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    bank_id BIGINT REFERENCES question_banks(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    stage TEXT NOT NULL DEFAULT 'queued',
    request_payload TEXT NOT NULL DEFAULT '{}',
    raw_result_json TEXT,
    warning_messages TEXT NOT NULL DEFAULT '[]',
    error_payload TEXT,
    total_questions INTEGER NOT NULL DEFAULT 0,
    imported_questions INTEGER NOT NULL DEFAULT 0,
    file_name VARCHAR(255),
    source_type TEXT,
    conversion_id VARCHAR(64),
    page_count INTEGER NOT NULL DEFAULT 0,
    wave_count INTEGER NOT NULL DEFAULT 0,
    failed_block_count INTEGER NOT NULL DEFAULT 0,
    block_count INTEGER NOT NULL DEFAULT 0,
    completed_block_count INTEGER NOT NULL DEFAULT 0,
    retry_count INTEGER NOT NULL DEFAULT 0,
    coverage_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
    quality_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    high_risk_block_count INTEGER NOT NULL DEFAULT 0,
    review_item_count INTEGER NOT NULL DEFAULT 0,
    last_error_code TEXT,
    risk_level TEXT NOT NULL DEFAULT 'low',
    last_error TEXT,
    current_step_code VARCHAR(64),
    current_step_label VARCHAR(128),
    overall_progress_percent DOUBLE PRECISION,
    step_progress_percent DOUBLE PRECISION,
    current_target_kind VARCHAR(64),
    current_target_name VARCHAR(512),
    last_event_id BIGINT,
    last_event_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT chk_question_import_jobs_status CHECK (status IN ('queued', 'processing', 'completed', 'failed')),
    CONSTRAINT chk_question_import_jobs_totals_nonnegative CHECK (
        total_questions >= 0
        AND imported_questions >= 0
        AND page_count >= 0
        AND wave_count >= 0
        AND failed_block_count >= 0
        AND block_count >= 0
        AND completed_block_count >= 0
        AND retry_count >= 0
        AND high_risk_block_count >= 0
        AND review_item_count >= 0
    ),
    CONSTRAINT chk_question_import_jobs_counts_consistent CHECK (
        imported_questions <= total_questions
        AND completed_block_count <= block_count
        AND failed_block_count <= block_count
        AND high_risk_block_count <= block_count
    ),
    CONSTRAINT chk_question_import_jobs_progress_range CHECK (
        coverage_percent BETWEEN 0 AND 100
        AND quality_score BETWEEN 0 AND 100
        AND (overall_progress_percent IS NULL OR overall_progress_percent BETWEEN 0 AND 100)
        AND (step_progress_percent IS NULL OR step_progress_percent BETWEEN 0 AND 100)
    ),
    CONSTRAINT chk_question_import_jobs_completed_at CHECK (
        (status IN ('completed', 'failed') AND completed_at IS NOT NULL)
        OR (status IN ('queued', 'processing') AND completed_at IS NULL)
    ),
    CONSTRAINT chk_question_import_jobs_risk_level CHECK (risk_level IN ('low', 'medium', 'high'))
);

CREATE INDEX idx_question_import_jobs_status_stage ON question_import_jobs (status, stage);
CREATE INDEX idx_question_import_jobs_conversion_id ON question_import_jobs (conversion_id);

CREATE TRIGGER trg_question_import_jobs_set_updated_at
BEFORE UPDATE ON question_import_jobs
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_import_job_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    wave_index INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'queued',
    total_blocks INTEGER NOT NULL DEFAULT 0,
    completed_blocks INTEGER NOT NULL DEFAULT 0,
    failed_blocks INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_import_job_batches_job_wave UNIQUE (job_id, wave_index),
    CONSTRAINT chk_question_import_job_batches_status CHECK (status IN ('queued', 'processing', 'completed', 'failed')),
    CONSTRAINT chk_question_import_job_batches_counts CHECK (
        wave_index > 0
        AND total_blocks >= 0
        AND completed_blocks >= 0
        AND failed_blocks >= 0
        AND completed_blocks <= total_blocks
        AND failed_blocks <= total_blocks
    )
);

CREATE INDEX idx_question_import_job_batches_status ON question_import_job_batches (status, next_attempt_at);

CREATE TRIGGER trg_question_import_job_batches_set_updated_at
BEFORE UPDATE ON question_import_job_batches
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_import_job_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    artifact_type TEXT NOT NULL,
    storage_path VARCHAR(512),
    content_json TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_import_job_artifacts_content CHECK (
        storage_path IS NOT NULL OR content_json IS NOT NULL
    )
);

CREATE TABLE question_import_job_pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    page_no INTEGER NOT NULL,
    layout_json TEXT,
    complexity_score DOUBLE PRECISION,
    coverage_status TEXT NOT NULL DEFAULT 'pending',
    render_profile TEXT,
    analysis_status TEXT NOT NULL DEFAULT 'queued',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_import_job_pages_job_page UNIQUE (job_id, page_no),
    CONSTRAINT chk_question_import_job_pages_page_no CHECK (page_no > 0),
    CONSTRAINT chk_question_import_job_pages_coverage_status CHECK (
        coverage_status IN ('pending', 'partial', 'covered', 'failed')
    ),
    CONSTRAINT chk_question_import_job_pages_analysis_status CHECK (
        analysis_status IN ('queued', 'processing', 'completed', 'failed')
    )
);

CREATE INDEX idx_question_import_job_pages_job_status ON question_import_job_pages (job_id, analysis_status);

CREATE TRIGGER trg_question_import_job_pages_set_updated_at
BEFORE UPDATE ON question_import_job_pages
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_import_job_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    batch_id BIGINT REFERENCES question_import_job_batches(id) ON DELETE SET NULL,
    block_id VARCHAR(128) NOT NULL,
    block_type TEXT NOT NULL,
    page_start INTEGER,
    page_end INTEGER,
    char_start INTEGER,
    char_end INTEGER,
    bbox_json TEXT,
    scene_hint TEXT,
    group_ref_hint TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    parser_profile TEXT NOT NULL DEFAULT 'standard',
    dpi INTEGER,
    status TEXT NOT NULL DEFAULT 'queued',
    retry_count INTEGER NOT NULL DEFAULT 0,
    selected_attempt_id BIGINT,
    risk_level TEXT NOT NULL DEFAULT 'low',
    confidence DOUBLE PRECISION,
    coverage DOUBLE PRECISION,
    error_message TEXT,
    next_attempt_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT uq_question_import_job_blocks_job_block UNIQUE (job_id, block_id),
    CONSTRAINT chk_question_import_job_blocks_status CHECK (status IN ('queued', 'processing', 'completed', 'failed', 'needs_review')),
    CONSTRAINT chk_question_import_job_blocks_retry_count CHECK (retry_count >= 0),
    CONSTRAINT chk_question_import_job_blocks_location CHECK (
        (page_start IS NULL OR page_start > 0)
        AND (page_end IS NULL OR page_end > 0)
        AND (page_start IS NULL OR page_end IS NULL OR page_start <= page_end)
        AND (char_start IS NULL OR char_start >= 0)
        AND (char_end IS NULL OR char_end >= 0)
        AND (char_start IS NULL OR char_end IS NULL OR char_start <= char_end)
    ),
    CONSTRAINT chk_question_import_job_blocks_scores CHECK (
        (confidence IS NULL OR confidence BETWEEN 0 AND 1)
        AND (coverage IS NULL OR coverage BETWEEN 0 AND 1)
    ),
    CONSTRAINT chk_question_import_job_blocks_completed_at CHECK (
        (status IN ('completed', 'failed') AND completed_at IS NOT NULL)
        OR (status IN ('queued', 'processing', 'needs_review') AND completed_at IS NULL)
    ),
    CONSTRAINT chk_question_import_job_blocks_risk_level CHECK (risk_level IN ('low', 'medium', 'high'))
);

CREATE INDEX idx_question_import_job_blocks_job_status ON question_import_job_blocks (job_id, status, next_attempt_at);
CREATE INDEX idx_question_import_job_blocks_batch_status ON question_import_job_blocks (batch_id, status);

CREATE TRIGGER trg_question_import_job_blocks_set_updated_at
BEFORE UPDATE ON question_import_job_blocks
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_import_job_block_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_id BIGINT NOT NULL REFERENCES question_import_job_blocks(id) ON DELETE CASCADE,
    attempt_no INTEGER NOT NULL,
    parser_profile TEXT NOT NULL,
    dpi INTEGER,
    raw_output_json TEXT,
    issues_json TEXT,
    confidence DOUBLE PRECISION,
    coverage DOUBLE PRECISION,
    quality_score DOUBLE PRECISION,
    error_payload TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_import_job_block_attempts UNIQUE (block_id, attempt_no),
    CONSTRAINT chk_question_import_job_block_attempts_attempt_no CHECK (attempt_no > 0),
    CONSTRAINT chk_question_import_job_block_attempts_scores CHECK (
        (confidence IS NULL OR confidence BETWEEN 0 AND 1)
        AND (coverage IS NULL OR coverage BETWEEN 0 AND 1)
        AND (quality_score IS NULL OR quality_score BETWEEN 0 AND 100)
    )
);

CREATE UNIQUE INDEX uq_question_import_job_block_attempts_id_block
    ON question_import_job_block_attempts (id, block_id);

CREATE TABLE question_import_job_review_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    severity TEXT NOT NULL,
    code TEXT NOT NULL,
    payload_json TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'open',
    resolved_by BIGINT,
    resolution_note TEXT,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_import_job_review_items_status CHECK (status IN ('open', 'resolved')),
    CONSTRAINT chk_question_import_job_review_items_severity CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    CONSTRAINT chk_question_import_job_review_items_resolution CHECK (
        (status = 'open' AND resolved_at IS NULL)
        OR (status = 'resolved' AND resolved_at IS NOT NULL)
    ),
    CONSTRAINT fk_question_import_job_review_items_resolved_by
        FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_question_import_job_review_items_job_status
    ON question_import_job_review_items (job_id, status, severity);

CREATE TRIGGER trg_question_import_job_review_items_set_updated_at
BEFORE UPDATE ON question_import_job_review_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_import_job_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    stage VARCHAR(64) NOT NULL,
    step_code VARCHAR(64) NOT NULL,
    step_label VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    message TEXT,
    overall_progress_percent DOUBLE PRECISION,
    step_progress_percent DOUBLE PRECISION,
    target_kind VARCHAR(64),
    target_name VARCHAR(512),
    payload_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_import_job_events_status CHECK (
        status IN ('queued', 'processing', 'completed', 'failed', 'warning', 'info')
    ),
    CONSTRAINT chk_question_import_job_events_progress CHECK (
        (overall_progress_percent IS NULL OR overall_progress_percent BETWEEN 0 AND 100)
        AND (step_progress_percent IS NULL OR step_progress_percent BETWEEN 0 AND 100)
    )
);

CREATE INDEX idx_question_import_job_events_job_id
    ON question_import_job_events (job_id, id);

CREATE INDEX idx_question_import_job_events_step_code
    ON question_import_job_events (job_id, step_code, created_at);
CREATE UNIQUE INDEX uq_question_import_job_events_id_job
    ON question_import_job_events (id, job_id);

CREATE TABLE question_import_outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT REFERENCES question_import_jobs(id) ON DELETE SET NULL,
    job_event_id BIGINT REFERENCES question_import_job_events(id) ON DELETE SET NULL,
    event_type VARCHAR(80) NOT NULL,
    routing_key VARCHAR(120) NOT NULL,
    payload_json TEXT NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'pending',
    retry_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    next_attempt_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_import_outbox_events_status CHECK (
        status IN ('pending', 'processing', 'published', 'failed')
    ),
    CONSTRAINT chk_question_import_outbox_events_retry_count CHECK (retry_count >= 0),
    CONSTRAINT chk_question_import_outbox_events_published_at CHECK (
        (status = 'published' AND published_at IS NOT NULL)
        OR (status <> 'published')
    )
);

CREATE INDEX idx_question_import_outbox_events_status
    ON question_import_outbox_events (status, next_attempt_at, created_at);
CREATE INDEX idx_question_import_outbox_events_job
    ON question_import_outbox_events (job_id, job_event_id);

CREATE TRIGGER trg_question_import_outbox_events_set_updated_at
BEFORE UPDATE ON question_import_outbox_events
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

ALTER TABLE question_import_jobs
    ADD CONSTRAINT fk_question_import_jobs_last_event
    FOREIGN KEY (last_event_id, id) REFERENCES question_import_job_events(id, job_id);

ALTER TABLE question_import_job_blocks
    ADD CONSTRAINT fk_question_import_job_blocks_selected_attempt
    FOREIGN KEY (selected_attempt_id, id) REFERENCES question_import_job_block_attempts(id, block_id);

-- ============================================================
-- 30_questions.sql
-- ============================================================

CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_type TEXT NOT NULL DEFAULT 'standalone',
    subject_id VARCHAR(32) NOT NULL DEFAULT 'general' REFERENCES subjects(subject_id) ON DELETE RESTRICT,
    question_type_id VARCHAR(64) NOT NULL DEFAULT 'generic_answer_mode' REFERENCES question_types(type_id) ON DELETE RESTRICT,
    answer_mode TEXT NOT NULL,
    choice_variant TEXT,
    hierarchy_level INTEGER NOT NULL DEFAULT 1,
    hierarchy_path VARCHAR(512),
    chapter_ref VARCHAR(128),
    chapter_title VARCHAR(512),
    chapter_order INTEGER,
    content_mode VARCHAR(32),
    stem TEXT NOT NULL,
    analysis TEXT,
    detail_payload TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'draft',
    source_type TEXT NOT NULL DEFAULT 'parsed',
    source_ref VARCHAR(128),
    source_job_id BIGINT REFERENCES question_import_jobs(id) ON DELETE SET NULL,
    imported_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_questions_business_type_not_blank CHECK (btrim(business_type) <> ''),
    CONSTRAINT chk_questions_answer_mode CHECK (
        answer_mode IN ('choice', 'true_false', 'fill_blank', 'short_answer')
    ),
    CONSTRAINT chk_questions_choice_variant CHECK (
        choice_variant IS NULL OR choice_variant IN ('single', 'multiple')
    ),
    CONSTRAINT chk_questions_hierarchy_level CHECK (hierarchy_level >= 1),
    CONSTRAINT chk_questions_chapter_order CHECK (chapter_order IS NULL OR chapter_order > 0),
    CONSTRAINT chk_questions_content_mode CHECK (
        content_mode IS NULL OR content_mode IN ('text_only', 'mixed_media', 'structured_rich')
    ),
    CONSTRAINT chk_questions_stem_not_blank CHECK (btrim(stem) <> ''),
    CONSTRAINT chk_questions_status CHECK (status IN ('draft', 'active', 'archived')),
    CONSTRAINT chk_questions_source_type CHECK (source_type IN ('manual', 'imported', 'parsed')),
    CONSTRAINT fk_questions_subject_type
        FOREIGN KEY (subject_id, question_type_id)
        REFERENCES question_types(subject_id, type_id)
        ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_questions_id_subject ON questions (id, subject_id);
CREATE INDEX idx_questions_business_type ON questions (business_type);
CREATE INDEX idx_questions_subject_type ON questions (subject_id, question_type_id);
CREATE INDEX idx_questions_content_mode ON questions (content_mode);
CREATE INDEX idx_questions_source_ref ON questions (source_type, source_ref);
CREATE INDEX idx_questions_source_job ON questions (source_job_id);
CREATE INDEX idx_questions_imported_by ON questions (imported_by);
CREATE INDEX idx_questions_chapter ON questions (chapter_ref, chapter_order);
CREATE INDEX idx_questions_stem_fts ON questions USING GIN (to_tsvector('simple', stem));

ALTER TABLE question_groups
    ADD COLUMN source_job_id BIGINT REFERENCES question_import_jobs(id) ON DELETE SET NULL;

CREATE INDEX idx_question_groups_source_job ON question_groups (source_job_id);

CREATE TRIGGER trg_questions_set_updated_at
BEFORE UPDATE ON questions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE bank_question_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id BIGINT NOT NULL REFERENCES question_banks(id) ON DELETE CASCADE,
    bank_subject VARCHAR(32) NOT NULL,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    question_subject_id VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 1,
    question_no VARCHAR(32),
    status TEXT NOT NULL DEFAULT 'draft',
    added_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_bank_question_links_bank_question UNIQUE (bank_id, question_id),
    CONSTRAINT uq_bank_question_links_bank_sort UNIQUE (bank_id, sort_order),
    CONSTRAINT uq_bank_question_links_bank_question_no UNIQUE (bank_id, question_no),
    CONSTRAINT chk_bank_question_links_sort_order CHECK (sort_order > 0),
    CONSTRAINT chk_bank_question_links_status CHECK (status IN ('draft', 'active', 'archived')),
    CONSTRAINT chk_bank_question_links_subject_match CHECK (bank_subject = question_subject_id),
    CONSTRAINT fk_bank_question_links_bank_subject
        FOREIGN KEY (bank_id, bank_subject)
        REFERENCES question_banks(id, subject)
        ON DELETE CASCADE,
    CONSTRAINT fk_bank_question_links_question_subject
        FOREIGN KEY (question_id, question_subject_id)
        REFERENCES questions(id, subject_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_bank_question_links_bank_sort ON bank_question_links (bank_id, sort_order);
CREATE INDEX idx_bank_question_links_question_id ON bank_question_links (question_id);
CREATE UNIQUE INDEX uq_bank_question_links_id_question
    ON bank_question_links (id, question_id);

CREATE TRIGGER trg_bank_question_links_set_subjects
BEFORE INSERT OR UPDATE OF bank_id, question_id ON bank_question_links
FOR EACH ROW
EXECUTE FUNCTION set_bank_question_link_subjects();

CREATE TRIGGER trg_bank_question_links_set_updated_at
BEFORE UPDATE ON bank_question_links
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE bank_group_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id BIGINT NOT NULL REFERENCES question_banks(id) ON DELETE CASCADE,
    bank_subject VARCHAR(32) NOT NULL,
    group_id BIGINT NOT NULL REFERENCES question_groups(id) ON DELETE CASCADE,
    group_subject_id VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'draft',
    added_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_bank_group_links_bank_group UNIQUE (bank_id, group_id),
    CONSTRAINT uq_bank_group_links_bank_sort UNIQUE (bank_id, sort_order),
    CONSTRAINT chk_bank_group_links_sort_order CHECK (sort_order > 0),
    CONSTRAINT chk_bank_group_links_status CHECK (status IN ('draft', 'active', 'archived')),
    CONSTRAINT chk_bank_group_links_subject_match CHECK (bank_subject = group_subject_id),
    CONSTRAINT fk_bank_group_links_bank_subject
        FOREIGN KEY (bank_id, bank_subject)
        REFERENCES question_banks(id, subject)
        ON DELETE CASCADE,
    CONSTRAINT fk_bank_group_links_group_subject
        FOREIGN KEY (group_id, group_subject_id)
        REFERENCES question_groups(id, subject_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_bank_group_links_bank_sort ON bank_group_links (bank_id, sort_order);
CREATE INDEX idx_bank_group_links_group_id ON bank_group_links (group_id);
CREATE UNIQUE INDEX uq_bank_group_links_id_group
    ON bank_group_links (id, group_id);

CREATE TRIGGER trg_bank_group_links_set_subjects
BEFORE INSERT OR UPDATE OF bank_id, group_id ON bank_group_links
FOR EACH ROW
EXECUTE FUNCTION set_bank_group_link_subjects();

CREATE TRIGGER trg_bank_group_links_set_updated_at
BEFORE UPDATE ON bank_group_links
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE group_question_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES question_groups(id) ON DELETE CASCADE,
    group_subject_id VARCHAR(32) NOT NULL,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    question_subject_id VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 1,
    question_no VARCHAR(32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_group_question_links_group_question UNIQUE (group_id, question_id),
    CONSTRAINT uq_group_question_links_group_sort UNIQUE (group_id, sort_order),
    CONSTRAINT uq_group_question_links_group_question_no UNIQUE (group_id, question_no),
    CONSTRAINT chk_group_question_links_sort_order CHECK (sort_order > 0),
    CONSTRAINT chk_group_question_links_subject_match CHECK (group_subject_id = question_subject_id),
    CONSTRAINT fk_group_question_links_group_subject
        FOREIGN KEY (group_id, group_subject_id)
        REFERENCES question_groups(id, subject_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_group_question_links_question_subject
        FOREIGN KEY (question_id, question_subject_id)
        REFERENCES questions(id, subject_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_group_question_links_group_sort ON group_question_links (group_id, sort_order);
CREATE INDEX idx_group_question_links_question_id ON group_question_links (question_id);

CREATE TRIGGER trg_group_question_links_set_subjects
BEFORE INSERT OR UPDATE OF group_id, question_id ON group_question_links
FOR EACH ROW
EXECUTE FUNCTION set_group_question_link_subjects();

CREATE TRIGGER trg_group_question_links_set_updated_at
BEFORE UPDATE ON group_question_links
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_import_job_outputs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    block_id BIGINT REFERENCES question_import_job_blocks(id) ON DELETE SET NULL,
    attempt_id BIGINT,
    output_kind VARCHAR(32) NOT NULL,
    question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE,
    group_id BIGINT REFERENCES question_groups(id) ON DELETE CASCADE,
    bank_question_link_id BIGINT,
    bank_group_link_id BIGINT,
    confidence DOUBLE PRECISION,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_import_job_outputs_kind CHECK (
        output_kind IN ('question', 'group')
    ),
    CONSTRAINT chk_question_import_job_outputs_target CHECK (
        (output_kind = 'question' AND question_id IS NOT NULL AND group_id IS NULL)
        OR (output_kind = 'group' AND group_id IS NOT NULL AND question_id IS NULL)
    ),
    CONSTRAINT chk_question_import_job_outputs_link CHECK (
        (bank_question_link_id IS NULL OR output_kind = 'question')
        AND (bank_group_link_id IS NULL OR output_kind = 'group')
    ),
    CONSTRAINT chk_question_import_job_outputs_attempt_block CHECK (
        attempt_id IS NULL OR block_id IS NOT NULL
    ),
    CONSTRAINT chk_question_import_job_outputs_confidence CHECK (
        confidence IS NULL OR confidence BETWEEN 0 AND 1
    ),
    CONSTRAINT fk_question_import_job_outputs_attempt_block
        FOREIGN KEY (attempt_id, block_id)
        REFERENCES question_import_job_block_attempts(id, block_id),
    CONSTRAINT fk_question_import_job_outputs_bank_question
        FOREIGN KEY (bank_question_link_id, question_id)
        REFERENCES bank_question_links(id, question_id),
    CONSTRAINT fk_question_import_job_outputs_bank_group
        FOREIGN KEY (bank_group_link_id, group_id)
        REFERENCES bank_group_links(id, group_id)
);

CREATE UNIQUE INDEX uq_question_import_job_outputs_question
    ON question_import_job_outputs (job_id, question_id)
    WHERE question_id IS NOT NULL;
CREATE UNIQUE INDEX uq_question_import_job_outputs_group
    ON question_import_job_outputs (job_id, group_id)
    WHERE group_id IS NOT NULL;
CREATE INDEX idx_question_import_job_outputs_block
    ON question_import_job_outputs (block_id, attempt_id);

CREATE VIEW v_bank_question_items AS
SELECT
    bgl.bank_id,
    g.id AS group_id,
    q.id AS question_id,
    'grouped' AS item_scope,
    bgl.sort_order AS bank_sort_order,
    gql.sort_order AS group_sort_order,
    gql.question_no AS question_no,
    bgl.status AS bank_link_status,
    q.business_type,
    q.subject_id,
    q.question_type_id,
    q.answer_mode,
    q.choice_variant,
    q.content_mode,
    q.stem,
    q.analysis,
    q.status AS question_status,
    q.source_type,
    q.source_ref,
    q.source_job_id,
    q.imported_by,
    q.hierarchy_level,
    q.hierarchy_path,
    q.chapter_ref,
    q.chapter_title,
    q.chapter_order,
    g.business_type AS group_business_type,
    g.subject_id AS group_subject_id,
    g.group_type_id,
    g.content_mode AS group_content_mode,
    g.title AS group_title,
    g.instructions AS group_instructions,
    g.source_ref AS group_source_ref,
    g.parent_group_id,
    g.source_job_id AS group_source_job_id,
    g.imported_by AS group_imported_by,
    g.hierarchy_level AS group_hierarchy_level,
    g.hierarchy_path AS group_hierarchy_path,
    g.chapter_ref AS group_chapter_ref,
    g.chapter_title AS group_chapter_title,
    g.chapter_order AS group_chapter_order
FROM bank_group_links bgl
JOIN question_groups g ON g.id = bgl.group_id
JOIN group_question_links gql ON gql.group_id = g.id
JOIN questions q ON q.id = gql.question_id
UNION ALL
SELECT
    bql.bank_id,
    CAST(NULL AS BIGINT) AS group_id,
    q.id AS question_id,
    'standalone' AS item_scope,
    bql.sort_order AS bank_sort_order,
    CAST(NULL AS INTEGER) AS group_sort_order,
    bql.question_no AS question_no,
    bql.status AS bank_link_status,
    q.business_type,
    q.subject_id,
    q.question_type_id,
    q.answer_mode,
    q.choice_variant,
    q.content_mode,
    q.stem,
    q.analysis,
    q.status AS question_status,
    q.source_type,
    q.source_ref,
    q.source_job_id,
    q.imported_by,
    q.hierarchy_level,
    q.hierarchy_path,
    q.chapter_ref,
    q.chapter_title,
    q.chapter_order,
    CAST(NULL AS VARCHAR(64)) AS group_business_type,
    CAST(NULL AS VARCHAR(32)) AS group_subject_id,
    CAST(NULL AS VARCHAR(64)) AS group_type_id,
    CAST(NULL AS VARCHAR(32)) AS group_content_mode,
    CAST(NULL AS VARCHAR(512)) AS group_title,
    CAST(NULL AS VARCHAR(1024)) AS group_instructions,
    CAST(NULL AS VARCHAR(128)) AS group_source_ref,
    CAST(NULL AS BIGINT) AS parent_group_id,
    CAST(NULL AS BIGINT) AS group_source_job_id,
    CAST(NULL AS BIGINT) AS group_imported_by,
    CAST(NULL AS INTEGER) AS group_hierarchy_level,
    CAST(NULL AS VARCHAR(512)) AS group_hierarchy_path,
    CAST(NULL AS VARCHAR(128)) AS group_chapter_ref,
    CAST(NULL AS VARCHAR(512)) AS group_chapter_title,
    CAST(NULL AS INTEGER) AS group_chapter_order
FROM bank_question_links bql
JOIN questions q ON q.id = bql.question_id;

CREATE TABLE question_choice_details (
    question_id BIGINT PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,
    selection_mode TEXT NOT NULL DEFAULT 'single',
    CONSTRAINT chk_question_choice_details_selection_mode CHECK (selection_mode IN ('single', 'multiple'))
);

CREATE TABLE question_true_false_details (
    question_id BIGINT PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,
    correct_answer BOOLEAN
);

CREATE TABLE question_fill_blank_details (
    question_id BIGINT PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,
    correct_answer TEXT NOT NULL DEFAULT '[]'
);

CREATE TABLE question_short_answer_details (
    question_id BIGINT PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,
    correct_answer TEXT
);

CREATE TABLE question_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    option_label VARCHAR(16) NOT NULL,
    sort_order SMALLINT NOT NULL DEFAULT 1,
    content TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_options_label_not_blank CHECK (btrim(option_label) <> ''),
    CONSTRAINT chk_question_options_sort_order CHECK (sort_order > 0),
    CONSTRAINT chk_question_options_content_not_blank CHECK (btrim(content) <> '')
);

CREATE UNIQUE INDEX uq_question_options_question_label ON question_options (question_id, option_label);
CREATE UNIQUE INDEX uq_question_options_question_sort ON question_options (question_id, sort_order);

CREATE TRIGGER trg_question_options_set_updated_at
BEFORE UPDATE ON question_options
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_subquestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    label VARCHAR(32),
    sort_order SMALLINT NOT NULL DEFAULT 1,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_subquestions_sort_order CHECK (sort_order > 0),
    CONSTRAINT chk_question_subquestions_content_not_blank CHECK (btrim(content) <> ''),
    CONSTRAINT chk_question_subquestions_label_not_blank CHECK (label IS NULL OR btrim(label) <> '')
);

CREATE UNIQUE INDEX uq_question_subquestions_question_sort ON question_subquestions (question_id, sort_order);
CREATE INDEX idx_question_subquestions_question_label ON question_subquestions (question_id, label);

CREATE TRIGGER trg_question_subquestions_set_updated_at
BEFORE UPDATE ON question_subquestions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_answer_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    answer_mode VARCHAR(32) NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    is_primary BOOLEAN NOT NULL DEFAULT TRUE,
    answer_payload TEXT NOT NULL DEFAULT '{}',
    explanation_payload TEXT NOT NULL DEFAULT '{}',
    score_payload TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_answer_keys_question_version UNIQUE (question_id, version),
    CONSTRAINT chk_question_answer_keys_version CHECK (version > 0),
    CONSTRAINT chk_question_answer_keys_answer_mode CHECK (
        answer_mode IN ('choice', 'true_false', 'fill_blank', 'short_answer')
    )
);

CREATE UNIQUE INDEX uq_question_answer_keys_id_question
    ON question_answer_keys (id, question_id);
CREATE INDEX idx_question_answer_keys_question ON question_answer_keys (question_id, is_primary);
CREATE UNIQUE INDEX uq_question_answer_keys_primary
    ON question_answer_keys (question_id)
    WHERE is_primary;

CREATE TRIGGER trg_question_answer_keys_set_updated_at
BEFORE UPDATE ON question_answer_keys
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_fill_blank_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    blank_ref VARCHAR(64) NOT NULL,
    blank_index INTEGER NOT NULL,
    label VARCHAR(64),
    stem_anchor VARCHAR(256),
    correct_answer TEXT,
    accepted_answers_json TEXT NOT NULL DEFAULT '[]',
    formula_latex TEXT,
    formula_mathml TEXT,
    unit_text VARCHAR(64),
    tolerance_text VARCHAR(64),
    case_sensitive BOOLEAN NOT NULL DEFAULT FALSE,
    score_weight DOUBLE PRECISION,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_fill_blank_slots_ref UNIQUE (question_id, blank_ref),
    CONSTRAINT uq_question_fill_blank_slots_index UNIQUE (question_id, blank_index),
    CONSTRAINT chk_question_fill_blank_slots_index CHECK (blank_index > 0)
);

CREATE INDEX idx_question_fill_blank_slots_question ON question_fill_blank_slots (question_id, blank_index);

CREATE TRIGGER trg_question_fill_blank_slots_set_updated_at
BEFORE UPDATE ON question_fill_blank_slots
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_rubric_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    rubric_ref VARCHAR(64),
    sort_order INTEGER NOT NULL DEFAULT 1,
    criterion VARCHAR(256) NOT NULL,
    description TEXT,
    score_value DOUBLE PRECISION,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_rubric_items_sort UNIQUE (question_id, sort_order),
    CONSTRAINT chk_question_rubric_items_sort_order CHECK (sort_order > 0),
    CONSTRAINT chk_question_rubric_items_criterion_not_blank CHECK (btrim(criterion) <> '')
);

CREATE INDEX idx_question_rubric_items_question ON question_rubric_items (question_id, sort_order);

CREATE TRIGGER trg_question_rubric_items_set_updated_at
BEFORE UPDATE ON question_rubric_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_educational_metadata (
    question_id BIGINT PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,
    difficulty_level VARCHAR(32),
    difficulty_score DOUBLE PRECISION,
    grade_level VARCHAR(64),
    exam_type VARCHAR(64),
    curriculum_standard VARCHAR(128),
    textbook_version VARCHAR(128),
    knowledge_tags_json TEXT NOT NULL DEFAULT '[]',
    skill_tags_json TEXT NOT NULL DEFAULT '[]',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_question_educational_metadata_exam
    ON question_educational_metadata (exam_type, difficulty_level);

CREATE TRIGGER trg_question_educational_metadata_set_updated_at
BEFORE UPDATE ON question_educational_metadata
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE knowledge_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id VARCHAR(32) NOT NULL REFERENCES subjects(subject_id) ON DELETE RESTRICT,
    code VARCHAR(128) NOT NULL,
    display_name VARCHAR(256) NOT NULL,
    parent_id BIGINT REFERENCES knowledge_points(id) ON DELETE SET NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_knowledge_points_subject_code UNIQUE (subject_id, code),
    CONSTRAINT chk_knowledge_points_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT chk_knowledge_points_name_not_blank CHECK (btrim(display_name) <> '')
);

CREATE UNIQUE INDEX uq_knowledge_points_id_subject ON knowledge_points (id, subject_id);
CREATE INDEX idx_knowledge_points_parent ON knowledge_points (parent_id);

CREATE TRIGGER trg_knowledge_points_set_updated_at
BEFORE UPDATE ON knowledge_points
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_knowledge_point_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    question_subject_id VARCHAR(32) NOT NULL,
    knowledge_point_id BIGINT NOT NULL REFERENCES knowledge_points(id) ON DELETE CASCADE,
    knowledge_point_subject_id VARCHAR(32) NOT NULL,
    relevance_score DOUBLE PRECISION,
    source_type VARCHAR(32) NOT NULL DEFAULT 'parsed',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_knowledge_point_links UNIQUE (question_id, knowledge_point_id),
    CONSTRAINT chk_question_knowledge_point_links_subject_match CHECK (
        question_subject_id = knowledge_point_subject_id
    ),
    CONSTRAINT chk_question_knowledge_point_links_relevance CHECK (
        relevance_score IS NULL OR relevance_score BETWEEN 0 AND 1
    ),
    CONSTRAINT fk_question_knowledge_point_links_question_subject
        FOREIGN KEY (question_id, question_subject_id)
        REFERENCES questions(id, subject_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_question_knowledge_point_links_kp_subject
        FOREIGN KEY (knowledge_point_id, knowledge_point_subject_id)
        REFERENCES knowledge_points(id, subject_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_question_knowledge_point_links_kp
    ON question_knowledge_point_links (knowledge_point_id);

CREATE TRIGGER trg_question_knowledge_point_links_set_subjects
BEFORE INSERT OR UPDATE OF question_id, knowledge_point_id ON question_knowledge_point_links
FOR EACH ROW
EXECUTE FUNCTION set_question_knowledge_point_link_subjects();

CREATE TABLE question_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    tag_type VARCHAR(32) NOT NULL DEFAULT 'general',
    tag_value VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_tags UNIQUE (question_id, tag_type, tag_value),
    CONSTRAINT chk_question_tags_value_not_blank CHECK (btrim(tag_value) <> '')
);

CREATE INDEX idx_question_tags_type_value ON question_tags (tag_type, tag_value);

CREATE TABLE question_provenance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    source_job_id BIGINT REFERENCES question_import_jobs(id) ON DELETE SET NULL,
    source_block_ref VARCHAR(128),
    source_page_no INTEGER,
    source_page_start INTEGER,
    source_page_end INTEGER,
    source_bbox_json TEXT,
    source_text TEXT,
    confidence DOUBLE PRECISION,
    quality_flags_json TEXT NOT NULL DEFAULT '[]',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_question_provenance_question ON question_provenance (question_id);
CREATE INDEX idx_question_provenance_source_job
    ON question_provenance (source_job_id, source_block_ref);

CREATE TABLE ai_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_type VARCHAR(64) NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    bank_id BIGINT REFERENCES question_banks(id) ON DELETE SET NULL,
    question_id BIGINT REFERENCES questions(id) ON DELETE SET NULL,
    import_job_id BIGINT REFERENCES question_import_jobs(id) ON DELETE SET NULL,
    practice_session_id BIGINT,
    provider VARCHAR(64) NOT NULL DEFAULT 'mastra',
    model VARCHAR(128),
    input_payload JSONB NOT NULL DEFAULT '{}',
    output_payload JSONB NOT NULL DEFAULT '{}',
    status VARCHAR(32) NOT NULL DEFAULT 'completed',
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_ai_artifacts_type CHECK (
        artifact_type IN ('document_parse', 'answer_generation', 'learning_report')
    ),
    CONSTRAINT chk_ai_artifacts_status CHECK (
        status IN ('completed', 'failed')
    ),
    CONSTRAINT chk_ai_artifacts_payload_object CHECK (
        jsonb_typeof(input_payload) = 'object'
        AND jsonb_typeof(output_payload) = 'object'
    )
);

CREATE INDEX idx_ai_artifacts_question
    ON ai_artifacts (question_id, artifact_type, created_at DESC);
CREATE INDEX idx_ai_artifacts_import_job
    ON ai_artifacts (import_job_id, artifact_type, created_at DESC);
CREATE INDEX idx_ai_artifacts_user
    ON ai_artifacts (user_id, artifact_type, created_at DESC);

-- ============================================================
-- 40_media.sql
-- ============================================================

CREATE TABLE media_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_path VARCHAR(512) NOT NULL UNIQUE,
    storage_disk TEXT NOT NULL DEFAULT 'local',
    external_url VARCHAR(1024),
    oss_bucket VARCHAR(128),
    oss_object_key VARCHAR(512),
    original_name VARCHAR(255),
    mime_type VARCHAR(64),
    width INTEGER,
    height INTEGER,
    size_bytes BIGINT,
    duration_ms INTEGER,
    checksum_sha256 VARCHAR(64),
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_media_assets_dimensions CHECK (
        (width IS NULL OR width > 0)
        AND (height IS NULL OR height > 0)
        AND (size_bytes IS NULL OR size_bytes >= 0)
        AND (duration_ms IS NULL OR duration_ms >= 0)
    )
);

CREATE TABLE question_media_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    media_id BIGINT NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE,
    media_kind TEXT NOT NULL,
    sort_order SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_media_links_sort UNIQUE (question_id, sort_order),
    CONSTRAINT uq_question_media_links_media UNIQUE (question_id, media_id, media_kind),
    CONSTRAINT chk_question_media_links_sort CHECK (sort_order > 0)
);

CREATE TABLE question_option_media_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_id BIGINT NOT NULL REFERENCES question_options(id) ON DELETE CASCADE,
    media_id BIGINT NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE,
    media_kind TEXT NOT NULL,
    sort_order SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_option_media_links_sort UNIQUE (option_id, sort_order),
    CONSTRAINT uq_question_option_media_links_media UNIQUE (option_id, media_id, media_kind),
    CONSTRAINT chk_question_option_media_links_sort CHECK (sort_order > 0)
);

CREATE TABLE question_subquestion_media_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subquestion_id BIGINT NOT NULL REFERENCES question_subquestions(id) ON DELETE CASCADE,
    media_id BIGINT NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE,
    media_kind TEXT NOT NULL,
    sort_order SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_subquestion_media_links_sort UNIQUE (subquestion_id, sort_order),
    CONSTRAINT uq_question_subquestion_media_links_media UNIQUE (subquestion_id, media_id, media_kind),
    CONSTRAINT chk_question_subquestion_media_links_sort CHECK (sort_order > 0)
);

CREATE TABLE question_group_media_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES question_groups(id) ON DELETE CASCADE,
    media_id BIGINT NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE,
    media_kind TEXT NOT NULL,
    sort_order SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_group_media_links_sort UNIQUE (group_id, sort_order),
    CONSTRAINT uq_question_group_media_links_media UNIQUE (group_id, media_id, media_kind),
    CONSTRAINT chk_question_group_media_links_sort CHECK (sort_order > 0)
);

CREATE TABLE question_content_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE,
    group_id BIGINT REFERENCES question_groups(id) ON DELETE CASCADE,
    option_id BIGINT REFERENCES question_options(id) ON DELETE CASCADE,
    subquestion_id BIGINT REFERENCES question_subquestions(id) ON DELETE CASCADE,
    media_id BIGINT REFERENCES media_assets(id) ON DELETE SET NULL,
    owner_kind VARCHAR(32) NOT NULL,
    role VARCHAR(64),
    part_type VARCHAR(32) NOT NULL,
    sequence INTEGER NOT NULL DEFAULT 1,
    content_mode VARCHAR(32),
    text_format VARCHAR(32),
    text_value TEXT,
    latex_value TEXT,
    mathml_value TEXT,
    html_value TEXT,
    markdown_value TEXT,
    json_value TEXT,
    source_url VARCHAR(1024),
    page_no INTEGER,
    bbox_json TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_content_blocks_owner_kind CHECK (
        owner_kind IN ('question', 'group', 'stem', 'option', 'subquestion', 'answer_key', 'analysis', 'explanation')
    ),
    CONSTRAINT chk_question_content_blocks_part_type CHECK (
        part_type IN ('text', 'formula', 'image', 'table', 'list', 'html', 'markdown', 'chart', 'diagram', 'qr_code')
    ),
    CONSTRAINT chk_question_content_blocks_sequence CHECK (sequence > 0),
    CONSTRAINT chk_question_content_blocks_content_mode CHECK (
        content_mode IS NULL OR content_mode IN ('text_only', 'mixed_media', 'structured_rich')
    ),
    CONSTRAINT chk_question_content_blocks_owner_ref CHECK (
        (CASE WHEN question_id IS NOT NULL THEN 1 ELSE 0 END)
        + (CASE WHEN group_id IS NOT NULL THEN 1 ELSE 0 END)
        + (CASE WHEN option_id IS NOT NULL THEN 1 ELSE 0 END)
        + (CASE WHEN subquestion_id IS NOT NULL THEN 1 ELSE 0 END) = 1
    ),
    CONSTRAINT chk_question_content_blocks_owner_kind_ref CHECK (
        (owner_kind IN ('question', 'stem', 'answer_key', 'analysis', 'explanation') AND question_id IS NOT NULL)
        OR (owner_kind = 'group' AND group_id IS NOT NULL)
        OR (owner_kind = 'option' AND option_id IS NOT NULL)
        OR (owner_kind = 'subquestion' AND subquestion_id IS NOT NULL)
    )
);

CREATE INDEX idx_question_content_blocks_question
    ON question_content_blocks (question_id, owner_kind, sequence);
CREATE INDEX idx_question_content_blocks_group
    ON question_content_blocks (group_id, owner_kind, sequence);
CREATE INDEX idx_question_content_blocks_option ON question_content_blocks (option_id, sequence);
CREATE INDEX idx_question_content_blocks_subquestion ON question_content_blocks (subquestion_id, sequence);

CREATE TRIGGER trg_question_content_blocks_set_updated_at
BEFORE UPDATE ON question_content_blocks
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- 50_user_answers.sql
-- ============================================================

CREATE TABLE user_practice_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bank_id BIGINT REFERENCES question_banks(id) ON DELETE SET NULL,
    session_type VARCHAR(32) NOT NULL DEFAULT 'practice',
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    question_count INTEGER NOT NULL DEFAULT 0,
    answered_count INTEGER NOT NULL DEFAULT 0,
    correct_count INTEGER NOT NULL DEFAULT 0,
    wrong_count INTEGER NOT NULL DEFAULT 0,
    score DOUBLE PRECISION,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_user_practice_sessions_type CHECK (
        session_type IN ('practice', 'review', 'exam')
    ),
    CONSTRAINT chk_user_practice_sessions_status CHECK (
        status IN ('active', 'completed', 'abandoned')
    ),
    CONSTRAINT chk_user_practice_sessions_counts CHECK (
        question_count >= 0
        AND answered_count >= 0
        AND correct_count >= 0
        AND wrong_count >= 0
        AND answered_count <= question_count
        AND correct_count <= answered_count
        AND wrong_count <= answered_count
    ),
    CONSTRAINT chk_user_practice_sessions_score CHECK (
        score IS NULL OR score >= 0
    ),
    CONSTRAINT chk_user_practice_sessions_completed_at CHECK (
        (status = 'active' AND completed_at IS NULL)
        OR (status IN ('completed', 'abandoned') AND completed_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_user_practice_sessions_id_user
    ON user_practice_sessions (id, user_id);
CREATE INDEX idx_user_practice_sessions_user_started
    ON user_practice_sessions (user_id, started_at DESC);
CREATE INDEX idx_user_practice_sessions_bank
    ON user_practice_sessions (bank_id, status);

CREATE TRIGGER trg_user_practice_sessions_set_updated_at
BEFORE UPDATE ON user_practice_sessions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

ALTER TABLE ai_artifacts
    ADD CONSTRAINT fk_ai_artifacts_practice_session
    FOREIGN KEY (practice_session_id) REFERENCES user_practice_sessions(id) ON DELETE SET NULL;

CREATE TABLE user_question_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id BIGINT,
    bank_id BIGINT REFERENCES question_banks(id) ON DELETE SET NULL,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    answer_key_id BIGINT,
    answer_payload JSONB NOT NULL,
    is_correct BOOLEAN,
    score DOUBLE PRECISION,
    max_score DOUBLE PRECISION,
    duration_ms INTEGER,
    answered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_user_question_answers_payload_object CHECK (jsonb_typeof(answer_payload) = 'object'),
    CONSTRAINT chk_user_question_answers_score CHECK (
        (score IS NULL OR score >= 0)
        AND (max_score IS NULL OR max_score >= 0)
        AND (score IS NULL OR max_score IS NULL OR score <= max_score)
    ),
    CONSTRAINT chk_user_question_answers_duration CHECK (
        duration_ms IS NULL OR duration_ms >= 0
    ),
    CONSTRAINT fk_user_question_answers_session_user
        FOREIGN KEY (session_id, user_id)
        REFERENCES user_practice_sessions(id, user_id),
    CONSTRAINT fk_user_question_answers_answer_key_question
        FOREIGN KEY (answer_key_id, question_id)
        REFERENCES question_answer_keys(id, question_id)
);

CREATE UNIQUE INDEX uq_user_question_answers_id_user_question
    ON user_question_answers (id, user_id, question_id);
CREATE INDEX idx_user_question_answers_user_question_answered_at
    ON user_question_answers (user_id, question_id, answered_at DESC);
CREATE INDEX idx_user_question_answers_question_id ON user_question_answers (question_id);
CREATE INDEX idx_user_question_answers_session
    ON user_question_answers (session_id, answered_at);
CREATE INDEX idx_user_question_answers_bank
    ON user_question_answers (bank_id, user_id, answered_at DESC);

CREATE TRIGGER trg_user_question_answers_apply_stats
AFTER INSERT ON user_question_answers
FOR EACH ROW
EXECUTE FUNCTION apply_user_question_answer_stats();

CREATE TABLE user_question_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    correct_count INTEGER NOT NULL DEFAULT 0,
    wrong_count INTEGER NOT NULL DEFAULT 0,
    last_answer_id BIGINT,
    last_answered_at TIMESTAMPTZ,
    last_is_correct BOOLEAN,
    mastery_score DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_user_question_stats_user_question UNIQUE (user_id, question_id),
    CONSTRAINT chk_user_question_stats_counts CHECK (
        attempt_count >= 0
        AND correct_count >= 0
        AND wrong_count >= 0
        AND correct_count <= attempt_count
        AND wrong_count <= attempt_count
    ),
    CONSTRAINT chk_user_question_stats_mastery CHECK (
        mastery_score IS NULL OR mastery_score BETWEEN 0 AND 1
    ),
    CONSTRAINT fk_user_question_stats_last_answer
        FOREIGN KEY (last_answer_id, user_id, question_id)
        REFERENCES user_question_answers(id, user_id, question_id)
);

CREATE INDEX idx_user_question_stats_question
    ON user_question_stats (question_id);
CREATE INDEX idx_user_question_stats_last_answered
    ON user_question_stats (user_id, last_answered_at DESC);

CREATE TRIGGER trg_user_question_stats_set_updated_at
BEFORE UPDATE ON user_question_stats
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
