-- Purpose: Define user accounts and Paddle billing subscription state.
-- PostgreSQL-only schema fragment. Apply after earlier numbered fragments in db/*/*.sql order.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) NOT NULL,
    email VARCHAR(254),
    avatar_url TEXT,
    password_hash VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    role TEXT NOT NULL DEFAULT 'user',
    membership TEXT NOT NULL DEFAULT 'free',
    plus_trial_ends_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '3 days'),
    plus_expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_users_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT chk_users_role CHECK (role IN ('admin', 'user')),
    CONSTRAINT chk_users_membership CHECK (membership IN ('free', 'plus', 'enterprise'))
);

CREATE UNIQUE INDEX uq_users_username_lower ON users (LOWER(username));
CREATE UNIQUE INDEX uq_users_email_lower ON users (LOWER(email)) WHERE email IS NOT NULL;

CREATE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE users IS '用户表';
COMMENT ON COLUMN users.username IS '用户名';
COMMENT ON COLUMN users.email IS '邮箱';
COMMENT ON COLUMN users.avatar_url IS '头像对象存储地址';
COMMENT ON COLUMN users.password_hash IS '密码哈希';
COMMENT ON COLUMN users.is_active IS '是否启用';
COMMENT ON COLUMN users.role IS '系统角色，admin / user';
COMMENT ON COLUMN users.membership IS '会员类型，free / plus / enterprise';
COMMENT ON COLUMN users.plus_trial_ends_at IS 'Plus 试用到期时间，新注册用户默认 3 天';
COMMENT ON COLUMN users.plus_expires_at IS '付费会员到期时间，空值表示长期有效的付费会员';

CREATE TABLE billing_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    membership TEXT NOT NULL DEFAULT 'free',
    status TEXT NOT NULL DEFAULT 'inactive',
    source TEXT NOT NULL DEFAULT 'free',
    paddle_subscription_id VARCHAR(64),
    paddle_transaction_id VARCHAR(64),
    paddle_customer_id VARCHAR(64),
    paddle_price_id VARCHAR(64),
    current_period_starts_at TIMESTAMPTZ,
    current_period_ends_at TIMESTAMPTZ,
    scheduled_change_action VARCHAR(32),
    scheduled_change_effective_at TIMESTAMPTZ,
    raw_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_billing_subscriptions_membership CHECK (membership IN ('free', 'plus', 'enterprise')),
    CONSTRAINT chk_billing_subscriptions_status CHECK (status IN ('inactive', 'trialing', 'active', 'past_due', 'canceled')),
    CONSTRAINT chk_billing_subscriptions_source CHECK (source IN ('free', 'paddle')),
    CONSTRAINT chk_billing_subscriptions_period CHECK (
        current_period_starts_at IS NULL
        OR current_period_ends_at IS NULL
        OR current_period_ends_at > current_period_starts_at
    )
);

CREATE UNIQUE INDEX uq_billing_subscriptions_subscription_id ON billing_subscriptions (paddle_subscription_id) WHERE paddle_subscription_id IS NOT NULL;
CREATE INDEX idx_billing_subscriptions_customer_id ON billing_subscriptions (paddle_customer_id) WHERE paddle_customer_id IS NOT NULL;
CREATE INDEX idx_billing_subscriptions_status ON billing_subscriptions (status, updated_at DESC);

CREATE TRIGGER trg_billing_subscriptions_set_updated_at
BEFORE UPDATE ON billing_subscriptions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE billing_subscriptions IS 'Paddle 订阅同步状态';
COMMENT ON COLUMN billing_subscriptions.membership IS '本地会员档位，free / plus / enterprise';
COMMENT ON COLUMN billing_subscriptions.status IS '本地订阅状态';
COMMENT ON COLUMN billing_subscriptions.source IS '状态来源，free / paddle';
COMMENT ON COLUMN billing_subscriptions.paddle_subscription_id IS 'Paddle 订阅 ID';
COMMENT ON COLUMN billing_subscriptions.paddle_transaction_id IS '最近一次 Paddle 交易 ID';
