-- Purpose: Define learning groups/classes, member roles, and group-to-bank sharing.
-- PostgreSQL-only schema fragment. Apply after earlier numbered fragments in db/*/*.sql order.

-- Purpose: model learning groups/classes, membership roles, and shared banks.

CREATE TABLE study_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    description VARCHAR(500),
    topic VARCHAR(80),
    visibility VARCHAR(16) NOT NULL DEFAULT 'private',
    created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_study_groups_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT chk_study_groups_visibility CHECK (visibility IN ('private', 'public'))
);

CREATE INDEX idx_study_groups_created_by ON study_groups (created_by, created_at DESC);
CREATE INDEX idx_study_groups_visibility ON study_groups (visibility, updated_at DESC);
CREATE INDEX idx_study_groups_topic ON study_groups (topic);

CREATE TRIGGER trg_study_groups_set_updated_at
BEFORE UPDATE ON study_groups
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE study_group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES study_groups(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(16) NOT NULL DEFAULT 'member',
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_study_group_members_group_user UNIQUE (group_id, user_id),
    CONSTRAINT chk_study_group_members_role CHECK (role IN ('owner', 'admin', 'member')),
    CONSTRAINT chk_study_group_members_status CHECK (status IN ('active', 'pending', 'left', 'banned'))
);

CREATE INDEX idx_study_group_members_user ON study_group_members (user_id, status);
CREATE INDEX idx_study_group_members_group_role ON study_group_members (group_id, role, status);

CREATE TRIGGER trg_study_group_members_set_updated_at
BEFORE UPDATE ON study_group_members
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE study_group_bank_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES study_groups(id) ON DELETE CASCADE,
    bank_id BIGINT NOT NULL REFERENCES question_banks(id) ON DELETE CASCADE,
    added_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_study_group_bank_links_group_bank UNIQUE (group_id, bank_id),
    CONSTRAINT fk_study_group_bank_links_added_by_member
        FOREIGN KEY (group_id, added_by)
        REFERENCES study_group_members(group_id, user_id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_study_group_bank_links_bank ON study_group_bank_links (bank_id);
CREATE INDEX idx_study_group_bank_links_group ON study_group_bank_links (group_id, created_at DESC);

CREATE VIEW study_group_admins AS
SELECT group_id, user_id, role
FROM study_group_members
WHERE status = 'active'
  AND role IN ('owner', 'admin');
