-- Purpose: Define user accounts and membership state.
-- PostgreSQL-only schema fragment. Apply after earlier numbered fragments in db/*/*.sql order.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) NOT NULL,
    email VARCHAR(254),
    avatar_url TEXT,
    password_hash VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    role TEXT NOT NULL DEFAULT 'user',
    membership TEXT NOT NULL DEFAULT 'free',
    trial_ends_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '3 days'),
    revenuecat_app_user_id UUID NOT NULL DEFAULT gen_random_uuid(),
    llm_provider TEXT,
    llm_api_key_ciphertext BYTEA,
    llm_text_model TEXT,
    llm_vision_model TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_users_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT chk_users_role CHECK (role IN ('admin', 'user')),
    CONSTRAINT chk_users_membership CHECK (membership IN ('free', 'pro', 'organization')),
    CONSTRAINT chk_users_llm_provider CHECK (
        llm_provider IS NULL OR llm_provider IN (
            'dashscope', 'deepseek', 'moonshot'
        )
    ),
    CONSTRAINT chk_users_llm_config CHECK (
        (llm_provider IS NULL AND llm_api_key_ciphertext IS NULL AND llm_text_model IS NULL AND llm_vision_model IS NULL)
        OR
        (
            llm_provider IS NOT NULL
            AND llm_api_key_ciphertext IS NOT NULL
            AND llm_text_model IS NOT NULL
            AND btrim(llm_text_model) <> ''
            AND (llm_vision_model IS NULL OR btrim(llm_vision_model) <> '')
            AND (llm_vision_model IS NULL OR llm_provider IN ('dashscope', 'moonshot'))
        )
    )
);

CREATE UNIQUE INDEX uq_users_username_lower ON users (LOWER(username));
CREATE UNIQUE INDEX uq_users_email_lower ON users (LOWER(email)) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX uq_users_revenuecat_app_user_id ON users (revenuecat_app_user_id);

CREATE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE users IS '用户表';
COMMENT ON COLUMN users.username IS '用户名';
COMMENT ON COLUMN users.email IS '邮箱';
COMMENT ON COLUMN users.avatar_url IS '头像对象存储地址';
COMMENT ON COLUMN users.password_hash IS '密码哈希';
COMMENT ON COLUMN users.is_active IS '是否启用';
COMMENT ON COLUMN users.role IS '系统角色，admin / user';
COMMENT ON COLUMN users.membership IS 'RevenueCat 权益投影，free / pro / organization（不含试用，试用见 trial_ends_at）';
COMMENT ON COLUMN users.trial_ends_at IS '新用户 Pro 试用截止时间；试用内有效等级视为 pro';
COMMENT ON COLUMN users.revenuecat_app_user_id IS 'RevenueCat 不可猜测的 App User ID';
COMMENT ON COLUMN users.llm_api_key_ciphertext IS '用户 LLM API Key 的 pgcrypto 密文';
