-- Purpose: Define study groups created by organization-tier users, their members and linked banks.
-- PostgreSQL-only schema fragment. Apply after earlier numbered fragments in db/*/*.sql order.

CREATE TABLE study_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_study_groups_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE study_group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES study_groups(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'member',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_study_group_members_group_user UNIQUE (group_id, user_id),
    CONSTRAINT chk_study_group_members_role CHECK (role IN ('owner', 'member'))
);

CREATE TABLE study_group_banks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES study_groups(id) ON DELETE CASCADE,
    bank_id BIGINT NOT NULL REFERENCES question_banks(id) ON DELETE CASCADE,
    linked_by BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    linked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_study_group_banks_group_bank UNIQUE (group_id, bank_id)
);

CREATE INDEX idx_study_group_members_user ON study_group_members (user_id);
CREATE INDEX idx_study_group_banks_bank ON study_group_banks (bank_id);
CREATE INDEX idx_study_groups_created_by ON study_groups (created_by);

CREATE TRIGGER trg_study_groups_set_updated_at
BEFORE UPDATE ON study_groups
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE study_groups IS '学习小组（organization 会员创建）';
COMMENT ON COLUMN study_groups.name IS '小组名称';
COMMENT ON COLUMN study_groups.description IS '小组简介';
COMMENT ON COLUMN study_groups.created_by IS '创建者（owner）用户 ID';
COMMENT ON TABLE study_group_members IS '学习小组成员表，创建者以 owner 角色入库';
COMMENT ON COLUMN study_group_members.role IS '组内角色，owner / member';
COMMENT ON COLUMN study_group_members.joined_at IS '加入时间';
COMMENT ON TABLE study_group_banks IS '学习小组关联题库，组内成员获得只读权限';
COMMENT ON COLUMN study_group_banks.linked_by IS '执行关联操作的用户 ID';
