-- Purpose: Define normalized questions, bank/group question links, answer keys, educational metadata, provenance, and AI artifacts.
-- PostgreSQL-only schema fragment. Apply after earlier numbered fragments in db/*/*.sql order.

CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_type TEXT NOT NULL DEFAULT 'standalone',
    subject_id VARCHAR(32) NOT NULL DEFAULT 'general' REFERENCES subjects(subject_id) ON DELETE RESTRICT,
    question_type_id VARCHAR(64) NOT NULL DEFAULT 'generic_answer_mode' REFERENCES question_types(type_id) ON DELETE RESTRICT,
    answer_mode TEXT NOT NULL,
    choice_variant TEXT,
    hierarchy_level INTEGER NOT NULL DEFAULT 1,
    hierarchy_path VARCHAR(512),
    chapter_ref VARCHAR(128),
    chapter_title VARCHAR(512),
    chapter_order INTEGER,
    content_mode VARCHAR(32),
    stem TEXT NOT NULL,
    analysis TEXT,
    detail_payload TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'draft',
    source_type TEXT NOT NULL DEFAULT 'parsed',
    source_ref VARCHAR(128),
    source_job_id BIGINT REFERENCES question_import_jobs(id) ON DELETE SET NULL,
    imported_by BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_questions_business_type_not_blank CHECK (btrim(business_type) <> ''),
    CONSTRAINT chk_questions_answer_mode CHECK (
        answer_mode IN ('choice', 'true_false', 'fill_blank', 'short_answer')
    ),
    CONSTRAINT chk_questions_choice_variant CHECK (
        choice_variant IS NULL OR choice_variant IN ('single', 'multiple')
    ),
    CONSTRAINT chk_questions_hierarchy_level CHECK (hierarchy_level >= 1),
    CONSTRAINT chk_questions_chapter_order CHECK (chapter_order IS NULL OR chapter_order > 0),
    CONSTRAINT chk_questions_content_mode CHECK (
        content_mode IS NULL OR content_mode IN ('text_only', 'mixed_media', 'structured_rich')
    ),
    CONSTRAINT chk_questions_stem_not_blank CHECK (btrim(stem) <> ''),
    CONSTRAINT chk_questions_status CHECK (status IN ('draft', 'active', 'archived')),
    CONSTRAINT chk_questions_source_type CHECK (source_type IN ('manual', 'imported', 'parsed')),
    CONSTRAINT fk_questions_subject_type
        FOREIGN KEY (subject_id, question_type_id)
        REFERENCES question_types(subject_id, type_id)
        ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_questions_id_subject ON questions (id, subject_id);
CREATE INDEX idx_questions_business_type ON questions (business_type);
CREATE INDEX idx_questions_subject_type ON questions (subject_id, question_type_id);
CREATE INDEX idx_questions_status_type ON questions (status, question_type_id, id);
CREATE INDEX idx_questions_content_mode ON questions (content_mode);
CREATE INDEX idx_questions_source_ref ON questions (source_type, source_ref);
CREATE INDEX idx_questions_source_job ON questions (source_job_id);
CREATE INDEX idx_questions_imported_by ON questions (imported_by);
CREATE INDEX idx_questions_chapter ON questions (chapter_ref, chapter_order);
CREATE INDEX idx_questions_stem_trgm ON questions USING GIN (stem gin_trgm_ops);
CREATE INDEX idx_questions_stem_fts ON questions USING GIN (to_tsvector('simple', COALESCE(stem, '')));

ALTER TABLE question_groups
    ADD COLUMN source_job_id BIGINT REFERENCES question_import_jobs(id) ON DELETE SET NULL;

CREATE INDEX idx_question_groups_source_job ON question_groups (source_job_id);

CREATE TRIGGER trg_questions_set_updated_at
BEFORE UPDATE ON questions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE bank_question_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id BIGINT NOT NULL REFERENCES question_banks(id) ON DELETE CASCADE,
    bank_subject VARCHAR(32) NOT NULL,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    question_subject_id VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 1,
    question_no VARCHAR(32),
    status TEXT NOT NULL DEFAULT 'draft',
    added_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_bank_question_links_bank_question UNIQUE (bank_id, question_id),
    CONSTRAINT uq_bank_question_links_bank_sort UNIQUE (bank_id, sort_order),
    CONSTRAINT uq_bank_question_links_bank_question_no UNIQUE (bank_id, question_no),
    CONSTRAINT chk_bank_question_links_sort_order CHECK (sort_order > 0),
    CONSTRAINT chk_bank_question_links_status CHECK (status IN ('draft', 'active', 'archived')),
    CONSTRAINT chk_bank_question_links_subject_match CHECK (bank_subject = question_subject_id),
    CONSTRAINT fk_bank_question_links_bank_subject
        FOREIGN KEY (bank_id, bank_subject)
        REFERENCES question_banks(id, subject)
        ON DELETE CASCADE,
    CONSTRAINT fk_bank_question_links_question_subject
        FOREIGN KEY (question_id, question_subject_id)
        REFERENCES questions(id, subject_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_bank_question_links_bank_sort ON bank_question_links (bank_id, sort_order);
CREATE INDEX idx_bank_question_links_bank_active
    ON bank_question_links (bank_id, sort_order, question_id)
    WHERE status = 'active';
CREATE INDEX idx_bank_question_links_bank_status_sort
    ON bank_question_links (bank_id, status, sort_order, question_id);
CREATE INDEX idx_bank_question_links_question_id ON bank_question_links (question_id);
CREATE UNIQUE INDEX uq_bank_question_links_id_question
    ON bank_question_links (id, question_id);

CREATE TRIGGER trg_bank_question_links_set_subjects
BEFORE INSERT OR UPDATE OF bank_id, question_id ON bank_question_links
FOR EACH ROW
EXECUTE FUNCTION set_bank_question_link_subjects();

CREATE TRIGGER trg_bank_question_links_set_updated_at
BEFORE UPDATE ON bank_question_links
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE bank_group_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id BIGINT NOT NULL REFERENCES question_banks(id) ON DELETE CASCADE,
    bank_subject VARCHAR(32) NOT NULL,
    group_id BIGINT NOT NULL REFERENCES question_groups(id) ON DELETE CASCADE,
    group_subject_id VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'draft',
    added_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_bank_group_links_bank_group UNIQUE (bank_id, group_id),
    CONSTRAINT uq_bank_group_links_bank_sort UNIQUE (bank_id, sort_order),
    CONSTRAINT chk_bank_group_links_sort_order CHECK (sort_order > 0),
    CONSTRAINT chk_bank_group_links_status CHECK (status IN ('draft', 'active', 'archived')),
    CONSTRAINT chk_bank_group_links_subject_match CHECK (bank_subject = group_subject_id),
    CONSTRAINT fk_bank_group_links_bank_subject
        FOREIGN KEY (bank_id, bank_subject)
        REFERENCES question_banks(id, subject)
        ON DELETE CASCADE,
    CONSTRAINT fk_bank_group_links_group_subject
        FOREIGN KEY (group_id, group_subject_id)
        REFERENCES question_groups(id, subject_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_bank_group_links_bank_sort ON bank_group_links (bank_id, sort_order);
CREATE INDEX idx_bank_group_links_bank_active
    ON bank_group_links (bank_id, sort_order, group_id)
    WHERE status = 'active';
CREATE INDEX idx_bank_group_links_bank_status_sort
    ON bank_group_links (bank_id, status, sort_order, group_id);
CREATE INDEX idx_bank_group_links_group_id ON bank_group_links (group_id);
CREATE UNIQUE INDEX uq_bank_group_links_id_group
    ON bank_group_links (id, group_id);

CREATE TRIGGER trg_bank_group_links_set_subjects
BEFORE INSERT OR UPDATE OF bank_id, group_id ON bank_group_links
FOR EACH ROW
EXECUTE FUNCTION set_bank_group_link_subjects();

CREATE TRIGGER trg_bank_group_links_set_updated_at
BEFORE UPDATE ON bank_group_links
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE group_question_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES question_groups(id) ON DELETE CASCADE,
    group_subject_id VARCHAR(32) NOT NULL,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    question_subject_id VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 1,
    question_no VARCHAR(32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_group_question_links_group_question UNIQUE (group_id, question_id),
    CONSTRAINT uq_group_question_links_group_sort UNIQUE (group_id, sort_order),
    CONSTRAINT uq_group_question_links_group_question_no UNIQUE (group_id, question_no),
    CONSTRAINT chk_group_question_links_sort_order CHECK (sort_order > 0),
    CONSTRAINT chk_group_question_links_subject_match CHECK (group_subject_id = question_subject_id),
    CONSTRAINT fk_group_question_links_group_subject
        FOREIGN KEY (group_id, group_subject_id)
        REFERENCES question_groups(id, subject_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_group_question_links_question_subject
        FOREIGN KEY (question_id, question_subject_id)
        REFERENCES questions(id, subject_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_group_question_links_group_sort ON group_question_links (group_id, sort_order);
CREATE INDEX idx_group_question_links_group_question_sort
    ON group_question_links (group_id, question_id, sort_order);
CREATE INDEX idx_group_question_links_question_id ON group_question_links (question_id);

CREATE TRIGGER trg_group_question_links_set_subjects
BEFORE INSERT OR UPDATE OF group_id, question_id ON group_question_links
FOR EACH ROW
EXECUTE FUNCTION set_group_question_link_subjects();

CREATE TRIGGER trg_group_question_links_set_updated_at
BEFORE UPDATE ON group_question_links
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_import_job_outputs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES question_import_jobs(id) ON DELETE CASCADE,
    block_id BIGINT REFERENCES question_import_job_blocks(id) ON DELETE SET NULL,
    attempt_id BIGINT,
    output_kind VARCHAR(32) NOT NULL,
    question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE,
    group_id BIGINT REFERENCES question_groups(id) ON DELETE CASCADE,
    bank_question_link_id BIGINT,
    bank_group_link_id BIGINT,
    confidence DOUBLE PRECISION,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_import_job_outputs_kind CHECK (
        output_kind IN ('question', 'group')
    ),
    CONSTRAINT chk_question_import_job_outputs_target CHECK (
        (output_kind = 'question' AND question_id IS NOT NULL AND group_id IS NULL)
        OR (output_kind = 'group' AND group_id IS NOT NULL AND question_id IS NULL)
    ),
    CONSTRAINT chk_question_import_job_outputs_link CHECK (
        (bank_question_link_id IS NULL OR output_kind = 'question')
        AND (bank_group_link_id IS NULL OR output_kind = 'group')
    ),
    CONSTRAINT chk_question_import_job_outputs_attempt_block CHECK (
        attempt_id IS NULL OR block_id IS NOT NULL
    ),
    CONSTRAINT chk_question_import_job_outputs_confidence CHECK (
        confidence IS NULL OR confidence BETWEEN 0 AND 1
    ),
    CONSTRAINT fk_question_import_job_outputs_attempt_block
        FOREIGN KEY (attempt_id, block_id)
        REFERENCES question_import_job_block_attempts(id, block_id),
    CONSTRAINT fk_question_import_job_outputs_bank_question
        FOREIGN KEY (bank_question_link_id, question_id)
        REFERENCES bank_question_links(id, question_id),
    CONSTRAINT fk_question_import_job_outputs_bank_group
        FOREIGN KEY (bank_group_link_id, group_id)
        REFERENCES bank_group_links(id, group_id)
);

CREATE UNIQUE INDEX uq_question_import_job_outputs_question
    ON question_import_job_outputs (job_id, question_id)
    WHERE question_id IS NOT NULL;
CREATE UNIQUE INDEX uq_question_import_job_outputs_group
    ON question_import_job_outputs (job_id, group_id)
    WHERE group_id IS NOT NULL;
CREATE INDEX idx_question_import_job_outputs_block
    ON question_import_job_outputs (block_id, attempt_id);

CREATE VIEW v_bank_question_items AS
SELECT
    bgl.bank_id,
    g.id AS group_id,
    q.id AS question_id,
    'grouped' AS item_scope,
    bgl.sort_order AS bank_sort_order,
    gql.sort_order AS group_sort_order,
    gql.question_no AS question_no,
    bgl.status AS bank_link_status,
    q.business_type,
    q.subject_id,
    q.question_type_id,
    q.answer_mode,
    q.choice_variant,
    q.content_mode,
    q.stem,
    q.analysis,
    q.status AS question_status,
    q.source_type,
    q.source_ref,
    q.source_job_id,
    q.imported_by,
    q.hierarchy_level,
    q.hierarchy_path,
    q.chapter_ref,
    q.chapter_title,
    q.chapter_order,
    g.business_type AS group_business_type,
    g.subject_id AS group_subject_id,
    g.group_type_id,
    g.content_mode AS group_content_mode,
    g.title AS group_title,
    g.instructions AS group_instructions,
    g.source_ref AS group_source_ref,
    g.parent_group_id,
    g.source_job_id AS group_source_job_id,
    g.imported_by AS group_imported_by,
    g.hierarchy_level AS group_hierarchy_level,
    g.hierarchy_path AS group_hierarchy_path,
    g.chapter_ref AS group_chapter_ref,
    g.chapter_title AS group_chapter_title,
    g.chapter_order AS group_chapter_order
FROM bank_group_links bgl
JOIN question_groups g ON g.id = bgl.group_id
JOIN group_question_links gql ON gql.group_id = g.id
JOIN questions q ON q.id = gql.question_id
UNION ALL
SELECT
    bql.bank_id,
    CAST(NULL AS BIGINT) AS group_id,
    q.id AS question_id,
    'standalone' AS item_scope,
    bql.sort_order AS bank_sort_order,
    CAST(NULL AS INTEGER) AS group_sort_order,
    bql.question_no AS question_no,
    bql.status AS bank_link_status,
    q.business_type,
    q.subject_id,
    q.question_type_id,
    q.answer_mode,
    q.choice_variant,
    q.content_mode,
    q.stem,
    q.analysis,
    q.status AS question_status,
    q.source_type,
    q.source_ref,
    q.source_job_id,
    q.imported_by,
    q.hierarchy_level,
    q.hierarchy_path,
    q.chapter_ref,
    q.chapter_title,
    q.chapter_order,
    CAST(NULL AS VARCHAR(64)) AS group_business_type,
    CAST(NULL AS VARCHAR(32)) AS group_subject_id,
    CAST(NULL AS VARCHAR(64)) AS group_type_id,
    CAST(NULL AS VARCHAR(32)) AS group_content_mode,
    CAST(NULL AS VARCHAR(512)) AS group_title,
    CAST(NULL AS VARCHAR(1024)) AS group_instructions,
    CAST(NULL AS VARCHAR(128)) AS group_source_ref,
    CAST(NULL AS BIGINT) AS parent_group_id,
    CAST(NULL AS BIGINT) AS group_source_job_id,
    CAST(NULL AS BIGINT) AS group_imported_by,
    CAST(NULL AS INTEGER) AS group_hierarchy_level,
    CAST(NULL AS VARCHAR(512)) AS group_hierarchy_path,
    CAST(NULL AS VARCHAR(128)) AS group_chapter_ref,
    CAST(NULL AS VARCHAR(512)) AS group_chapter_title,
    CAST(NULL AS INTEGER) AS group_chapter_order
FROM bank_question_links bql
JOIN questions q ON q.id = bql.question_id;

CREATE TABLE question_choice_details (
    question_id BIGINT PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,
    selection_mode TEXT NOT NULL DEFAULT 'single',
    CONSTRAINT chk_question_choice_details_selection_mode CHECK (selection_mode IN ('single', 'multiple'))
);

CREATE TABLE question_true_false_details (
    question_id BIGINT PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,
    correct_answer BOOLEAN
);

CREATE TABLE question_fill_blank_details (
    question_id BIGINT PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,
    correct_answer TEXT NOT NULL DEFAULT '[]'
);

CREATE TABLE question_short_answer_details (
    question_id BIGINT PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,
    correct_answer TEXT
);

CREATE TABLE question_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    option_label VARCHAR(16) NOT NULL,
    sort_order SMALLINT NOT NULL DEFAULT 1,
    content TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_options_label_not_blank CHECK (btrim(option_label) <> ''),
    CONSTRAINT chk_question_options_sort_order CHECK (sort_order > 0),
    CONSTRAINT chk_question_options_content_not_blank CHECK (btrim(content) <> '')
);

CREATE UNIQUE INDEX uq_question_options_question_label ON question_options (question_id, option_label);
CREATE UNIQUE INDEX uq_question_options_question_sort ON question_options (question_id, sort_order);

CREATE TRIGGER trg_question_options_set_updated_at
BEFORE UPDATE ON question_options
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_subquestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    label VARCHAR(32),
    sort_order SMALLINT NOT NULL DEFAULT 1,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_question_subquestions_sort_order CHECK (sort_order > 0),
    CONSTRAINT chk_question_subquestions_content_not_blank CHECK (btrim(content) <> ''),
    CONSTRAINT chk_question_subquestions_label_not_blank CHECK (label IS NULL OR btrim(label) <> '')
);

CREATE UNIQUE INDEX uq_question_subquestions_question_sort ON question_subquestions (question_id, sort_order);
CREATE INDEX idx_question_subquestions_question_label ON question_subquestions (question_id, label);

CREATE TRIGGER trg_question_subquestions_set_updated_at
BEFORE UPDATE ON question_subquestions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_answer_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    answer_mode VARCHAR(32) NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    is_primary BOOLEAN NOT NULL DEFAULT TRUE,
    answer_payload TEXT NOT NULL DEFAULT '{}',
    explanation_payload TEXT NOT NULL DEFAULT '{}',
    score_payload TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_answer_keys_question_version UNIQUE (question_id, version),
    CONSTRAINT chk_question_answer_keys_version CHECK (version > 0),
    CONSTRAINT chk_question_answer_keys_answer_mode CHECK (
        answer_mode IN ('choice', 'true_false', 'fill_blank', 'short_answer')
    )
);

CREATE UNIQUE INDEX uq_question_answer_keys_id_question
    ON question_answer_keys (id, question_id);
CREATE INDEX idx_question_answer_keys_question ON question_answer_keys (question_id, is_primary);
CREATE UNIQUE INDEX uq_question_answer_keys_primary
    ON question_answer_keys (question_id)
    WHERE is_primary;

CREATE TRIGGER trg_question_answer_keys_set_updated_at
BEFORE UPDATE ON question_answer_keys
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_fill_blank_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    blank_ref VARCHAR(64) NOT NULL,
    blank_index INTEGER NOT NULL,
    label VARCHAR(64),
    stem_anchor VARCHAR(256),
    correct_answer TEXT,
    accepted_answers_json TEXT NOT NULL DEFAULT '[]',
    formula_latex TEXT,
    formula_mathml TEXT,
    unit_text VARCHAR(64),
    tolerance_text VARCHAR(64),
    case_sensitive BOOLEAN NOT NULL DEFAULT FALSE,
    score_weight DOUBLE PRECISION,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_fill_blank_slots_ref UNIQUE (question_id, blank_ref),
    CONSTRAINT uq_question_fill_blank_slots_index UNIQUE (question_id, blank_index),
    CONSTRAINT chk_question_fill_blank_slots_index CHECK (blank_index > 0)
);

CREATE INDEX idx_question_fill_blank_slots_question ON question_fill_blank_slots (question_id, blank_index);

CREATE TRIGGER trg_question_fill_blank_slots_set_updated_at
BEFORE UPDATE ON question_fill_blank_slots
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_rubric_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    rubric_ref VARCHAR(64),
    sort_order INTEGER NOT NULL DEFAULT 1,
    criterion VARCHAR(256) NOT NULL,
    description TEXT,
    score_value DOUBLE PRECISION,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_rubric_items_sort UNIQUE (question_id, sort_order),
    CONSTRAINT chk_question_rubric_items_sort_order CHECK (sort_order > 0),
    CONSTRAINT chk_question_rubric_items_criterion_not_blank CHECK (btrim(criterion) <> '')
);

CREATE INDEX idx_question_rubric_items_question ON question_rubric_items (question_id, sort_order);

CREATE TRIGGER trg_question_rubric_items_set_updated_at
BEFORE UPDATE ON question_rubric_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_educational_metadata (
    question_id BIGINT PRIMARY KEY REFERENCES questions(id) ON DELETE CASCADE,
    difficulty_level VARCHAR(32),
    difficulty_score DOUBLE PRECISION,
    grade_level VARCHAR(64),
    exam_type VARCHAR(64),
    curriculum_standard VARCHAR(128),
    textbook_version VARCHAR(128),
    knowledge_tags_json TEXT NOT NULL DEFAULT '[]',
    skill_tags_json TEXT NOT NULL DEFAULT '[]',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_question_educational_metadata_exam
    ON question_educational_metadata (exam_type, difficulty_level);

CREATE TRIGGER trg_question_educational_metadata_set_updated_at
BEFORE UPDATE ON question_educational_metadata
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE knowledge_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id VARCHAR(32) NOT NULL REFERENCES subjects(subject_id) ON DELETE RESTRICT,
    code VARCHAR(128) NOT NULL,
    display_name VARCHAR(256) NOT NULL,
    parent_id BIGINT REFERENCES knowledge_points(id) ON DELETE SET NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_knowledge_points_subject_code UNIQUE (subject_id, code),
    CONSTRAINT chk_knowledge_points_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT chk_knowledge_points_name_not_blank CHECK (btrim(display_name) <> '')
);

CREATE UNIQUE INDEX uq_knowledge_points_id_subject ON knowledge_points (id, subject_id);
CREATE INDEX idx_knowledge_points_parent ON knowledge_points (parent_id);

CREATE TRIGGER trg_knowledge_points_set_updated_at
BEFORE UPDATE ON knowledge_points
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE question_knowledge_point_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    question_subject_id VARCHAR(32) NOT NULL,
    knowledge_point_id BIGINT NOT NULL REFERENCES knowledge_points(id) ON DELETE CASCADE,
    knowledge_point_subject_id VARCHAR(32) NOT NULL,
    relevance_score DOUBLE PRECISION,
    source_type VARCHAR(32) NOT NULL DEFAULT 'parsed',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_knowledge_point_links UNIQUE (question_id, knowledge_point_id),
    CONSTRAINT chk_question_knowledge_point_links_subject_match CHECK (
        question_subject_id = knowledge_point_subject_id
    ),
    CONSTRAINT chk_question_knowledge_point_links_relevance CHECK (
        relevance_score IS NULL OR relevance_score BETWEEN 0 AND 1
    ),
    CONSTRAINT fk_question_knowledge_point_links_question_subject
        FOREIGN KEY (question_id, question_subject_id)
        REFERENCES questions(id, subject_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_question_knowledge_point_links_kp_subject
        FOREIGN KEY (knowledge_point_id, knowledge_point_subject_id)
        REFERENCES knowledge_points(id, subject_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_question_knowledge_point_links_kp
    ON question_knowledge_point_links (knowledge_point_id);

CREATE TRIGGER trg_question_knowledge_point_links_set_subjects
BEFORE INSERT OR UPDATE OF question_id, knowledge_point_id ON question_knowledge_point_links
FOR EACH ROW
EXECUTE FUNCTION set_question_knowledge_point_link_subjects();

CREATE TABLE question_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    tag_type VARCHAR(32) NOT NULL DEFAULT 'general',
    tag_value VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_question_tags UNIQUE (question_id, tag_type, tag_value),
    CONSTRAINT chk_question_tags_value_not_blank CHECK (btrim(tag_value) <> '')
);

CREATE INDEX idx_question_tags_type_value ON question_tags (tag_type, tag_value);

CREATE TABLE question_provenance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    source_job_id BIGINT REFERENCES question_import_jobs(id) ON DELETE SET NULL,
    source_block_ref VARCHAR(128),
    source_page_no INTEGER,
    source_page_start INTEGER,
    source_page_end INTEGER,
    source_bbox_json TEXT,
    source_text TEXT,
    confidence DOUBLE PRECISION,
    quality_flags_json TEXT NOT NULL DEFAULT '[]',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_question_provenance_question ON question_provenance (question_id);
CREATE INDEX idx_question_provenance_source_job
    ON question_provenance (source_job_id, source_block_ref);

CREATE TABLE ai_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artifact_type VARCHAR(64) NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    bank_id BIGINT REFERENCES question_banks(id) ON DELETE SET NULL,
    question_id BIGINT REFERENCES questions(id) ON DELETE SET NULL,
    import_job_id BIGINT REFERENCES question_import_jobs(id) ON DELETE SET NULL,
    practice_session_id BIGINT,
    provider VARCHAR(64) NOT NULL DEFAULT 'mastra',
    model VARCHAR(128),
    input_payload JSONB NOT NULL DEFAULT '{}',
    output_payload JSONB NOT NULL DEFAULT '{}',
    status VARCHAR(32) NOT NULL DEFAULT 'completed',
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_ai_artifacts_type CHECK (
        artifact_type IN ('document_parse', 'answer_generation', 'learning_report')
    ),
    CONSTRAINT chk_ai_artifacts_status CHECK (
        status IN ('completed', 'failed')
    ),
    CONSTRAINT chk_ai_artifacts_payload_object CHECK (
        jsonb_typeof(input_payload) = 'object'
        AND jsonb_typeof(output_payload) = 'object'
    )
);

CREATE INDEX idx_ai_artifacts_question
    ON ai_artifacts (question_id, artifact_type, created_at DESC);
CREATE INDEX idx_ai_artifacts_import_job
    ON ai_artifacts (import_job_id, artifact_type, created_at DESC);
CREATE INDEX idx_ai_artifacts_user
    ON ai_artifacts (user_id, artifact_type, created_at DESC);

DO $$
BEGIN
    IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'openwook_ai') THEN
        EXECUTE format('GRANT CONNECT ON DATABASE %I TO openwook_ai', current_database());
        GRANT USAGE ON SCHEMA public TO openwook_ai;
        GRANT SELECT (id, created_by, bank_id) ON question_import_jobs TO openwook_ai;
        GRANT INSERT, SELECT (id) ON ai_artifacts TO openwook_ai;
        GRANT USAGE, SELECT ON SEQUENCE ai_artifacts_id_seq TO openwook_ai;
    END IF;
END
$$;
