import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Button, Checkbox, Chip, FieldError, Input, Label, ListBox, Radio, RadioGroup, Select, Separator, TextField, Typography } from '@heroui/react';
import { answerPayload, mutate, type Bank, type Question, type QuestionPage, type QuestionType, type Session, type Snapshot, type Task } from './api';
import { Choice, Confirm, Empty, Field, Go, LoadState, Notice, PageTitle, Panel, SaveForm, Stat, useAction, useResource } from './ui';
import { QuestionBody, describePayload } from './pages-content';

export function Home() {
  const state = useResource<Snapshot>('/analytics/snapshot');
  const summary = state.data?.summary;
  return <><PageTitle title="今天，从一道题开始"><Go to="/search">搜索题目</Go></PageTitle><LoadState state={state} />{summary && <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[['题库', summary.banks], ['已答题', summary.attempts], ['正确率', `${summary.accuracy}%`], ['收藏', summary.favorite_banks]].map(([label, value]) => <Stat key={label} label={String(label)} value={value} />)}</div>}<Panel title="继续学习" description="选择题库练习，或将手头资料导入为可练习的题目。"><div className="flex flex-wrap gap-4"><Go to="/banks">打开题库</Go><Go to="/imports/new">导入资料</Go><Go to="/analytics">查看学习分析</Go></div></Panel><Panel title="最近练习">{state.data?.recentSessions.length === 0 && <Empty>还没有练习记录，从题库开始第一次练习。</Empty>}{state.data?.recentSessions.map(s => <div key={s.id} className="flex flex-wrap items-center justify-between gap-3"><Typography.Paragraph className="min-w-0 max-w-full flex-1 overflow-x-auto">练习 #{s.id} · {s.answered_count}/{s.question_count} 题</Typography.Paragraph><Chip>{s.status === 'active' ? '进行中' : s.status === 'completed' ? '已完成' : '已放弃'}</Chip><Go to={`/practice/${s.id}${s.status === 'active' ? '' : '/results'}`}>{s.status === 'active' ? '继续练习' : '查看结果'}</Go></div>)}</Panel></>;
}

export function PracticeSetup() {
  const id = Number(useParams().id), bank = useResource<Bank>(`/banks/${id}`), types = useResource<QuestionType[]>('/question-types');
  const [mode, setMode] = useState('all'), [count, setCount] = useState('30'), [type, setType] = useState('choice');
  const action = useAction(), navigate = useNavigate();
  return <><PageTitle title="开始练习"><Go to={`/banks/${id}`}>返回题库</Go></PageTitle><LoadState state={bank} /><div className="mx-auto w-full max-w-2xl"><Panel title={bank.data?.name ?? '练习设置'} description="只使用已发布的题目；考试模式在交卷后显示答案。"><SaveForm action={action} label="开始" onSave={async () => { const s = await mutate<Session>('/practice-sessions', 'POST', { bankId: id, mode, questionCount: Number(count), questionTypeId: mode === 'by_type' ? type : '' }); navigate(`/practice/${s.id}`); }}><Choice label="练习模式" value={mode} onChange={setMode} items={[{ id: 'all', label: '顺序练习' }, { id: 'wrong', label: '错题复习' }, { id: 'by_type', label: '按题型练习' }, { id: 'exam', label: '模拟考试' }]} /><Field label="题目数量（1–500）" value={count} onChange={setCount} type="number" required />{mode === 'by_type' && <Choice label="题型" value={type} onChange={setType} items={(types.data ?? []).map(t => ({ id: t.type_id, label: t.display_name }))} />}</SaveForm></Panel></div></>;
}

export function PracticePage() {
  const id = Number(useParams().id), [index, setIndex] = useState<number | null>(null), state = useResource<QuestionPage>(`/practice-sessions/${id}/question-page${index === null ? '' : `?index=${index}`}`);
  const [selected, setSelected] = useState<string[]>([]), [value, setValue] = useState(''), [blanks, setBlanks] = useState<string[]>([]), [order, setOrder] = useState<number[]>([]), [matches, setMatches] = useState<Record<number, number>>({});
  const action = useAction(), navigate = useNavigate();
  const page = state.data, q = page?.question;
  useEffect(() => {
    const payload = page?.result?.answer_payload;
    setSelected(Array.isArray(payload?.selected) ? payload.selected as string[] : []);
    setValue(Array.isArray(payload?.value) ? '' : String(payload?.value ?? ''));
    setBlanks(Array.isArray(payload?.value) ? payload.value as string[] : []);
    setOrder(Array.isArray(payload?.order) ? payload.order as number[] : (page?.question.items ?? []).map(i => i.id));
    const restored: Record<number, number> = {};
    if (Array.isArray(payload?.matches)) for (const m of payload.matches as { left: number; right: number }[]) restored[m.left] = m.right;
    setMatches(restored);
  }, [page]);
  const moveItem = (pos: number, delta: number) => setOrder(old => { const next = [...old]; const [picked] = next.splice(pos, 1); next.splice(pos + delta, 0, picked); return next; });
  const submitPayload = () => {
    if (!q) return {};
    if (q.answer_mode === 'ordering') return { order };
    if (q.answer_mode === 'matching') return { matches: (q.items ?? []).filter(i => i.side === 'left').map(l => ({ left: l.id, right: matches[l.id] })) };
    if (q.answer_mode === 'fill_blank') return { value: blanks };
    return answerPayload(q.answer_mode, value, selected);
  };
  return <><PageTitle title={page?.session.mode === 'exam' ? '模拟考试' : '专注练习'}><Go to="/">稍后继续</Go></PageTitle><LoadState state={state} />{page && q && <div className="grid gap-6 lg:grid-cols-3"><div className="min-w-0 lg:col-span-2"><Panel title={`第 ${page.questionIndex+1} / ${page.total} 题`}><QuestionBody question={q} /><SaveForm action={action} label={page.result ? '已提交' : '提交答案'} onSave={async () => { if (page.result || !q) return; if (q.answer_mode === 'true_false' && !value) throw new Error('请选择正确或错误'); if (q.answer_mode === 'ordering' && order.length !== (q.items?.length ?? 0)) throw new Error('请排列全部条目'); if (q.answer_mode === 'matching' && (q.items ?? []).some(i => i.side === 'left' && !matches[i.id])) throw new Error('请为每个左项选择配对'); if (q.answer_mode === 'fill_blank' && blanks.some(b => !b.trim())) throw new Error('请填写每个空'); await mutate(`/practice-sessions/${id}/answers`, 'POST', { questionId: q.id, answerPayload: submitPayload() }); state.reload(); }}>
      {q.answer_mode === 'choice' && (q.choice_variant === 'multiple' ? <div className="flex flex-col gap-3">{q.options.map(o => <Checkbox key={o.id} isDisabled={Boolean(page.result)} isSelected={selected.includes(o.option_label)} onChange={checked => setSelected(old => checked ? [...old, o.option_label] : old.filter(v => v !== o.option_label))}><Checkbox.Control><Checkbox.Indicator /></Checkbox.Control><Checkbox.Content>{o.option_label}. {o.content}</Checkbox.Content></Checkbox>)}</div> : <RadioGroup aria-label="选择答案" value={selected[0] ?? ''} onChange={v => setSelected([v])} isDisabled={Boolean(page.result)}>{q.options.map(o => <Radio key={o.id} value={o.option_label}><Radio.Control><Radio.Indicator /></Radio.Control><Radio.Content>{o.option_label}. {o.content}</Radio.Content></Radio>)}</RadioGroup>)}
      {q.answer_mode === 'true_false' && <RadioGroup aria-label="判断答案" value={value} onChange={setValue} isDisabled={Boolean(page.result)}><Radio value="true"><Radio.Control><Radio.Indicator /></Radio.Control><Radio.Content>正确</Radio.Content></Radio><Radio value="false"><Radio.Control><Radio.Indicator /></Radio.Control><Radio.Content>错误</Radio.Content></Radio></RadioGroup>}
      {q.answer_mode === 'ordering' && <div className="flex flex-col gap-2">{order.map((itemId, pos) => { const item = q.items?.find(i => i.id === itemId); return <div key={itemId} className="flex items-center gap-2"><Chip>{pos + 1}</Chip><Typography.Paragraph className="min-w-0 flex-1 max-w-full overflow-x-auto">{item?.content}</Typography.Paragraph><Button size="sm" variant="secondary" isDisabled={pos === 0 || Boolean(page.result)} onPress={() => moveItem(pos, -1)} aria-label="上移">↑</Button><Button size="sm" variant="secondary" isDisabled={pos === order.length - 1 || Boolean(page.result)} onPress={() => moveItem(pos, 1)} aria-label="下移">↓</Button></div>; })}</div>}
      {q.answer_mode === 'matching' && <div className="flex flex-col gap-3">{(q.items ?? []).filter(i => i.side === 'left').map((l, li) => { const taken = new Set(Object.entries(matches).filter(([lid]) => Number(lid) !== l.id).map(([, rid]) => rid)); const options = (q.items ?? []).filter(i => i.side === 'right' && (q.matching_variant !== 'one_to_one' || matches[l.id] === i.id || !taken.has(i.id))); return <div key={l.id} className="flex flex-wrap items-center gap-3"><Chip>{li + 1}</Chip><Typography.Paragraph className="min-w-0 flex-1 max-w-full overflow-x-auto">{l.content}</Typography.Paragraph><Select aria-label={`「${l.content}」的配对`} value={matches[l.id] ? String(matches[l.id]) : null} onChange={v => setMatches(old => ({ ...old, [l.id]: Number(v ?? 0) }))} className="w-full sm:w-64"><Select.Trigger><Select.Value /><Select.Indicator /></Select.Trigger><Select.Popover><ListBox>{options.map(r => <ListBox.Item key={r.id} id={String(r.id)} textValue={r.content}>{r.content}<ListBox.ItemIndicator /></ListBox.Item>)}</ListBox></Select.Popover></Select></div>; })}</div>}
      {q.answer_mode === 'fill_blank' && <div className="flex flex-col gap-3">{Array.from({ length: q.blank_count ?? 1 }, (_, i) => <TextField key={i} value={blanks[i] ?? ''} onChange={v => setBlanks(old => { const next = [...old]; next[i] = v; return next; })} type="text" fullWidth isDisabled={Boolean(page.result)}><Label>{`第 ${i + 1} 空`}</Label><Input /><FieldError /></TextField>)}</div>}
      {q.answer_mode === 'short_answer' && <Field label="你的答案" value={value} onChange={setValue} multiline required />}
    </SaveForm>{page.result && <Panel title={page.session.mode === 'exam' && page.session.status !== 'completed' ? '答案已记录，交卷后显示结果' : page.result.is_correct === null ? '请对照参考答案自查' : page.result.is_correct ? '回答正确' : '继续加油'}>{page.result.answer_key_payload && <Typography.Paragraph className="max-w-full overflow-x-auto">参考答案：{describePayload(q.answer_mode, page.result.answer_key_payload, q.items)}</Typography.Paragraph>}</Panel>}{page.result && page.result.is_correct === null && (page.session.mode !== 'exam' || page.session.status === 'completed') && <div className="flex flex-wrap gap-3"><Button isDisabled={action.busy} onPress={() => void action.run(async () => { await mutate(`/practice-sessions/${id}/answers/${q.id}/review`, 'POST', { isCorrect: true }); state.reload(); })}>记为正确</Button><Button variant="danger-soft" isDisabled={action.busy} onPress={() => void action.run(async () => { await mutate(`/practice-sessions/${id}/answers/${q.id}/review`, 'POST', { isCorrect: false }); state.reload(); })}>记为错误</Button></div>}<div className="flex flex-wrap justify-between gap-3"><Button variant="secondary" isDisabled={page.previousIndex === null || action.busy} onPress={() => setIndex(page.previousIndex)}>上一题</Button><Button variant="secondary" isDisabled={page.nextIndex === null || action.busy} onPress={() => setIndex(page.nextIndex)}>下一题</Button></div></Panel></div><Panel title="练习进度"><div className="flex flex-wrap gap-2">{page.progress.map(p => <Button key={p.index} size="sm" variant={p.index === page.questionIndex ? 'primary' : p.isAnswered ? 'secondary' : 'tertiary'} onPress={() => setIndex(p.index)} aria-label={`第 ${p.index+1} 题${p.isAnswered ? '，已作答' : ''}`}>{p.index+1}</Button>)}</div><Typography.Paragraph className="max-w-full overflow-x-auto">{page.session.answered_count}/{page.total} 题已提交</Typography.Paragraph><Confirm label="完成并查看结果" onConfirm={async () => { await mutate(`/practice-sessions/${id}/complete`); navigate(`/practice/${id}/results`); }} /><Confirm label="放弃本次练习" onConfirm={async () => { await mutate(`/practice-sessions/${id}/abandon`); navigate('/'); }} /></Panel></div>}</>;
}
export function ResultsPage() {
  const id = Number(useParams().id), state = useResource<Question[]>(`/practice-sessions/${id}/results`);
  return <><PageTitle title="练习结果"><Go to="/">返回学习</Go></PageTitle><LoadState state={state} />{state.data?.map((q, i) => <Panel key={q.id} title={`第 ${i+1} 题`}><div className="flex flex-wrap items-center gap-3"><Chip>{!q.result ? '未作答' : q.result.is_correct === null ? '未判分' : q.result.is_correct ? '正确' : '错误'}</Chip>{q.result && q.result.score !== null && q.result.score > 0 && q.result.score < 1 && <Chip>部分得分 {Math.round(q.result.score * 100)}%</Chip>}{q.group && <Chip>组合：{q.group.title}</Chip>}</div><QuestionBody question={q} /><Separator /><Typography.Paragraph className="max-w-full overflow-x-auto">你的答案：{describePayload(q.answer_mode, q.result?.answer_payload, q.items)}</Typography.Paragraph>{q.result?.answer_key_payload && <Typography.Paragraph className="max-w-full overflow-x-auto">参考答案：{describePayload(q.answer_mode, q.result.answer_key_payload, q.items)}</Typography.Paragraph>}</Panel>)}</>;
}
export function Analytics() {
  const state = useResource<Snapshot>('/analytics/snapshot'), reports = useResource<Task[]>('/ai-tasks'); const action = useAction(), navigate = useNavigate();
  return <><PageTitle title="学习分析"><Button isDisabled={action.busy || !state.data?.summary.attempts} onPress={() => void action.run(async () => { const t = await mutate<Task>('/analytics/report-tasks'); navigate(`/tasks/${t.id}`); })}>生成 AI 学习报告</Button></PageTitle><LoadState state={state} />{action.error && <Notice>{action.error}</Notice>}{state.data && <><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[['累计作答', state.data.summary.attempts], ['正确', state.data.summary.correct], ['错误', state.data.summary.wrong], ['正确率', `${state.data.summary.accuracy}%`]].map(([label, value]) => <Stat key={label} label={String(label)} value={value} />)}</div><div className="grid gap-6 lg:grid-cols-2"><Panel title="需要巩固的题目">{state.data.weakQuestions.length === 0 && <Empty>练习后会在这里看到薄弱题目。</Empty>}{state.data.weakQuestions.map(q => <div key={q.question_id} className="flex min-w-0 flex-col gap-2"><Typography.Paragraph className="max-w-full overflow-x-auto">{q.stem}</Typography.Paragraph><Go to={`/questions/${q.question_id}`}>查看 · 错误 {q.wrong_count} 次</Go></div>)}</Panel><Panel title="近期学习记录">{state.data.trend.length === 0 && <Empty />}{state.data.trend.map(d => <Typography.Paragraph key={d.day}>{d.day} · 作答 {d.attempts} · 正确 {d.correct}</Typography.Paragraph>)}</Panel></div></>}<Panel title="AI 任务与报告">{reports.data?.length === 0 && <Empty />}{reports.data?.map(t => <div key={t.id} className="flex flex-wrap gap-3"><Go to={`/tasks/${t.id}`}>任务 #{t.id} · {t.kind}</Go><Chip>{t.status}</Chip></div>)}</Panel></>;
}

export function BankAnalytics() {
  const id = Number(useParams().id), bank = useResource<Bank>(`/banks/${id}`), state = useResource<Snapshot['summary']>(`/analytics/banks/${id}`);
  return <><PageTitle title={`${bank.data?.name ?? '题库'} · 学习分析`}><Go to={`/banks/${id}`}>返回题库</Go></PageTitle><LoadState state={state} />{state.data && <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[['作答次数', state.data.attempts], ['正确次数', state.data.correct], ['错误次数', state.data.wrong], ['正确率', `${state.data.accuracy}%`]].map(([label, value]) => <Stat key={label} label={String(label)} value={value} />)}</div>}<Go to={`/practice/new/${id}`}>开始练习或复习错题</Go></>;
}
