import { useEffect, useRef, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Button, Card, Checkbox, Chip, Separator, Typography } from '@heroui/react';
import { clearClientCache, mutate, type Bank, type Block, type Group, type Knowledge, type Media, type Mode, type Question, type QuestionType, type Subset, type Task } from './api';
import { Choice, Confirm, Empty, Field, Go, LoadState, Notice, PageTitle, Panel, SaveForm, useAction, useResource } from './ui';

export function Banks() {
  const [scope, setScope] = useState('all'), [query, setQuery] = useState(''), [cursor, setCursor] = useState('');
  const state = useResource<Bank[]>(`/banks?scope=${scope}&q=${encodeURIComponent(query)}&cursor=${cursor}`);
  const [name, setName] = useState(''), [description, setDescription] = useState('');
  const action = useAction(), navigate = useNavigate();
  return <><PageTitle title="我的题库"><Go to="/search">搜索题目</Go></PageTitle><div className="grid gap-6 lg:grid-cols-3"><section className="flex min-w-0 flex-col gap-4 lg:col-span-2"><div className="grid gap-3 sm:grid-cols-2"><Field label="查找题库" value={query} onChange={v => { setQuery(v); setCursor(''); }} /><Choice label="范围" value={scope} onChange={v => { setScope(v); setCursor(''); }} items={[{ id: 'all', label: '全部题库' }, { id: 'favorites', label: '收藏' }]} /></div><LoadState state={state} />{state.data?.length === 0 && <Empty>还没有题库。新建题库后可手动添加或导入题目。</Empty>}{state.data?.map(b => <Panel key={b.id} title={b.name} description={b.description}><div className="flex flex-wrap items-center gap-4"><Go to={`/banks/${b.id}`}>打开题库</Go>{b.is_favorite && <Chip>已收藏</Chip>}</div></Panel>)}<div className="flex gap-3">{cursor && <Button variant="secondary" onPress={() => setCursor('')}>返回第一页</Button>}{state.pagination?.hasMore && <Button variant="secondary" onPress={() => setCursor(state.pagination!.cursor)}>下一页</Button>}</div></section><Panel title="新建题库" description="为一个学科或学习目标建立题库。"><SaveForm action={action} label="创建题库" onSave={async () => { const b = await mutate<Bank>('/banks', 'POST', { name, description }); navigate(`/banks/${b.id}`); }}><Field label="题库名称" value={name} onChange={setName} required /><Field label="简介" value={description} onChange={setDescription} multiline /></SaveForm></Panel></div></>;
}

export function BankDetail() {
  const id = Number(useParams().id), navigate = useNavigate();
  const state = useResource<Bank>(`/banks/${id}`);
  const [cursor, setCursor] = useState('');
  const items = useResource<Question[]>(`/banks/${id}/items?cursor=${cursor}`), groups = useResource<Group[]>(`/banks/${id}/groups`), subsets = useResource<Subset[]>(`/banks/${id}/subsets`), tags = useResource<string[]>(`/banks/${id}/tags`);
  const [name, setName] = useState(''), [description, setDescription] = useState(''), [tagText, setTagText] = useState('');
  const action = useAction();
  useEffect(() => { if (state.data) { setName(state.data.name); setDescription(state.data.description ?? ''); } }, [state.data]);
  useEffect(() => { if (tags.data) setTagText(tags.data.join(', ')); }, [tags.data]);
  return <><PageTitle title={state.data?.name ?? '题库'}><Go to="/banks">全部题库</Go></PageTitle><LoadState state={state} />{state.data && <><div className="flex flex-wrap gap-4"><Go to={`/practice/new/${id}`}>开始练习</Go><Go to={`/banks/${id}/questions/new`}>添加题目</Go><Go to={`/imports/new?bankId=${id}`}>导入题目</Go><Go to={`/analytics/banks/${id}`}>题库分析</Go><Button variant="secondary" isDisabled={action.busy} onPress={() => void action.run(async () => { await mutate(`/banks/${id}/favorite`, state.data!.is_favorite ? 'DELETE' : 'POST'); state.reload(); })}>{state.data.is_favorite ? '取消收藏' : '收藏题库'}</Button></div>{action.error && <Notice>{action.error}</Notice>}<div className="grid gap-6 lg:grid-cols-3"><section className="flex min-w-0 flex-col gap-4 lg:col-span-2"><Panel title="题目"><LoadState state={items} />{items.data?.length === 0 && <Empty />}{items.data?.map(q => <Card key={q.id}><Card.Content><Typography.Paragraph className="max-w-full overflow-x-auto">{q.stem}</Typography.Paragraph><div className="mt-3 flex flex-wrap items-center gap-4"><Chip>{q.question_status}</Chip><Go to={`/questions/${q.id}`}>查看</Go><Go to={`/questions/${q.id}/edit`}>编辑</Go></div></Card.Content></Card>)}<div className="flex gap-3">{cursor && <Button variant="secondary" onPress={() => setCursor('')}>第一页</Button>}{items.pagination?.hasMore && <Button variant="secondary" onPress={() => setCursor(items.pagination!.cursor)}>下一页</Button>}</div></Panel><GroupManager bankId={id} groups={groups.data ?? []} reload={groups.reload} /><SubsetManager bankId={id} subsets={subsets.data ?? []} reload={subsets.reload} /></section><section className="flex min-w-0 flex-col gap-6"><Panel title="题库设置"><SaveForm action={action} onSave={async () => { await mutate(`/banks/${id}`, 'PATCH', { name, description }); await mutate(`/banks/${id}/tags`, 'PATCH', { tags: tagText.split(',').map(s => s.trim()).filter(Boolean) }); state.reload(); tags.reload(); }}><Field label="名称" value={name} onChange={setName} required /><Field label="简介" value={description} onChange={setDescription} multiline /><Field label="标签（逗号分隔）" value={tagText} onChange={setTagText} /></SaveForm><Separator /><Confirm label="清除本题库练习记录" onConfirm={() => mutate(`/banks/${id}/practice-data`, 'DELETE')} /><Confirm label="删除题库" onConfirm={async () => { await mutate(`/banks/${id}`, 'DELETE'); navigate('/banks'); }} /></Panel></section></div></>}</>;
}

function GroupManager({ bankId, groups, reload }: { bankId: number; groups: Group[]; reload: () => void }) {
  const [edit, setEdit] = useState<number | null>(null), [title, setTitle] = useState(''), [instructions, setInstructions] = useState('');
  const action = useAction();
  return <Panel title="材料题分组" description="共用一段阅读材料的题目可归入同一组。">{groups.map(g => <div key={g.id} className="flex flex-wrap items-center justify-between gap-3"><Typography.Paragraph className="max-w-full overflow-x-auto">{g.title}</Typography.Paragraph><div className="flex gap-2"><Button variant="secondary" onPress={() => { setEdit(g.id); setTitle(g.title); setInstructions(g.instructions ?? ''); }}>编辑</Button><Confirm label="删除分组" onConfirm={async () => { await mutate(`/groups/${g.id}`, 'DELETE'); reload(); }} /></div></div>)}<SaveForm action={action} label={edit ? '保存分组' : '创建分组'} onSave={async () => { await mutate(edit ? `/groups/${edit}` : `/banks/${bankId}/groups`, edit ? 'PATCH' : 'POST', { title, instructions, status: 'active' }); setEdit(null); setTitle(''); setInstructions(''); reload(); }}><Field label="材料标题" value={title} onChange={setTitle} required /><Field label="材料内容" value={instructions} onChange={setInstructions} multiline /></SaveForm>{edit && <Button variant="tertiary" onPress={() => { setEdit(null); setTitle(''); setInstructions(''); }}>取消编辑</Button>}</Panel>;
}
function SubsetManager({ bankId, subsets, reload }: { bankId: number; subsets: Subset[]; reload: () => void }) {
  const [name, setName] = useState(''), [parent, setParent] = useState('none'), [edit, setEdit] = useState<number | null>(null); const action = useAction();
  return <Panel title="题库目录">{subsets.map(s => <div key={s.id} className="flex flex-wrap items-center justify-between gap-3"><Typography.Paragraph className="max-w-full overflow-x-auto">{s.parent_id ? `${subsets.find(p => p.id === s.parent_id)?.name ?? ''} / ` : ''}{s.name}</Typography.Paragraph><div className="flex gap-2"><Button variant="secondary" onPress={() => { setEdit(s.id); setName(s.name); setParent(String(s.parent_id ?? 'none')); }}>编辑</Button><Confirm label="删除目录" onConfirm={async () => { await mutate(`/banks/${bankId}/subsets/${s.id}`, 'DELETE'); reload(); }} /></div></div>)}<SaveForm action={action} label={edit ? '保存目录' : '添加目录'} onSave={async () => { await mutate(`/banks/${bankId}/subsets${edit ? `/${edit}` : ''}`, edit ? 'PATCH' : 'POST', { name, parentId: parent === 'none' ? null : Number(parent), sortOrder: edit ? subsets.find(s => s.id === edit)!.sort_order : subsets.length+1 }); setName(''); setEdit(null); reload(); }}><Field label="目录名称" value={name} onChange={setName} required /><Choice label="父目录" value={parent} onChange={setParent} items={[{ id: 'none', label: '根目录' }, ...subsets.filter(s => s.id !== edit).map(s => ({ id: String(s.id), label: s.name }))]} /></SaveForm></Panel>;
}

const modeLabels: Record<Mode, string> = { choice: '选择题', true_false: '判断题', fill_blank: '填空题', short_answer: '简答题' };
export function QuestionEditor() {
  const id = Number(useParams().id), editing = !useLocation().pathname.includes('/banks/'), navigate = useNavigate();
  const existing = useResource<Question>(editing ? `/questions/${id}/management` : null);
  const types = useResource<QuestionType[]>('/question-types');
  const bankId = editing ? existing.data?.bank_id ?? 0 : id;
  const groups = useResource<Group[]>(bankId ? `/banks/${bankId}/groups` : null), subsets = useResource<Subset[]>(bankId ? `/banks/${bankId}/subsets` : null);
  const [mode, setMode] = useState<Mode>('choice'), [variant, setVariant] = useState('single'), [type, setType] = useState('choice');
  const [stem, setStem] = useState(''), [analysis, setAnalysis] = useState(''), [answers, setAnswers] = useState(''), [groupId, setGroup] = useState('none'), [subsetId, setSubset] = useState('none');
  const [options, setOptions] = useState([{ label: 'A', content: '' }, { label: 'B', content: '' }]); const action = useAction();
  useEffect(() => { const q = existing.data; if (editing && q) { setStem(q.stem); setAnalysis(q.analysis ?? ''); setMode(q.answer_mode); setVariant(q.choice_variant ?? 'single'); setType(q.question_type_id); setOptions(q.options.map(o => ({ label: o.option_label, content: o.content }))); setGroup(String(q.group_id ?? 'none')); setSubset(String(q.subset_id ?? 'none')); const key = q.answer_keys?.find(k => k.is_primary)?.answer_payload ?? {}; const raw = key.correct ?? key.answers ?? key.answer; setAnswers(Array.isArray(raw) ? raw.join(q.answer_mode === 'choice' ? ',' : '\n') : String(raw ?? '')); } }, [existing.data, editing]);
  const keyPayload = () => mode === 'choice' ? { correct: answers.split(',').map(s => s.trim()).filter(Boolean) } : { value: mode === 'true_false' ? answers === 'true' : mode === 'fill_blank' ? answers.split('\n') : answers };
  return <><PageTitle title={editing ? '编辑题目' : '添加题目'}><Go to={`/banks/${bankId || id}`}>返回题库</Go></PageTitle>{editing && <LoadState state={existing} />}<Panel title="题目内容" description={editing ? '答案修改会创建新版本，不影响已开始的练习。' : '新题保存为草稿，核对后可发布用于练习。'}><SaveForm action={action} onSave={async () => { if (editing) { await mutate(`/questions/${id}`, 'PATCH', { stem, analysis, options: mode === 'choice' ? options : undefined, groupId: groupId === 'none' ? null : Number(groupId), subsetId: subsetId === 'none' ? null : Number(subsetId) }); await mutate(`/questions/${id}/answer-keys`, 'POST', { answerMode: mode, answerPayload: keyPayload() }); navigate(`/questions/${id}`); } else { const q = await mutate<Question>(`/banks/${bankId}/questions`, 'POST', { questionTypeId: type, answerMode: mode, stem, analysis, choiceVariant: mode === 'choice' ? variant : null, options: mode === 'choice' ? options : [], answerPayload: keyPayload(), groupId: groupId === 'none' ? null : Number(groupId), subsetId: subsetId === 'none' ? null : Number(subsetId) }); navigate(`/questions/${q.id}`); } }}>
      {!editing && <div className="grid gap-4 sm:grid-cols-2"><Choice label="题型" value={type} onChange={v => { setType(v); setMode(types.data?.find(t => t.type_id === v)?.default_answer_mode ?? 'choice'); setAnswers(''); }} items={(types.data ?? []).map(t => ({ id: t.type_id, label: t.display_name }))} />{mode === 'choice' && <Choice label="选择方式" value={variant} onChange={setVariant} items={[{ id: 'single', label: '单选' }, { id: 'multiple', label: '多选' }]} />}</div>}
      <Field label="题干" value={stem} onChange={setStem} required multiline />{mode === 'choice' && options.map((o, i) => <Field key={o.label} label={`选项 ${o.label}`} value={o.content} onChange={v => setOptions(old => old.map((item, n) => n === i ? { ...item, content: v } : item))} required />)}{!editing && mode === 'choice' && options.length < 10 && <Button variant="secondary" onPress={() => setOptions(old => [...old, { label: String.fromCharCode(65+old.length), content: '' }])}>添加选项</Button>}
      {mode === 'true_false' ? <Choice label="参考答案" value={answers} onChange={setAnswers} items={[{ id: 'true', label: '正确' }, { id: 'false', label: '错误' }]} /> : <Field label={mode === 'choice' ? '正确选项（多选用逗号分隔，例如 A,C）' : mode === 'fill_blank' ? '参考答案（每空一行）' : '参考答案'} value={answers} onChange={setAnswers} multiline={mode !== 'choice'} required />}
      <Field label="解析" value={analysis} onChange={setAnalysis} multiline /><div className="grid gap-4 sm:grid-cols-2"><Choice label="材料分组" value={groupId} onChange={setGroup} items={[{ id: 'none', label: '无分组' }, ...(groups.data ?? []).map(g => ({ id: String(g.id), label: g.title }))]} /><Choice label="目录" value={subsetId} onChange={setSubset} items={[{ id: 'none', label: '根目录' }, ...(subsets.data ?? []).map(s => ({ id: String(s.id), label: s.name }))]} /></div>
    </SaveForm></Panel></>;
}

export function ContentBlocks({ blocks }: { blocks?: Block[] }) { return <>{blocks?.map(b => <Typography.Paragraph key={b.id}>{b.payload.textValue ?? b.payload.markdownValue ?? b.payload.latexValue ?? (b.payload.jsonValue ? JSON.stringify(b.payload.jsonValue) : '')}</Typography.Paragraph>)}</>; }
export function MediaList({ media }: { media?: Media[] }) { return <div className="flex flex-col gap-3">{media?.map(m => m.mime_type.startsWith('image/') ? <img className="h-auto max-w-full" key={m.id} src={`/api/v1/media/${m.media_id}/content`} alt="题目附图" /> : <audio className="max-w-full" controls key={m.id} src={`/api/v1/media/${m.media_id}/content`} />)}</div>; }
export function QuestionBody({ question: q }: { question: Question }) { return <>{q.group && <Panel title={q.group.title}><Typography.Paragraph className="max-w-full overflow-x-auto">{q.group.instructions}</Typography.Paragraph><ContentBlocks blocks={q.group.content_blocks} /><MediaList media={q.group.media} /></Panel>}<Typography.Paragraph className="max-w-full overflow-x-auto">{q.stem}</Typography.Paragraph><ContentBlocks blocks={q.content_blocks} /><MediaList media={q.media} /></>; }
export function QuestionDetail() {
  const id = Number(useParams().id), state = useResource<Question>(`/questions/${id}/management`), points = useResource<Knowledge[]>('/knowledge-points?limit=100');
  const [selected, setSelected] = useState<number[]>([]); const action = useAction(), file = useRef<HTMLInputElement>(null), navigate = useNavigate();
  useEffect(() => { setSelected(state.data?.knowledge_points?.map(k => k.id) ?? []); }, [state.data]);
  const q = state.data;
  return <><PageTitle title="题目详情">{q && <Go to={`/banks/${q.bank_id}`}>返回题库</Go>}</PageTitle><LoadState state={state} />{q && <><Panel title={modeLabels[q.answer_mode]}><Chip>{q.status}</Chip><QuestionBody question={q} />{q.options.map(o => <Typography.Paragraph key={o.id}>{o.option_label}. {o.content}</Typography.Paragraph>)}<Separator /><Typography.Heading level={3}>参考答案</Typography.Heading>{q.answer_keys?.filter(k => k.is_primary).map(k => <Typography.Paragraph key={k.id}>{JSON.stringify(k.answer_payload)}</Typography.Paragraph>)}<Typography.Paragraph className="max-w-full overflow-x-auto">{q.analysis || '暂无解析'}</Typography.Paragraph><div className="flex flex-wrap gap-3"><Go to={`/questions/${id}/edit`}>编辑题目</Go><Button isDisabled={action.busy} onPress={() => void action.run(async () => { await mutate(`/questions/${id}/${q.status === 'active' ? 'archive' : 'publish'}`); state.reload(); })}>{q.status === 'active' ? '归档' : '发布'}</Button><Button variant="secondary" isDisabled={action.busy} onPress={() => void action.run(async () => { const t = await mutate<Task>(`/questions/${id}/ai-answer-tasks`); navigate(`/tasks/${t.id}?questionId=${id}`); })}>AI 生成答案</Button><Confirm label="删除题目" onConfirm={async () => { await mutate(`/questions/${id}`, 'DELETE'); navigate(`/banks/${q.bank_id}`); }} /></div>{action.error && <Notice>{action.error}</Notice>}</Panel><Panel title="媒体附件"><input ref={file} type="file" accept="image/png,image/jpeg,image/gif,image/webp,audio/mpeg,audio/wav,audio/mp4" hidden onChange={e => { const picked = e.target.files?.[0]; if (picked) void action.run(async () => { const form = new FormData(); form.append('file', picked); const m = await mutate<Media>('/media', 'POST', form); await mutate(`/questions/${id}/media-links`, 'POST', { mediaId: m.id }); state.reload(); }); }} /><Button variant="secondary" isDisabled={action.busy} onPress={() => file.current?.click()}>上传图片或音频</Button>{q.media?.map(m => <div key={m.id} className="flex items-center gap-3"><Typography.Paragraph className="max-w-full overflow-x-auto">附件 {m.media_id}</Typography.Paragraph><Confirm label="移除附件" onConfirm={async () => { await mutate(`/questions/${id}/media-links/${m.media_id}`, 'DELETE'); state.reload(); }} /></div>)}</Panel><Panel title="关联知识点">{points.data?.map(k => <Checkbox key={k.id} isSelected={selected.includes(k.id)} onChange={yes => setSelected(old => yes ? [...old, k.id] : old.filter(i => i !== k.id))}><Checkbox.Control><Checkbox.Indicator /></Checkbox.Control><Checkbox.Content>{k.display_name}</Checkbox.Content></Checkbox>)}<Button isDisabled={action.busy} onPress={() => void action.run(async () => { await mutate(`/questions/${id}/knowledge-points`, 'PUT', { knowledgePointIds: selected }); state.reload(); })}>保存知识点</Button></Panel></>}</>;
}

export function SearchPage() {
  const [q, setQ] = useState(''), [cursor, setCursor] = useState(''); const state = useResource<Question[]>(`/search/questions?q=${encodeURIComponent(q)}&cursor=${cursor}`);
  return <><PageTitle title="搜索题目" /><Field label="题干关键词" value={q} onChange={v => { setQ(v); setCursor(''); }} /><LoadState state={state} />{state.data?.length === 0 && <Empty>没有匹配的题目。</Empty>}{state.data?.map(item => <Panel key={item.id} title={item.stem}><Go to={`/questions/${item.id}`}>查看题目</Go></Panel>)}<div className="flex gap-3">{cursor && <Button variant="secondary" onPress={() => setCursor('')}>第一页</Button>}{state.pagination?.hasMore && <Button variant="secondary" onPress={() => setCursor(state.pagination!.cursor)}>下一页</Button>}</div></>;
}
export function SettingsPage() {
  const [cursor, setCursor] = useState(''), state = useResource<Knowledge[]>(`/knowledge-points?cursor=${cursor}`);
  const [id, setId] = useState<number | null>(null), [code, setCode] = useState(''), [name, setName] = useState(''), [parent, setParent] = useState('none');
  const action = useAction(), [notice, setNotice] = useState('');
  return <><PageTitle title="设置" /><div className="grid gap-6 lg:grid-cols-2"><Panel title="知识点维护"><LoadState state={state} />{state.data?.map(k => <div key={k.id} className="flex flex-wrap items-center justify-between gap-3"><Typography.Paragraph className="max-w-full overflow-x-auto">{k.code} · {k.display_name}</Typography.Paragraph><div className="flex gap-2"><Button variant="secondary" onPress={() => { setId(k.id); setCode(k.code); setName(k.display_name); setParent(String(k.parent_id ?? 'none')); }}>编辑</Button><Confirm label="删除知识点" onConfirm={async () => { await mutate(`/knowledge-points/${k.id}`, 'DELETE'); state.reload(); }} /></div></div>)}<div className="flex gap-3">{cursor && <Button variant="secondary" onPress={() => setCursor('')}>第一页</Button>}{state.pagination?.hasMore && <Button variant="secondary" onPress={() => setCursor(state.pagination!.cursor)}>下一页</Button>}</div><SaveForm action={action} label={id ? '保存知识点' : '添加知识点'} onSave={async () => { await mutate(`/knowledge-points${id ? `/${id}` : ''}`, id ? 'PATCH' : 'POST', { code, displayName: name, parentId: parent === 'none' ? null : Number(parent) }); setId(null); setCode(''); setName(''); setParent('none'); state.reload(); }}><Field label="编码" value={code} onChange={setCode} required /><Field label="名称" value={name} onChange={setName} required /><Choice label="父知识点" value={parent} onChange={setParent} items={[{ id: 'none', label: '根节点' }, ...(state.data ?? []).filter(k => k.id !== id).map(k => ({ id: String(k.id), label: k.display_name }))]} /></SaveForm></Panel><Panel title="本地缓存" description="清除浏览器中的导入恢复信息，不删除数据库内容或服务端任务。"><Confirm label="清除本地缓存" onConfirm={async () => { clearClientCache(); setNotice('浏览器缓存已清除'); }} />{notice && <Typography.Paragraph className="max-w-full overflow-x-auto">{notice}</Typography.Paragraph>}<Typography.Paragraph className="max-w-full overflow-x-auto">PractiQ 是本机使用的单用户工具。无需登录，所有内容保存在本机配置的数据库中。</Typography.Paragraph></Panel></div></>;
}
