import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Button, Checkbox, Chip, Radio, RadioGroup, Typography } from '@heroui/react';
import { answerPayload, mutate, type Bank, type Question, type QuestionPage, type QuestionType, type Session, type Snapshot, type Task } from './api';
import { Choice, Confirm, Empty, Field, Go, LoadState, Notice, PageTitle, Panel, SaveForm, useAction, useResource } from './ui';
import { QuestionBody } from './pages-content';

export function Home() {
  const state = useResource<Snapshot>('/analytics/snapshot');
  const summary = state.data?.summary;
  return <><PageTitle title="今天，从一道题开始"><Go to="/search">搜索题目</Go></PageTitle><LoadState state={state} />{summary && <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[['题库', summary.banks], ['已答题', summary.attempts], ['正确率', `${summary.accuracy}%`], ['收藏', summary.favorite_banks]].map(([label, value]) => <Panel title={String(label)} key={label}><Typography.Heading level={2}>{value}</Typography.Heading></Panel>)}</div>}<Panel title="继续学习" description="选择题库练习，或将手头资料导入为可练习的题目。"><div className="flex flex-wrap gap-5"><Go to="/banks">打开题库</Go><Go to="/imports/new">导入资料</Go><Go to="/analytics">查看学习分析</Go></div></Panel><Panel title="最近练习">{state.data?.recentSessions.length === 0 && <Empty>还没有练习记录，从题库开始第一次练习。</Empty>}{state.data?.recentSessions.map(s => <div key={s.id} className="flex flex-wrap items-center justify-between gap-3"><Typography.Paragraph className="max-w-full overflow-x-auto">练习 #{s.id} · {s.answered_count}/{s.question_count} 题</Typography.Paragraph><Chip>{s.status === 'active' ? '进行中' : s.status === 'completed' ? '已完成' : '已放弃'}</Chip><Go to={`/practice/${s.id}${s.status === 'active' ? '' : '/results'}`}>{s.status === 'active' ? '继续练习' : '查看结果'}</Go></div>)}</Panel></>;
}

export function PracticeSetup() {
  const id = Number(useParams().id), bank = useResource<Bank>(`/banks/${id}`), types = useResource<QuestionType[]>('/question-types');
  const [mode, setMode] = useState('all'), [count, setCount] = useState('30'), [type, setType] = useState('choice');
  const action = useAction(), navigate = useNavigate();
  return <><PageTitle title="开始练习"><Go to={`/banks/${id}`}>返回题库</Go></PageTitle><LoadState state={bank} /><div className="mx-auto w-full max-w-2xl"><Panel title={bank.data?.name ?? '练习设置'} description="只使用已发布的题目；考试模式在交卷后显示答案。"><SaveForm action={action} label="开始" onSave={async () => { const s = await mutate<Session>('/practice-sessions', 'POST', { bankId: id, mode, questionCount: Number(count), questionTypeId: mode === 'by_type' ? type : '' }); navigate(`/practice/${s.id}`); }}><Choice label="练习模式" value={mode} onChange={setMode} items={[{ id: 'all', label: '顺序练习' }, { id: 'wrong', label: '错题复习' }, { id: 'by_type', label: '按题型练习' }, { id: 'exam', label: '模拟考试' }]} /><Field label="题目数量（1–500）" value={count} onChange={setCount} type="number" required />{mode === 'by_type' && <Choice label="题型" value={type} onChange={setType} items={(types.data ?? []).map(t => ({ id: t.type_id, label: t.display_name }))} />}</SaveForm></Panel></div></>;
}

export function PracticePage() {
  const id = Number(useParams().id), [index, setIndex] = useState<number | null>(null), state = useResource<QuestionPage>(`/practice-sessions/${id}/question-page${index === null ? '' : `?index=${index}`}`);
  const [selected, setSelected] = useState<string[]>([]), [value, setValue] = useState(''); const action = useAction(), navigate = useNavigate();
  const page = state.data, q = page?.question;
  useEffect(() => { const payload = page?.result?.answer_payload; setSelected(Array.isArray(payload?.selected) ? payload.selected as string[] : []); setValue(Array.isArray(payload?.value) ? (payload.value as string[]).join('\n') : String(payload?.value ?? '')); }, [page]);
  return <><PageTitle title={page?.session.mode === 'exam' ? '模拟考试' : '专注练习'}><Go to="/">稍后继续</Go></PageTitle><LoadState state={state} />{page && q && <div className="grid gap-6 lg:grid-cols-3"><div className="min-w-0 lg:col-span-2"><Panel title={`第 ${page.questionIndex+1} / ${page.total} 题`}><QuestionBody question={q} /><SaveForm action={action} label={page.result ? '已提交' : '提交答案'} onSave={async () => { if (page.result) return; if (q.answer_mode === 'true_false' && !value) throw new Error('请选择正确或错误'); await mutate(`/practice-sessions/${id}/answers`, 'POST', { questionId: q.id, answerPayload: answerPayload(q.answer_mode, value, selected) }); state.reload(); }}>
      {q.answer_mode === 'choice' && (q.choice_variant === 'multiple' ? <div className="flex flex-col gap-3">{q.options.map(o => <Checkbox key={o.id} isDisabled={Boolean(page.result)} isSelected={selected.includes(o.option_label)} onChange={checked => setSelected(old => checked ? [...old, o.option_label] : old.filter(v => v !== o.option_label))}><Checkbox.Control><Checkbox.Indicator /></Checkbox.Control><Checkbox.Content>{o.option_label}. {o.content}</Checkbox.Content></Checkbox>)}</div> : <RadioGroup aria-label="选择答案" value={selected[0] ?? ''} onChange={v => setSelected([v])} isDisabled={Boolean(page.result)}>{q.options.map(o => <Radio key={o.id} value={o.option_label}><Radio.Control><Radio.Indicator /></Radio.Control><Radio.Content>{o.option_label}. {o.content}</Radio.Content></Radio>)}</RadioGroup>)}
      {q.answer_mode === 'true_false' && <RadioGroup aria-label="判断答案" value={value} onChange={setValue} isDisabled={Boolean(page.result)}><Radio value="true"><Radio.Control><Radio.Indicator /></Radio.Control><Radio.Content>正确</Radio.Content></Radio><Radio value="false"><Radio.Control><Radio.Indicator /></Radio.Control><Radio.Content>错误</Radio.Content></Radio></RadioGroup>}
      {(q.answer_mode === 'fill_blank' || q.answer_mode === 'short_answer') && <Field label={q.answer_mode === 'fill_blank' ? '每空填写一行' : '你的答案'} value={value} onChange={setValue} multiline required />}
    </SaveForm>{page.result && <Panel title={page.session.mode === 'exam' && page.session.status !== 'completed' ? '答案已记录，交卷后显示结果' : page.result.is_correct === null ? '请对照参考答案自查' : page.result.is_correct ? '回答正确' : '继续加油'}>{page.result.answer_key_payload && <Typography.Paragraph className="max-w-full overflow-x-auto">参考答案：{JSON.stringify(page.result.answer_key_payload)}</Typography.Paragraph>}</Panel>}<div className="flex flex-wrap justify-between gap-3"><Button variant="secondary" isDisabled={page.previousIndex === null || action.busy} onPress={() => setIndex(page.previousIndex)}>上一题</Button><Button variant="secondary" isDisabled={page.nextIndex === null || action.busy} onPress={() => setIndex(page.nextIndex)}>下一题</Button></div></Panel></div><Panel title="练习进度"><div className="flex flex-wrap gap-2">{page.progress.map(p => <Button key={p.index} size="sm" variant={p.index === page.questionIndex ? 'primary' : p.isAnswered ? 'secondary' : 'tertiary'} onPress={() => setIndex(p.index)} aria-label={`第 ${p.index+1} 题${p.isAnswered ? '，已作答' : ''}`}>{p.index+1}</Button>)}</div><Typography.Paragraph className="max-w-full overflow-x-auto">{page.session.answered_count}/{page.total} 题已提交</Typography.Paragraph><Confirm label="完成并查看结果" onConfirm={async () => { await mutate(`/practice-sessions/${id}/complete`); navigate(`/practice/${id}/results`); }} /><Confirm label="放弃本次练习" onConfirm={async () => { await mutate(`/practice-sessions/${id}/abandon`); navigate('/'); }} /></Panel></div>}</>;
}
export function ResultsPage() {
  const id = Number(useParams().id), state = useResource<Question[]>(`/practice-sessions/${id}/results`);
  return <><PageTitle title="练习结果"><Go to="/">返回学习</Go></PageTitle><LoadState state={state} />{state.data?.map((q, i) => <Panel key={q.id} title={`第 ${i+1} 题`}><QuestionBody question={q} /><Typography.Paragraph className="max-w-full overflow-x-auto">你的答案：{q.result ? JSON.stringify(q.result.answer_payload) : '未作答'}</Typography.Paragraph>{q.result?.answer_key_payload && <Typography.Paragraph className="max-w-full overflow-x-auto">参考答案：{JSON.stringify(q.result.answer_key_payload)}</Typography.Paragraph>}<Chip>{!q.result ? '未作答' : q.result.is_correct === null ? '未判分' : q.result.is_correct ? '正确' : '错误'}</Chip></Panel>)}</>;
}
export function Analytics() {
  const state = useResource<Snapshot>('/analytics/snapshot'), reports = useResource<Task[]>('/ai-tasks'); const action = useAction(), navigate = useNavigate();
  return <><PageTitle title="学习分析"><Button isDisabled={action.busy || !state.data?.summary.attempts} onPress={() => void action.run(async () => { const t = await mutate<Task>('/analytics/report-tasks'); navigate(`/tasks/${t.id}`); })}>生成 AI 学习报告</Button></PageTitle><LoadState state={state} />{action.error && <Notice>{action.error}</Notice>}{state.data && <><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[['累计作答', state.data.summary.attempts], ['正确', state.data.summary.correct], ['错误', state.data.summary.wrong], ['正确率', `${state.data.summary.accuracy}%`]].map(([label, value]) => <Panel key={label} title={String(label)}><Typography.Heading level={2}>{value}</Typography.Heading></Panel>)}</div><div className="grid gap-6 lg:grid-cols-2"><Panel title="需要巩固的题目">{state.data.weakQuestions.length === 0 && <Empty>练习后会在这里看到薄弱题目。</Empty>}{state.data.weakQuestions.map(q => <div key={q.question_id} className="flex flex-col gap-2"><Typography.Paragraph className="max-w-full overflow-x-auto">{q.stem}</Typography.Paragraph><Go to={`/questions/${q.question_id}`}>查看 · 错误 {q.wrong_count} 次</Go></div>)}</Panel><Panel title="近期学习记录">{state.data.trend.length === 0 && <Empty />}{state.data.trend.map(d => <Typography.Paragraph key={d.day}>{d.day} · 作答 {d.attempts} · 正确 {d.correct}</Typography.Paragraph>)}</Panel></div></>}<Panel title="AI 任务与报告">{reports.data?.length === 0 && <Empty />}{reports.data?.map(t => <div key={t.id} className="flex flex-wrap gap-3"><Go to={`/tasks/${t.id}`}>任务 #{t.id} · {t.kind}</Go><Chip>{t.status}</Chip></div>)}</Panel></>;
}

export function BankAnalytics() {
  const id = Number(useParams().id), bank = useResource<Bank>(`/banks/${id}`), state = useResource<Snapshot['summary']>(`/analytics/banks/${id}`);
  return <><PageTitle title={`${bank.data?.name ?? '题库'} · 学习分析`}><Go to={`/banks/${id}`}>返回题库</Go></PageTitle><LoadState state={state} />{state.data && <div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[['作答次数', state.data.attempts], ['正确次数', state.data.correct], ['错误次数', state.data.wrong], ['正确率', `${state.data.accuracy}%`]].map(([label, value]) => <Panel key={label} title={String(label)}><Typography.Heading level={2}>{value}</Typography.Heading></Panel>)}</div>}<Go to={`/practice/new/${id}`}>开始练习或复习错题</Go></>;
}
