import type { DocumentTaskDetail, DocumentTaskReview, ParsedQuestion } from "./contracts.generated";
import type { Capabilities } from "./api";

export const taskId = "11111111-1111-4111-8111-111111111111";
export const newTaskId = "22222222-2222-4222-8222-222222222222";
export const runId = "33333333-3333-4333-8333-333333333333";
export const capabilities: Capabilities = { sourceTypes: ["pdf", "text", "csv", "image", "doc", "docx", "xls", "xlsx"], sourceMaxBytes: 25 * 1024 * 1024, officeAvailable: true, officeModes: ["pdf", "text"], modelConfigured: true };
export const question = (values: Partial<ParsedQuestion> = {}): ParsedQuestion => ({ id: "q-child", parentId: "q-material", optionSourceId: "q-material", stem: "根据材料选择答案", answerMode: "choice", questionTypeId: "single_choice", choiceVariant: "single", options: [], items: [], answerPayload: null, contentBlocks: [], sourceText: "原文包含题目，但未提供参考答案。", confidence: 72, needsReview: true, missingFields: ["answerPayload"], ...values });
export const material = question({ id: "q-material", parentId: null, optionSourceId: null, stem: "共享阅读材料", answerMode: "reading", questionTypeId: "reading", choiceVariant: null, options: [{ label: "A", content: "共享选项一" }, { label: "B", content: "共享选项二" }], passage: [{ partType: "markdown", markdownValue: "阅读材料 **原文**。![外部图片](https://untrusted.invalid/image.png)" }], missingFields: [], needsReview: false });
export const task: DocumentTaskDetail = { threadId: taskId, runId: null, parentThreadId: null, modelConfigured: true, resumeCompatible: true, fileName: "sample.docx", state: "COMPLETED", phase: "completed", checkpointId: "checkpoint-one", updatedAt: "2026-10-04T00:00:00Z", expiresAt: "2026-10-05T00:00:00Z", allowedActions: [], failures: [{ stage: "document_parse", index: 1, code: "PARSE_FAILED", retryable: true, retriesRemaining: 1 }], blocking: [], progress: { chunks: { total: 3, succeeded: 2, failed: 1, remaining: 0 }, visuals: { total: 1, succeeded: 1, failed: 0, remaining: 0 } }, status: "PARTIAL", result: { schemaVersion: 3, questions: [material, question(), question({ id: "q-null", parentId: null, optionSourceId: null, stem: null, answerMode: null, questionTypeId: null, sourceText: "只辨认出部分原文", contentBlocks: [{ partType: "html", textValue: "<script>window.documentInjected=true</script>" }], missingFields: ["stem", "answerMode", "answerPayload"] })], groups: [{ title: "阅读分组", questionIds: ["q-material", "q-child"] }], visualElements: [], warnings: ["保留失败单元；参考答案缺失。"], confidenceScore: 72, missingFields: ["media"] }, modelBudget: { limit: 8, reserved: 4 }, processing: { chunks: { total: 3, succeeded: 2 }, visuals: { total: 1, succeeded: 1 }, truncated: false, failures: [], questionSources: [{ questionId: "q-child", stage: "document_parse", unitIndex: 0 }], quality: { reviewRequired: true, reviewQuestionCount: 2, issues: [{ questionId: "q-child", code: "MISSING_FIELDS" }] } }, usage: [{ callKey: runId, modelId: "fake-model", inputTokens: 21, outputTokens: 8, callKind: "document_parse" }], unknownUsageCalls: [newTaskId] };
export const preview: DocumentTaskReview = { threadId: taskId, checkpointId: task.checkpointId, state: task.state, phase: task.phase, units: [{ stage: "result", index: 0, questions: task.result!.questions, groups: task.result!.groups, visualElements: [], sourceRef: null }], failures: task.failures, quality: task.processing!.quality!, questionSources: task.processing!.questionSources! };
export const summary = { threadId: taskId, fileName: task.fileName, createdAt: task.updatedAt, expiresAt: task.expiresAt, state: task.state, status: task.status, checkpointId: task.checkpointId, questionCount: 3, reviewCount: 2 };
