package com.practiq.web;

import com.practiq.auth.AuthService;
import com.practiq.common.*;
import java.sql.ResultSet;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1")
public class AnalyticsSearchController {
 private final JdbcTemplate db; private final AuthService auth; AnalyticsSearchController(JdbcTemplate db,AuthService auth){this.db=db;this.auth=auth;} private long user(String h){return auth.require(h);} private static ApiException bad(String m){return ApiException.of(422,"VALIDATION_ERROR",m);} private static void id(long n){if(n<1)throw bad("Invalid request");}
 private Map<String,Object> row(ResultSet r,int n)throws java.sql.SQLException{var m=new LinkedHashMap<String,Object>();for(int i=1;i<=r.getMetaData().getColumnCount();i++){Object v=r.getObject(i);m.put(r.getMetaData().getColumnLabel(i),v instanceof OffsetDateTime t?t.toString():v);}return m;}
 private void bank(long u,long id){Integer n=db.queryForObject("select count(*) from question_banks b left join user_bank_links l on l.bank_id=b.id and l.user_id=? where b.id=? and (b.is_public or l.id is not null or exists(select 1 from study_group_banks gb join study_group_members gm on gm.group_id=gb.group_id where gb.bank_id=b.id and gm.user_id=?))",Integer.class,u,id,u);if(n==null||n==0)throw ApiException.of(404,"NOT_FOUND","Question bank not found");}
 @GetMapping("/analytics/me/summary") ApiResponse<?> summary(@RequestHeader(value="Authorization",required=false)String h){long u=user(h);var x=db.query("select (select count(*) from user_bank_links where user_id=? and is_owner) owned_banks,(select count(*) from user_bank_links where user_id=? and is_favorite) favorite_banks,coalesce((select sum(attempt_count) from user_question_stats where user_id=?),0) attempts,coalesce((select sum(correct_count) from user_question_stats where user_id=?),0) correct,coalesce((select sum(wrong_count) from user_question_stats where user_id=?),0) wrong,(select count(*) from user_practice_sessions where user_id=?) sessions,(select count(*) from user_practice_sessions where user_id=? and status='active') active_sessions,(select count(*) from question_import_jobs where created_by=? and status in ('queued','processing')) active_imports",this::row,u,u,u,u,u,u,u,u).getFirst();long a=((Number)x.get("attempts")).longValue(),c=((Number)x.get("correct")).longValue();x.put("accuracy",a==0?0:Math.round(c*100d/a));return ApiResponse.ok(x);}
 @GetMapping("/analytics/me/snapshot") ApiResponse<?> snapshot(@RequestHeader(value="Authorization",required=false)String h){long u=user(h);var summary=summary(h).data();var sessions=db.query("select id,user_id,bank_id,session_type,status,question_count,answered_count,correct_count,wrong_count,score,started_at,completed_at from user_practice_sessions where user_id=? order by started_at desc,id desc limit 10",this::row,u);var weak=db.query("select s.question_id,s.attempt_count,s.correct_count,s.wrong_count,s.mastery_score,q.stem,q.question_type_id from user_question_stats s join questions q on q.id=s.question_id where s.user_id=? and s.attempt_count>0 order by s.mastery_score asc nulls first,s.wrong_count desc,s.last_answered_at desc nulls last limit 10",this::row,u);return ApiResponse.ok(Map.of("summary",summary,"recentSessions",sessions,"weakQuestions",weak));}
 @GetMapping("/analytics/banks/{bankId}") ApiResponse<?> bankAnalytics(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long bankId){long u=user(h);id(bankId);bank(u,bankId);return ApiResponse.ok(db.query("select coalesce(sum(completed_count),0) completed_count,coalesce(sum(wrong_count),0) wrong_count,count(*) practiced_users,(select count(*) from user_question_answers where bank_id=?) answer_count from user_bank_stats where bank_id=?",this::row,bankId,bankId).getFirst());}
 @GetMapping("/analytics/banks/{bankId}/leaderboard") ApiResponse<?> board(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long bankId,@RequestParam(defaultValue="20")int limit){long u=user(h);id(bankId);if(limit<1||limit>100)throw bad("Invalid request");bank(u,bankId);return ApiResponse.ok(db.query("select u.id user_id,u.username,s.completed_count,s.wrong_count,s.last_practiced_at,case when s.completed_count>0 then round(((s.completed_count-s.wrong_count)::numeric/s.completed_count)*100,2) else 0 end accuracy_percent from user_bank_stats s join users u on u.id=s.user_id where s.bank_id=? order by s.completed_count desc,accuracy_percent desc,s.last_practiced_at desc nulls last limit ?",this::row,bankId,limit));}
 @GetMapping("/analytics/imports/{jobId}") ApiResponse<?> imported(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long jobId){long u=user(h);id(jobId);var x=db.query("select q.*, (select count(*) from question_import_job_events e where e.job_id=q.id) events,(select count(*) from question_import_job_outputs o where o.job_id=q.id) outputs from question_import_jobs q where q.id=? and q.created_by=?",this::row,jobId,u);if(x.isEmpty())throw ApiException.of(404,"NOT_FOUND","Import job not found");return ApiResponse.ok(x.getFirst());}
 @GetMapping("/search/questions") ApiResponse<?> search(@RequestHeader(value="Authorization",required=false)String h,@RequestParam(required=false)Long bankId,@RequestParam(name="type",defaultValue="")String type,@RequestParam(defaultValue="")String status,@RequestParam(required=false)Integer limit,@RequestParam(defaultValue="")String cursor,@RequestParam(name="q",defaultValue="")String q){long u=user(h);if(bankId!=null&&bankId<1)throw bad("bankId must be a positive integer");if(!status.isBlank()&&!Set.of("draft","active","archived").contains(status))throw bad("status must be one of draft, active, archived");int l=limit==null?50:limit;if(l<1||l>100)throw bad("limit must be between 1 and 100");int o=PageSupport.cursor(cursor);var rows=db.query("with visible as (select i.question_id,bool_or(coalesce(l.is_owner,false)) can_edit from v_bank_question_items i join question_banks b on b.id=i.bank_id left join user_bank_links l on l.bank_id=b.id and l.user_id=? where (? is null or i.bank_id=?) and (coalesce(l.is_owner,false) or ((b.is_public or l.id is not null) and i.question_status='active' and i.bank_link_status='active')) group by i.question_id) select q.id,q.business_type,q.subject_id,q.question_type_id,q.answer_mode,q.choice_variant,q.stem,case when v.can_edit then q.analysis else null end analysis,q.status,v.can_edit from visible v join questions q on q.id=v.question_id where (?='' or q.question_type_id=?) and (?='' or q.status=?) and (?='' or q.stem ilike '%'||?||'%' or to_tsvector('simple',coalesce(q.stem,'')) @@ plainto_tsquery('simple',?)) order by q.updated_at desc limit ? offset ?",this::row,u,bankId,bankId,type.trim(),type.trim(),status,status,q.trim(),q.trim(),q.trim(),l+1,o);boolean more=rows.size()>l;if(more)rows=rows.subList(0,l);return ApiResponse.ok(rows,Map.of("pagination",Map.of("cursor",more?PageSupport.next(o,l):"","limit",l,"hasMore",more)));}
}
