package com.practiq.web;

import com.practiq.auth.AuthService;
import com.practiq.common.*;
import com.practiq.service.ContentAccess;
import com.practiq.service.PracticeService;
import java.sql.ResultSet;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1")
public class AnalyticsSearchController {
  private final JdbcTemplate db; private final AuthService auth;
  AnalyticsSearchController(JdbcTemplate db, AuthService auth) { this.db = db; this.auth = auth; }
  private long user(String header) { return auth.require(header); }
  private static ApiException bad(String message) { return ApiException.of(422, "VALIDATION_ERROR", message); }
  private static void id(long value) { if (value < 1) throw bad("Invalid request"); }
  private Map<String, Object> row(ResultSet result, int number) throws java.sql.SQLException { var value = new LinkedHashMap<String, Object>(); for (int i = 1; i <= result.getMetaData().getColumnCount(); i++) { Object item = result.getObject(i); value.put(result.getMetaData().getColumnLabel(i), item instanceof OffsetDateTime time ? time.toString() : item); } return value; }
  private void bank(long user, long bank) { Integer count = db.queryForObject("select count(*) from question_banks b where b.id=? and b.deleted_at is null and b.status<>'banned' and (b.owner_user_id=? or b.status='public' or exists(select 1 from study_group_banks gb join study_group_members gm on gm.group_id=gb.group_id where gb.bank_id=b.id and gm.user_id=? and gm.status='accepted'))", Integer.class, bank, user, user); if (count == null || count == 0) throw ApiException.of(404, "NOT_FOUND", "Question bank not found"); }
  private String answerVisible(long user) {
    return ContentAccess.answerVisible("a", user);
  }
  @GetMapping("/analytics/me/summary") ApiResponse<?> summary(@RequestHeader(value = "Authorization", required = false) String header) {
    long user = user(header);
    var value = db.query("select count(*) attempts,count(*) filter(where a.is_correct) correct,count(*) filter(where a.is_correct=false) wrong from practice_answers a where a.user_id=? and " + answerVisible(user), this::row, user).getFirst();
    value.put("owned_banks", db.queryForObject("select count(*) from question_banks b where b.owner_user_id=? and " + ContentAccess.bankVisible("b", user), Long.class, user));
    value.put("favorite_banks", db.queryForObject("select count(*) from user_bank_favorites f join question_banks b on b.id=f.bank_id where f.user_id=? and " + ContentAccess.bankVisible("b", user), Long.class, user));
    value.put("sessions", db.queryForObject("select count(*) from practice_sessions s join question_banks b on b.id=s.bank_id where s.user_id=? and " + ContentAccess.bankVisible("b", user), Long.class, user));
    value.put("active_sessions", db.queryForObject("select count(*) from practice_sessions s join question_banks b on b.id=s.bank_id where s.user_id=? and s.status='active' and " + ContentAccess.bankVisible("b", user), Long.class, user));
    value.put("active_imports", db.queryForObject("select count(*) from question_import_jobs where created_by=? and status in ('queued','processing')", Long.class, user));
    long attempts = ((Number) value.get("attempts")).longValue(), correct = ((Number) value.get("correct")).longValue(); value.put("accuracy", attempts == 0 ? 0 : Math.round(correct * 100d / attempts)); return ApiResponse.ok(value);
  }
  @GetMapping("/analytics/me/snapshot") ApiResponse<?> snapshot(@RequestHeader(value = "Authorization", required = false) String header) { long user = user(header); var summary = summary(header).data(); var sessions = db.query("select s.id,s.user_id,s.bank_id,s.mode session_type,s.status,(select count(*) from practice_session_questions q where q.session_id=s.id) question_count,(select count(*) from practice_answers a where a.session_id=s.id) answered_count,(select count(*) from practice_answers a where a.session_id=s.id and a.is_correct) correct_count,(select count(*) from practice_answers a where a.session_id=s.id and a.is_correct=false) wrong_count,s.started_at,s.completed_at from practice_sessions s where s.user_id=? and exists(select 1 from question_banks b where b.id=s.bank_id and " + ContentAccess.bankVisible("b", user) + ") and not exists(select 1 from practice_session_questions sq where sq.session_id=s.id and not (" + ContentAccess.questionInBank("s.bank_id", "sq.question_id", user, true) + ")) order by s.started_at desc,s.id desc limit 10", this::row, user); sessions.forEach(PracticeService::hideSummary); var weak = db.query("with stats as (select a.bank_id,a.question_id,count(*) attempt_count,count(*) filter(where a.is_correct) correct_count,count(*) filter(where a.is_correct=false) wrong_count,max(a.answered_at) last_answered_at from practice_answers a where a.user_id=? and " + answerVisible(user) + " group by a.bank_id,a.question_id) select s.bank_id,s.question_id,s.attempt_count,s.correct_count,s.wrong_count,s.correct_count::numeric/s.attempt_count mastery_score,q.stem,q.question_type_id from stats s join questions q on q.id=s.question_id order by mastery_score asc,s.wrong_count desc,s.last_answered_at desc limit 10", this::row, user); return ApiResponse.ok(Map.of("summary", summary, "recentSessions", sessions, "weakQuestions", weak)); }
  @GetMapping("/analytics/banks/{bankId}") ApiResponse<?> bankAnalytics(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long bankId) { long user = user(header); id(bankId); bank(user, bankId); return ApiResponse.ok(db.query("select count(*) answer_count,count(distinct user_id) practiced_users,coalesce(sum(case when is_correct=false then 1 else 0 end),0) wrong_count,coalesce(sum(case when is_correct then 1 else 0 end),0) completed_count from practice_answers a where bank_id=? and " + answerVisible(user), this::row, bankId).getFirst()); }
  @GetMapping("/analytics/banks/{bankId}/leaderboard") ApiResponse<?> board(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long bankId, @RequestParam(defaultValue = "20") int limit) { long user = user(header); id(bankId); if (limit < 1 || limit > 100) throw bad("Invalid request"); bank(user, bankId); return ApiResponse.ok(db.query("select u.id user_id,u.display_name,count(a.id) completed_count,coalesce(sum(case when a.is_correct=false then 1 else 0 end),0) wrong_count,max(a.answered_at) last_practiced_at,coalesce(round(avg(case when a.is_correct then 100 else 0 end),2),0) accuracy_percent from practice_answers a join users u on u.id=a.user_id where a.bank_id=? and " + answerVisible(user) + " group by u.id,u.display_name order by completed_count desc,accuracy_percent desc,last_practiced_at desc nulls last limit ?", this::row, bankId, limit)); }
  @GetMapping("/analytics/imports/{jobId}") ApiResponse<?> imported(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long jobId) { long user = user(header); id(jobId); var rows = db.query("select q.*,(select count(*) from question_import_job_events e where e.job_id=q.id) events,(select count(*) from question_import_job_outputs o where o.job_id=q.id) outputs from question_import_jobs q where q.id=? and q.created_by=? and exists(select 1 from question_banks b where b.id=q.bank_id and " + ContentAccess.bankVisible("b", user) + ")", this::row, jobId, user); if (rows.isEmpty()) throw ApiException.of(404, "NOT_FOUND", "Import job not found"); return ApiResponse.ok(rows.getFirst()); }
  @GetMapping("/search/questions") ApiResponse<?> search(@RequestHeader(value = "Authorization", required = false) String header, @RequestParam(required = false) Long bankId, @RequestParam(name = "type", defaultValue = "") String type, @RequestParam(defaultValue = "") String status, @RequestParam(required = false) Integer limit, @RequestParam(defaultValue = "") String cursor, @RequestParam(name = "q", defaultValue = "") String query) {
    long user = user(header); if (bankId != null && bankId < 1) throw bad("bankId must be a positive integer"); if (!status.isBlank() && !Set.of("draft", "active", "archived").contains(status)) throw bad("status must be one of draft, active, archived"); int size = limit == null ? 50 : limit; if (size < 1 || size > 100) throw bad("limit must be between 1 and 100"); int offset = PageSupport.cursor(cursor);
    var rows = db.query("with visible as (select l.question_id,b.owner_user_id=? can_edit from bank_question_links l join question_banks b on b.id=l.bank_id join questions q on q.id=l.question_id where (cast(? as bigint) is null or l.bank_id=cast(? as bigint)) and b.deleted_at is null and b.status<>'banned' and (b.owner_user_id=? or b.status='public' or exists(select 1 from study_group_banks sb join study_group_members gm on gm.group_id=sb.group_id where sb.bank_id=b.id and gm.user_id=? and gm.status='accepted')) and (b.owner_user_id=? or (l.status='active' and q.status='active')) union select q.id,b.owner_user_id=? can_edit from bank_group_links gl join question_banks b on b.id=gl.bank_id join question_groups g on g.id=gl.group_id join group_question_links gql on gql.group_id=g.id join questions q on q.id=gql.question_id where (cast(? as bigint) is null or gl.bank_id=cast(? as bigint)) and b.deleted_at is null and b.status<>'banned' and (b.owner_user_id=? or b.status='public' or exists(select 1 from study_group_banks sb join study_group_members gm on gm.group_id=sb.group_id where sb.bank_id=b.id and gm.user_id=? and gm.status='accepted')) and (b.owner_user_id=? or (gl.status='active' and g.status='active' and q.status='active'))), access as (select question_id,bool_or(can_edit) can_edit from visible group by question_id) select q.id,q.subject_id,q.question_type_id,q.answer_mode,q.choice_variant,q.stem,null::text analysis,q.status,a.can_edit from access a join questions q on q.id=a.question_id where (?='' or q.question_type_id=?) and (?='' or q.status=?) and (?='' or q.stem ilike '%'||?||'%' or to_tsvector('simple',q.stem) @@ plainto_tsquery('simple',?)) order by q.updated_at desc,q.id desc limit ? offset ?", this::row, user, bankId, bankId, user, user, user, user, bankId, bankId, user, user, user, type.trim(), type.trim(), status, status, query.trim(), query.trim(), query.trim(), size + 1, offset);
    boolean more = rows.size() > size; if (more) rows = rows.subList(0, size); return ApiResponse.ok(rows, Map.of("pagination", Map.of("cursor", more ? PageSupport.next(offset, size) : "", "limit", size, "hasMore", more)));
  }

}
