package com.practiq.web;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.practiq.auth.AuthService;
import com.practiq.common.*;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.sql.ResultSet;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.http.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

/** Content API backed by the existing PostgreSQL schema/triggers. */
@RestController @RequestMapping("/api/v1")
public class ContentController {
  private final JdbcTemplate db; private final AuthService auth; private final ObjectMapper json;
  ContentController(JdbcTemplate db, AuthService auth, ObjectMapper json){this.db=db;this.auth=auth;this.json=json;}
  private long user(String h){return auth.require(h);}
  private static ApiException valid(String s){return ApiException.of(422,"VALIDATION_ERROR",s);} private static void nonblank(String v,String f){if(v==null||v.trim().isEmpty())throw valid(f+" is required");}
  private static String status(String v,String fallback){if(v==null||v.isBlank())return fallback; if(Set.of("draft","active","archived").contains(v.trim()))return v.trim(); throw valid("Invalid question status");}
  private static int limit(Integer v,int fallback){return Math.min(v==null?fallback:Math.max(1,v),100);} private static ApiResponse<List<Map<String,Object>>> page(List<Map<String,Object>> x,int offset,int limit){boolean more=x.size()>limit;if(more)x=x.subList(0,limit);return ApiResponse.ok(x,Map.of("pagination",Map.of("cursor",more?PageSupport.next(offset,limit):"","limit",limit,"hasMore",more)));}
  private Map<String,Object> row(ResultSet r,int n)throws java.sql.SQLException{var m=new LinkedHashMap<String,Object>();for(int i=1;i<=r.getMetaData().getColumnCount();i++){String k=r.getMetaData().getColumnLabel(i);Object v=r.getObject(i);m.put(k,v instanceof OffsetDateTime t?t.toString():v);}return m;}
  private Map<String,Object> bank(long uid,long bid){var x=db.query("select b.*,coalesce(l.is_owner,false) is_owner,coalesce(l.is_favorite,false) is_favorite from question_banks b left join user_bank_links l on l.bank_id=b.id and l.user_id=? where b.id=? and b.deleted_at is null and (b.is_public or l.id is not null or exists(select 1 from study_group_banks gb join study_group_members gm on gm.group_id=gb.group_id where gb.bank_id=b.id and gm.user_id=?))",this::row,uid,bid,uid);if(x.isEmpty())throw ApiException.of(404,"NOT_FOUND","Question bank not found");return x.getFirst();}
  private String owner(long uid,long bid){var x=db.query("select subject_id from question_banks where id=? and deleted_at is null and owner_user_id=?",(r,n)->r.getString(1),bid,uid);if(x.isEmpty())throw ApiException.of(403,"FORBIDDEN","Bank owner access required");return x.getFirst();}
  private void editableQuestion(long uid,long qid){Integer n=db.queryForObject("select count(*) from bank_question_links l join question_banks b on b.id=l.bank_id where l.question_id=? and b.owner_user_id=? and b.deleted_at is null",Integer.class,qid,uid);if(n==null||n==0)throw ApiException.of(403,"FORBIDDEN","Question editor access required");}
  private void editableGroup(long uid,long gid){Integer n=db.queryForObject("select count(*) from bank_group_links l join question_banks b on b.id=l.bank_id where l.group_id=? and b.owner_user_id=? and b.deleted_at is null",Integer.class,gid,uid);if(n==null||n==0)throw ApiException.of(403,"FORBIDDEN","Group editor access required");}
  private String stringify(Object v){try{return json.writeValueAsString(v==null?Map.of():v);}catch(Exception e){throw valid("Invalid JSON value");}}

  @GetMapping("/banks") ApiResponse<?> banks(@RequestHeader(value="Authorization",required=false)String h,@RequestParam(defaultValue="")String scope,@RequestParam(defaultValue="")String subject,@RequestParam(name="q",defaultValue="")String q,@RequestParam(required=false)Integer limit,@RequestParam(defaultValue="")String cursor){long u=user(h);String s=scope.isBlank()?"mine":scope;if(!Set.of("mine","public","favorites","all").contains(s))throw valid("scope must be one of mine, public, favorites, all");int l=limit(limit,30),o=PageSupport.cursor(cursor);var x=db.query("select b.*,coalesce(ubl.is_owner,false) is_owner,coalesce(ubl.is_favorite,false) is_favorite from question_banks b left join user_bank_links ubl on ubl.bank_id=b.id and ubl.user_id=? where b.deleted_at is null and ((?='mine' and coalesce(ubl.is_owner,false)) or (?='public' and b.is_public) or (?='favorites' and coalesce(ubl.is_favorite,false)) or (?='all' and (b.is_public or ubl.id is not null))) and (?='' or b.subject=?) and (?='' or b.name ilike ?) order by b.updated_at desc,b.id desc limit ? offset ?",this::row,u,s,s,s,s,subject.trim(),subject.trim(),q.trim(),"%"+q.trim()+"%",l+1,o);return page(x,o,l);}
  public record BankIn(@NotBlank @Size(max=100)String name,@Size(max=500)String description,@NotBlank String subject,Boolean isPublic){} public record BankPatch(@Size(max=100)String name,@Size(max=500)String description,Boolean isPublic){}
  @PostMapping("/banks") @Transactional ResponseEntity<ApiResponse<?>> createBank(@RequestHeader(value="Authorization",required=false)String h,@Valid @RequestBody BankIn b){long u=user(h);var x=db.query("insert into question_banks(name,description,subject,created_by,is_public) values(?,?,?,?,?) returning *",this::row,b.name().trim(),b.description(),b.subject().trim(),u,Boolean.TRUE.equals(b.isPublic())).getFirst();db.update("insert into user_bank_links(user_id,bank_id,is_owner) values(?,?,true)",u,x.get("id"));return ResponseEntity.status(201).body(ApiResponse.ok(x));}
  @GetMapping("/banks/{bankId}") ApiResponse<?> getBank(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long bankId){return ApiResponse.ok(bank(user(h),bankId));}
  @PatchMapping("/banks/{bankId}") @Transactional ApiResponse<?> patchBank(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long bankId,@RequestBody BankPatch b){long u=user(h);owner(u,bankId);if(b.name()==null&&b.description()==null&&b.isPublic()==null)throw valid("body must include a field to update");if(b.name()!=null)nonblank(b.name(),"name");return ApiResponse.ok(db.query("update question_banks set name=coalesce(?,name),description=case when ? then ? else description end,is_public=coalesce(?,is_public) where id=? returning *",this::row,b.name()==null?null:b.name().trim(),b.description()!=null,b.description(),b.isPublic(),bankId).getFirst());}
  @DeleteMapping("/banks/{bankId}") @Transactional ResponseEntity<Void> deleteBank(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long bankId){long u=user(h);owner(u,bankId);db.update("update question_banks set deleted_at=now() where id=? and deleted_at is null",bankId);return ResponseEntity.noContent().build();}
  @PostMapping("/banks/{bankId}/favorite") @Transactional ResponseEntity<Void> favorite(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long bankId){long u=user(h);bank(u,bankId);db.update("insert into user_bank_links(user_id,bank_id,is_favorite) values(?,?,true) on conflict(user_id,bank_id) do update set is_favorite=true",u,bankId);return ResponseEntity.noContent().build();}
  @DeleteMapping("/banks/{bankId}/favorite") @Transactional ResponseEntity<Void> unfavorite(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long bankId){long u=user(h);bank(u,bankId);db.update("delete from user_bank_links where user_id=? and bank_id=? and not is_owner",u,bankId);db.update("update user_bank_links set is_favorite=false where user_id=? and bank_id=? and is_owner",u,bankId);return ResponseEntity.noContent().build();}
  @PostMapping("/banks/{bankId}/clone") @Transactional ApiResponse<?> cloneBank(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long bankId){long u=user(h);var src=db.query("select * from question_banks where id=? and is_public and deleted_at is null",this::row,bankId);if(src.isEmpty())throw ApiException.of(404,"BANK_NOT_FOUND","Question bank not found");var s=src.getFirst();String name=((String)s.get("name"));name=(name.length()>96?name.substring(0,96):name)+"（副本）";var out=db.query("insert into question_banks(name,description,subject,total_count,created_by,is_public) values(?,?,?,?,?,false) returning *",this::row,name,s.get("description"),s.get("subject"),s.get("total_count"),u).getFirst();long n=((Number)out.get("id")).longValue();db.update("insert into user_bank_links(user_id,bank_id,is_owner) values(?,?,true)",u,n);db.update("insert into bank_question_links(bank_id,question_id,sort_order,question_no,status,added_by) select ?,question_id,sort_order,question_no,status,? from bank_question_links where bank_id=?",n,u,bankId);return ApiResponse.ok(out);}
  @GetMapping("/banks/{bankId}/items") ApiResponse<?> items(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long bankId,@RequestParam(defaultValue="")String status,@RequestParam(name="type",defaultValue="")String type,@RequestParam(required=false)Integer limit,@RequestParam(defaultValue="")String cursor,@RequestParam(name="includeAnswers",defaultValue="false")boolean answers){long u=user(h);var b=bank(u,bankId);boolean edit=Boolean.TRUE.equals(b.get("is_owner"));if(!status.isBlank()&&!Set.of("draft","active","archived").contains(status))throw valid("Invalid request");int l=limit(limit,50),o=PageSupport.cursor(cursor);var x=db.query("select item.*,case when ? then item.analysis else null end visible_analysis from v_bank_question_items item where item.bank_id=? and (?='' or item.bank_link_status=?) and (?='' or item.question_type_id=?) and (? or (item.bank_link_status='active' and item.question_status='active')) order by item.bank_sort_order,item.group_sort_order nulls first,item.question_id limit ? offset ?",this::row,edit,bankId,status,status,type,type,edit,l+1,o);for(var r:x){long q=((Number)r.get("question_id")).longValue();r.put("options",db.query("select id,question_id,option_label,sort_order,content,case when ? then is_correct else null end is_correct,created_at,updated_at from question_options where question_id=? order by sort_order",this::row,edit&&answers,q));}return page(x,o,l);}
  public record ReorderItem(Long questionId,Long groupId,@Positive Integer sortOrder){} public record Reorder(@NotEmpty List<@Valid ReorderItem> items){}
  @PatchMapping("/banks/{bankId}/items/reorder") @Transactional ResponseEntity<Void> reorderBank(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long bankId,@Valid @RequestBody Reorder body){long u=user(h);owner(u,bankId);Set<String> seen=new HashSet<>();Set<Integer> orders=new HashSet<>();for(var i:body.items()){if((i.questionId()==null)==(i.groupId()==null)||!seen.add((i.questionId()==null?"g":"q")+(i.questionId()==null?i.groupId():i.questionId()))||!orders.add(i.sortOrder()))throw valid("item IDs and sortOrder values must be unique");}int count=db.queryForObject("select (select count(*) from bank_question_links where bank_id=?)+(select count(*) from bank_group_links where bank_id=?)",Integer.class,bankId,bankId);if(count!=body.items().size())throw valid("items must include every bank item exactly once");db.update("update bank_question_links set sort_order=sort_order+1000000 where bank_id=?",bankId);db.update("update bank_group_links set sort_order=sort_order+1000000 where bank_id=?",bankId);for(var i:body.items()){int n=i.questionId()!=null?db.update("update bank_question_links set sort_order=? where bank_id=? and question_id=?",i.sortOrder(),bankId,i.questionId()):db.update("update bank_group_links set sort_order=? where bank_id=? and group_id=?",i.sortOrder(),bankId,i.groupId());if(n!=1)throw valid("items contains an unknown item");}return ResponseEntity.noContent().build();}

  public record OptionIn(@NotBlank @Size(max=16)String label,@NotBlank String content,Boolean isCorrect,Integer sortOrder){} public record QuestionIn(@NotBlank String questionTypeId,@NotBlank String answerMode,@NotBlank String stem,String analysis,String choiceVariant,String status,List<OptionIn> options,Map<String,Object> answerPayload){} public record QuestionPatch(String stem,String analysis){} public record KeyIn(@NotBlank String answerMode,Map<String,Object> answerPayload,Map<String,Object> explanationPayload){}
  private void questionInput(QuestionIn q){if(!Set.of("choice","true_false","fill_blank","short_answer").contains(q.answerMode()))throw valid("Invalid request");if(!"choice".equals(q.answerMode())&&q.options()!=null&&!q.options().isEmpty())throw valid("Options are only supported for choice questions");if("choice".equals(q.answerMode())&&q.options()!=null){var labels=new HashSet<String>();for(var o:q.options())if(!labels.add(o.label().trim()))throw valid("Choice option labels must be unique");}}
  @PostMapping("/banks/{bankId}/questions") @Transactional ResponseEntity<ApiResponse<?>> createQuestion(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long bankId,@Valid @RequestBody QuestionIn q){long u=user(h);String subject=owner(u,bankId);questionInput(q);String st=status(q.status(),"draft");if("active".equals(st))publishableNew(q);String type=db.query("select type_id from question_types where subject_id=? and type_id=? limit 1",(r,n)->r.getString(1),subject,q.questionTypeId().trim()).stream().findFirst().orElseThrow(()->valid("Invalid question type"));var x=db.query("insert into questions(subject_id,question_type_id,answer_mode,choice_variant,stem,analysis,status,source_type,imported_by) values(?,?,?,?,?,?,?,'manual',?) returning *",this::row,subject,type,q.answerMode(),q.choiceVariant(),q.stem().trim(),q.analysis(),st,u).getFirst();long id=((Number)x.get("id")).longValue();List<OptionIn> os=q.options()==null?List.of():q.options();var selected=selected(q.answerPayload());if("choice".equals(q.answerMode())&&selected.isEmpty())selected=os.stream().filter(o->Boolean.TRUE.equals(o.isCorrect())).map(OptionIn::label).toList();db.update("insert into question_answer_keys(question_id,answer_mode,answer_payload) values(?,?,?::text)",id,q.answerMode(),stringify(Map.of("selected",selected)));for(int i=0;i<os.size();i++){var o=os.get(i);db.update("insert into question_options(question_id,option_label,sort_order,content,is_correct) values(?,?,?,?,?)",id,o.label().trim(),i+1,o.content().trim(),selected.contains(o.label().trim()));}db.update("insert into bank_question_links(bank_id,question_id,sort_order,status,added_by) values(?,?,coalesce((select max(sort_order)+1 from bank_question_links where bank_id=?),1),?,?)",bankId,id,bankId,st,u);db.update("update question_banks set total_count=total_count+1 where id=?",bankId);return ResponseEntity.status(201).body(ApiResponse.ok(x));}
  private List<String> selected(Map<String,Object> p){if(p==null)return List.of();Object x=p.containsKey("selected")?p.get("selected"):p.getOrDefault("correctOptions",p.get("correctOption"));if(x instanceof Collection<?> c)return c.stream().map(Object::toString).map(String::trim).filter(s->!s.isEmpty()).toList();return x==null?List.of():List.of(x.toString().trim());}
  private void publishableNew(QuestionIn q){if("choice".equals(q.answerMode())){var o=q.options()==null?List.<OptionIn>of():q.options();if(o.size()<2||o.stream().noneMatch(x->Boolean.TRUE.equals(x.isCorrect()))&&selected(q.answerPayload()).isEmpty())throw ApiException.of(409,"INVALID_STATE","Active choice questions require at least two options and one correct option");}}
  @GetMapping("/questions/{questionId}") ApiResponse<?> getQuestion(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long questionId){long u=user(h);var x=db.query("select q.*,exists(select 1 from bank_question_links b join user_bank_links l on l.bank_id=b.bank_id where b.question_id=q.id and l.user_id=? and l.is_owner) can_edit from questions q where q.id=?",this::row,u,questionId);if(x.isEmpty())throw ApiException.of(404,"NOT_FOUND","Question not found");var q=x.getFirst();boolean edit=Boolean.TRUE.equals(q.get("can_edit"));if(!edit){Integer n=db.queryForObject("select count(*) from v_bank_question_items i join question_banks b on b.id=i.bank_id left join user_bank_links l on l.bank_id=b.id and l.user_id=? where i.question_id=? and (b.is_public or l.id is not null) and i.bank_link_status='active' and i.question_status='active'",Integer.class,u,questionId);if(n==0)throw ApiException.of(404,"NOT_FOUND","Question not found");}q.put("options",db.query("select id,question_id,option_label,sort_order,content"+(edit?",is_correct":"")+" from question_options where question_id=? order by sort_order",this::row,questionId));q.put("content_blocks",db.query("select * from question_content_blocks where question_id=? order by sequence",this::row,questionId));q.put("media_links",db.query("select * from question_media_links where question_id=? order by sort_order",this::row,questionId));if(edit)q.put("answer_keys",db.query("select * from question_answer_keys where question_id=? order by version",this::row,questionId));return ApiResponse.ok(q);}
  @PatchMapping("/questions/{questionId}") @Transactional ApiResponse<?> patchQuestion(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long questionId,@RequestBody QuestionPatch p){long u=user(h);editableQuestion(u,questionId);if(p.stem()==null&&p.analysis()==null)throw valid("body must include stem or analysis");if(p.stem()!=null)nonblank(p.stem(),"stem");return ApiResponse.ok(db.query("update questions set stem=coalesce(?,stem),analysis=case when ? then ? else analysis end where id=? returning *",this::row,p.stem()==null?null:p.stem().trim(),p.analysis()!=null,p.analysis(),questionId).getFirst());}
  @DeleteMapping("/questions/{questionId}") @Transactional ResponseEntity<Void> deleteQuestion(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long questionId){long u=user(h);editableQuestion(u,questionId);var banks=db.queryForList("select distinct bank_id from v_bank_question_items where question_id=?",Long.class,questionId);db.update("delete from questions where id=?",questionId);for(long b:banks)db.update("update question_banks set total_count=greatest(total_count-1,0) where id=?",b);return ResponseEntity.noContent().build();}
  @PostMapping("/questions/{questionId}/publish") @Transactional ApiResponse<?> publish(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long questionId){long u=user(h);editableQuestion(u,questionId);assertPublishable(questionId);return ApiResponse.ok(setQuestion(questionId,"active"));}
  @PostMapping("/questions/{questionId}/archive") @Transactional ApiResponse<?> archive(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long questionId){editableQuestion(user(h),questionId);return ApiResponse.ok(setQuestion(questionId,"archived"));}
  private Map<String,Object> setQuestion(long q,String s){var x=db.query("update questions set status=? where id=? returning *",this::row,s,q).getFirst();db.update("update bank_question_links set status=? where question_id=?",s,q);return x;}
  private void assertPublishable(long q){var x=db.query("select q.answer_mode,(select count(*) from question_options o where o.question_id=q.id),(select count(*) from question_options o where o.question_id=q.id and o.is_correct),(select count(*) from question_answer_keys k where k.question_id=q.id and k.is_primary) from questions q where q.id=?",(r,n)->new Object[]{r.getString(1),r.getInt(2),r.getInt(3),r.getInt(4)},q);if(x.isEmpty())throw ApiException.of(404,"NOT_FOUND","Question not found");var a=x.getFirst();if((int)a[3]<1||("choice".equals(a[0])&&((int)a[1]<2||(int)a[2]<1)))throw ApiException.of(409,"INVALID_STATE","Question is not publishable");}
  @PostMapping("/questions/{questionId}/options") @Transactional ResponseEntity<ApiResponse<?>> addOption(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long questionId,@Valid @RequestBody OptionIn o){editableQuestion(user(h),questionId);if(o.sortOrder()!=null&&(o.sortOrder()<1||o.sortOrder()>32767))throw valid("Invalid request");var x=db.query("insert into question_options(question_id,option_label,sort_order,content,is_correct) values(?,?,coalesce(?,(select coalesce(max(sort_order),0)+1 from question_options where question_id=?)),?,?) returning *",this::row,questionId,o.label().trim(),o.sortOrder(),questionId,o.content().trim(),Boolean.TRUE.equals(o.isCorrect())).getFirst();syncOptions(questionId);return ResponseEntity.status(201).body(ApiResponse.ok(x));}
  @PatchMapping("/questions/{questionId}/options/{optionId}") @Transactional ApiResponse<?> patchOption(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long questionId,@PathVariable long optionId,@RequestBody OptionIn o){editableQuestion(user(h),questionId);if(o.label()==null&&o.content()==null&&o.isCorrect()==null&&o.sortOrder()==null)throw valid("body must include a field to update");var x=db.query("update question_options set option_label=coalesce(?,option_label),content=coalesce(?,content),is_correct=coalesce(?,is_correct),sort_order=coalesce(?,sort_order) where id=? and question_id=? returning *",this::row,o.label(),o.content(),o.isCorrect(),o.sortOrder(),optionId,questionId);if(x.isEmpty())throw ApiException.of(404,"NOT_FOUND","Option not found");syncOptions(questionId);return ApiResponse.ok(x.getFirst());}
  @DeleteMapping("/questions/{questionId}/options/{optionId}") @Transactional ResponseEntity<Void> deleteOption(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long questionId,@PathVariable long optionId){editableQuestion(user(h),questionId);if(db.update("delete from question_options where id=? and question_id=?",optionId,questionId)==0)throw ApiException.of(404,"NOT_FOUND","Option not found");syncOptions(questionId);return ResponseEntity.noContent().build();}
  private void syncOptions(long q){var s=db.queryForList("select option_label from question_options where question_id=? and is_correct order by sort_order",String.class,q);db.update("update question_answer_keys set answer_payload=? where question_id=? and is_primary",stringify(Map.of("selected",s)),q);}
  @PutMapping("/questions/{questionId}/answer-key") @Transactional ApiResponse<?> key(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long questionId,@Valid @RequestBody KeyIn k){editableQuestion(user(h),questionId);String mode=db.queryForObject("select answer_mode from questions where id=?",String.class,questionId);if(!mode.equals(k.answerMode()))throw valid("answerMode must match the question answer mode");if("choice".equals(mode)){var labels=new HashSet<>(db.queryForList("select option_label from question_options where question_id=?",String.class,questionId));if(!labels.containsAll(selected(k.answerPayload())))throw valid("answerPayload must reference existing option labels");}db.update("update question_answer_keys set is_primary=false where question_id=? and is_primary",questionId);var x=db.query("insert into question_answer_keys(question_id,answer_mode,version,is_primary,answer_payload,explanation_payload) values(?,?,(select coalesce(max(version),0)+1 from question_answer_keys where question_id=?),true,?::jsonb,?::jsonb) returning *",this::row,questionId,mode,questionId,stringify(k.answerPayload()),stringify(k.explanationPayload())).getFirst();return ApiResponse.ok(x);}
  public record Block(String partType,String ownerKind,String role,Integer sequence,String contentMode,String textFormat,String textValue,String latexValue,String mathmlValue,String htmlValue,String markdownValue,Object jsonValue,Long mediaId){} public record Blocks(List<Block> blocks){}
  @PutMapping("/questions/{questionId}/content-blocks") @Transactional ResponseEntity<Void> blocks(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long questionId,@RequestBody Blocks b){long u=user(h);editableQuestion(u,questionId);if(b.blocks()==null||b.blocks().size()>1000)throw valid("Invalid request");db.update("delete from question_content_blocks where question_id=?",questionId);int i=0;for(var x:b.blocks()){if(x.partType()==null||!Set.of("text","formula","image","table","list","html","markdown","chart","diagram","qr_code").contains(x.partType()))throw valid("Invalid request");String owner=x.ownerKind()==null||x.ownerKind().isBlank()?"question":x.ownerKind();if(!Set.of("question","stem","answer_key","analysis","explanation").contains(owner))throw valid("Invalid request");db.update("insert into question_content_blocks(question_id,owner_kind,role,part_type,sequence,content_mode,text_format,text_value,latex_value,mathml_value,html_value,markdown_value,json_value,media_id) values(?,?,?,?,?,?,?,?,?,?,?,?,?::text,?)",questionId,owner,x.role(),x.partType(),x.sequence()==null?++i:x.sequence(),x.contentMode(),x.textFormat(),x.textValue(),x.latexValue(),x.mathmlValue(),x.htmlValue(),x.markdownValue(),x.jsonValue()==null?null:stringify(x.jsonValue()),x.mediaId());}return ResponseEntity.noContent().build();}

  public record GroupIn(@NotBlank String title,String instructions,String groupTypeId,String contentMode,String status){} public record GroupPatch(String title,String instructions,String contentMode){} public record GroupQuestion(@Positive long questionId,Integer sortOrder){} public record GroupReorder(@NotEmpty List<@Valid GroupQuestion> items){}
  @GetMapping("/banks/{bankId}/groups") ApiResponse<?> bankGroups(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long bankId,@RequestParam(required=false)Integer limit,@RequestParam(defaultValue="")String cursor){var b=bank(user(h),bankId);int l=limit(limit,30),o=PageSupport.cursor(cursor);var x=db.query("select g.id,g.group_type_id,g.title,g.instructions,g.content_mode,b.status,b.sort_order,count(q.question_id) question_count from bank_group_links b join question_groups g on g.id=b.group_id left join group_question_links q on q.group_id=g.id where b.bank_id=? and (? or b.status='active') group by g.id,b.status,b.sort_order order by b.sort_order,g.id limit ? offset ?",this::row,bankId,Boolean.TRUE.equals(b.get("is_owner")),l+1,o);for(var r:x)r.put("can_edit",b.get("is_owner"));return page(x,o,l);}
  @PostMapping("/banks/{bankId}/groups") @Transactional ResponseEntity<ApiResponse<?>> createGroup(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long bankId,@Valid @RequestBody GroupIn g){long u=user(h);String subject=owner(u,bankId),mode=g.contentMode()==null?"text_only":g.contentMode();if(!Set.of("text_only","mixed_media","structured_rich").contains(mode))throw valid("Invalid request");String type=(g.groupTypeId()==null||g.groupTypeId().isBlank())?db.queryForObject("select type_id from question_types where subject_id=? order by type_id limit 1",String.class,subject):g.groupTypeId();var x=db.query("insert into question_groups(subject_id,group_type_id,title,instructions,content_mode,imported_by) values(?,?,?,?,?,?) returning *",this::row,subject,type,g.title().trim(),g.instructions(),mode,u).getFirst();db.update("insert into bank_group_links(bank_id,group_id,sort_order,status,added_by) values(?,?,coalesce((select max(sort_order)+1 from bank_group_links where bank_id=?),1),?,?)",bankId,x.get("id"),bankId,status(g.status(),"draft"),u);return ResponseEntity.status(201).body(ApiResponse.ok(x));}
  @GetMapping("/groups/{groupId}") ApiResponse<?> getGroup(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long groupId){long u=user(h);var x=db.query("select g.*,exists(select 1 from bank_group_links b join user_bank_links l on l.bank_id=b.bank_id where b.group_id=g.id and l.user_id=? and l.is_owner) can_edit from question_groups g where g.id=?",this::row,u,groupId);if(x.isEmpty())throw ApiException.of(404,"NOT_FOUND","Group not found");var g=x.getFirst();boolean edit=Boolean.TRUE.equals(g.get("can_edit"));Integer n=db.queryForObject("select count(*) from bank_group_links b join question_banks q on q.id=b.bank_id left join user_bank_links l on l.bank_id=q.id and l.user_id=? where b.group_id=? and (q.is_public or l.id is not null) and (? or b.status='active')",Integer.class,u,groupId,edit);if(n==0)throw ApiException.of(404,"NOT_FOUND","Group not found");g.put("questions",db.query("select q.id,q.subject_id,q.question_type_id,q.answer_mode,q.choice_variant,q.stem,"+(edit?"q.analysis":"null as analysis")+",q.status from group_question_links l join questions q on q.id=l.question_id where l.group_id=? and (? or q.status='active') order by l.sort_order",this::row,groupId,edit));return ApiResponse.ok(g);}
  @PatchMapping("/groups/{groupId}") @Transactional ApiResponse<?> patchGroup(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long groupId,@RequestBody GroupPatch g){editableGroup(user(h),groupId);if(g.title()==null&&g.instructions()==null&&g.contentMode()==null)throw valid("body must include a field to update");if(g.title()!=null)nonblank(g.title(),"title");if(g.contentMode()!=null&&!Set.of("text_only","mixed_media","structured_rich").contains(g.contentMode()))throw valid("Invalid request");return ApiResponse.ok(db.query("update question_groups set title=coalesce(?,title),instructions=case when ? then ? else instructions end,content_mode=coalesce(?,content_mode) where id=? returning *",this::row,g.title(),g.instructions()!=null,g.instructions(),g.contentMode(),groupId).getFirst());}
  @DeleteMapping("/groups/{groupId}") @Transactional ResponseEntity<Void> deleteGroup(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long groupId){long u=user(h);editableGroup(u,groupId);db.update("delete from bank_group_links b using user_bank_links l where b.group_id=? and l.bank_id=b.bank_id and l.user_id=? and l.is_owner",groupId,u);db.update("delete from question_groups where id=? and not exists(select 1 from bank_group_links where group_id=?)",groupId,groupId);return ResponseEntity.noContent().build();}
  @PostMapping("/groups/{groupId}/publish") @Transactional ApiResponse<?> publishGroup(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long groupId){long u=user(h);editableGroup(u,groupId);Integer bad=db.queryForObject("select count(*) from group_question_links l join questions q on q.id=l.question_id where l.group_id=? and q.status<>'active'",Integer.class,groupId);Integer total=db.queryForObject("select count(*) from group_question_links where group_id=?",Integer.class,groupId);if(total==0||bad>0)throw ApiException.of(409,"GROUP_NOT_PUBLISHABLE","Publish every question before publishing the group");db.update("update bank_group_links b set status='active' from user_bank_links l where b.group_id=? and l.bank_id=b.bank_id and l.user_id=? and l.is_owner",groupId,u);return getGroup(h,groupId);}
  @PostMapping("/groups/{groupId}/archive") @Transactional ApiResponse<?> archiveGroup(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long groupId){long u=user(h);editableGroup(u,groupId);db.update("update bank_group_links b set status='archived' from user_bank_links l where b.group_id=? and l.bank_id=b.bank_id and l.user_id=? and l.is_owner",groupId,u);return getGroup(h,groupId);}
  @PostMapping("/groups/{groupId}/questions") @Transactional ResponseEntity<ApiResponse<?>> addGroupQuestion(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long groupId,@Valid @RequestBody GroupQuestion q){long u=user(h);editableGroup(u,groupId);editableQuestion(u,q.questionId());if(q.sortOrder()!=null&&q.sortOrder()<1)throw valid("Invalid request");var x=db.query("insert into group_question_links(group_id,question_id,sort_order) values(?,?,coalesce(?,(select coalesce(max(sort_order),0)+1 from group_question_links where group_id=?))) returning *",this::row,groupId,q.questionId(),q.sortOrder(),groupId).getFirst();db.update("delete from bank_question_links b using bank_group_links g where g.group_id=? and b.bank_id=g.bank_id and b.question_id=?",groupId,q.questionId());return ResponseEntity.status(201).body(ApiResponse.ok(x));}
  @PatchMapping("/groups/{groupId}/questions/reorder") @Transactional ResponseEntity<Void> reorderGroup(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long groupId,@Valid @RequestBody GroupReorder body){editableGroup(user(h),groupId);Set<Long> qs=new HashSet<>();Set<Integer> ss=new HashSet<>();for(var x:body.items())if(!qs.add(x.questionId())||x.sortOrder()==null||x.sortOrder()<1||!ss.add(x.sortOrder()))throw valid("questionId and sortOrder values must be unique");Integer count=db.queryForObject("select count(*) from group_question_links where group_id=?",Integer.class,groupId);if(count!=body.items().size())throw valid("items must include every group question exactly once");db.update("update group_question_links set sort_order=sort_order+1000000 where group_id=?",groupId);for(var x:body.items())if(db.update("update group_question_links set sort_order=? where group_id=? and question_id=?",x.sortOrder(),groupId,x.questionId())!=1)throw valid("items contains an unknown question");return ResponseEntity.noContent().build();}
  @DeleteMapping("/groups/{groupId}/questions/{questionId}") @Transactional ResponseEntity<Void> removeGroupQuestion(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long groupId,@PathVariable long questionId){long u=user(h);editableGroup(u,groupId);if(db.update("delete from group_question_links where group_id=? and question_id=?",groupId,questionId)==0)throw ApiException.of(404,"NOT_FOUND","Group question link not found");db.update("insert into bank_question_links(bank_id,question_id,sort_order,status,added_by) select g.bank_id,?,coalesce((select max(x.sort_order)+1 from bank_question_links x where x.bank_id=g.bank_id),1),q.status,? from bank_group_links g join questions q on q.id=? join user_bank_links l on l.bank_id=g.bank_id and l.user_id=? and l.is_owner where g.group_id=? on conflict(bank_id,question_id) do nothing",questionId,u,questionId,u,groupId);return ResponseEntity.noContent().build();}
}
