package com.practiq.web;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.practiq.auth.AuthService;
import com.practiq.common.*;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.sql.ResultSet;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.http.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1")
public class ContentController {
  private final JdbcTemplate db; private final AuthService auth; private final ObjectMapper json;
  ContentController(JdbcTemplate db, AuthService auth, ObjectMapper json) { this.db = db; this.auth = auth; this.json = json; }
  private long user(String header) { return auth.require(header); }
  private static ApiException valid(String message) { return ApiException.of(422, "VALIDATION_ERROR", message); }
  private static void nonblank(String value, String field) { if (value == null || value.trim().isEmpty()) throw valid(field + " is required"); }
  private static String status(String value, String fallback) { if (value == null || value.isBlank()) return fallback; if (Set.of("draft", "active", "archived").contains(value.trim())) return value.trim(); throw valid("Invalid question status"); }
  private static int limit(Integer value, int fallback) { return Math.min(value == null ? fallback : Math.max(1, value), 100); }
  private static ApiResponse<List<Map<String, Object>>> page(List<Map<String, Object>> rows, int offset, int size) { boolean more = rows.size() > size; if (more) rows = rows.subList(0, size); return ApiResponse.ok(rows, Map.of("pagination", Map.of("cursor", more ? PageSupport.next(offset, size) : "", "limit", size, "hasMore", more))); }
  private Map<String, Object> row(ResultSet result, int number) throws java.sql.SQLException { var value = new LinkedHashMap<String, Object>(); for (int i = 1; i <= result.getMetaData().getColumnCount(); i++) { Object item = result.getObject(i); value.put(result.getMetaData().getColumnLabel(i), item instanceof OffsetDateTime time ? time.toString() : item); } return value; }
  private Map<String, Object> bank(long user, long bank) { var rows = db.query("select b.id,b.subject_id,b.name,b.description,b.status,b.created_at,b.updated_at,b.owner_user_id=? is_owner,exists(select 1 from user_bank_favorites f where f.user_id=? and f.bank_id=b.id) is_favorite from question_banks b where b.id=? and b.deleted_at is null and b.status<>'banned' and (b.owner_user_id=? or b.status='public' or exists(select 1 from study_group_banks gb join study_group_members gm on gm.group_id=gb.group_id where gb.bank_id=b.id and gm.user_id=? and gm.status='accepted'))", this::row, user, user, bank, user, user); if (rows.isEmpty()) throw ApiException.of(404, "NOT_FOUND", "Question bank not found"); return rows.getFirst(); }
  private String owner(long user, long bank) { var rows = db.query("select subject_id from question_banks where id=? and owner_user_id=? and deleted_at is null", (r, n) -> r.getString(1), bank, user); if (rows.isEmpty()) throw ApiException.of(403, "FORBIDDEN", "Bank owner access required"); return rows.getFirst(); }
  private void editableQuestion(long user, long question) { if (db.queryForObject("select count(*) from questions where id=? and owner_user_id=?", Integer.class, question, user) == 0) throw ApiException.of(403, "FORBIDDEN", "Question owner access required"); }
  private void editableGroup(long user, long group) { if (db.queryForObject("select count(*) from question_groups where id=? and owner_user_id=?", Integer.class, group, user) == 0) throw ApiException.of(403, "FORBIDDEN", "Group owner access required"); }
  private String stringify(Object value) { try { return json.writeValueAsString(value == null ? Map.of() : value); } catch (Exception error) { throw valid("Invalid JSON value"); } }

  @GetMapping("/banks") ApiResponse<?> banks(@RequestHeader(value = "Authorization", required = false) String header, @RequestParam(defaultValue = "") String scope, @RequestParam(defaultValue = "") String subject, @RequestParam(name = "q", defaultValue = "") String query, @RequestParam(required = false) Integer limit, @RequestParam(defaultValue = "") String cursor) { long user = user(header); String selected = scope.isBlank() ? "mine" : scope; if (!Set.of("mine", "public", "favorites", "all").contains(selected)) throw valid("scope must be one of mine, public, favorites, all"); int size = limit(limit, 30), offset = PageSupport.cursor(cursor); var rows = db.query("select b.id,b.subject_id,b.name,b.description,b.status,b.created_at,b.updated_at,b.owner_user_id=? is_owner,exists(select 1 from user_bank_favorites f where f.user_id=? and f.bank_id=b.id) is_favorite from question_banks b where b.deleted_at is null and b.status<>'banned' and ((?='mine' and b.owner_user_id=?) or (?='public' and b.status='public') or (?='favorites' and exists(select 1 from user_bank_favorites f where f.user_id=? and f.bank_id=b.id)) or (?='all' and (b.owner_user_id=? or b.status='public'))) and (?='' or b.subject_id=?) and (?='' or b.name ilike ?) order by b.updated_at desc,b.id desc limit ? offset ?", this::row, user, user, selected, user, selected, selected, user, selected, user, subject.trim(), subject.trim(), query.trim(), "%" + query.trim() + "%", size + 1, offset); return page(rows, offset, size); }
  public record BankIn(@NotBlank @Size(max = 100) String name, @Size(max = 500) String description, @NotBlank String subject, Boolean isPublic) {} public record BankPatch(@Size(max = 100) String name, @Size(max = 500) String description, Boolean isPublic) {}
  @PostMapping("/banks") @Transactional ResponseEntity<ApiResponse<?>> createBank(@RequestHeader(value = "Authorization", required = false) String header, @Valid @RequestBody BankIn body) { long user = user(header); var bank = db.query("insert into question_banks(owner_user_id,subject_id,name,description) values(?,?,?,?) returning *", this::row, user, body.subject().trim(), body.name().trim(), body.description()).getFirst(); if (Boolean.TRUE.equals(body.isPublic())) bank = db.query("update question_banks set status='public' where id=? returning *", this::row, bank.get("id")).getFirst(); return ResponseEntity.status(201).body(ApiResponse.ok(bank)); }
  @GetMapping("/banks/{bankId}") ApiResponse<?> getBank(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long bankId) { return ApiResponse.ok(bank(user(header), bankId)); }
  @PatchMapping("/banks/{bankId}") @Transactional ApiResponse<?> patchBank(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long bankId, @RequestBody BankPatch body) { long user = user(header); owner(user, bankId); if (body.name() == null && body.description() == null && body.isPublic() == null) throw valid("body must include a field to update"); if (body.name() != null) nonblank(body.name(), "name"); if (Boolean.FALSE.equals(body.isPublic())) throw valid("Public banks cannot be unpublished"); String next = body.isPublic() == null ? null : "public"; var rows = db.query("update question_banks set name=coalesce(?,name),description=case when ? then ? else description end,status=coalesce(?,status) where id=? returning *", this::row, body.name() == null ? null : body.name().trim(), body.description() != null, body.description(), next, bankId); return ApiResponse.ok(rows.getFirst()); }
  @DeleteMapping("/banks/{bankId}") @Transactional ResponseEntity<Void> deleteBank(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long bankId) { long user = user(header); owner(user, bankId); db.update("update question_banks set deleted_at=now() where id=? and deleted_at is null", bankId); return ResponseEntity.noContent().build(); }
  @PostMapping("/banks/{bankId}/favorite") @Transactional ResponseEntity<Void> favorite(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long bankId) { long user = user(header); bank(user, bankId); db.update("insert into user_bank_favorites(user_id,bank_id) values(?,?) on conflict do nothing", user, bankId); return ResponseEntity.noContent().build(); }
  @DeleteMapping("/banks/{bankId}/favorite") @Transactional ResponseEntity<Void> unfavorite(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long bankId) { long user = user(header); db.update("delete from user_bank_favorites where user_id=? and bank_id=?", user, bankId); return ResponseEntity.noContent().build(); }
  @GetMapping("/banks/{bankId}/items") ApiResponse<?> items(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long bankId, @RequestParam(defaultValue = "") String status, @RequestParam(name = "type", defaultValue = "") String type, @RequestParam(required = false) Integer limit, @RequestParam(defaultValue = "") String cursor, @RequestParam(name = "includeAnswers", defaultValue = "false") boolean answers) { long user = user(header); var bank = bank(user, bankId); boolean edit = Boolean.TRUE.equals(bank.get("is_owner")); int size = limit(limit, 50), offset = PageSupport.cursor(cursor); var rows = db.query("select * from (select l.bank_id,l.question_id,l.subset_id,l.sort_order bank_sort_order,l.status bank_link_status,q.subject_id,q.question_type_id,q.answer_mode,q.choice_variant,q.stem,case when ? then q.analysis else null end analysis,q.status question_status from bank_question_links l join questions q on q.id=l.question_id where l.bank_id=? union all select gl.bank_id,gql.question_id,gl.subset_id,gl.sort_order bank_sort_order,gl.status bank_link_status,q.subject_id,q.question_type_id,q.answer_mode,q.choice_variant,q.stem,case when ? then q.analysis else null end analysis,q.status question_status from bank_group_links gl join question_groups g on g.id=gl.group_id join group_question_links gql on gql.group_id=g.id join questions q on q.id=gql.question_id where gl.bank_id=?) item where (?='' or bank_link_status=?) and (?='' or question_type_id=?) and (? or (bank_link_status='active' and question_status='active')) order by bank_sort_order,question_id limit ? offset ?", this::row, edit, bankId, edit, bankId, status, status, type, type, edit, size + 1, offset); for (var row : rows) { long question = ((Number) row.get("question_id")).longValue(); row.put("options", db.query("select o.id,o.question_id,o.option_label,o.sort_order,o.content,case when ? then jsonb_exists(k.answer_payload->'correct', o.option_label) else null end is_correct from question_options o left join question_answer_keys k on k.question_id=o.question_id and k.is_primary where o.question_id=? order by o.sort_order", this::row, edit && answers, question)); } return page(rows, offset, size); }
  public record ReorderItem(Long questionId, Long groupId, @Positive Integer sortOrder) {} public record Reorder(@NotEmpty List<@Valid ReorderItem> items) {}
  @PatchMapping("/banks/{bankId}/items/reorder") @Transactional ResponseEntity<Void> reorderBank(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long bankId, @Valid @RequestBody Reorder body) { owner(user(header), bankId); Set<String> seen = new HashSet<>(); Set<Integer> orders = new HashSet<>(); for (var item : body.items()) if ((item.questionId()==null)==(item.groupId()==null)||!seen.add((item.questionId()==null?"g":"q")+(item.questionId()==null?item.groupId():item.questionId()))||!orders.add(item.sortOrder())) throw valid("item IDs and sortOrder values must be unique"); int count=db.queryForObject("select (select count(*) from bank_question_links where bank_id=?)+(select count(*) from bank_group_links where bank_id=?)",Integer.class,bankId,bankId); if(count!=body.items().size()) throw valid("items must include every bank item exactly once"); db.update("update bank_question_links set sort_order=sort_order+1000000 where bank_id=?",bankId); db.update("update bank_group_links set sort_order=sort_order+1000000 where bank_id=?",bankId); for(var item:body.items()){int changed=item.questionId()!=null?db.update("update bank_question_links set sort_order=? where bank_id=? and question_id=?",item.sortOrder(),bankId,item.questionId()):db.update("update bank_group_links set sort_order=? where bank_id=? and group_id=?",item.sortOrder(),bankId,item.groupId()); if(changed!=1) throw valid("items contains an unknown item");} return ResponseEntity.noContent().build(); }

  public record OptionIn(@NotBlank @Size(max = 16) String label, @NotBlank String content, Boolean isCorrect, Integer sortOrder) {} public record QuestionIn(@NotBlank String questionTypeId, @NotBlank String answerMode, @NotBlank String stem, String analysis, String choiceVariant, String status, List<OptionIn> options, Map<String, Object> answerPayload) {} public record QuestionPatch(String stem, String analysis) {} public record KeyIn(@NotBlank String answerMode, Map<String, Object> answerPayload, Map<String, Object> explanationPayload) {}
  private List<String> selected(Map<String, Object> payload) { if (payload == null) return List.of(); Object value = payload.containsKey("correct") ? payload.get("correct") : payload.containsKey("selected") ? payload.get("selected") : payload.getOrDefault("correctOption", List.of()); if (value instanceof Collection<?> items) return items.stream().map(Object::toString).map(String::trim).filter(item -> !item.isEmpty()).toList(); return value == null ? List.of() : List.of(value.toString().trim()); }
  private Map<String, Object> keyPayload(String mode, Map<String, Object> payload, List<String> selected) { var value = new LinkedHashMap<String, Object>(); if ("choice".equals(mode)) value.put("correct", selected); else if ("true_false".equals(mode)) value.put("answer", payload == null ? null : payload.get("value")); else if ("fill_blank".equals(mode)) value.put("answers", payload == null ? List.of() : payload.getOrDefault("value", List.of())); else value.put("answer", payload == null ? "" : payload.getOrDefault("value", "")); return value; }
  @PostMapping("/banks/{bankId}/questions") @Transactional ResponseEntity<ApiResponse<?>> createQuestion(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long bankId, @Valid @RequestBody QuestionIn body) { long user = user(header); String subject = owner(user, bankId); if (!Set.of("choice", "true_false", "fill_blank", "short_answer").contains(body.answerMode())) throw valid("Invalid answerMode"); if (db.queryForObject("select count(*) from question_types where subject_id=? and id=?", Integer.class, subject, body.questionTypeId().trim()) == 0) throw valid("Invalid question type"); String requested = status(body.status(), "draft"); if ("choice".equals(body.answerMode()) && !Set.of("single", "multiple").contains(body.choiceVariant())) throw valid("Choice questions require choiceVariant"); var question = db.query("insert into questions(owner_user_id,subject_id,question_type_id,answer_mode,choice_variant,stem,analysis) values(?,?,?,?,?,?,?) returning *", this::row, user, subject, body.questionTypeId().trim(), body.answerMode(), body.choiceVariant(), body.stem().trim(), body.analysis()).getFirst(); long id = ((Number) question.get("id")).longValue(); var options = body.options() == null ? List.<OptionIn>of() : body.options(); var correct = selected(body.answerPayload()); if ("choice".equals(body.answerMode()) && correct.isEmpty()) correct = options.stream().filter(option -> Boolean.TRUE.equals(option.isCorrect())).map(OptionIn::label).toList(); for (int i = 0; i < options.size(); i++) db.update("insert into question_options(question_id,option_label,sort_order,content) values(?,?,?,?)", id, options.get(i).label().trim(), i + 1, options.get(i).content().trim()); db.update("insert into question_answer_keys(question_id,answer_mode,answer_payload) values(?,?,?::jsonb)", id, body.answerMode(), stringify(keyPayload(body.answerMode(), body.answerPayload(), correct))); db.update("insert into bank_question_links(bank_id,question_id,sort_order) values(?,?,coalesce((select max(sort_order)+1 from bank_question_links where bank_id=?),1))", bankId, id, bankId); if ("active".equals(requested)) { db.update("update questions set status='active' where id=?", id); db.update("update bank_question_links set status='active' where bank_id=? and question_id=?", bankId, id); } return ResponseEntity.status(201).body(ApiResponse.ok(question)); }
  @GetMapping("/questions/{questionId}") ApiResponse<?> getQuestion(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long questionId) { long user = user(header); var rows = db.query("select q.id,q.subject_id,q.question_type_id,q.answer_mode,q.choice_variant,q.stem,case when q.owner_user_id=? then q.analysis else null end analysis,q.status,q.owner_user_id=? can_edit from questions q where q.id=?", this::row, user, user, questionId); if (rows.isEmpty()) throw ApiException.of(404, "NOT_FOUND", "Question not found"); var question = rows.getFirst(); boolean edit = Boolean.TRUE.equals(question.get("can_edit")); if (!edit && db.queryForObject("select count(*) from (select l.question_id from bank_question_links l join question_banks b on b.id=l.bank_id where l.question_id=? and b.deleted_at is null and b.status<>'banned' and l.status='active' and (select status from questions where id=l.question_id)='active' and (b.status='public' or exists(select 1 from study_group_banks sb join study_group_members gm on gm.group_id=sb.group_id where sb.bank_id=b.id and gm.user_id=? and gm.status='accepted')) union all select gql.question_id from bank_group_links gl join question_groups g on g.id=gl.group_id join group_question_links gql on gql.group_id=g.id join question_banks b on b.id=gl.bank_id join questions q on q.id=gql.question_id where gql.question_id=? and b.deleted_at is null and b.status<>'banned' and gl.status='active' and g.status='active' and q.status='active' and (b.status='public' or exists(select 1 from study_group_banks sb join study_group_members gm on gm.group_id=sb.group_id where sb.bank_id=b.id and gm.user_id=? and gm.status='accepted'))) visible", Integer.class, questionId, user, questionId, user) == 0) throw ApiException.of(404, "NOT_FOUND", "Question not found"); question.put("options", db.query("select id,question_id,option_label,sort_order,content from question_options where question_id=? order by sort_order", this::row, questionId)); question.put("content_blocks", db.query("select * from question_content_blocks where question_id=? order by sequence", this::row, questionId)); if (edit) question.put("answer_keys", db.query("select * from question_answer_keys where question_id=? order by version", this::row, questionId)); return ApiResponse.ok(question); }
  @PatchMapping("/questions/{questionId}") @Transactional ApiResponse<?> patchQuestion(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long questionId, @RequestBody QuestionPatch body) { editableQuestion(user(header), questionId); if (body.stem() == null && body.analysis() == null) throw valid("body must include stem or analysis"); if (body.stem() != null) nonblank(body.stem(), "stem"); return ApiResponse.ok(db.query("update questions set stem=coalesce(?,stem),analysis=case when ? then ? else analysis end where id=? returning *", this::row, body.stem() == null ? null : body.stem().trim(), body.analysis() != null, body.analysis(), questionId).getFirst()); }
  @PostMapping("/questions/{questionId}/publish") @Transactional ApiResponse<?> publish(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long questionId) { editableQuestion(user(header), questionId); db.update("update questions set status='active' where id=?", questionId); db.update("update bank_question_links set status='active' where question_id=?", questionId); return getQuestion(header, questionId); }
  @PostMapping("/questions/{questionId}/archive") @Transactional ApiResponse<?> archive(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long questionId) { editableQuestion(user(header), questionId); db.update("update questions set status='archived' where id=?", questionId); db.update("update bank_question_links set status='archived' where question_id=?", questionId); return getQuestion(header, questionId); }
  @PutMapping("/questions/{questionId}/content-blocks") @Transactional ResponseEntity<Void> blocks(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long questionId, @RequestBody Blocks body) { editableQuestion(user(header), questionId); if (body.blocks() == null || body.blocks().size() > 1000) throw valid("Invalid request"); db.update("delete from question_content_blocks where question_id=?", questionId); int sequence = 0; for (var block : body.blocks()) { if (block.partType() == null || !Set.of("text", "formula", "image", "table", "markdown", "html", "chart", "qr_code").contains(block.partType())) throw valid("Invalid request"); db.update("insert into question_content_blocks(question_id,part_type,sequence,payload) values(?,?,?,?::jsonb)", questionId, block.partType(), block.sequence() == null ? ++sequence : block.sequence(), stringify(block.payload())); } return ResponseEntity.noContent().build(); }
  public record Block(String partType, Integer sequence, Object payload) {} public record Blocks(List<Block> blocks) {}
  public record GroupIn(@NotBlank String title, String instructions, String status) {} public record GroupPatch(String title, String instructions) {} public record GroupQuestion(@Positive long questionId, Integer sortOrder) {} public record GroupReorder(@NotEmpty List<@Valid GroupQuestion> items) {}
  @GetMapping("/banks/{bankId}/groups") ApiResponse<?> bankGroups(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long bankId, @RequestParam(required = false) Integer limit, @RequestParam(defaultValue = "") String cursor) { long user = user(header); var bank = bank(user, bankId); boolean edit = Boolean.TRUE.equals(bank.get("is_owner")); int size = limit(limit, 30), offset = PageSupport.cursor(cursor); var rows = db.query("select g.id,g.subject_id,g.title,g.instructions,g.status group_status,l.status,l.sort_order,(select count(*) from group_question_links q where q.group_id=g.id) question_count from bank_group_links l join question_groups g on g.id=l.group_id where l.bank_id=? and (? or (l.status='active' and g.status='active')) order by l.sort_order,g.id limit ? offset ?", this::row, bankId, edit, size + 1, offset); return page(rows, offset, size); }
  @PostMapping("/banks/{bankId}/groups") @Transactional ResponseEntity<ApiResponse<?>> createGroup(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long bankId, @Valid @RequestBody GroupIn body) { long user = user(header); String subject = owner(user, bankId); var group = db.query("insert into question_groups(owner_user_id,subject_id,title,instructions) values(?,?,?,?) returning *", this::row, user, subject, body.title().trim(), body.instructions()).getFirst(); long id = ((Number) group.get("id")).longValue(); db.update("insert into bank_group_links(bank_id,group_id,sort_order) values(?,?,coalesce((select max(sort_order)+1 from bank_group_links where bank_id=?),1))", bankId, id, bankId); if ("active".equals(status(body.status(), "draft"))) { db.update("update question_groups set status='active' where id=?", id); db.update("update bank_group_links set status='active' where bank_id=? and group_id=?", bankId, id); } return ResponseEntity.status(201).body(ApiResponse.ok(group)); }
  @GetMapping("/groups/{groupId}") ApiResponse<?> getGroup(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long groupId) { long user = user(header); var rows = db.query("select g.id,g.subject_id,g.title,case when g.owner_user_id=? then g.instructions else null end instructions,g.status,g.owner_user_id=? can_edit from question_groups g where g.id=?", this::row, user, user, groupId); if (rows.isEmpty()) throw ApiException.of(404, "NOT_FOUND", "Group not found"); var group = rows.getFirst(); boolean edit = Boolean.TRUE.equals(group.get("can_edit")); if (!edit && db.queryForObject("select count(*) from bank_group_links l join question_banks b on b.id=l.bank_id where l.group_id=? and b.deleted_at is null and b.status<>'banned' and l.status='active' and (select status from question_groups where id=l.group_id)='active' and (b.status='public' or exists(select 1 from study_group_banks sb join study_group_members gm on gm.group_id=sb.group_id where sb.bank_id=b.id and gm.user_id=? and gm.status='accepted'))", Integer.class, groupId, user) == 0) throw ApiException.of(404, "NOT_FOUND", "Group not found"); group.put("questions", db.query("select q.id,q.subject_id,q.question_type_id,q.answer_mode,q.choice_variant,q.stem,case when ? then q.analysis else null end analysis,q.status from group_question_links l join questions q on q.id=l.question_id where l.group_id=? and (? or q.status='active') order by l.sort_order", this::row, edit, groupId, edit)); return ApiResponse.ok(group); }
  @PatchMapping("/groups/{groupId}") @Transactional ApiResponse<?> patchGroup(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long groupId, @RequestBody GroupPatch body) { editableGroup(user(header), groupId); if (body.title() == null && body.instructions() == null) throw valid("body must include title or instructions"); if (body.title() != null) nonblank(body.title(), "title"); return ApiResponse.ok(db.query("update question_groups set title=coalesce(?,title),instructions=case when ? then ? else instructions end where id=? returning *", this::row, body.title() == null ? null : body.title().trim(), body.instructions() != null, body.instructions(), groupId).getFirst()); }
  @PostMapping("/groups/{groupId}/questions") @Transactional ResponseEntity<ApiResponse<?>> addGroupQuestion(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long groupId, @Valid @RequestBody GroupQuestion body) { long user = user(header); editableGroup(user, groupId); editableQuestion(user, body.questionId()); var rows = db.query("insert into group_question_links(group_id,question_id,sort_order) values(?,?,coalesce(?,(select coalesce(max(sort_order),0)+1 from group_question_links where group_id=?))) returning *", this::row, groupId, body.questionId(), body.sortOrder(), groupId); return ResponseEntity.status(201).body(ApiResponse.ok(rows.getFirst())); }
  @DeleteMapping("/groups/{groupId}/questions/{questionId}") @Transactional ResponseEntity<Void> removeGroupQuestion(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long groupId, @PathVariable long questionId) { editableGroup(user(header), groupId); if (db.update("delete from group_question_links where group_id=? and question_id=?", groupId, questionId) == 0) throw ApiException.of(404, "NOT_FOUND", "Group question link not found"); return ResponseEntity.noContent().build(); }
  @PostMapping("/banks/{bankId}/clone") @Transactional ApiResponse<?> cloneBank(@RequestHeader(value="Authorization",required=false) String header,@PathVariable long bankId) { long user=user(header); var source=bank(user,bankId); if (!"public".equals(source.get("status"))) throw ApiException.of(404,"BANK_NOT_FOUND","Question bank not found"); var clone=db.query("insert into question_banks(owner_user_id,subject_id,name,description,cloned_from_bank_id,cloned_at) values(?,?,?,?,?,now()) returning *",this::row,user,source.get("subject_id"),String.valueOf(source.get("name"))+"（副本）",source.get("description"),bankId).getFirst(); long target=((Number)clone.get("id")).longValue(); var copies=new HashMap<Long,Long>(); for (var question:db.query("select q.*,l.sort_order bank_sort_order from bank_question_links l join questions q on q.id=l.question_id where l.bank_id=? and l.status='active' and q.status='active' order by l.sort_order",this::row,bankId)){ long sourceId=((Number)question.get("id")).longValue(); long copied=copies.computeIfAbsent(sourceId,ignored->copyQuestion(user,question,sourceId)); db.update("insert into bank_question_links(bank_id,question_id,sort_order,status) values(?,?,?,'active')",target,copied,question.get("bank_sort_order")); } for(var groupSource:db.query("select g.*,l.sort_order bank_sort_order from bank_group_links l join question_groups g on g.id=l.group_id where l.bank_id=? and l.status='active' and g.status='active' order by l.sort_order",this::row,bankId)){ long groupId=db.queryForObject("insert into question_groups(owner_user_id,subject_id,title,instructions) values(?,?,?,?) returning id",Long.class,user,groupSource.get("subject_id"),groupSource.get("title"),groupSource.get("instructions")); db.update("insert into bank_group_links(bank_id,group_id,sort_order,status) values(?,?,?,'active')",target,groupId,groupSource.get("bank_sort_order")); for(var groupQuestion:db.query("select q.*,gl.sort_order group_sort_order from group_question_links gl join questions q on q.id=gl.question_id where gl.group_id=? and q.status='active' order by gl.sort_order",this::row,groupSource.get("id"))){ long sourceId=((Number)groupQuestion.get("id")).longValue(); long copied=copies.computeIfAbsent(sourceId,ignored->copyQuestion(user,groupQuestion,sourceId)); db.update("insert into group_question_links(group_id,question_id,sort_order) values(?,?,?)",groupId,copied,groupQuestion.get("group_sort_order")); } db.update("update question_groups set status='active' where id=?",groupId); } return ApiResponse.ok(clone); }
  private long copyQuestion(long owner,Map<String,Object> source,long sourceId) { long id=db.queryForObject("insert into questions(owner_user_id,subject_id,question_type_id,answer_mode,choice_variant,stem,analysis,source_job_id,cloned_from_question_id) values(?,?,?,?,?,?,?,?,?) returning id",Long.class,owner,source.get("subject_id"),source.get("question_type_id"),source.get("answer_mode"),source.get("choice_variant"),source.get("stem"),source.get("analysis"),null,sourceId); for(var option:db.query("select option_label,sort_order,content from question_options where question_id=? order by sort_order",this::row,sourceId)) db.update("insert into question_options(question_id,option_label,sort_order,content) values(?,?,?,?)",id,option.get("option_label"),option.get("sort_order"),option.get("content")); for(var key:db.query("select answer_mode,version,is_primary,answer_payload,explanation_payload from question_answer_keys where question_id=? order by version",this::row,sourceId)) db.update("insert into question_answer_keys(question_id,answer_mode,version,is_primary,answer_payload,explanation_payload) values(?,?,?,?,?::jsonb,?::jsonb)",id,key.get("answer_mode"),key.get("version"),key.get("is_primary"),key.get("answer_payload"),key.get("explanation_payload")); db.update("insert into question_content_blocks(question_id,part_type,sequence,payload) select ?,part_type,sequence,payload from question_content_blocks where question_id=?",id,sourceId); db.update("insert into question_media_links(question_id,media_id,sort_order) select ?,media_id,sort_order from question_media_links where question_id=?",id,sourceId); db.update("update questions set status='active' where id=?",id); return id; }
  @DeleteMapping("/questions/{questionId}") @Transactional ResponseEntity<Void> deleteQuestion(@RequestHeader(value="Authorization",required=false) String header,@PathVariable long questionId) { editableQuestion(user(header),questionId); db.update("delete from questions where id=?",questionId); return ResponseEntity.noContent().build(); }
  @PostMapping("/questions/{questionId}/options") @Transactional ResponseEntity<ApiResponse<?>> addOption(@RequestHeader(value="Authorization",required=false) String header,@PathVariable long questionId,@Valid @RequestBody OptionIn body) { editableQuestion(user(header),questionId); var rows=db.query("insert into question_options(question_id,option_label,sort_order,content) values(?,?,coalesce(?,(select coalesce(max(sort_order),0)+1 from question_options where question_id=?)),?) returning *",this::row,questionId,body.label().trim(),body.sortOrder(),questionId,body.content().trim()); return ResponseEntity.status(201).body(ApiResponse.ok(rows.getFirst())); }
  @PatchMapping("/questions/{questionId}/options/{optionId}") @Transactional ApiResponse<?> patchOption(@RequestHeader(value="Authorization",required=false) String header,@PathVariable long questionId,@PathVariable long optionId,@RequestBody OptionIn body) { editableQuestion(user(header),questionId); if(body.label()==null&&body.content()==null&&body.sortOrder()==null) throw valid("body must include a field to update"); var rows=db.query("update question_options set option_label=coalesce(?,option_label),content=coalesce(?,content),sort_order=coalesce(?,sort_order) where id=? and question_id=? returning *",this::row,body.label(),body.content(),body.sortOrder(),optionId,questionId); if(rows.isEmpty()) throw ApiException.of(404,"NOT_FOUND","Option not found"); return ApiResponse.ok(rows.getFirst()); }
  @DeleteMapping("/questions/{questionId}/options/{optionId}") @Transactional ResponseEntity<Void> deleteOption(@RequestHeader(value="Authorization",required=false) String header,@PathVariable long questionId,@PathVariable long optionId) { editableQuestion(user(header),questionId); if(db.update("delete from question_options where id=? and question_id=?",optionId,questionId)==0) throw ApiException.of(404,"NOT_FOUND","Option not found"); return ResponseEntity.noContent().build(); }
  @PutMapping("/questions/{questionId}/answer-key") @Transactional ApiResponse<?> key(@RequestHeader(value="Authorization",required=false) String header,@PathVariable long questionId,@Valid @RequestBody KeyIn body) { editableQuestion(user(header),questionId); String mode=db.queryForObject("select answer_mode from questions where id=?",String.class,questionId); if(!mode.equals(body.answerMode())) throw valid("answerMode must match the question answer mode"); db.update("update question_answer_keys set is_primary=false where question_id=? and is_primary",questionId); var rows=db.query("insert into question_answer_keys(question_id,answer_mode,version,is_primary,answer_payload,explanation_payload) values(?,?,(select coalesce(max(version),0)+1 from question_answer_keys where question_id=?),true,?::jsonb,?::jsonb) returning *",this::row,questionId,mode,questionId,stringify(keyPayload(mode,body.answerPayload(),selected(body.answerPayload()))),stringify(body.explanationPayload())); return ApiResponse.ok(rows.getFirst()); }
  @DeleteMapping("/groups/{groupId}") @Transactional ResponseEntity<Void> deleteGroup(@RequestHeader(value="Authorization",required=false) String header,@PathVariable long groupId) { editableGroup(user(header),groupId); db.update("delete from question_groups where id=?",groupId); return ResponseEntity.noContent().build(); }
  @PostMapping("/groups/{groupId}/publish") @Transactional ApiResponse<?> publishGroup(@RequestHeader(value="Authorization",required=false) String header,@PathVariable long groupId) { editableGroup(user(header),groupId); db.update("update question_groups set status='active' where id=?",groupId); db.update("update bank_group_links set status='active' where group_id=?",groupId); return getGroup(header,groupId); }
  @PostMapping("/groups/{groupId}/archive") @Transactional ApiResponse<?> archiveGroup(@RequestHeader(value="Authorization",required=false) String header,@PathVariable long groupId) { editableGroup(user(header),groupId); db.update("update question_groups set status='archived' where id=?",groupId); db.update("update bank_group_links set status='archived' where group_id=?",groupId); return getGroup(header,groupId); }
  @PatchMapping("/groups/{groupId}/questions/reorder") @Transactional ResponseEntity<Void> reorderGroup(@RequestHeader(value="Authorization",required=false) String header,@PathVariable long groupId,@Valid @RequestBody GroupReorder body) { editableGroup(user(header),groupId); if(db.queryForObject("select count(*) from group_question_links where group_id=?",Integer.class,groupId)!=body.items().size()) throw valid("items must include every group question exactly once"); db.update("update group_question_links set sort_order=sort_order+1000000 where group_id=?",groupId); for(var item:body.items()) if(db.update("update group_question_links set sort_order=? where group_id=? and question_id=?",item.sortOrder(),groupId,item.questionId())!=1) throw valid("items contains an unknown question"); return ResponseEntity.noContent().build(); }

}
