package com.practiq.web;
import com.practiq.auth.AuthService;import com.practiq.common.*;import com.practiq.service.ImportService;import jakarta.validation.constraints.*;import java.io.IOException;import java.util.*;import java.util.concurrent.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;
@RestController @RequestMapping("/api/v1/import-jobs") public class ImportController {final AuthService auth;final ImportService imports;static final Set<String> STREAMS=ConcurrentHashMap.newKeySet();static final ScheduledExecutorService EXEC=Executors.newScheduledThreadPool(2);ImportController(AuthService a,ImportService i){auth=a;imports=i;}long u(String h){return auth.require(h);}Map<String,Object> me(long u){return auth.user(u);}void id(long x){if(x<1)throw ApiException.of(422,"VALIDATION_ERROR","Invalid request");}record Create(@NotNull @Positive Long bankId,@Size(max=255)String fileName,String sourceType,Map<String,Object> requestPayload){}record Parse(Boolean persistQuestions){}
 @GetMapping @SuppressWarnings("unchecked") ApiResponse<?> list(@RequestHeader(value="Authorization",required=false)String h,@RequestParam(defaultValue="")String status,@RequestParam(defaultValue="")String cursor,@RequestParam(required=false)Integer limit){long u=u(h);var x=imports.list(u,status,cursor,limit);return ApiResponse.ok(x.get("items"),(Map<String,Object>)x.get("meta"));}
 @PostMapping ResponseEntity<ApiResponse<?>>create(@RequestHeader(value="Authorization",required=false)String h,@org.springframework.web.bind.annotation.RequestBody @jakarta.validation.Valid Create b){long u=u(h);return ResponseEntity.status(201).body(ApiResponse.ok(imports.create(u,me(u),b.bankId(),b.fileName(),b.sourceType(),b.requestPayload())));}
 @GetMapping("/{id}")ApiResponse<?>get(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id){long u=u(h);id(id);return ApiResponse.ok(imports.job(u,id));}
 @PostMapping(value="/{id}/file",consumes=MediaType.MULTIPART_FORM_DATA_VALUE)ResponseEntity<ApiResponse<?>>file(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id,@RequestPart(value="file",required=false)MultipartFile f){long u=u(h);id(id);return ResponseEntity.status(201).body(ApiResponse.ok(imports.upload(u,me(u),id,f)));}
 @PostMapping("/{id}/{action:parse|retry|cancel}")ApiResponse<?>action(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id,@PathVariable String action,@RequestBody(required=false)Parse b){long u=u(h);id(id);return ApiResponse.ok(imports.action(u,me(u),id,action,b==null?null:b.persistQuestions()));}
 @GetMapping("/{id}/{kind:events|outputs}")ApiResponse<?>children(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id,@PathVariable String kind){long u=u(h);id(id);return ApiResponse.ok(imports.children(u,id,kind));}
 @GetMapping(value="/{id}/stream",produces=MediaType.TEXT_EVENT_STREAM_VALUE)SseEmitter stream(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id,@RequestHeader(value="Last-Event-ID",required=false)String last){long u=u(h);id(id);imports.job(u,id);long after;try{after=last==null||last.isBlank()?0:Long.parseLong(last);}catch(NumberFormatException e){throw ApiException.of(400,"INVALID_LAST_EVENT_ID","Last-Event-ID must be a non-negative integer");}if(after<0||after>0&&!imports.event(id,after))throw ApiException.of(400,"INVALID_LAST_EVENT_ID","Last-Event-ID does not belong to this import job");String key=u+":"+id;if(STREAMS.size()>=100||!STREAMS.add(key))throw ApiException.of(429,"IMPORT_STREAM_LIMIT","Too many active import event streams");SseEmitter out=new SseEmitter(60_000L);final long[] cursor={after};ScheduledFuture<?> task=EXEC.scheduleAtFixedRate(()->{try{for(var e:imports.eventsAfter(id,cursor[0])){cursor[0]=((Number)e.get("id")).longValue();out.send(SseEmitter.event().id(String.valueOf(cursor[0])).data(e));if(Set.of("completed","failed","cancelled").contains(String.valueOf(e.get("status"))))out.complete();}}catch(IOException e){out.completeWithError(e);}catch(Exception e){out.completeWithError(e);}},0,1,TimeUnit.SECONDS);ScheduledFuture<?> heart=EXEC.scheduleAtFixedRate(()->{try{out.send(SseEmitter.event().comment("heartbeat"));}catch(IOException e){out.complete();}},15,15,TimeUnit.SECONDS);Runnable done=()->{task.cancel(false);heart.cancel(false);STREAMS.remove(key);};out.onCompletion(done);out.onTimeout(done);out.onError(e->done.run());return out;}
}
