package com.practiq.web;
import com.practiq.auth.AuthService; import com.practiq.common.*; import com.practiq.service.MediaService; import jakarta.validation.constraints.*; import java.util.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile;
@RestController @RequestMapping("/api/v1") public class MediaController {final AuthService auth;final MediaService media;MediaController(AuthService a,MediaService m){auth=a;media=m;}long u(String h){return auth.require(h);} Map<String,Object> user(long id){return auth.user(id);}void pos(long x){if(x<1)throw ApiException.of(422,"VALIDATION_ERROR","Invalid request");}record Link(@Positive Long mediaId,@NotBlank @Size(max=64)String mediaKind,@Min(1)@Max(32767)Integer sortOrder){}
 @PostMapping(value="/media",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) ResponseEntity<ApiResponse<?>> upload(@RequestHeader(value="Authorization",required=false)String h,@RequestPart(value="file",required=false)MultipartFile file){return ResponseEntity.status(201).body(ApiResponse.ok(media.upload(u(h),file)));}
 @PostMapping(value="/media",consumes="!multipart/form-data") ApiResponse<?> badUpload(@RequestHeader(value="Authorization",required=false)String h){u(h);throw ApiException.of(400,"INVALID_MULTIPART","A multipart file upload is required");}
 @GetMapping("/media/{id}")ApiResponse<?> get(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id){pos(id);long u=u(h);return ApiResponse.ok(media.asset(u,(String)user(u).get("role"),id));}
 @GetMapping("/media/{id}/content")ResponseEntity<byte[]> content(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id){pos(id);long u=u(h);var a=media.asset(u,(String)user(u).get("role"),id);return ResponseEntity.ok().cacheControl(CacheControl.noStore()).contentType(MediaType.parseMediaType((String)a.get("mime_type"))).header(HttpHeaders.CONTENT_DISPOSITION,"inline; filename=\""+String.valueOf(a.get("original_name")).replace("\"","")+"\"").body(media.content(u,(String)user(u).get("role"),id));}
 @DeleteMapping("/media/{id}")ResponseEntity<Void> delete(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id){pos(id);long u=u(h);media.delete(u,(String)user(u).get("role"),id);return ResponseEntity.noContent().build();}
 @PostMapping("/questions/{id}/media-links")ResponseEntity<ApiResponse<?>> linkQ(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id,@jakarta.validation.Valid@RequestBody Link b){return link(h,"question",id,b);}@PostMapping("/groups/{id}/media-links")ResponseEntity<ApiResponse<?>>linkG(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id,@jakarta.validation.Valid@RequestBody Link b){return link(h,"group",id,b);}@PostMapping("/options/{id}/media-links")ResponseEntity<ApiResponse<?>>linkO(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id,@jakarta.validation.Valid@RequestBody Link b){return link(h,"option",id,b);}private ResponseEntity<ApiResponse<?>>link(String h,String t,long id,Link b){pos(id);return ResponseEntity.status(201).body(ApiResponse.ok(media.link(u(h),t,id,b.mediaId(),b.mediaKind(),b.sortOrder())));}
 @DeleteMapping("/questions/{id}/media-links/{media}")ResponseEntity<Void>unQ(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id,@PathVariable("media") long mediaId){return unlink(h,"question",id,mediaId);}@DeleteMapping("/groups/{id}/media-links/{media}")ResponseEntity<Void>unG(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id,@PathVariable("media") long mediaId){return unlink(h,"group",id,mediaId);}@DeleteMapping("/options/{id}/media-links/{media}")ResponseEntity<Void>unO(@RequestHeader(value="Authorization",required=false)String h,@PathVariable long id,@PathVariable("media") long mediaId){return unlink(h,"option",id,mediaId);}private ResponseEntity<Void>unlink(String h,String t,long id,long m){pos(id);pos(m);media.unlink(u(h),t,id,m);return ResponseEntity.noContent().build();}
}
