package com.practiq.web;

import com.practiq.auth.AuthService;
import com.practiq.common.ApiException;
import com.practiq.common.ApiResponse;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.sql.ResultSet;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/v1")
public class StudyGroupController {
  private static final SecureRandom RANDOM = new SecureRandom();
  private final JdbcTemplate db; private final AuthService auth;
  StudyGroupController(JdbcTemplate db, AuthService auth) { this.db = db; this.auth = auth; }
  record GroupIn(@NotBlank @Size(max = 100) String name, @Size(max = 1000) String description) {}
  record GroupPatch(@Size(max = 100) String name, @Size(max = 1000) String description) {}
  private long user(String header) { return auth.require(header); }
  private Map<String, Object> row(ResultSet result, int ignored) throws java.sql.SQLException { var value = new LinkedHashMap<String, Object>(); for (int index = 1; index <= result.getMetaData().getColumnCount(); index++) { Object item = result.getObject(index); value.put(result.getMetaData().getColumnLabel(index), item instanceof OffsetDateTime time ? time.toString() : item); } return value; }
  private static ApiException invalid(String message) { return ApiException.of(422, "VALIDATION_ERROR", message); }
  private void proOwner(long user) { if (!Boolean.TRUE.equals(auth.user(user).get("paidPro"))) throw ApiException.of(403, "PAID_PRO_REQUIRED", "A paid Pro membership is required to own a study group"); }
  private void owner(long user, long group) { Integer count = db.queryForObject("select count(*) from study_groups where id=? and owner_user_id=?", Integer.class, group, user); if (count == null || count == 0) throw ApiException.of(403, "GROUP_OWNER_REQUIRED", "Study group owner access required"); }
  private void member(long user, long group) { Integer count = db.queryForObject("select count(*) from study_group_members where group_id=? and user_id=? and status='accepted'", Integer.class, group, user); if (count == null || count == 0) throw ApiException.of(404, "NOT_FOUND", "Study group not found"); }
  private Map<String, Object> group(long user, long id) { var rows = db.query("select g.id,g.owner_user_id,g.name,g.description,g.created_at,g.updated_at,case when g.owner_user_id=? then 'owner' else 'member' end role,(select count(*) from study_group_members m where m.group_id=g.id and m.status='accepted') member_count,(select count(*) from study_group_banks b where b.group_id=g.id) bank_count from study_groups g join study_group_members mine on mine.group_id=g.id and mine.user_id=? and mine.status='accepted' where g.id=?", this::row, user, user, id); if (rows.isEmpty()) throw ApiException.of(404, "NOT_FOUND", "Study group not found"); return rows.getFirst(); }

  @GetMapping("/study-groups") ApiResponse<?> groups(@RequestHeader(value = "Authorization", required = false) String header) { long user = user(header); return ApiResponse.ok(db.query("select g.id,g.owner_user_id,g.name,g.description,g.created_at,g.updated_at,case when g.owner_user_id=? then 'owner' else 'member' end role,(select count(*) from study_group_members all_members where all_members.group_id=g.id and all_members.status='accepted') member_count,(select count(*) from study_group_banks b where b.group_id=g.id) bank_count from study_groups g join study_group_members mine on mine.group_id=g.id and mine.user_id=? and mine.status='accepted' order by g.updated_at desc,g.id desc", this::row, user, user)); }

  @PostMapping("/study-groups") @Transactional ResponseEntity<ApiResponse<?>> create(@RequestHeader(value = "Authorization", required = false) String header, @Valid @RequestBody GroupIn body) { long user = user(header); proOwner(user); var value = db.query("insert into study_groups(owner_user_id,name,description) values(?,?,?) returning *", this::row, user, body.name().trim(), body.description()).getFirst(); db.update("insert into study_group_members(group_id,user_id,status) values(?,?,'accepted')", value.get("id"), user); return ResponseEntity.status(201).body(ApiResponse.ok(group(user, ((Number) value.get("id")).longValue()))); }
  @GetMapping("/study-groups/{id}") ApiResponse<?> get(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long id) { return ApiResponse.ok(group(user(header), id)); }
  @PatchMapping("/study-groups/{id}") @Transactional ApiResponse<?> update(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long id, @RequestBody GroupPatch body) { long user = user(header); owner(user, id); if (body.name() == null && body.description() == null) throw invalid("body must include name or description"); if (body.name() != null && body.name().trim().isEmpty()) throw invalid("name must not be blank"); db.update("update study_groups set name=coalesce(?,name),description=case when ? then ? else description end where id=?", body.name() == null ? null : body.name().trim(), body.description() != null, body.description(), id); return ApiResponse.ok(group(user, id)); }
  @DeleteMapping("/study-groups/{id}") @Transactional ResponseEntity<Void> remove(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long id) { long user = user(header); owner(user, id); db.update("delete from study_groups where id=?", id); return ResponseEntity.noContent().build(); }

  @GetMapping("/study-groups/{id}/members") ApiResponse<?> members(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long id) { long user = user(header); member(user, id); return ApiResponse.ok(db.query("select m.user_id,u.display_name,u.avatar_url,m.status,m.joined_at,m.left_at,case when g.owner_user_id=m.user_id then 'owner' else 'member' end role from study_group_members m join users u on u.id=m.user_id join study_groups g on g.id=m.group_id where m.group_id=? and m.status='accepted' order by case when g.owner_user_id=m.user_id then 0 else 1 end,m.joined_at,m.user_id", this::row, id)); }
  @DeleteMapping("/study-groups/{id}/members/{memberId}") @Transactional ResponseEntity<Void> removeMember(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long id, @PathVariable long memberId) { long user = user(header); owner(user, id); if (user == memberId) throw ApiException.of(409, "OWNER_CANNOT_LEAVE", "Delete the study group instead"); if (db.update("update study_group_members set status='removed',left_at=now() where group_id=? and user_id=? and status='accepted'", id, memberId) == 0) throw ApiException.of(404, "NOT_FOUND", "Study group member not found"); return ResponseEntity.noContent().build(); }
  @PostMapping("/study-groups/{id}/leave") @Transactional ResponseEntity<Void> leave(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long id) { long user = user(header); if (db.queryForObject("select count(*) from study_groups where id=? and owner_user_id=?", Integer.class, id, user) > 0) throw ApiException.of(409, "OWNER_CANNOT_LEAVE", "Delete the study group instead"); if (db.update("update study_group_members set status='left',left_at=now() where group_id=? and user_id=? and status='accepted'", id, user) == 0) throw ApiException.of(404, "NOT_FOUND", "Study group not found"); return ResponseEntity.noContent().build(); }

  @PostMapping("/study-groups/{id}/invitations") @Transactional ResponseEntity<ApiResponse<?>> invite(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long id) { long user = user(header); owner(user, id); String token = token(); OffsetDateTime expires = OffsetDateTime.now(ZoneOffset.UTC).plusDays(7); long invitation = db.queryForObject("insert into study_group_invitations(group_id,created_by,token_hash,expires_at) values(?,?,?,?) returning id", Long.class, id, user, hash(token), expires); return ResponseEntity.status(201).body(ApiResponse.ok(Map.of("id", invitation, "token", token, "expiresAt", expires.toString()))); }
  @DeleteMapping("/study-groups/{id}/invitations/{invitationId}") @Transactional ResponseEntity<Void> revoke(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long id, @PathVariable long invitationId) { long user = user(header); owner(user, id); if (db.update("update study_group_invitations set status='revoked' where id=? and group_id=? and status='pending'", invitationId, id) == 0) throw ApiException.of(409, "INVITATION_NOT_PENDING", "Invitation is no longer pending"); return ResponseEntity.noContent().build(); }
  @GetMapping("/study-group-invitations/{token}") ApiResponse<?> invitation(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable String token) { long user = user(header); var rows = invitation(token, false); long group = ((Number) rows.getFirst().get("group_id")).longValue(); var visible = db.query("select id,owner_user_id,name,description,created_at,updated_at from study_groups where id=?", this::row, group); if (visible.isEmpty()) throw ApiException.of(404, "INVITATION_INVALID", "Invitation is invalid or expired"); var value = visible.getFirst(); value.put("role", db.queryForObject("select case when exists(select 1 from study_group_members where group_id=? and user_id=? and status='accepted') then 'member' else null end", String.class, group, user)); return ApiResponse.ok(value); }
  @PostMapping("/study-group-invitations/{token}/{action:accept|reject}") @Transactional ApiResponse<?> respond(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable String token, @PathVariable String action) { long user = user(header); var invitation = invitation(token, true).getFirst(); long invitationId = ((Number) invitation.get("id")).longValue(), group = ((Number) invitation.get("group_id")).longValue(); Long owner = db.queryForObject("select owner_user_id from study_groups where id=?", Long.class, group); if (owner != null && owner == user) throw ApiException.of(409, "ALREADY_GROUP_OWNER", "The study group owner cannot accept an invitation"); if ("reject".equals(action)) { db.update("update study_group_invitations set status='rejected' where id=? and status='pending'", invitationId); return ApiResponse.ok(Map.of("id", group, "status", "rejected")); } db.update("insert into study_group_members(group_id,user_id,status,joined_at,left_at) values(?,?,'accepted',now(),null) on conflict(group_id,user_id) do update set status='accepted',joined_at=now(),left_at=null", group, user); if (db.update("update study_group_invitations set status='accepted',accepted_by=?,used_at=now() where id=? and status='pending'", user, invitationId) != 1) throw ApiException.of(409, "INVITATION_ALREADY_USED", "Invitation has already been used"); return ApiResponse.ok(group(user, group)); }

  @PostMapping("/study-groups/{id}/banks/{bankId}") @Transactional ResponseEntity<Void> linkBank(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long id, @PathVariable long bankId) { long user = user(header); owner(user, id); if (db.queryForObject("select count(*) from question_banks where id=? and owner_user_id=? and deleted_at is null", Integer.class, bankId, user) == 0) throw ApiException.of(403, "FORBIDDEN", "Only an owned live bank can be linked"); db.update("insert into study_group_banks(group_id,bank_id,linked_by) values(?,?,?) on conflict do nothing", id, bankId, user); return ResponseEntity.noContent().build(); }
  @DeleteMapping("/study-groups/{id}/banks/{bankId}") @Transactional ResponseEntity<Void> unlinkBank(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long id, @PathVariable long bankId) { long user = user(header); owner(user, id); db.update("delete from study_group_banks where group_id=? and bank_id=?", id, bankId); return ResponseEntity.noContent().build(); }
  @GetMapping("/study-groups/{id}/members/{memberId}/analytics") ApiResponse<?> memberAnalytics(@RequestHeader(value = "Authorization", required = false) String header, @PathVariable long id, @PathVariable long memberId) { long user = user(header); member(user, id); if (user != memberId) owner(user, id); if (db.queryForObject("select count(*) from study_group_members where group_id=? and user_id=? and status='accepted'", Integer.class, id, memberId) == 0) throw ApiException.of(404, "NOT_FOUND", "Study group member not found"); return ApiResponse.ok(db.query("select count(a.id) attempts,coalesce(sum(case when a.is_correct then 1 else 0 end),0) correct,coalesce(sum(case when a.is_correct=false then 1 else 0 end),0) wrong,case when count(a.id)=0 then 0 else round(100.0*sum(case when a.is_correct then 1 else 0 end)/count(a.id),2) end accuracy from study_group_banks gb left join practice_answers a on a.bank_id=gb.bank_id and a.user_id=? where gb.group_id=?", this::row, memberId, id).getFirst()); }

  private List<Map<String, Object>> invitation(String raw, boolean lock) { if (raw == null || raw.length() < 20 || raw.length() > 200) throw ApiException.of(404, "INVITATION_INVALID", "Invitation is invalid or expired"); var rows = db.query("select id,group_id,expires_at from study_group_invitations where token_hash=? and status='pending' and expires_at>now()" + (lock ? " for update" : ""), this::row, hash(raw)); if (rows.isEmpty()) throw ApiException.of(404, "INVITATION_INVALID", "Invitation is invalid, expired, revoked, or already used"); return rows; }
  private static String token() { byte[] bytes = new byte[32]; RANDOM.nextBytes(bytes); return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes); }
  private static byte[] hash(String value) { try { return MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8)); } catch (Exception error) { throw new IllegalStateException(error); } }
}
