"""Export AI wire schemas; --check verifies the checked-in contract has not drifted."""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / 'server/src'))
from practiq_ai.contracts import (  # noqa: E402
    DocumentParseResult, DocumentProcessing, DocumentTaskReview, DocumentTaskSummary,
)

path = Path(__file__).resolve().parents[1] / 'src-tauri/contracts.json'
content = json.dumps({name: model.model_json_schema() for name, model in {
    'result': DocumentParseResult, 'processing': DocumentProcessing,
    'taskSummary': DocumentTaskSummary, 'taskReview': DocumentTaskReview,
}.items()}, ensure_ascii=False, indent=2) + '\n'
if '--check' in sys.argv:
    if path.read_text(encoding='utf-8') != content:
        raise SystemExit('AI contract changed: run app/scripts/export-contracts.py and review the desktop importer.')
else:
    path.write_text(content, encoding='utf-8')

# Derive desktop types from the same schema; defaults are optional input fields.
def ts_type(node):
    if '$ref' in node:
        return node['$ref'].rsplit('/', 1)[-1]
    if 'const' in node:
        return json.dumps(node['const'], ensure_ascii=False)
    if 'enum' in node:
        return ' | '.join(json.dumps(v, ensure_ascii=False) for v in node['enum'])
    for union in ('anyOf', 'oneOf'):
        if union in node:
            return ' | '.join(ts_type(v) for v in node[union])
    kind = node.get('type')
    if kind == 'array':
        return '(' + ts_type(node['items']) + ')[]'
    if kind == 'object':
        if 'properties' not in node:
            extra = node.get('additionalProperties')
            return 'Record<string, ' + (ts_type(extra) if isinstance(extra, dict) else 'unknown') + '>'
        required = set(node.get('required', []))
        return '{ ' + '; '.join(json.dumps(k) + ('' if k in required else '?') + ': ' + ts_type(v) for k, v in node['properties'].items()) + ' }'
    if kind in ('string', 'boolean', 'null'):
        return kind
    if kind in ('number', 'integer'):
        return 'number'
    if not node or set(node) <= {'title', 'description', 'default'}:
        return 'unknown'
    raise ValueError(f'Unsupported schema type: {node}')

schema = DocumentParseResult.model_json_schema()
definitions = {**DocumentTaskReview.model_json_schema()['$defs'], **schema['$defs']}
# These fields are always present on normalized UI questions, as before v2.
normalized = {'stem', 'answerMode', 'questionTypeId', 'options', 'items', 'answerPayload', 'contentBlocks', 'confidence', 'needsReview', 'missingFields'}
definitions['ParsedQuestion']['required'] = sorted(normalized)
answer_fields = {}
for name, value in definitions.items():
    if name.endswith('AnswerPayload') or name == 'ShortAnswerPayload':
        answer_fields.update(value.get('properties', {}))
lines = ['// Generated by app/scripts/export-contracts.py. Do not edit.']
for name, node in definitions.items():
    lines.append('export type ' + name + ' = ' + ts_type(node) + ';')
lines.append('export type Answer = ' + ts_type({'type': 'object', 'properties': answer_fields}) + ';')
lines.append('export type Question = Omit<ParsedQuestion, "answerPayload"> & { answerPayload: Answer | null };')
lines.append('export type DocumentResult = ' + ts_type(schema) + ';')
generated = '\n'.join(lines) + '\n'
types_path = path.parents[1] / 'src' / 'contracts.generated.ts'
if '--check' in sys.argv:
    if types_path.read_text(encoding='utf-8') != generated:
        raise SystemExit('Desktop types changed: run app/scripts/export-contracts.py')
else:
    types_path.write_text(generated, encoding='utf-8')
