package com.practiq.service;

import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.node.ArrayNode;
import tools.jackson.databind.node.ObjectNode;
import com.practiq.common.ApiException;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.ResultSet;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class AiTaskService {
  public record Claim(long id, long userId, String kind, JsonNode requestPayload, OffsetDateTime deadlineAt) {}
  private record ReportTotals(long attempts, long correct, OffsetDateTime started, OffsetDateTime ended, Long[] answerIds, String sources) {}
  private final JdbcTemplate db; private final ObjectMapper json; private final BigDecimal inputPrice; private final BigDecimal outputPrice; private final BigDecimal answerEstimate; private final BigDecimal reportEstimate;
  AiTaskService(JdbcTemplate db, ObjectMapper json, @Value("${practiq.ai.input-price-per-1k}") BigDecimal inputPrice, @Value("${practiq.ai.output-price-per-1k}") BigDecimal outputPrice, @Value("${practiq.ai.answer-estimated-credits}") BigDecimal answerEstimate, @Value("${practiq.ai.report-estimated-credits}") BigDecimal reportEstimate) {
    this.db = db; this.json = json; this.inputPrice = nonnegative(inputPrice, "AI_INPUT_PRICE_PER_1K"); this.outputPrice = nonnegative(outputPrice, "AI_OUTPUT_PRICE_PER_1K"); this.answerEstimate = positive(answerEstimate, "AI_ANSWER_ESTIMATED_CREDITS"); this.reportEstimate = positive(reportEstimate, "AI_REPORT_ESTIMATED_CREDITS");
  }

  @Transactional public Map<String, Object> createAnswer(long user, long question) {
    new ContentAccess(db).editQuestion(user, question);
    var rows = db.query("select q.stem,q.answer_mode,q.analysis from questions q where q.id=? and q.owner_user_id=?", this::row, question, user); if (rows.isEmpty()) throw ApiException.of(403, "FORBIDDEN", "Question owner access required"); var source = rows.getFirst(); ObjectNode request = json.createObjectNode().put("stem", String.valueOf(source.get("stem"))).put("answerMode", String.valueOf(source.get("answer_mode"))); if (source.get("analysis") != null) request.put("analysis", String.valueOf(source.get("analysis"))); ArrayNode options = request.putArray("options"); for (var option : db.query("select option_label,content from question_options where question_id=? order by sort_order", this::row, question)) options.addObject().put("label", String.valueOf(option.get("option_label"))).put("content", String.valueOf(option.get("content")));
    var task = create(user, "answer_generation", request, answerEstimate, question);
    return publicTask(task);
  }

  @Transactional public Map<String, Object> createReport(long user) {
    var totals = db.query("select count(*) attempts,coalesce(sum(case when is_correct then 1 else 0 end),0) correct,min(answered_at) started,max(answered_at) ended,array_agg(a.id) answer_ids,jsonb_agg(distinct jsonb_build_object('bank_id',a.bank_id,'question_id',a.question_id)) sources from practice_answers a where user_id=? and " + ContentAccess.answerVisible("a", user), (result, ignored) -> new ReportTotals(result.getLong("attempts"), result.getLong("correct"), result.getObject("started", OffsetDateTime.class), result.getObject("ended", OffsetDateTime.class), result.getArray("answer_ids") == null ? new Long[0] : (Long[]) result.getArray("answer_ids").getArray(), result.getString("sources")), user).getFirst(); long attempts = totals.attempts(), correct = totals.correct(); if (attempts == 0) throw ApiException.of(409, "INSUFFICIENT_LEARNING_DATA", "Complete at least one practice answer before generating a report"); OffsetDateTime started = totals.started(), ended = totals.ended(); if (!ended.isAfter(started)) ended = started.plusSeconds(1);
    ObjectNode request = json.createObjectNode().put("scope", "individual"); ObjectNode stats = request.putObject("stats").put("attemptCount", attempts).put("correctCount", correct).put("accuracy", (double) correct / attempts).put("startedAt", started.toString()).put("endedAt", ended.toString()); ArrayNode mastery = stats.putArray("mastery"); for (var item : db.query("select q.question_type_id label,count(*) attempts,coalesce(sum(case when a.is_correct then 1 else 0 end),0) correct from practice_answers a join questions q on q.id=a.question_id where a.id=any(?::bigint[]) group by q.question_type_id order by count(*) desc", this::row, (Object) totals.answerIds())) mastery.addObject().put("label", String.valueOf(item.get("label"))).put("attempts", ((Number) item.get("attempts")).longValue()).put("correct", ((Number) item.get("correct")).longValue()); stats.putArray("accuracyTrend").addObject().put("label", "当前").put("accuracy", (double) correct / attempts); ArrayNode weak = stats.putArray("weakKnowledgePoints"); for (String label : db.queryForList("select q.question_type_id from practice_answers a join questions q on q.id=a.question_id where a.id=any(?::bigint[]) and a.is_correct=false group by q.question_type_id order by count(*) desc limit 20", String.class, (Object) totals.answerIds())) if (!contains(weak, label)) weak.add(label); if (weak.isEmpty()) weak.add("继续积累练习数据");
    var task = create(user, "learning_report", request, reportEstimate, null);
    db.update("insert into ai_report_sources(task_id,bank_id,question_id) select ?,src.bank_id,src.question_id from jsonb_to_recordset(?::jsonb) as src(bank_id bigint,question_id bigint)", task.get("id"), totals.sources());
    return publicTask(task);
  }

  public Map<String, Object> get(long user, long id) { var rows = db.query("select * from ai_tasks where id=? and user_id=?", this::row, id, user); if (rows.isEmpty()) throw ApiException.of(404, "NOT_FOUND", "AI task not found"); new ContentAccess(db).task(user, id); return publicTask(rows.getFirst()); }

  @Transactional public Map<String, Object> cancel(long user, long id) {
    var rows = db.query("select * from ai_tasks where id=? and user_id=? for update", this::row, id, user); if (rows.isEmpty()) throw ApiException.of(404, "NOT_FOUND", "AI task not found"); var task = rows.getFirst(); new ContentAccess(db).task(user, id); if (!List.of("queued", "running").contains(String.valueOf(task.get("status")))) throw ApiException.of(409, "AI_TASK_TERMINAL", "AI task is already terminal"); if ("import".equals(task.get("kind"))) throw ApiException.of(409, "USE_IMPORT_CANCEL", "Cancel import tasks through the import endpoint"); refund(task, "release", "cancel"); db.update("update ai_tasks set status='cancelled',finished_at=now(),worker_id=null,worker_lease_until=null where id=?", id); return get(user, id);
  }

  @Transactional public Claim claim(UUID worker) {
    var ids = db.query("select t.id from ai_tasks t left join question_import_jobs j on j.ai_task_id=t.id where t.status='queued' and t.deadline_at>now() and (t.kind<>'import' or j.status='processing') order by t.created_at,t.id for update of t skip locked limit 1", (result, ignored) -> result.getLong(1)); if (ids.isEmpty()) return null; long id = ids.getFirst(); var rows = db.query("update ai_tasks set status='running',started_at=now(),worker_id=?,worker_lease_until=now()+interval '185 seconds' where id=? and status='queued' returning id,user_id,kind,request_payload,deadline_at", this::row, worker, id); if (rows.isEmpty()) return null; var value = rows.getFirst(); return new Claim(id, ((Number) value.get("user_id")).longValue(), String.valueOf(value.get("kind")), parse(value.get("request_payload")), (OffsetDateTime) value.get("deadline_at"));
  }

  @Transactional public void recordUsage(long task, List<InternalAiClient.Usage> usage) {
    for (var call : usage) db.update("insert into ai_task_calls(task_id,call_key,model_id,input_tokens,output_tokens,input_price_per_1k,output_price_per_1k,call_kind) values(?,?,?,?,?,?,?,?) on conflict(task_id,call_key) do nothing", task, call.callKey(), call.modelId(), call.inputTokens(), call.outputTokens(), inputPrice, outputPrice, call.callKind());
  }

  @Transactional public void succeed(long task, JsonNode result) { var value = lockedRunning(task); settle(value); if (db.update("update ai_tasks set status='succeeded',result=?::jsonb,finished_at=now(),worker_id=null,worker_lease_until=null where id=? and status='running'", write(result), task) != 1) throw ApiException.of(409, "AI_TASK_STATE_CHANGED", "AI task state changed"); }

  @Transactional public void completeImport(long task, JsonNode result, boolean sourceDeleted) {
    var value = lockedRunning(task); var jobs = db.query("select * from question_import_jobs where ai_task_id=? and status='processing' for update", this::row, task); if (jobs.isEmpty()) throw ApiException.of(409, "IMPORT_STATE_CHANGED", "Import job state changed"); var job = jobs.getFirst(); long jobId = ((Number) job.get("id")).longValue(), owner = ((Number) job.get("created_by")).longValue(), bank = ((Number) job.get("bank_id")).longValue(); String subject = db.queryForObject("select subject_id from question_banks where id=?", String.class, bank); int order = db.queryForObject("select coalesce(max(sort_order),0) from bank_question_links where bank_id=?", Integer.class, bank);
    JsonNode questions = result.path("questions"); if (!questions.isArray() || questions.isEmpty()) throw ApiException.of(502, "AI_EMPTY_RESULT", "AI document parsing returned no questions");
    for (JsonNode question : questions) { String mode = question.path("answerMode").asText(); String type = resolveType(subject, question.path("questionTypeId").asText(), mode); String variant = "choice".equals(mode) ? (correctLabels(question).size() == 1 ? "single" : "multiple") : null; long questionId = db.queryForObject("insert into questions(owner_user_id,subject_id,question_type_id,answer_mode,choice_variant,stem,analysis,source_job_id) values(?,?,?,?,?,?,?,?) returning id", Long.class, owner, subject, type, mode, variant, question.path("stem").asText(), nullable(question, "analysis"), jobId); int optionOrder = 0; for (JsonNode option : question.path("options")) db.update("insert into question_options(question_id,option_label,sort_order,content) values(?,?,?,?)", questionId, option.path("label").asText(), ++optionOrder, option.path("content").asText()); JsonNode answer = normalizeAnswer(mode, question.path("answerPayload")); if (answer != null && answer.isObject() && !answer.isEmpty()) db.update("insert into question_answer_keys(question_id,answer_mode,answer_payload,explanation_payload) values(?,?,?::jsonb,?::jsonb)", questionId, mode, write(answer), write(json.createObjectNode().put("text", question.path("analysis").asText("")))); int sequence = 0; for (JsonNode block : question.path("contentBlocks")) { String part = block.path("partType").asText("text"); if (!List.of("text", "formula", "image", "table", "markdown", "html", "chart", "qr_code").contains(part)) part = "text"; ObjectNode payload = json.createObjectNode(); if (block.hasNonNull("textValue")) payload.put("text", block.get("textValue").asText()); else if (block.hasNonNull("markdownValue")) payload.put("content", block.get("markdownValue").asText()); else if (block.hasNonNull("latexValue")) payload.put("text", block.get("latexValue").asText()); else if (block.hasNonNull("jsonValue")) payload.set("data", block.get("jsonValue")); else payload.put("text", question.path("stem").asText()); db.update("insert into question_content_blocks(question_id,part_type,sequence,payload) values(?,?,?,?::jsonb)", questionId, part, ++sequence, write(payload)); } db.update("insert into bank_question_links(bank_id,question_id,sort_order,status) values(?,?,?,'draft')", bank, questionId, ++order); db.update("insert into question_import_job_outputs(job_id,question_id,confidence,review_required) values(?,?,?,?)", jobId, questionId, question.path("confidence").decimalValue(), question.path("needsReview").asBoolean()); }
    settle(value); db.update("update question_import_jobs set status='completed',completed_at=now(),source_deleted_at=case when ? then now() else source_deleted_at end where id=?", sourceDeleted, jobId); db.update("insert into question_import_job_events(job_id,stage,status,payload) values(?,'persist','completed',jsonb_build_object('questionCount',?))", jobId, questions.size()); if (db.update("update ai_tasks set status='succeeded',result=?::jsonb,finished_at=now(),worker_id=null,worker_lease_until=null where id=? and status='running'", write(result), task) != 1) throw ApiException.of(409, "AI_TASK_STATE_CHANGED", "AI task state changed");
  }

  @Transactional public void fail(long task, JsonNode error, boolean timedOut) {
    var rows = db.query("select * from ai_tasks where id=? and status in ('queued','running') for update", this::row, task); if (rows.isEmpty()) return; var value = rows.getFirst(); String status = timedOut ? "timed_out" : "failed"; if ("import".equals(value.get("kind"))) { if (timedOut) db.update("update question_import_jobs set status='timed_out',completed_at=now() where ai_task_id=? and status in ('queued','processing')", task); else db.update("update question_import_jobs set status='failed',completed_at=now(),retry_expires_at=now()+interval '7 days' where ai_task_id=? and status in ('queued','processing')", task); Long job = db.queryForObject("select id from question_import_jobs where ai_task_id=?", Long.class, task); if (job != null) db.update("insert into question_import_job_events(job_id,stage,status,payload) values(?,'ai',?,?::jsonb)", job, status, write(error)); } refund(value, "failure_refund", status); db.update("update ai_tasks set status=?,error=?::jsonb,finished_at=now(),worker_id=null,worker_lease_until=null where id=?", status, write(error), task);
  }

  @Transactional public void expireOverdue() { for (Long task : db.queryForList("select id from ai_tasks where status in ('queued','running') and deadline_at<=now() order by id for update skip locked", Long.class)) fail(task, json.createObjectNode().put("code", "AI_TIMEOUT").put("message", "AI task deadline exceeded"), true); }

  public Map<String, Object> importSource(long task) { var rows = db.query("select j.id,j.source_type,j.source_file_name,j.source_storage_path,j.source_size_bytes from question_import_jobs j join ai_tasks t on t.id=j.ai_task_id where t.id=? and t.status='running' and j.status='processing'", this::row, task); if (rows.isEmpty()) throw ApiException.of(409, "IMPORT_STATE_CHANGED", "Import source is not ready"); return rows.getFirst(); }

  @Transactional public void markImportSourceDeleted(long task) { db.update("update question_import_jobs set source_deleted_at=coalesce(source_deleted_at,now()) where ai_task_id=? and status='completed'", task); }
  public Map<String, Object> importSourceForCleanup(long task) { var rows = db.query("select source_storage_path from question_import_jobs where ai_task_id=? and status='completed'", this::row, task); if (rows.isEmpty()) throw ApiException.of(404, "NOT_FOUND", "Import job not found"); return rows.getFirst(); }

  private Map<String, Object> create(long user, String kind, JsonNode request, BigDecimal estimate, Long sourceQuestion) { OffsetDateTime paid = db.queryForObject("select paid_pro_at from users where id=?", OffsetDateTime.class, user); if (paid == null) throw ApiException.of(403, "PAID_PRO_REQUIRED", "A paid Pro membership is required for AI tasks"); db.update("insert into credit_accounts(user_id) values(?) on conflict do nothing", user); BigDecimal balance = db.queryForObject("select balance from credit_accounts where user_id=? for update", BigDecimal.class, user); if (balance == null || balance.compareTo(estimate) < 0) throw ApiException.of(409, "INSUFFICIENT_CREDITS", "Insufficient credits for AI task"); if (db.queryForObject("select count(*) from ai_tasks where user_id=? and status in ('queued','running')", Integer.class, user) > 0) throw ApiException.of(409, "AI_TASK_CONFLICT", "Another AI task is already active"); ObjectNode prices = json.createObjectNode().put("inputPricePer1k", inputPrice).put("outputPricePer1k", outputPrice); try { long id = db.queryForObject("insert into ai_tasks(user_id,kind,deadline_at,price_snapshot,request_payload,estimated_credits,reserved_credits,source_question_id) values(?,?,now()+interval '180 seconds',?::jsonb,?::jsonb,?,?,?) returning id", Long.class, user, kind, write(prices), write(request), estimate, estimate, sourceQuestion); db.update("insert into credit_ledger(user_id,kind,amount,idempotency_key,ai_task_id) values(?,'reserve',?,?,?)", user, estimate.negate(), kind + "-reserve-" + id, id); return db.query("select * from ai_tasks where id=?", this::row, id).getFirst(); } catch (DataIntegrityViolationException error) { throw ApiException.of(409, "AI_TASK_CONFLICT", "Another AI task is already active"); } }

  private Map<String, Object> lockedRunning(long task) { var rows = db.query("select * from ai_tasks where id=? and status='running' for update", this::row, task); if (rows.isEmpty()) throw ApiException.of(409, "AI_TASK_STATE_CHANGED", "AI task state changed"); return rows.getFirst(); }
  private void settle(Map<String, Object> task) { long id = ((Number) task.get("id")).longValue(), user = ((Number) task.get("user_id")).longValue(); BigDecimal reserved = (BigDecimal) task.get("reserved_credits"); BigDecimal actual = db.queryForObject("select coalesce(sum(input_tokens*input_price_per_1k/1000.0+output_tokens*output_price_per_1k/1000.0),0) from ai_task_calls where task_id=?", BigDecimal.class, id).setScale(2, RoundingMode.CEILING); if (actual.compareTo(reserved) < 0) { BigDecimal release = reserved.subtract(actual); db.update("insert into credit_ledger(user_id,kind,amount,idempotency_key,ai_task_id) values(?,'release',?,?,?) on conflict do nothing", user, release, "ai-release-" + id, id); db.update("update ai_tasks set settled_credits=?,refunded_credits=refunded_credits+? where id=?", actual, release, id); } else { BigDecimal extra = actual.subtract(reserved); if (extra.signum() > 0) db.update("insert into credit_ledger(user_id,kind,amount,idempotency_key,ai_task_id) values(?,'settle',?,?,?) on conflict do nothing", user, extra.negate(), "ai-settle-" + id, id); db.update("update ai_tasks set settled_credits=? where id=?", actual, id); } }
  private void refund(Map<String, Object> task, String kind, String suffix) { long id = ((Number) task.get("id")).longValue(), user = ((Number) task.get("user_id")).longValue(); BigDecimal amount = ((BigDecimal) task.get("reserved_credits")).subtract((BigDecimal) task.get("settled_credits")).subtract((BigDecimal) task.get("refunded_credits")).max(BigDecimal.ZERO); if (amount.signum() > 0) { String attempt = String.valueOf(task.get("attempt_started_at")).replaceAll("[^0-9]", ""); int inserted = db.update("insert into credit_ledger(user_id,kind,amount,idempotency_key,ai_task_id) values(?,?,?,?,?) on conflict do nothing", user, kind, amount, "ai-" + suffix + "-" + id + "-" + attempt, id); if (inserted == 1) db.update("update ai_tasks set refunded_credits=refunded_credits+? where id=?", amount, id); } }
  private Map<String, Object> publicTask(Map<String, Object> source) { var value = new LinkedHashMap<String, Object>(); for (String key : List.of("id", "kind", "status", "estimated_credits", "reserved_credits", "settled_credits", "refunded_credits", "created_at", "updated_at", "started_at", "finished_at")) value.put(key, normalize(source.get(key))); value.put("result", parseNullable(source.get("result"))); value.put("error", parseNullable(source.get("error"))); return value; }
  private Object normalize(Object value) { return value instanceof OffsetDateTime time ? time.toString() : value; }
  private JsonNode parse(Object value) { try { return value instanceof JsonNode node ? node : json.readTree(String.valueOf(value)); } catch (Exception error) { throw new IllegalStateException(error); } }
  private JsonNode parseNullable(Object value) { return value == null ? null : parse(value); }
  private String write(Object value) { try { return json.writeValueAsString(value); } catch (Exception error) { throw new IllegalStateException(error); } }
  private Map<String, Object> row(ResultSet result, int ignored) throws java.sql.SQLException {
    var value = new LinkedHashMap<String, Object>();
    for (int index = 1; index <= result.getMetaData().getColumnCount(); index++) {
      Object field = result.getObject(index);
      // PostgreSQL getObject returns Timestamp for timestamptz; task deadlines use OffsetDateTime.
      if (field instanceof java.sql.Timestamp timestamp) field = timestamp.toInstant().atOffset(ZoneOffset.UTC);
      value.put(result.getMetaData().getColumnLabel(index), field);
    }
    return value;
  }
  private String resolveType(String subject, String requested, String mode) { var exact = db.queryForList("select id from question_types where subject_id=? and id=? and (answer_mode is null or answer_mode=?)", String.class, subject, requested, mode); if (!exact.isEmpty()) return exact.getFirst(); var fallback = db.queryForList("select id from question_types where subject_id=? and (answer_mode is null or answer_mode=?) order by case when answer_mode=? then 0 else 1 end,id limit 1", String.class, subject, mode, mode); if (fallback.isEmpty()) throw ApiException.of(409, "QUESTION_TYPE_REQUIRED", "No compatible question type exists for imported content"); return fallback.getFirst(); }
  private List<String> correctLabels(JsonNode question) { var labels = new ArrayList<String>(); JsonNode answer = question.path("answerPayload"); if (answer.hasNonNull("correctOption")) labels.add(answer.get("correctOption").asText()); if (answer.path("correct").isArray()) answer.path("correct").forEach(item -> labels.add(item.asText())); question.path("options").forEach(option -> { if (option.path("isCorrect").asBoolean(false) && !labels.contains(option.path("label").asText())) labels.add(option.path("label").asText()); }); return labels; }
  private JsonNode normalizeAnswer(String mode, JsonNode source) { ObjectNode answer = json.createObjectNode(); if ("choice".equals(mode)) { ArrayNode correct = answer.putArray("correct"); if (source.hasNonNull("correctOption")) correct.add(source.get("correctOption").asText()); else if (source.path("correct").isArray()) source.path("correct").forEach(correct::add); return correct.isEmpty() ? null : answer; } if ("true_false".equals(mode)) { if (source.has("answer") && source.get("answer").isBoolean()) return answer.put("answer", source.get("answer").asBoolean()); return null; } if ("fill_blank".equals(mode)) { JsonNode values = source.path("answers"); if (values.isArray() && !values.isEmpty()) { answer.set("answers", values); return answer; } return null; } String text = source.path("answer").asText(source.path("value").asText("")); return text.isBlank() ? null : answer.put("answer", text); }
  private static String nullable(JsonNode node, String field) { return node.hasNonNull(field) ? node.get(field).asText() : null; }
  private static boolean contains(ArrayNode values, String value) { for (JsonNode item : values) if (item.asText().equals(value)) return true; return false; }
  private static BigDecimal positive(BigDecimal value, String name) { if (value == null || value.signum() <= 0) throw new IllegalStateException(name + " must be positive"); return value; }
  private static BigDecimal nonnegative(BigDecimal value, String name) { if (value == null || value.signum() < 0) throw new IllegalStateException(name + " must not be negative"); return value; }
}
