package com.practiq.service;

import com.practiq.common.ApiException;
import com.practiq.common.PageSupport;
import java.io.IOException;
import java.math.BigDecimal;
import java.nio.file.*;
import java.sql.ResultSet;
import java.util.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

@Service
public class ImportService {
  private final JdbcTemplate db; private final String mount; private final BigDecimal estimate; private final BigDecimal inputPrice; private final BigDecimal outputPrice;
  @org.springframework.beans.factory.annotation.Autowired public ImportService(JdbcTemplate db, @Value("${practiq.object-storage-mount-dir}") String mount, @Value("${practiq.import-estimated-credits:1.00}") BigDecimal estimate, @Value("${OSS_PUBLIC_BASE_URL:}") String ignoredBase, @Value("${OSS_URL_PREFIX:oss://practiq}") String ignoredPrefix, @Value("${practiq.ai.input-price-per-1k:0.010000}") BigDecimal inputPrice, @Value("${practiq.ai.output-price-per-1k:0.030000}") BigDecimal outputPrice) { this.db = db; this.mount = mount; this.estimate = estimate; this.inputPrice = inputPrice; this.outputPrice = outputPrice; if (estimate.signum() <= 0) throw new IllegalStateException("IMPORT_ESTIMATED_CREDITS must be positive"); }
  public ImportService(JdbcTemplate db, String mount, BigDecimal estimate, String ignoredBase, String ignoredPrefix) { this(db, mount, estimate, ignoredBase, ignoredPrefix, new BigDecimal("0.010000"), new BigDecimal("0.030000")); }
  private Map<String, Object> row(ResultSet result, int number) throws java.sql.SQLException { var value = new LinkedHashMap<String, Object>(); for (int i = 1; i <= result.getMetaData().getColumnCount(); i++) value.put(result.getMetaData().getColumnLabel(i), result.getObject(i)); return value; }
  private void pro(Map<String, Object> user) { if (!Boolean.TRUE.equals(user.get("paidPro"))) throw ApiException.of(403, "PAID_PRO_REQUIRED", "AI document imports require paid Pro"); }
  public Map<String, Object> job(long user, long id) { var rows = db.query("select * from question_import_jobs where id=? and created_by=?", this::row, id, user); if (rows.isEmpty()) throw ApiException.of(404, "NOT_FOUND", "Import job not found"); new ContentAccess(db).bank(user, ((Number) rows.getFirst().get("bank_id")).longValue()); return rows.getFirst(); }
  private String source(String value) { String type = value == null ? "text" : value.trim().toLowerCase(); return switch (type) { case "", "text", "txt" -> "text"; case "docx", "pdf", "xlsx" -> type; default -> throw ApiException.of(400, "UNSUPPORTED_SOURCE_TYPE", "Only txt, docx, pdf, and xlsx imports are supported"); }; }
  @Transactional public Map<String, Object> create(long user, Map<String, Object> me, Long bank, String file, String type, Map<String, Object> ignoredRequest) {
    pro(me); if (bank == null || bank < 1) throw ApiException.of(422, "VALIDATION_ERROR", "bankId is required");
    if (db.queryForObject("select count(*) from question_banks where id=? and owner_user_id=? and deleted_at is null and status<>'banned'", Integer.class, bank, user) == 0) throw ApiException.of(403, "FORBIDDEN", "Question bank owner access required");
    String source = source(type); db.update("insert into credit_accounts(user_id) values(?) on conflict do nothing", user); BigDecimal balance = db.queryForObject("select balance from credit_accounts where user_id=? for update", BigDecimal.class, user); if (balance == null || balance.compareTo(estimate) < 0) throw ApiException.of(409, "INSUFFICIENT_CREDITS", "Insufficient credits for document import"); long task;
    try { task = db.queryForObject("insert into ai_tasks(user_id,kind,deadline_at,price_snapshot,estimated_credits,reserved_credits) values(?,'import',now()+interval '180 seconds',?::jsonb,?,?) returning id", Long.class, user, "{\"estimatedCredits\":" + estimate.toPlainString() + ",\"inputPricePer1k\":" + inputPrice.toPlainString() + ",\"outputPricePer1k\":" + outputPrice.toPlainString() + "}", estimate, estimate); } catch (RuntimeException error) { throw ApiException.of(409, "AI_TASK_CONFLICT", "Another AI task is already active"); }
    db.update("insert into credit_ledger(user_id,kind,amount,idempotency_key,ai_task_id) values(?,'reserve',?,?,?)", user, estimate.negate(), "import-reserve-" + task, task);
    return db.query("insert into question_import_jobs(ai_task_id,created_by,bank_id,source_type,source_file_name) values(?,?,?,?,?) returning *", this::row, task, user, bank, source, file == null || file.isBlank() ? null : file).getFirst();
  }
  public Map<String, Object> list(long user, String status, String cursor, Integer requested) {
    Set<String> allowed = Set.of("queued", "processing", "completed", "failed", "cancelled", "timed_out"); var values = status == null ? List.<String>of() : Arrays.stream(status.split(",")).filter(value -> !value.isBlank()).map(String::trim).toList(); if (!allowed.containsAll(values)) throw ApiException.of(422, "VALIDATION_ERROR", "Invalid request"); int size = requested == null ? 30 : requested; if (size < 1 || size > 100) throw ApiException.of(422, "VALIDATION_ERROR", "Invalid request"); int offset = PageSupport.cursor(cursor); var rows = db.query("select * from question_import_jobs j where created_by=? and exists(select 1 from question_banks b where b.id=j.bank_id and " + ContentAccess.bankVisible("b", user) + ") and (?='' or status=any(string_to_array(?,','))) order by created_at desc,id desc limit ? offset ?", this::row, user, String.join(",", values), String.join(",", values), size + 1, offset); boolean more = rows.size() > size; if (more) rows = rows.subList(0, size); return Map.of("items", rows, "meta", Map.of("pagination", Map.of("cursor", more ? PageSupport.next(offset, size) : "", "limit", size, "hasMore", more))); }
  @Transactional public Map<String, Object> upload(long user, Map<String, Object> me, long id, MultipartFile file) {
    pro(me); var job = job(user, id); if (!"queued".equals(job.get("status")) || job.get("source_storage_path") != null) throw ApiException.of(409, "IMPORT_SOURCE_EXISTS", "Import source already exists"); if (file == null) throw ApiException.of(400, "FILE_REQUIRED", "Upload file is required"); byte[] bytes;
    try { bytes = file.getBytes(); } catch (IOException error) { throw ApiException.of(400, "INVALID_FILE_CONTENT", "Could not read upload"); }
    String name = Optional.ofNullable(file.getOriginalFilename()).orElse(""); if (name.isBlank() || name.length() > 255) throw ApiException.of(400, "INVALID_FILE_NAME", "Upload file name is invalid"); String extension = UploadSupport.extension(name, file.getContentType());
    if (!Set.of(".txt", ".docx", ".pdf", ".xlsx").contains(extension)) throw ApiException.of(400, "UNSUPPORTED_SOURCE_TYPE", "Only txt, docx, pdf, and xlsx imports are supported"); UploadSupport.validateImport(extension, file.getContentType(), bytes, name); String type = source(UploadSupport.sourceType(extension));
    String relative = "imports/" + user + "/" + id + "/source-" + System.currentTimeMillis() + "-" + UploadSupport.token() + extension; Path path = UploadSupport.path(mount, relative);
    try { Files.createDirectories(path.getParent()); Files.write(path, bytes, StandardOpenOption.CREATE_NEW); } catch (IOException error) { throw ApiException.of(500, "IMPORT_STORAGE_FAILED", "Could not store import source"); }
    try { var rows = db.query("update question_import_jobs set source_type=?,source_file_name=?,source_storage_path=?,source_size_bytes=? where id=? and created_by=? and status='queued' and source_storage_path is null returning *", this::row, type, name, relative, bytes.length, id, user); if (rows.isEmpty()) throw ApiException.of(409, "IMPORT_SOURCE_EXISTS", "Import source already exists"); return rows.getFirst(); } catch (RuntimeException error) { try { Files.deleteIfExists(path); } catch (IOException ignored) {} throw error; }
  }
  @Transactional public Map<String, Object> action(long user, Map<String, Object> me, long id, String action, Boolean ignoredPersist) {
    var job = job(user, id); String status = String.valueOf(job.get("status"));
    if ("parse".equals(action)) { pro(me); if (!"queued".equals(status) || job.get("source_storage_path") == null) throw ApiException.of(409, "SOURCE_FILE_REQUIRED", "Import job requires an uploaded source file before parsing"); var rows = db.query("update question_import_jobs set status='processing' where id=? and status='queued' returning *", this::row, id); if (rows.isEmpty()) throw ApiException.of(409, "IMPORT_STATE_CHANGED", "Import job state changed; refresh and try again"); db.update("insert into question_import_job_events(job_id,stage,status,payload) values(?,'queue','queued','{}')", id); return rows.getFirst(); }
    if ("retry".equals(action)) { pro(me); if (!"failed".equals(status) || job.get("source_storage_path") == null || job.get("source_deleted_at") != null) throw ApiException.of(409, "IMPORT_RETRY_NOT_ALLOWED", "Only failed jobs with a retained source can be retried"); Integer eligible = db.queryForObject("select count(*) from question_import_jobs where id=? and retry_expires_at>now()", Integer.class, id); if (eligible == null || eligible == 0) throw ApiException.of(409, "IMPORT_RETRY_NOT_ALLOWED", "Import retry window has expired"); long task = ((Number) job.get("ai_task_id")).longValue(); BigDecimal required = db.queryForObject("select estimated_credits from ai_tasks where id=? for update", BigDecimal.class, task); db.update("insert into credit_accounts(user_id) values(?) on conflict do nothing", user); BigDecimal balance = db.queryForObject("select balance from credit_accounts where user_id=? for update", BigDecimal.class, user); if (balance == null || balance.compareTo(required) < 0) throw ApiException.of(409, "INSUFFICIENT_CREDITS", "Insufficient credits for import retry"); int nextRetry = ((Number) job.get("retry_count")).intValue() + 1; db.update("insert into credit_ledger(user_id,kind,amount,idempotency_key,ai_task_id) values(?,'reserve',?,?,?)", user, required.negate(), "import-retry-reserve-" + task + "-" + nextRetry, task); db.update("update ai_tasks set status='queued',attempt_started_at=now(),deadline_at=now()+interval '180 seconds',started_at=null,finished_at=null,error=null,refunded_credits=0,worker_id=null,worker_lease_until=null where id=? and status='failed'", task); var rows = db.query("update question_import_jobs set status='queued',retry_count=retry_count+1,retry_expires_at=null,completed_at=null where id=? and status='failed' returning *", this::row, id); if (rows.isEmpty()) throw ApiException.of(409, "IMPORT_STATE_CHANGED", "Import job state changed; refresh and try again"); db.update("insert into question_import_job_events(job_id,stage,status,payload) values(?,'retry','queued','{}')", id); return rows.getFirst(); }
    if ("cancel".equals(action)) { if (!Set.of("queued", "processing").contains(status)) throw ApiException.of(409, "IMPORT_CANCEL_NOT_ALLOWED", "Import job cannot be cancelled"); String source = (String) job.get("source_storage_path"); if (source != null) try { Files.deleteIfExists(UploadSupport.path(mount, source)); } catch (IOException error) { throw ApiException.of(500, "IMPORT_STORAGE_FAILED", "Could not delete import source"); } var rows = db.query("update question_import_jobs set status='cancelled',completed_at=now(),source_deleted_at=now() where id=? and status=? returning *", this::row, id, status); if (rows.isEmpty()) throw ApiException.of(409, "IMPORT_STATE_CHANGED", "Import job state changed; refresh and try again"); Object task = job.get("ai_task_id"); BigDecimal release = db.queryForObject("select greatest(reserved_credits-settled_credits-refunded_credits,0) from ai_tasks where id=? for update", BigDecimal.class, task); if (db.update("update ai_tasks set status='cancelled',finished_at=now(),refunded_credits=refunded_credits+? where id=? and status in ('queued','running')", release, task) != 1) throw ApiException.of(409, "IMPORT_STATE_CHANGED", "Import job state changed; refresh and try again"); if (release != null && release.signum() > 0) db.update("insert into credit_ledger(user_id,kind,amount,idempotency_key,ai_task_id) values(?,'release',?,'import-release-'||?::text,?) on conflict do nothing", user, release, task, task); db.update("insert into question_import_job_events(job_id,stage,status,payload) values(?,'cancel','cancelled','{}')", id); return rows.getFirst(); }
    throw ApiException.of(400, "INVALID_IMPORT_ACTION", "Unsupported import action");
  }
  public List<Map<String, Object>> children(long user, long id, String kind) { job(user, id); String table = switch (kind) { case "events" -> "question_import_job_events"; case "outputs" -> "question_import_job_outputs"; default -> throw ApiException.of(400, "INVALID_IMPORT_CHILD_KIND", "Unsupported import child kind"); }; return db.query("select * from " + table + " where job_id=? order by " + (kind.equals("events") ? "id desc" : "question_id") + " limit " + (kind.equals("outputs") ? 200 : 100), this::row, id); }
  public boolean event(long id, long event) { return db.queryForObject("select count(*) from question_import_job_events where job_id=? and id=?", Integer.class, id, event) > 0; }
  public List<Map<String, Object>> eventsAfter(long id, long after) { return db.query("select * from question_import_job_events where job_id=? and id>? order by id limit 100", this::row, id, after); }
}
