package com.practiq.service;

import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;
import com.practiq.common.ApiException;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.PlatformTransactionManager;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.transaction.support.TransactionTemplate;

@Service public class PaymentService {
  private static final SecureRandom RANDOM=new SecureRandom();
  private static final Logger log=LoggerFactory.getLogger(PaymentService.class);
  private final JdbcTemplate db; private final WeChatPayGateway pay; private final ObjectMapper json; private final String app,mch; private final TransactionTemplate tx;
  @Autowired public PaymentService(JdbcTemplate db,WeChatPayGateway pay,ObjectMapper json,@Value("${practiq.wechat.app-id:}") String app,@Value("${practiq.wechat.pay.mch-id:}") String mch,PlatformTransactionManager manager){this.db=db;this.pay=pay;this.json=json;this.app=app;this.mch=mch;this.tx=new TransactionTemplate(manager);}
  // Keeps direct JDBC smoke construction small; Spring uses the constructor above.
  public PaymentService(JdbcTemplate db,WeChatPayGateway pay,ObjectMapper json,String app,String mch){this(db,pay,json,app,mch,new DataSourceTransactionManager(db.getDataSource()));}
  private record O(long id,long user,String kind,String merchant,String app,String mch,int cents,String currency,BigDecimal credits,String status,OffsetDateTime expires,String key,byte[] hash,String transaction,String cache){}
  private record R(long id,long order,String merchant,String transaction,int cents,String status){}
  public Map<String,Object> create(long user,String kind,String key){kind(kind);key(key);available();byte[] hash=hash("{\"kind\":\""+kind+"\"}"); for(int attempt=0;attempt<2;attempt++){O o=tx.execute(s->intent(user,kind,key,hash));if(o.cache!=null&&o.expires.isAfter(now()))return response(o);if("pending".equals(o.status)&&o.expires.isAfter(now()))return prepay(o);reconcileOne(o.id);O current=tx.execute(s->one(o.id));if("paid".equals(current.status))return response(current);if(!"closed".equals(current.status))throw unavailable();}throw unavailable();}
  public Map<String,Object> get(long user,long id){O o=tx.execute(s->owner(user,id));if(List.of("pending","expired").contains(o.status))reconcileOne(id);return publicOrder(tx.execute(s->owner(user,id)));}
  public List<Map<String,Object>> admin(long user){adminUser(user);return orders("select * from payment_orders order by created_at desc,id desc limit 100").stream().map(this::publicOrder).toList();}
  public Map<String,Object> refund(long admin,long order){adminUser(admin);available();R r=tx.execute(s->refundIntent(admin,order));if(!"pending".equals(r.status))return refundPublic(r);try{return applyRefund(r,pay.refund(r.merchant,tx.execute(s->one(r.order)).merchant,tx.execute(s->one(r.order)).transaction,r.cents));}catch(WeChatPayGateway.Unavailable|WeChatPayGateway.Failed e){try{return applyRefund(r,pay.queryRefund(r.merchant));}catch(WeChatPayGateway.Unavailable|WeChatPayGateway.Failed ignored){throw e;}}}
  public void paymentNotification(Map<String,String> h,String raw){timestamp(h);WeChatPayGateway.Payment p=pay.paymentNotification(h,raw);String id=notification(raw,"INVALID_PAYMENT_NOTIFICATION");tx.executeWithoutResult(s->{if(!replay(id,h.get("wechatpay-nonce"),"INVALID_PAYMENT_NOTIFICATION"))return;applyPayment(p);});}
  public void refundNotification(Map<String,String> h,String raw){timestamp(h);WeChatPayGateway.Refund r=pay.refundNotification(h,raw);String id=notification(raw,"INVALID_REFUND_NOTIFICATION");tx.executeWithoutResult(s->{if(!replay(id,h.get("wechatpay-nonce"),"INVALID_REFUND_NOTIFICATION"))return;applyRefundLocked(r);});}
  @Scheduled(fixedDelay=300_000) public void reconcilePending(){if(!pay.available())return;for(Long id:db.query("select id from payment_orders where status in ('pending','expired') and (last_reconciled_at is null or last_reconciled_at<now()-interval '1 minute') order by id limit 100",(r,n)->r.getLong(1)))try{reconcileOne(id);}catch(RuntimeException e){log.warn("Payment reconciliation failed for order {}",id);}for(Long id:db.query("select id from payment_refunds where status='pending' order by id limit 100",(r,n)->r.getLong(1)))try{R r=tx.execute(s->refund(id));applyRefund(r,pay.queryRefund(r.merchant));}catch(RuntimeException e){log.warn("Payment reconciliation failed for refund {}",id);}}
  private O intent(long user,String kind,String key,byte[] hash){lock("payment:key:"+user+":"+key);lock("payment:kind:"+user+":"+kind);var same=orders("select * from payment_orders where user_id=? and idempotency_key=? and expires_at>now() order by id desc for update",user,key);if(!same.isEmpty()){O o=same.getFirst();if(!MessageDigest.isEqual(o.hash,hash))throw conflict("IDEMPOTENCY_KEY_REUSED");return o;}var pending=orders("select * from payment_orders where user_id=? and kind=? and status='pending' for update",user,kind);if(!pending.isEmpty())return pending.getFirst();Boolean paid=db.queryForObject("select paid_pro_at is not null from users where id=?",Boolean.class,user);if("credits".equals(kind)&&!Boolean.TRUE.equals(paid))throw ApiException.of(409,"PAID_PRO_REQUIRED","Paid Pro is required for credit purchases");if("pro".equals(kind)&&Boolean.TRUE.equals(paid))throw conflict("PRO_ALREADY_ACTIVE");int cents="pro".equals(kind)?2990:1000;BigDecimal credits="credits".equals(kind)?new BigDecimal("100.00"):null;long id=db.queryForObject("insert into payment_orders(user_id,kind,merchant_order_no,app_id,mch_id,amount_cents,credits_amount,expires_at,idempotency_key,request_hash) values(?,?,?,?,?,?,?,now()+interval '30 minutes',?,?) returning id",Long.class,user,kind,number("P"),app,mch,cents,credits,key,hash);return one(id);}
  private Map<String,Object> prepay(O o){String openid=tx.execute(s->db.queryForObject("select openid from wechat_identities where user_id=?",String.class,o.user));Map<String,Object> request;try{request=pay.prepay(o.merchant,"PractiQ "+o.kind,o.cents,openid,o.expires.toString());}catch(WeChatPayGateway.Unavailable|WeChatPayGateway.Failed e){try{reconcileOne(o.id);O current=tx.execute(s->one(o.id));if("paid".equals(current.status))return response(current);}catch(WeChatPayGateway.Unavailable|WeChatPayGateway.Failed ignored){}throw e;}return tx.execute(s->{O current=locked(o.id);if(!"pending".equals(current.status))return response(current);db.update("update payment_orders set response_cache=?::jsonb,response_cache_expires_at=expires_at where id=?",write(request),o.id);return response(one(o.id));});}
  private void reconcileOne(long id){O o=tx.execute(s->locked(id));if(!List.of("pending","expired").contains(o.status))return;WeChatPayGateway.Payment p=pay.query(o.merchant);validatePayment(o,p);switch(p.state()){case "SUCCESS"->{tx.executeWithoutResult(s->applyPayment(p));return;}case "NOTPAY","USERPAYING"->{if(!now().isAfter(o.expires)){tx.executeWithoutResult(s->db.update("update payment_orders set last_reconciled_at=now() where id=?",id));return;}pay.close(o.merchant);}case "CLOSED","REVOKED","PAYERROR"->{}default->throw ApiException.of(422,"INVALID_PAYMENT_NOTIFICATION","Invalid payment notification");}tx.executeWithoutResult(s->db.update("update payment_orders set status='closed',last_reconciled_at=now() where id=? and status in ('pending','expired')",id));}
  private R refundIntent(long admin,long id){O o=locked(id);var old=refunds("select r.*,o.wechat_transaction_id from payment_refunds r join payment_orders o on o.id=r.order_id where r.order_id=? for update",id);if(!old.isEmpty())return old.getFirst();if(!"paid".equals(o.status))throw conflict("REFUND_NOT_ALLOWED");long r=db.queryForObject("insert into payment_refunds(order_id,initiated_by,merchant_refund_no,amount_cents) values(?,?,?,?) returning id",Long.class,id,admin,number("R"),o.cents);db.update("insert into admin_audits(actor_user_id,target_user_id,action,details) values(?,?, 'refund',jsonb_build_object('orderId',?))",admin,o.user,id);return refund(r);}
  private Map<String,Object> applyRefund(R local,WeChatPayGateway.Refund remote){return tx.execute(s->{applyRefundLocked(remote);return refundPublic(refund(local.id));});}
  private void applyPayment(WeChatPayGateway.Payment p){if(p==null)throw ApiException.of(422,"INVALID_PAYMENT_NOTIFICATION","Invalid payment notification");O o=lockedMerchant(p.merchantOrderNo());validatePayment(o,p);if(!"SUCCESS".equals(p.state()))throw ApiException.of(422,"INVALID_PAYMENT_NOTIFICATION","Invalid payment notification");int changed=db.update("update payment_orders set status='paid',fulfilled_at=now(),wechat_transaction_id=? where id=? and status in ('pending','expired')",p.transactionId(),o.id);if(changed!=1)return; if("pro".equals(o.kind)){db.update("update users set paid_pro_at=coalesce(paid_pro_at,now()) where id=?",o.user);db.update("insert into credit_ledger(user_id,kind,amount,idempotency_key,order_id) values(?,'bonus',200,?,?) on conflict do nothing",o.user,"payment-bonus-"+o.id,o.id);}else db.update("insert into credit_ledger(user_id,kind,amount,idempotency_key,order_id) values(?,'purchase',?,?,?) on conflict do nothing",o.user,o.credits,"payment-purchase-"+o.id,o.id);}
  private void applyRefundLocked(WeChatPayGateway.Refund remote){if(remote==null)throw ApiException.of(422,"INVALID_REFUND_NOTIFICATION","Invalid refund notification");R r=refundByMerchant(remote.merchantRefundNo());O o=locked(r.order);validateRefund(o,r,remote);String state=refundState(remote.state());if(!"pending".equals(r.status))return;if(!"succeeded".equals(state)){db.update("update payment_refunds set status=? where id=? and status='pending'",state,r.id);event(r.id,state,remote.state());return;}db.update("update payment_refunds set status='succeeded',processed_at=now(),wechat_refund_id=? where id=? and status='pending'",remote.refundId(),r.id);int changed=db.update("update payment_orders set status='refunded' where id=? and status='paid'",o.id);if(changed!=1)throw ApiException.of(422,"INVALID_REFUND_NOTIFICATION","Invalid refund notification");if("pro".equals(o.kind)){db.update("update users set paid_pro_at=null where id=?",o.user);if(db.queryForObject("select count(*) from credit_ledger where order_id=? and kind='bonus'",Integer.class,o.id)>0)db.update("insert into credit_ledger(user_id,kind,amount,idempotency_key,order_id) values(?,'payment_refund',-200,?,?) on conflict do nothing",o.user,"payment-refund-"+o.id,o.id);}else db.update("insert into credit_ledger(user_id,kind,amount,idempotency_key,order_id) values(?,'payment_refund',?,?,?) on conflict do nothing",o.user,o.credits.negate(),"payment-refund-"+o.id,o.id);event(r.id,"succeeded",remote.state());}
  private String refundState(String s){return switch(s==null?"":s){case "SUCCESS"->"succeeded";case "PROCESSING"->"pending";case "CLOSED"->"closed";case "ABNORMAL"->"failed";default->throw ApiException.of(422,"INVALID_REFUND_NOTIFICATION","Invalid refund notification");};}
  private void validatePayment(O o,WeChatPayGateway.Payment p){if(p==null||!o.merchant.equals(p.merchantOrderNo())||!o.app.equals(p.appId())||!o.mch.equals(p.mchId())||o.cents!=p.amountCents()||!o.currency.equals(p.currency())||("SUCCESS".equals(p.state())&&(p.transactionId()==null||p.transactionId().isBlank())))throw ApiException.of(422,"INVALID_PAYMENT_NOTIFICATION","Invalid payment notification");}
  private void validateRefund(O o,R local,WeChatPayGateway.Refund r){if(!local.merchant.equals(r.merchantRefundNo())||!o.merchant.equals(r.merchantOrderNo())||!local.transaction.equals(r.transactionId())||o.cents!=r.amountCents()||o.cents!=r.totalAmountCents()||(r.currency()!=null&&!o.currency.equals(r.currency()))||("SUCCESS".equals(r.state())&&(r.refundId()==null||r.refundId().isBlank())))throw ApiException.of(422,"INVALID_REFUND_NOTIFICATION","Invalid refund notification");}
  private boolean replay(String id,String nonce,String code){if(id==null||id.isBlank()||nonce==null||nonce.isBlank())throw ApiException.of(422,code,"Invalid payment notification");return db.update("insert into wechat_notification_replays(notification_id,nonce) values(?,?) on conflict do nothing",id,nonce)==1;}
  private void timestamp(Map<String,String> h){try{long t=Long.parseLong(h.get("wechatpay-timestamp")),n=Instant.now().getEpochSecond();for(String x:List.of("wechatpay-nonce","wechatpay-signature","wechatpay-serial"))if(h.get(x)==null||h.get(x).isBlank())throw new Exception();if(t<n-300||t>n+300)throw new Exception();}catch(Exception e){throw ApiException.of(401,"INVALID_WECHAT_SIGNATURE","Invalid WeChat signature");}}
  private String notification(String raw,String code){try{return json.readTree(raw).path("id").asText(null);}catch(Exception e){throw ApiException.of(422,code,"Invalid payment notification");}}
  private O one(long id){return orders("select * from payment_orders where id=?",id).getFirst();} private O locked(long id){return orders("select * from payment_orders where id=? for update",id).getFirst();}private O owner(long u,long id){var x=orders("select * from payment_orders where id=? and user_id=?",id,u);if(x.isEmpty())throw ApiException.of(404,"NOT_FOUND","Payment order not found");return x.getFirst();}private O lockedMerchant(String no){var x=orders("select * from payment_orders where merchant_order_no=? for update",no);if(x.isEmpty())throw ApiException.of(422,"INVALID_PAYMENT_NOTIFICATION","Invalid payment notification");return x.getFirst();}
  private R refund(long id){return refunds("select r.*,o.wechat_transaction_id from payment_refunds r join payment_orders o on o.id=r.order_id where r.id=? for update",id).getFirst();}private R refundByMerchant(String no){var x=refunds("select r.*,o.wechat_transaction_id from payment_refunds r join payment_orders o on o.id=r.order_id where r.merchant_refund_no=? for update",no);if(x.isEmpty())throw ApiException.of(422,"INVALID_REFUND_NOTIFICATION","Invalid refund notification");return x.getFirst();}
  private List<O> orders(String q,Object...a){return db.query(q,(r,n)->new O(r.getLong("id"),r.getLong("user_id"),r.getString("kind"),r.getString("merchant_order_no"),r.getString("app_id"),r.getString("mch_id"),r.getInt("amount_cents"),r.getString("currency"),r.getBigDecimal("credits_amount"),r.getString("status"),r.getObject("expires_at",OffsetDateTime.class),r.getString("idempotency_key"),r.getBytes("request_hash"),r.getString("wechat_transaction_id"),r.getString("response_cache")),a);}private List<R> refunds(String q,Object...a){return db.query(q,(r,n)->new R(r.getLong("id"),r.getLong("order_id"),r.getString("merchant_refund_no"),r.getString("wechat_transaction_id"),r.getInt("amount_cents"),r.getString("status")),a);}
  private Map<String,Object> response(O o){var value=new LinkedHashMap<String,Object>();value.put("order",publicOrder(o));if("pending".equals(o.status)&&o.cache!=null&&o.expires.isAfter(now()))value.put("requestPayment",read(o.cache));return value;}private Map<String,Object> read(String value){try{return json.readValue(value,new TypeReference<Map<String,Object>>(){});}catch(Exception e){throw new IllegalStateException(e);}}private Map<String,Object> publicOrder(O o){var v=new LinkedHashMap<String,Object>();v.put("id",o.id);v.put("kind",o.kind);v.put("status",o.status);v.put("amountCents",o.cents);v.put("currency",o.currency);v.put("creditsAmount",o.credits);v.put("expiresAt",o.expires.toString());return v;}private Map<String,Object> refundPublic(R r){return Map.of("id",r.id,"orderId",r.order,"status",r.status,"amountCents",r.cents);}
  private void event(long id,String state,String remote){db.update("insert into payment_refund_events(refund_id,status,details) values(?,?,jsonb_build_object('remoteStatus',?))",id,state,remote);}private void lock(String k){db.query("select pg_advisory_xact_lock(hashtextextended(?,0))",p->p.setString(1,k),r->null);}private void adminUser(long id){var x=db.query("select status,role from users where id=?",(r,n)->r.getString(1)+":"+r.getString(2),id);if(x.isEmpty()||!"active:admin".equals(x.getFirst()))throw ApiException.of(403,"ADMIN_REQUIRED","Administrator access required");}private void available(){if(!pay.available())throw unavailable();}private ApiException unavailable(){return ApiException.of(503,"WECHAT_PAY_UNAVAILABLE","WeChat Pay is temporarily unavailable");}private ApiException conflict(String c){return ApiException.of(409,c,"Payment request conflicts with existing order");}private void kind(String k){if(!"pro".equals(k)&&!"credits".equals(k))throw ApiException.of(422,"VALIDATION_ERROR","Invalid payment kind");}private void key(String k){if(k==null||k.isBlank()||k.length()>128||k.indexOf('\r')>=0||k.indexOf('\n')>=0)throw ApiException.of(422,"VALIDATION_ERROR","Invalid Idempotency-Key");}private String number(String p){byte[] b=new byte[16];RANDOM.nextBytes(b);return p+HexFormat.of().formatHex(b).substring(0,31);}private byte[] hash(String s){try{return MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));}catch(Exception e){throw new IllegalStateException(e);}}private String write(Object o){try{return json.writeValueAsString(o);}catch(Exception e){throw new IllegalStateException(e);}}private static OffsetDateTime now(){return OffsetDateTime.now(ZoneOffset.UTC);}
}
