package com.practiq.service;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.practiq.common.ApiException;
import com.practiq.common.PageSupport;
import java.sql.ResultSet;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** Practice state uses the existing PostgreSQL triggers for aggregate statistics. */
@Service
public class PracticeService {
  private static final int MAX = 500;
  private final JdbcTemplate db; private final StringRedisTemplate redis; private final ObjectMapper json; private final GradingService grader;
  public PracticeService(JdbcTemplate db,StringRedisTemplate redis,ObjectMapper json,GradingService grader){this.db=db;this.redis=redis;this.json=json;this.grader=grader;}
  private static ApiException bad(String m){return ApiException.of(422,"VALIDATION_ERROR",m);} private static ApiException state(String m){return ApiException.of(409,"INVALID_STATE",m);}
  private Map<String,Object> row(ResultSet r,int n)throws java.sql.SQLException {var m=new LinkedHashMap<String,Object>();for(int i=1;i<=r.getMetaData().getColumnCount();i++){Object v=r.getObject(i);m.put(r.getMetaData().getColumnLabel(i),v instanceof OffsetDateTime t?t.toString():v);}return m;}
  private static int limit(Integer n,int fallback){return Math.min(MAX,Math.max(1,n==null?fallback:n));}
  private String key(long session){return "practiq:practice:"+session+":question-ids";}
  private void visibleBank(long user,long bank){Integer n=db.queryForObject("select count(*) from question_banks b left join user_bank_links l on l.bank_id=b.id and l.user_id=? where b.id=? and (b.is_public or l.id is not null or exists(select 1 from study_group_banks gb join study_group_members gm on gm.group_id=gb.group_id where gb.bank_id=b.id and gm.user_id=?))",Integer.class,user,bank,user);if(n==null||n==0)throw ApiException.of(404,"NOT_FOUND","Question bank not found");}
  private Map<String,Object> session(long user,long id){var x=db.query("select id,user_id,bank_id,session_type,status,question_count,answered_count,correct_count,wrong_count,score,started_at,completed_at from user_practice_sessions where id=? and user_id=?",this::row,id,user);if(x.isEmpty())throw ApiException.of(404,"NOT_FOUND","Practice session not found");return x.getFirst();}
  public Map<String,Object> get(long user,long sessionId){return session(user,sessionId);}
  public Map<String,Object> start(long user,long bank,String sessionType,Integer requested,String mode,String type,boolean all){visibleBank(user,bank);String m=mode==null?"":mode.trim(), st=sessionType==null?"":sessionType.trim();if(!Set.of("","practice","review","exam").contains(st)||!Set.of("","all","wrong","by_type","exam").contains(m))throw bad("Invalid practice mode");if(m.isEmpty())m="review".equals(st)?"wrong":"exam".equals(st)?"exam":"all";if("by_type".equals(m)&&(type==null||type.isBlank()))throw bad("Question type is required for type-based practice");int count=all||("all".equals(m)&&(requested==null||requested<1))?MAX:limit(requested,1);String actual="exam".equals(m)?"exam":"wrong".equals(m)?"review":st.isEmpty()?"practice":st;
    var ids=db.queryForList("select i.question_id from v_bank_question_items i left join user_question_stats s on s.question_id=i.question_id and s.user_id=? where i.bank_id=? and i.bank_link_status='active' and i.question_status='active' and (?<> 'by_type' or i.question_type_id=?) and (?<> 'wrong' or coalesce(s.wrong_count,0)>0 or s.last_is_correct=false) group by i.question_id,i.bank_sort_order,i.group_sort_order,s.wrong_count,s.last_is_correct order by case when ?='wrong' then coalesce(s.wrong_count,0) else 0 end desc,case when ?='exam' then md5(i.question_id::text||?::text||current_date::text) else '' end,i.bank_sort_order,i.group_sort_order nulls first,i.question_id limit ?",Long.class,user,bank,m,type==null?"":type.trim(),m,m,m,user,count);
    if(ids.isEmpty())throw state("wrong".equals(m)?"No wrong questions are available for review":"No active questions are available for practice");var out=db.query("insert into user_practice_sessions(user_id,bank_id,session_type,question_count) values(?,?,?,?) returning id,user_id,bank_id,session_type,status,question_count,answered_count,correct_count,wrong_count,score,started_at,completed_at",this::row,user,bank,actual,ids.size()).getFirst();saveQueue(((Number)out.get("id")).longValue(),ids);return out;
  }
  private void saveQueue(long session,List<Long> ids){try{redis.opsForValue().set(key(session),json.writeValueAsString(ids),java.time.Duration.ofDays(7));}catch(Exception ignored){}}
  private List<Long> queue(Map<String,Object>s){long sid=((Number)s.get("id")).longValue();try{String raw=redis.opsForValue().get(key(sid));if(raw!=null&&!raw.isBlank())return json.readValue(raw,new TypeReference<List<Long>>(){});}catch(Exception ignored){} long bank=((Number)s.get("bank_id")).longValue();int n=((Number)s.get("question_count")).intValue();var ids=db.queryForList("select question_id from v_bank_question_items where bank_id=? and bank_link_status='active' and question_status='active' order by bank_sort_order,group_sort_order nulls first,question_id limit ?",Long.class,bank,n);saveQueue(sid,ids);return ids;}
  public Map<String,Object> list(long user,String status,String cursor,Integer requested,String updated){if(status==null)status="";if(!Set.of("","active","completed","abandoned").contains(status))throw bad("status must be one of active, completed, abandoned");int l=Math.min(100,Math.max(1,requested==null?20:requested)),o=PageSupport.cursor(cursor);var xs=db.query("select id,user_id,bank_id,session_type,status,question_count,answered_count,correct_count,wrong_count,score,started_at,completed_at from user_practice_sessions where user_id=? and (?='' or status=?) and (?='' or updated_at>=?::timestamptz) order by started_at desc,id desc limit ? offset ?",this::row,user,status,status,updated==null?"":updated,updated==null?"":updated,l+1,o);return page(xs,o,l);}
  private Map<String,Object> linked(Object... values){var out=new LinkedHashMap<String,Object>();for(int i=0;i<values.length;i+=2)out.put((String)values[i],values[i+1]);return out;}
  private Map<String,Object> page(List<Map<String,Object>> xs,int o,int l){boolean more=xs.size()>l;if(more)xs=xs.subList(0,l);return Map.of("items",xs,"meta",Map.of("pagination",Map.of("cursor",more?PageSupport.next(o,l):"","limit",l,"hasMore",more)));}
  public List<Map<String,Object>> questions(long user,long sid){var s=session(user,sid);return questionRows(s,queue(s),0,Integer.MAX_VALUE);}
  public Map<String,Object> questionPage(long user,long sid,Integer requested){var s=session(user,sid);var ids=queue(s);var answered=db.query("select question_id,is_correct from user_question_answers where user_id=? and session_id=?",(r,n)->Map.of("id",r.getLong(1),"correct",r.getObject(2)),user,sid);var set=new HashSet<Long>();for(var a:answered)set.add((Long)a.get("id"));int index=requested==null?0:Math.max(0,Math.min(requested,Math.max(0,ids.size()-1)));if(requested==null)for(int i=0;i<ids.size();i++)if(!set.contains(ids.get(i))){index=i;break;}var qs=questionRows(s,ids,index,1);Map<String,Object> answer=qs.isEmpty()?null:answer(user,sid,ids.get(index));if("exam".equals(s.get("session_type"))&&"active".equals(s.get("status"))&&answer!=null){answer=new LinkedHashMap<>(answer);answer.put("answer_key_id",null);answer.put("is_correct",null);answer.put("score",null);answer.put("max_score",null);}var progress=new ArrayList<Map<String,Object>>();for(int i=0;i<ids.size();i++){Long questionId=ids.get(i);Object correctness=null;for(var item:answered)if(item.get("id").equals(questionId)){correctness=item.get("correct");break;}if("exam".equals(s.get("session_type"))&&"active".equals(s.get("status")))correctness=null;progress.add(linked("index",i,"questionId",questionId,"isAnswered",set.contains(questionId),"isCorrect",correctness));}return linked("session",s,"question",qs.isEmpty()?null:qs.getFirst(),"questionIndex",qs.isEmpty()?0:index,"total",ids.size(),"answeredCount",answered.size(),"progress",progress,"result",answer,"previousIndex",index>0?index-1:null,"nextIndex",index<ids.size()-1?index+1:null);}
  private List<Map<String,Object>> questionRows(Map<String,Object>s,List<Long> ids,int offset,int take){if(ids.isEmpty()||offset>=ids.size())return List.of();var wanted=ids.subList(offset,Math.min(ids.size(),offset+take));var rows=db.query("select i.* from v_bank_question_items i where i.bank_id=? and i.question_id=any(?::bigint[]) and i.bank_link_status='active' and i.question_status='active'",this::row,s.get("bank_id"),wanted.toArray(Long[]::new));Map<Long,Map<String,Object>> by=new HashMap<>();for(var r:rows){long q=((Number)r.get("question_id")).longValue();r.put("options",db.query("select id,question_id,option_label,sort_order,content,created_at,updated_at from question_options where question_id=? order by sort_order",this::row,q));r.put("analysis",null);by.put(q,r);}return wanted.stream().map(by::get).filter(Objects::nonNull).toList();}
  private Map<String,Object> answer(long user,long session,long question){var x=db.query("select id,user_id,session_id,bank_id,question_id,answer_key_id,answer_payload,is_correct,score,max_score,duration_ms,answered_at from user_question_answers where user_id=? and session_id=? and question_id=?",this::row,user,session,question);return x.isEmpty()?null:x.getFirst();}
  @Transactional public Map<String,Object> submit(long user,long sid,long q,Map<String,Object> payload,Integer duration){if(duration!=null&&duration<0)throw bad("durationMs must be non-negative");var s=session(user,sid);var old=answer(user,sid,q);if(old!=null)return old;if(!"active".equals(s.get("status")))throw state("Practice session is not active");if(!queue(s).contains(q))throw ApiException.of(404,"NOT_FOUND","Question is not part of this practice session");var mode=db.query("select answer_mode from v_bank_question_items where bank_id=? and question_id=? and bank_link_status='active' and question_status='active'",(r,n)->r.getString(1),s.get("bank_id"),q);if(mode.isEmpty())throw ApiException.of(404,"NOT_FOUND","Question is not part of this active practice session");validate(mode.getFirst(),payload);var keys=db.query("select id,answer_payload from question_answer_keys where question_id=? and is_primary",this::row,q);Map<String,Object> expected=keys.isEmpty()?null:map(keys.getFirst().get("answer_payload"));Boolean correct=grader.grade(mode.getFirst(),expected,payload);String body=encode(payload);var inserted=db.query("insert into user_question_answers(user_id,session_id,bank_id,question_id,answer_key_id,answer_payload,is_correct,score,max_score,duration_ms) values(?,?,?,?,?,?::jsonb,?,?,?,?,?) on conflict(user_id,session_id,question_id) do nothing returning id,user_id,session_id,bank_id,question_id,answer_key_id,answer_payload,is_correct,score,max_score,duration_ms,answered_at",this::row,user,sid,s.get("bank_id"),q,keys.isEmpty()?null:keys.getFirst().get("id"),body,correct,correct==null?null:(correct?1d:0d),keys.isEmpty()?null:1d,duration);if(inserted.isEmpty())return answer(user,sid,q);bump(user,((Number)s.get("bank_id")).longValue());return inserted.getFirst();}
  private void validate(String mode,Map<String,Object> p){Object v=p==null?null:p.get("value");if("choice".equals(mode)&&selected(p).isEmpty())throw bad("Select at least one option before submitting");if("true_false".equals(mode)&&!(v instanceof Boolean))throw bad("Select true or false before submitting");if("fill_blank".equals(mode)&&values(p).isEmpty())throw bad("Fill at least one blank before submitting");if("short_answer".equals(mode)&&!(v instanceof String)||("short_answer".equals(mode)&&((String)v).trim().isEmpty()))throw bad("Answer text is required before submitting");}
  private List<String> selected(Map<String,Object> p){Object x=p==null?null:p.get("selected");if(x instanceof Collection<?> c)return c.stream().map(Object::toString).map(String::trim).filter(v->!v.isEmpty()).toList();return x==null?List.of():List.of(x.toString().trim());} private List<String> values(Map<String,Object> p){Object x=p==null?null:p.get("value");if(x instanceof Collection<?> c)return c.stream().map(Object::toString).map(v->v.trim().toLowerCase().replaceAll("\\s+"," ")).filter(v->!v.isEmpty()).toList();return x==null?List.of():List.of(x.toString().trim().toLowerCase());}
  @SuppressWarnings("unchecked") private Map<String,Object> map(Object x){try{return x instanceof Map<?,?> m?(Map<String,Object>)m:json.readValue(String.valueOf(x),new TypeReference<Map<String,Object>>(){});}catch(Exception e){return Map.of();}} private String encode(Object x){try{return json.writeValueAsString(x==null?Map.of():x);}catch(Exception e){throw bad("Invalid answer payload");}}
  @Transactional public Map<String,Object> complete(long user,long sid,String status){var x=db.query("update user_practice_sessions set status=?,completed_at=now() where id=? and user_id=? and status='active' returning id,user_id,bank_id,session_type,status,question_count,answered_count,correct_count,wrong_count,score,started_at,completed_at",this::row,status,sid,user);if(x.isEmpty())throw ApiException.of(404,"NOT_FOUND","Active practice session not found");bump(user,((Number)x.getFirst().get("bank_id")).longValue());return x.getFirst();}
  public List<Map<String,Object>> results(long user,long sid){var s=session(user,sid);if("active".equals(s.get("status")))throw state("Complete the practice session before viewing results");return db.query("select a.*,q.stem,q.answer_mode,q.analysis from user_question_answers a join questions q on q.id=a.question_id where a.user_id=? and a.session_id=? order by a.answered_at,a.id",this::row,user,sid);}
  @Transactional public Map<String,Object> offline(long user,long bank,String idempotencyKey,List<Map<String,Object>> answers){
    if(idempotencyKey==null||idempotencyKey.isBlank()||idempotencyKey.length()>128)throw bad("Idempotency-Key is required");
    String cache="practiq:offline-practice:"+user+":"+idempotencyKey.trim();
    try {String old=redis.opsForValue().get(cache);if(old!=null&&!old.isBlank())return get(user,Long.parseLong(old));}catch(Exception e){throw ApiException.of(503,"IDEMPOTENCY_UNAVAILABLE","Offline practice upload is temporarily unavailable");}
    var s=start(user,bank,"practice",answers.size(),"all",null,false);long sid=((Number)s.get("id")).longValue();
    try {redis.opsForValue().set(cache,Long.toString(sid),java.time.Duration.ofHours(24));}catch(Exception ignored){}
    for(var answer:answers)submit(user,sid,((Number)answer.get("questionId")).longValue(),map(answer.get("answerPayload")),null);
    return complete(user,sid,"completed");
  }
  public void bump(long user,long bank){try{redis.opsForValue().increment("practiq:cache-version:analytics:"+user);redis.opsForValue().increment("practiq:cache-version:bank-analytics:"+bank);redis.opsForValue().increment("practiq:cache-version:leaderboard:"+bank);}catch(Exception ignored){}}
}
