package com.practiq.service;

import com.practiq.common.ApiException;
import java.sql.ResultSet;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service public class StudyGroupService {
 private final JdbcTemplate db;
 public StudyGroupService(JdbcTemplate db){this.db=db;}
 private Map<String,Object> row(ResultSet r,int n)throws java.sql.SQLException{var m=new LinkedHashMap<String,Object>();for(int i=1;i<=r.getMetaData().getColumnCount();i++)m.put(r.getMetaData().getColumnLabel(i),r.getObject(i));return m;}
 private void organization(long user,String feature){var paid=db.queryForList("select paid_pro_at from users where id=? and status='active'",OffsetDateTime.class,user);if(paid.isEmpty())throw ApiException.of(404,"NOT_FOUND","User not found");if(paid.getFirst()==null)throw ApiException.of(403,"PAID_PRO_REQUIRED",feature+" requires paid Pro");}
 private String role(long group,long user){var x=db.queryForList("select role from study_group_members where group_id=? and user_id=?",String.class,group,user);return x.isEmpty()?null:x.getFirst();}
 private void member(long group,long user){if(role(group,user)==null)throw ApiException.of(404,"STUDY_GROUP_NOT_FOUND","Study group not found");}
 private void owner(long group,long user){String r=role(group,user);if(r==null)throw ApiException.of(404,"STUDY_GROUP_NOT_FOUND","Study group not found");if(!"owner".equals(r))throw ApiException.of(403,"FORBIDDEN","Study group owner access required");organization(user,"Study group management");}
 @Transactional public Map<String,Object> create(long user,String name,String description){organization(user,"Study groups");var g=db.query("insert into study_groups(name,description,created_by) values(?,?,?) returning id,name,description,created_by,created_at,updated_at",this::row,name.trim(),description,user).getFirst();db.update("insert into study_group_members(group_id,user_id,role) values(?,?, 'owner')",g.get("id"),user);return group(g);}
 public List<Map<String,Object>> list(long user){return db.query("select g.id,g.name,g.description,g.created_by,g.created_at,g.updated_at,m.role,(select count(*) from study_group_members x where x.group_id=g.id) member_count,(select count(*) from study_group_banks x where x.group_id=g.id) bank_count from study_groups g join study_group_members m on m.group_id=g.id and m.user_id=? order by g.created_at desc,g.id desc",this::row,user).stream().map(g->{var x=group(g);x.put("role",g.get("role"));x.put("memberCount",g.get("member_count"));x.put("bankCount",g.get("bank_count"));return x;}).toList();}
 public Map<String,Object> get(long user,long id){member(id,user);var x=db.query("select id,name,description,created_by,created_at,updated_at from study_groups where id=?",this::row,id);if(x.isEmpty())throw ApiException.of(404,"STUDY_GROUP_NOT_FOUND","Study group not found");var g=group(x.getFirst());g.put("role",role(id,user));g.put("members",db.query("select m.user_id,u.username,m.role,m.joined_at from study_group_members m join users u on u.id=m.user_id where m.group_id=? order by m.joined_at,m.id",this::row,id).stream().map(this::memberRow).toList());g.put("banks",db.query("select b.id bank_id,b.name,b.subject,s.linked_at from study_group_banks s join question_banks b on b.id=s.bank_id where s.group_id=? order by s.linked_at,s.id",this::row,id).stream().map(this::bankRow).toList());return g;}
 @Transactional public Map<String,Object> update(long user,long id,String name,boolean descriptionSet,String description){owner(id,user);if(name==null&&!descriptionSet)throw ApiException.of(422,"VALIDATION_ERROR","Invalid request");if(name!=null&&(name.isBlank()||name.trim().length()>100))throw ApiException.of(422,"VALIDATION_ERROR","Invalid request");var x=db.query("update study_groups set name=coalesce(?,name),description=case when ? then ? else description end where id=? returning id,name,description,created_by,created_at,updated_at",this::row,name==null?null:name.trim(),descriptionSet,description,id);return group(x.getFirst());}
 @Transactional public void delete(long user,long id){owner(id,user);db.update("delete from study_groups where id=?",id);}
 @Transactional public Map<String,Object> addMember(long user,long group,String username){owner(group,user);var x=db.query("select id,username from users where lower(username)=lower(?) and is_active=true limit 1",this::row,username.trim());if(x.isEmpty())throw ApiException.of(404,"MEMBER_NOT_FOUND","User not found or not active");var p=x.getFirst();var inserted=db.query("insert into study_group_members(group_id,user_id,role) values(?,?,'member') on conflict(group_id,user_id) do nothing returning joined_at",this::row,group,p.get("id"));if(inserted.isEmpty())throw ApiException.of(409,"MEMBER_CONFLICT","User is already a member of this group");return Map.of("userId",p.get("id"),"username",p.get("username"),"role","member","joinedAt",inserted.getFirst().get("joined_at"));}
 @Transactional public void removeMember(long user,long group,long memberId){owner(group,user);var r=role(group,memberId);if(r==null)throw ApiException.of(404,"MEMBER_NOT_FOUND","Member not found");if("owner".equals(r))throw ApiException.of(409,"CANNOT_REMOVE_OWNER","The group owner cannot be removed");db.update("delete from study_group_members where group_id=? and user_id=?",group,memberId);}
 @Transactional public Map<String,Object> linkBank(long user,long group,long bank){owner(group,user);if(db.queryForObject("select count(*) from user_bank_links where user_id=? and bank_id=? and is_owner=true",Integer.class,user,bank)==0)throw ApiException.of(403,"BANK_NOT_OWNED","You can only link banks you own");var x=db.query("insert into study_group_banks(group_id,bank_id,linked_by) values(?,?,?) on conflict(group_id,bank_id) do nothing returning linked_at",this::row,group,bank,user);if(x.isEmpty())throw ApiException.of(409,"BANK_LINK_CONFLICT","Bank is already linked to this group");return Map.of("groupId",group,"bankId",bank,"linkedAt",x.getFirst().get("linked_at"));}
 @Transactional public void unlinkBank(long user,long group,long bank){owner(group,user);if(db.update("delete from study_group_banks where group_id=? and bank_id=?",group,bank)!=1)throw ApiException.of(404,"BANK_LINK_NOT_FOUND","Bank is not linked to this group");}
 public Map<String,Object> stats(long user,long group,long memberId){owner(group,user);if(role(group,memberId)==null)throw ApiException.of(404,"MEMBER_NOT_FOUND","Member not found");var s=db.query("select (select count(*) from user_bank_links where user_id=? and is_owner) owned_banks,(select count(*) from user_bank_links where user_id=? and is_favorite) favorite_banks,coalesce((select sum(attempt_count) from user_question_stats where user_id=?),0) attempts,coalesce((select sum(correct_count) from user_question_stats where user_id=?),0) correct,coalesce((select sum(wrong_count) from user_question_stats where user_id=?),0) wrong,(select count(*) from user_practice_sessions where user_id=?) sessions,(select count(*) from user_practice_sessions where user_id=? and status='active') active_sessions",this::row,memberId,memberId,memberId,memberId,memberId,memberId,memberId).getFirst();long a=((Number)s.get("attempts")).longValue(),c=((Number)s.get("correct")).longValue();s.put("accuracy",a==0?0:Math.round(c*100d/a));return Map.of("summary",s,"recentSessions",db.query("select id,user_id,bank_id,session_type,status,question_count,answered_count,correct_count,wrong_count,score,started_at,completed_at from user_practice_sessions where user_id=? order by started_at desc,id desc limit 10",this::row,memberId),"weakQuestions",db.query("select s.question_id,s.attempt_count,s.correct_count,s.wrong_count,s.mastery_score,q.stem,q.question_type_id from user_question_stats s join questions q on q.id=s.question_id where s.user_id=? and s.attempt_count>0 order by s.mastery_score asc nulls first,s.wrong_count desc,s.last_answered_at desc nulls last limit 10",this::row,memberId));}
 private Map<String,Object> group(Map<String,Object> x){return new LinkedHashMap<>(Map.of("id",x.get("id"),"name",x.get("name"),"createdBy",x.get("created_by"),"createdAt",x.get("created_at"),"updatedAt",x.get("updated_at"))){ {put("description",x.get("description"));} };} private Map<String,Object> memberRow(Map<String,Object>x){return Map.of("userId",x.get("user_id"),"username",x.get("username"),"role",x.get("role"),"joinedAt",x.get("joined_at"));} private Map<String,Object> bankRow(Map<String,Object>x){return Map.of("bankId",x.get("bank_id"),"name",x.get("name"),"subject",x.get("subject"),"linkedAt",x.get("linked_at"));}
}
